### DISCUSSION TITLE
Notification Group

### DISCUSSION THREAD

**Discussion by sohail579** [SgtBatten/HA_blueprints#438] [Q&A]
I am trying to create a notification group in the UI for HA, I would like to have all mobile devices in a group.  cant seem to get this working can anyone help me?

**Comment by deanpm70** [comment]
Hi,

You'll need to create a notification group in Home Assistant. To do this, find and edit your HA configuration.yaml file by adding the following:

```
notify:
  - platform: group
    name: all_devices
    unique_id: all_devices
    services:
      - service: mobile_app_iphone12
      - service: mobile_app_iphone_13
      - service: mobile_app_ipad_2
```

This will create a group called all_devices and add the entities mobile_app_iphone12, mobile_app_iphone_13 and mobile_app_ipad_2. These entities correlate to all of the devices which are using the Home Assistant app to connect to your server.

In your frigate notification blueprint, add "notify.all_devices" to the "Notification Group or Android/Fire TV (Optional)" entry. You'll need to type the value as it does not list the groups defined this way.

<img width="972" alt="image" src="https://github.com/user-attachments/assets/39cc4a0d-d659-4b78-a01e-f1810b349e17" />
