### ISSUE TITLE
[Bug]: Label Names seem to be arrays in the beta Frigate, reads poorly when Notification updates

### ISSUE THREAD

**Issue by robchandhok** [SgtBatten/HA_blueprints#102]
### Description

Just started running Frigate 0.13.0-beta2 and Frigate Integration v5.0.0-beta.2.  Using DoubleTake 1.13.1.

Was solely using the Stable version (0.12.0.1) of this wonderful blueprint (THANK YOU).  Have also tried with the Beta (0.12.0.1r) version of the blueprint on one camera, no difference in behavior.

Both versions of the blueprint correctly report the object detection `A Person was detected on the Front Door camera.`

The bug is that when the notification updates with the face label from DoubleTake, it no longer reports `"Rob was detected on the Front Door camera"` (for example).  Instead the notification text reads `"['rob',None] was detected on the Front Door camera"`.

I am not overriding the template for generating the message.

I haven't been able to track it down in the Frigate changes, but maybe Labels come back as an array in the event now?  I'm happy to help debug if useful.

### Version

0.12.0.1

### Automation Config

```yaml
alias: Notice Camera - Front Door
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    tv_transparency: 0%
    camera: camera.front_door
    base_url: https://XXXXXXXXXXXXX
    update_thumbnail: true
    zones:
      - front_door_path
    labels:
      - person
    ios_live_view: false
    cooldown: 120
    state_entity: input_boolean.quiet_camera_notifications
    state_filter_states:
      - "off"
    state_filter: true
    tv_size: large
    tv_position: center
    zone_filter: true
    notify_group: all_mobile
    color: grey
```
