### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by francoisduprez** [SgtBatten/HA_blueprints#104]
### Describe the problem you are having or the outcome you are trying to achieve.

I'm trying to get  face detection from doubletake into  Frigate Notifications 0.12.0.1r , but don't understand how.
In the README.md i read Replace {{label}} in title and message of the notification with a persons name if double-take face match is detected. But tried different combinations without luck.
How can i put multiple faces in??

It will print the name i put in, even when unknown or an other person is detected..

### Version

0.12.0.1r

### Automation config file

```yaml
alias: Detectie_tuinpoort_francois
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.tuinpoort
    notify_device: cef0e544c5ae21a1ae4a2ea4b9ae49bc
    message: "{{label}} is gedetecteerd op camera {{camera_name}} "
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    attachment: snapshot.jpg?bbox=1
    critical: "false"
    zone_filter: true
    zones:
      - poort_stoep
    labels: []
    base_url: https://home.mirmooi.net/
    silence_timer: 0
    cooldown: 0
    zone_multi: false
    icon: mdi:cctv
    title: francois
    subtitle: "francois is gedetecteerd op camera {{camera_name}} "
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.44
  topic_prefix: frigate
  user: 
  password: 

database:
  path: /config/frigate.db

environment_vars:
  VARIABLE_NAME: LIBVA_DRIVER_NAME=i965

detectors:
 # coral1:
 #   type: edgetpu
 #   device: pci:0
  coral2:
    type: edgetpu
    device: pci:1

go2rtc:
  streams:
    voordeur:
      - "ffmpeg:http://192.168.1.7/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    voordeur_sub:
      - "ffmpeg:http://192.168.1.7/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_RTSP_PASSWORD}"
    tuinpoort:
      - "ffmpeg:http://192.168.1.8/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    tuinpoort_sub:
      - "ffmpeg:http://192.168.1.8/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_RTSP_PASSWORD}"
    tuin:
      - "ffmpeg:http://192.168.1.12/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_USER}&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus"
    tuin_sub:
      - "ffmpeg:http://192.168.1.12/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_USER}&password={FRIGATE_RTSP_PASSWORD}"
    aquarium:
      - "ffmpeg:rtsp://192.168.1.42:8554/cam"
#    bodem_cam:
#      - "ffmpeg:rtsp://192.168.1.42:8554/usbcam"

cameras:
  voordeur:
    enabled: True
    ffmpeg:
      output_args:
          record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/voordeur
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/voordeur_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.74
    snapshots:
      enabled: true
      required_zones:
        - voordeur_stoep
      retain:
        default: 14
    record:
      enabled: true
      retain:
       days: 5
      events:
       retain:
        default: 30
       required_zones:
          - voordeur_stoep
    zones:
      voordeur_stoep:
        coordinates: 171,480,415,480,279,284,108,348
    motion:
      mask:
        - 640,0,640,430,294,102,299,0
    birdseye:
     enabled: True
     quality: 5
     mode: continuous
    ui:
      order: 1

  tuinpoort:
    enabled: True
    ffmpeg:
      output_args:
            record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/tuinpoort
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuinpoort_sub
          input_args: preset-rtsp-restream
          roles:
           - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - cat
        - bicycle
        - motorcycle
      filters:
        person:
         threshold: 0.74
        dog:
          threshold: 0.8
        cat:
          threshold: 0.8
        bicycle:
          threshold: 0.7
        motorcycle:
          threshold: 0.7
    snapshots:
      enabled: true
      required_zones:
        - poort_stoep
      timestamp: false
      bounding_box: true
      retain:
        default: 14
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 14
        required_zones:
          - poort_stoep
    zones:
        poort_stoep:
         coordinates: 286,333,491,480,273,480,194,369
        poort_steeg:
         coordinates: 598,75,585,135,475,109,467,76
    motion:
     mask:
      - 172,0,157,480,0,480,0,0
      - 640,0,640,71,597,68,595,0
    birdseye:
     enabled: True
     quality: 5
     mode: continuous
    ui:
      order: 2

  tuin:
    enabled: True
    ffmpeg:
      output_args:
            record: preset-record-generic-audio-copy
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/tuin
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/tuin_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    birdseye:
     enabled: True
     quality: 5
     mode: continuous
    ui:
      order: 3

  aquarium:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/aquarium
          roles:
            - record
    ui:
      order: 4

  bodem_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.42:8554/usbcam
#        - path: rtsp://127.0.0.1:8554/Bodem_cam
          roles:
            - record
    ui:
      order: 5
```
