### ISSUE TITLE
[Config Support]: Unable to attach anything to SMTP alerts

### ISSUE THREAD

**Issue by myriad007** [SgtBatten/HA_blueprints#105]
### Describe the problem you are having or the outcome you are trying to achieve.

I have created a Notification Group to send smtp alert to my email which works but there are no links or attachments inserted in the email message:

`notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: richards_iphone
      
  - name: email_notification
    platform: smtp
    server: smtp.mailgun.org
    port: 587
    timeout: 15
    sender: noreply@mg.xxx.com
    starttls: true
    username: noreply@mg.xxx.com
    password: hidden
    recipient:
      - me@you.com
    sender_name: Home Assistant`

### Version

Frigate Notifications (0.12.0.1)

### Automation config file

```yaml
alias: Email Frigate
description: Front Porch
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_porch
    base_url: https://cctv.xxx.ca
    title: Front Porch Alert
    message: A Person was detected on the Front Porch camera. Email...
    critical: "false"
    alert_once: true
    update_thumbnail: false
    color: red
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    ios_live_view: true
    labels:
      - person
      - dog
    zone_filter: false
    debug: true
    sound: none
    notify_group: email_notification
    attachment: thumbnail
    zones:
      - porch
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    cooldown: 60
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.76
  user: homeassistant
  password: hidden

detectors:
  coral_pci:
    type: edgetpu
    device: pci:0

cameras:
  Back_Yard:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.1.8:554/Streaming/Channels/101
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    snapshots: # <----- Enable snapshots
      enabled: True
    motion:
      mask:
         - 0,252,70,540,381,510,335,281,455,347,1183,170,1920,171,1920,0,0,0
    zones:
      zone_0:
           coordinates: 770,297,784,391,882,589,961,600,1022,581,1088,625,972,723,1110,792,1208,669,939,482,909,259
      zone_1:
           coordinates: 104,699,240,658,366,953,365,997,1385,975,1139,810,917,682,861,663,745,680,693,696,652,680,499,659,328,647,218,619,88,619
    record:
      enabled: True
      events:
        retain:
          default: 30
  Side_Door:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.1.7:554/Streaming/Channels/101
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
    snapshots: # <----- Enable snapshots
      enabled: True
    motion:
      mask:
           - 1188,0,1204,124,1422,0,836,984,836,1080,425,1080,259,1080,149,1080,0,1080,0,0
    zones:
      zone_0:
           coordinates: 1383,786,1394,609,1416,354,1422,284,1406,217,1421,155,1416,85,1422,0,1216,0,1074,281,770,880,864,1080,1172,1080,1362,1080,1374,1040,1214,1035,1251,776
    record:
      enabled: True
      events:
        retain:
          default: 30           
  Front_Porch:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.1.10:554/Streaming/Channels/103
          roles:
            - detect
        - path: rtsp://admin:xxx@192.168.1.10:554/Streaming/Channels/101
          roles:
            - record
    detect:
      width: 1280
      height: 720
    snapshots: # <----- Enable snapshots
      enabled: True
    motion:
      mask:
           - 0,399,219,362,378,366,502,326,719,270,856,244,858,159,915,112,995,89,1136,121,1110,161,1154,209,1280,245,1280,0,0,0
    zones:
      zone_0:
           coordinates: 854,157,871,264,1062,615,1205,559,1280,306,1164,215,1148,207,1136,193,1113,178,1106,139,1056,127,1014,118,981,113,951,107,921,112
      zone_1:
           coordinates: 449,366,525,406,713,359,903,346,851,245
      zone_2:
           coordinates: 325,439,185,502,128,516,25,533,0,471,219,372
    record:
      enabled: True
      events:
        retain:
          default: 30
```

### Any other information that may be helpful

I am not sure if your awesome script can even attach anything to SMTP but I would appreciate any input you can offer.
