### ISSUE TITLE
[Bug]: Template Processor doesn't recognise the variable 'entered_zones'.

### ISSUE THREAD

**Issue by ZionFox** [SgtBatten/HA_blueprints#106]
### Description

Getting the following error message in HA Logs when attempting to use the Long notification message, or write my own versions of this message using the same variables. It seems the variable `entered_zones` isn't valid, or isn't being populated correctly upon calling.

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:239
First occurred: 19 October 2023 at 06:35:46 (154 occurrences)
Last logged: 13:51:37

Template variable warning: 'entered_zones' is undefined when rendering '{{ camera_name }} - {{ label }} {{ 'loitering' if loitering else 'detected' }} {{ ' in ' + entered_zones if entered_zones else '.'}}'
Template variable warning: 'enteredzones' is undefined when rendering '{{ camera_name }} - {{ label }} {{ 'loitering' if loitering else 'detected' }}{{ ' in ' + enteredzones if enteredzones else '.'}}'
Template variable warning: 'entered_zones' is undefined when rendering 'A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the {{ camera_name }} camera{{ ' in the ' + entered_zones if entered_zones else '.'}}'
```

I spotted the variable change in the Beta branch too, and tried using this variable name to no avail. I do see in the stack trace for the automation that there is an array called `entered_zones` that does have `- near_pavement` in it which is from the last object that walked by. This should fail the notification as I'm only interested in notifications for `home_path`. There another `entered_zones` in the payload from MQTT, which is empty.

### Version

0.12.0.1 Stable

### Automation Config

```yaml
alias: Frigate Fox-Front
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.fox_front
    notify_device: 61d0041a9de4b2ca2f02a004cdc16c04
    base_url: http://[redacted]:8123
    critical: "true"
    alert_once: true
    attachment: snapshot
    update_thumbnail: true
    icon: mdi:cctv
    zone_filter: true
    zones:
      - home_path
    labels: []
    silence_timer: 10
    tap_action: /lovelace
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera{{ ' in the ' + entered_zones if entered_zones
      else '.'}}
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 10.0.1.2
  user: [redacted]
  password: [redacted]

ffmpeg:
#  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-copy

objects:
  filters:
    person:
      threshold: 0.75

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 14

go2rtc:
  streams:
    Fox-Garden:
      - rtsp://admin:[redacted]@10.0.1.50:554/Streaming/Channels/101
    Fox-Front:
      - rtsp://admin:[redacted]@10.0.1.51:554/Streaming/Channels/101

cameras:
  Fox-Garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:[redacted]@10.0.1.50:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://admin:[redacted]@10.0.1.50:554/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      retain:
        mode: all
        days: 7
      events:
        post_capture: 30
        retain:
          default: 14
          mode: motion
          objects:
            cat: 2
            bird: 2
            mouse: 2
    objects:
      track:
        - person
        - "sports ball"
        - cat
        - dog
        - bird
        - mouse
    zones:  
      garden_path:
        coordinates: 461,699,85,699,90,0,257,0,223,530,742,549,740,476,879,489,892,649
      lawn:
        coordinates: 272,0,535,0,826,132,872,487,745,482,755,560,211,536,236,193
      walls:
        coordinates: 1134,327,1166,588,886,646,866,403,827,132,537,0,1033,0
    motion:
      mask:
        - 1280,720,1249,720,1235,529,1167,212,1096,0,1280,0
    ui:
      order: 2

  Fox-Front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:[redacted]@10.0.1.51:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://admin:[redacted]@10.0.1.51:554/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
    record:
      enabled: true
      events:
        post_capture: 30
        pre_capture: 10
        retain:
          default: 14
          mode: motion
          objects:
            cat: 2
            dog: 2
            #bird: 2
            car: 4
    objects:
      track:
        - person
        - car
        #- bycicle
        #- motorcycle
        - cat
        - dog
        #- bird
    zones:
      home_path:
        coordinates: 1280,506,1280,629,793,690,525,699,189,697,0,665,0,569,659,576
      near_pavement:
        coordinates: 653,557,273,555,0,542,0,256,624,207,1280,242,1280,356,1114,361,1196,508
      road:
        coordinates: 0,0,0,235,398,203,980,202,1280,232,1280,0
    motion:
      mask:
        - 52,720,423,720,422,679,55,677
    ui:
      order: 0

ui:
  use_experimental: false
  strftime_fmt: "%Y-%m-%d %H:%M:%S"
  timezone: Europe/London

timestamp_style:
  position: tl
  format: "%Y-%m-%d %H:%M:%S"
  effect: shadow
```

### Any other relevant information

```yaml
this:
  entity_id: automation.frigate_fox_front
  state: 'on'
  attributes:
    id: '1695356202129'
    last_triggered: '2023-10-24T12:51:37.644942+00:00'
    mode: parallel
    current: 1
    max: 10
    friendly_name: Frigate Fox-Front
  last_changed: '2023-10-24T00:07:08.838016+00:00'
  last_updated: '2023-10-24T12:51:37.645053+00:00'
  context:
    id: 01HDGVV6HAA4B66KA05SNXMQ9K
    parent_id: null
    user_id: null
trigger:
  id: frigate-event
  idx: '1'
  alias: null
  platform: mqtt
  topic: frigate/events
  payload: >-
    {"before": {"id": "1698151899.625427-o7w34l", "camera": "Fox-Front",
    "frame_time": 1698151899.625427, "snapshot_time": 0.0, "label": "person",
    "sub_label": null, "top_score": 0.0, "false_positive": true, "start_time":
    1698151899.625427, "end_time": null, "score": 0.8046875, "box": [574, 145,
    726, 322], "area": 26904, "ratio": 0.8587570621468926, "region": [488, 52,
    844, 408], "stationary": false, "motionless_count": 0, "position_changes":
    0, "current_zones": [], "entered_zones": [], "has_clip": false,
    "has_snapshot": false}, "after": {"id": "1698151899.625427-o7w34l",
    "camera": "Fox-Front", "frame_time": 1698151900.293719, "snapshot_time":
    1698151900.293719, "label": "person", "sub_label": null, "top_score":
    0.76953125, "false_positive": false, "start_time": 1698151899.625427,
    "end_time": null, "score": 0.83203125, "box": [402, 156, 609, 334], "area":
    36846, "ratio": 1.1629213483146068, "region": [325, 0, 845, 520],
    "stationary": false, "motionless_count": 0, "position_changes": 1,
    "current_zones": ["near_pavement"], "entered_zones": ["near_pavement"],
    "has_clip": true, "has_snapshot": true}, "type": "new"}
  qos: 0
  description: mqtt topic frigate/events
  payload_json:
    before:
      id: 1698151899.625427-o7w34l
      camera: Fox-Front
      frame_time: 1698151899.625427
      snapshot_time: 0
      label: person
      sub_label: null
      top_score: 0
      false_positive: true
      start_time: 1698151899.625427
      end_time: null
      score: 0.8046875
      box:
        - 574
        - 145
        - 726
        - 322
      area: 26904
      ratio: 0.8587570621468926
      region:
        - 488
        - 52
        - 844
        - 408
      stationary: false
      motionless_count: 0
      position_changes: 0
      current_zones: []
      entered_zones: []
      has_clip: false
      has_snapshot: false
    after:
      id: 1698151899.625427-o7w34l
      camera: Fox-Front
      frame_time: 1698151900.293719
      snapshot_time: 1698151900.293719
      label: person
      sub_label: null
      top_score: 0.76953125
      false_positive: false
      start_time: 1698151899.625427
      end_time: null
      score: 0.83203125
      box:
        - 402
        - 156
        - 609
        - 334
      area: 36846
      ratio: 1.1629213483146068
      region:
        - 325
        - 0
        - 845
        - 520
      stationary: false
      motionless_count: 0
      position_changes: 1
      current_zones:
        - near_pavement
      entered_zones:
        - near_pavement
      has_clip: true
      has_snapshot: true
    type: new
input_camera: camera.fox_front
camera: fox_front
camera_name: Fox Front
input_base_url: http://[redacted]:8123
base_url: http://[redacted]:8123
attachment: snapshot
critical_input: 'true'
critical: true
alert_once: true
update_thumbnail: true
ios_live_view: false
group: ''
group_target: ''
zone_only: true
input_zones:
  - home_path
zones:
  - home_path
zone_multi: false
input_labels: []
labels: []
presence_entity: ''
disable_times: []
cooldown: 30
loitering: false
loiter_timer: 0
fps: 5
state_only: false
input_entity: ''
input_states: []
states_filter: []
color: steelblue
sound: default
tv: false
tv_position: center
tv_size: large
tv_duration: 10
tv_transparency: 0%
tv_interrupt: false
debug: false
```
