### ISSUE TITLE
[Config Support]: Blueprint config only works when I have another automation active

### ISSUE THREAD

**Issue by randommonth** [SgtBatten/HA_blueprints#109]
### Describe the problem you are having or the outcome you are trying to achieve.

I installed this blueprint automation to get Frigate notifications on my phone. After installing it, I couldn't get it to work, so I created my own basic automation from scratch and ran it alongside this blueprint. Strangely after creating my own automation, not only does my automation successfully send notifications to my phone, but the blueprint does also along with clips for me to watch. If I disable or delete my own automation, the blueprint stops working. What's going on??

### Version

0.12.0.1

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: Driveway person to Tom's phone
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door_cam
    notify_device: 8ee84f1e29ac3882ee377d8f610ca4c9
    message: Person in driveway
    critical: "true"
    attachment: snapshot
    update_thumbnail: true
    zone_filter: true
    zones:
      - driveway_zone
    labels:
      - person
    silence_timer: 2
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.44
  port: 1883
  user: mqtt
  password: mqtt
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Front_Door_Cam: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:cooper66@192.168.1.64:554/Streaming/Channels/101 # <----- Update for your camera
          roles:
            - record
            - detect
            - rtmp
        
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080
      enabled: True      # <---- update for your camera's resolution
      stationary:
        interval: 0
        threshold: 50
    
    record: # <----- Enable recording
      enabled: True
      events:
        retain:
          default: 30
          mode: active_objects
        required_zones:
          - street_zone
          - driveway_zone
    
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - cat
        - dog
              
    motion:
      mask:    
        - 1876,1080,1882,1019,1259,1014,1260,1080
                
    zones:
      street_zone:
        coordinates: 309,156,464,136,612,108,802,93,942,80,1031,69,1158,55,1239,58,1321,58,1399,71,1400,153,1374,260,1316,300,1171,326,1635,492,1543,793,885,383,701,420,503,468,379,499
        objects:
          - person
          - bicycle
          - cat
          - dog
          - car
          - motorcycle
      driveway_zone:
        coordinates: 468,845,536,1080,827,1080,1102,1080,1384,1080,1597,1080,1642,994,1498,882,1342,772,1228,690,1072,569,902,470,788,407,681,430,543,466,432,496,413,644
        objects:
          - person
          - bicycle
          - cat
          - dog
          - car
```

### Any other information that may be helpful

This is the config of the other automation I created

alias: Person in Driveway
description: ""
trigger:
  - type: occupied
    platform: device
    device_id: 5859ec2a102b3f7b2ed3e6bffcdc03fe
    entity_id: 339d852dc4af57e28a98d0bd68f2eccd
    domain: binary_sensor
condition: []
action:
  - device_id: 8ee84f1e29ac3882ee377d8f610ca4c9
    domain: mobile_app
    type: notify
    message: Person in Driveway
mode: single
