### ISSUE TITLE
[Config Support]: Notification Sound - IOS only (Optional)

### ISSUE THREAD

**Issue by baylanger** [SgtBatten/HA_blueprints#11]
### Describe the problem you are having or the outcome you are trying to achieve.

My goal is to understand and then possibly create a PR to update the README / docs to explain in details how the notification sound option works.

Per the blueprint :
```
Notification Sound - IOS only (Optional):
You can specify a soud file on your device that will play for the notifications. You will need to import the sound file into home assistant.
```
Is the mentioned "import" related to "Home Assistant iOS app" or "Home Assistant server"?

IF related to the iOS app, going into "Notifications Settings -> Sounds" , there are 3 available tabs :
```
Imported
Bundled
System
```
Both Bundled & System shows a long list of sounds. The ones in Bundled all have extension ".wav" and the ones in System ends with ".caf" - only today I realized the difference into the extension.

Last night I tried to set the "Notification Sound" to:
```
Siren_Countdown_Major_Haptic.caf
```
That didn't work, then I removed the extension - still didn't work.

Perhaps .caf files aren't supported? Perhaps I need to import all of those sounds directly into the hass server, if so is it in .../config/www/ ?

Thanx.

### Version

0.11.0.16

### Automation config file

```yaml
alias: 5frontyard - person
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.5frontyard
    notify_device: a1aac1885481adc1579cabd10d5640f9
    base_url: https://ha.xxxxxxxxxxx.ccccc/
    title: FRONTYARD PRESENCE
    critical: "true"
    update_thumbnail: true
    alert_once: true
    ios_live_view: true
    labels:
      - person
    zone_filter: true
    cooldown: 60
    silence_timer: 120
    loiter_timer: 1
    tv_size: large
    sound: Siren_Countdown_Major_Haptic
    tv_position: center
    color: grey
    zones:
      - entrances
```
