### ISSUE TITLE
[Bug]: Telegram Error

### ISSUE THREAD

**Issue by joeblack2k** [SgtBatten/HA_blueprints#110]
### Description

I'm getting errors instead of videos when using telegram as notify
```

(Logger: homeassistant.components.automation.yard_notifications_to_telegram_group
Source: helpers/script.py:1783
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 3:49:56 PM (12 occurrences)
Last logged: 4:09:47 PM

    Yard Notifications to Telegram group: Choose at step 1: Frigate Event: Notify on new object: choice 1: Choose at step 1: choice 1: Error executing script. Error for device at pos 1: Unable to resolve webhook ID from the device ID
    Yard Notifications to Telegram group: Choose at step 1: Frigate Event: Notify on new object: choice 1: Error executing script. Error for choose at pos 1: Unable to resolve webhook ID from the device ID
    Yard Notifications to Telegram group: Choose at step 1: Frigate Event: Error executing script. Error for choose at pos 6: Unable to resolve webhook ID from the device ID
    Yard Notifications to Telegram group: Error executing script. Error for choose at pos 1: Unable to resolve webhook ID from the device ID)

```

```
 Logger: homeassistant.helpers.template
Source: helpers/template.py:2209
First occurred: 3:42:58 PM (11 occurrences)
Last logged: 4:11:25 PM
Template variable warning: 'id' is undefined when rendering '/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg
]
```

### Version

BETA

### Automation Config

```yaml
alias: Yard Notifications to Telegram group
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.deurbel
    notify_telegram_chat_id: "-100170349XXXXX"
    base_url: http://192.168.1.1:8123
    message: "{{ label }} detected - {{ camera_name }}"
    attachment: /api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    labels:
      - person
      - cat
    debug: true
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

#detectors:
#  cpu1:
#    type: cpu
mqtt:
  host: 
  port: 1883
  topic_prefix: frigate
  user: 
  password:
  stats_interval: 60

go2rtc:
  streams:
    front_door:
      

cameras:
  deurbel: 
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
          record: preset-record-generic-audio-copy
      inputs:
        - path: 
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
      fps: 10
    record:
      enabled: true
      retain:
        days: 1
        mode: all
    objects:
      track:
        - person
    snapshots:
      enabled: true
      retain:
        default: 7
    motion:
      mask:
        - 0,1285,1100,1523,1293,1507,1716,1481,1251,1584,2560,1243,2560,0,0,0
```
