### ISSUE TITLE
[Bug]: Automations are invalid after 2023.11 update

### ISSUE THREAD

**Issue by dmgerow** [SgtBatten/HA_blueprints#112]
### Description

After upgrading home assistant to the 2023.11 update, my automations using this blueprint started showing as unavailable and could not be edited. I tried reimporting the blueprint and making a new automation but I got the same error:

`Message malformed: Unknown device 'False' `

the below configuration is my attempt at making the simplest possible automation using the blueprint. 

### Version

0.12.0.1

### Automation Config

```yaml
description: ""
alias: Frigate Notifications (0.12.0.1)
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: doorbell
```
