### ISSUE TITLE
[Bug]: The Mobile Device field cannot be empty

### ISSUE THREAD

**Issue by janusn** [SgtBatten/HA_blueprints#114]
### Description

It was working fine before. However, I have noticed the automation was fails with an red icon today (2 Nov 2023). The notification target was set to a group defined on configuration.yaml in the field "Notification Group or Android/Fire TV (Optional)" and the field "Mobile Device" was empty.

It complaint "Message malformed: Unknown device 'False'" when I hit "SAVE" button. I have to select a mobile device in order to save the form successfully.

Please note that the Automation Config and the frigate config below are trims of the relevant part of the yaml file saved before the new form was submitted.

### Version

0.12.0.1

### Automation Config

```yaml
- id: '1690736397245'
  alias: A person was detected - Camera Backyard
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.backyard
      notify_group: ADULT_MOBILES
      icon: mdi:cctv
      labels:
      - person
      message: '{{ camera_name }}: A {{ label }} is detected.'
      critical: 'false'
      base_url: https://ha.chubbie.duckdns.org/
      update_thumbnail: true
      title: '{{ camera_name }} - A {{ label }} is detected.'
```

### Frigate Config

```yaml
mqtt:
  enabled: True
  host: 10.27.0.50
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: frigate
  stats_interval: 5
  
detectors:
   coral:
     type: edgetpu
     device: usb

birdseye:
  enabled: True
  restream: True
  mode: continuous      

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

objects:
  track:
    - person
    - dog
    - cat

go2rtc:
  rtsp:
    username: "[omitted]"
    password: "[omitted]"

  streams:

    backyard:
      - rtsp://[omitted]:[omitted]@10.27.0.203:554/cam/realmonitor?channel=1&subtype=0
    backyard_sub:
      - rtsp://[omitted]:[omitted]@10.27.0.203:554/cam/realmonitor?channel=1&subtype=2
      
cameras:
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://[omitted]:[omitted]@127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[omitted]:[omitted]@127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
    live:
      stream_name: backyard
    detect:
      enabled: True
      width: 1280
      height: 720
    record:
      enabled: True
      events:
        pre_capture: 7
        post_capture: 5
        retain:
          default: 60
          mode: motion
    snapshots:
      enabled: True
      retain:
        default: 60
    motion:
      mask:
        - 1280,0,1280,304,1173,352,1100,324,1046,201,906,219,857,80,884,0
        - 0,225,53,82,105,67,116,0,0,0
        - 606,93,829,80,837,0,159,0,162,135
    objects:
      track:
        - person
      filters:
        person:
          min_area: 3000
    birdseye:
      enable: object
```
