### ISSUE TITLE
[Config Support]:  

### ISSUE THREAD

**Issue by FigJam23** [SgtBatten/HA_blueprints#115]
### Describe the problem you are having or the outcome you are trying to achieve.

Is it possible to have multiple state filters as I have a situation that I only want to be notified if my front door is closed and my security alarm is off. I have the front door added and working just not sure how to add the alarm state as well.

### Version

12

### Automation config file

```yaml
- id: '1699142087299'
  alias: Person Front Entry Detected
  description: Person Detected Front Entry
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.front_entry
      notify_device: 37b26494a4f38c444b5b290a668dd585
      notify_group: all_devices
      base_url: http://dilligaf.asuscomm.com:8123
      title: Person Detected
      message: A Person Was Detected At The Front Entry
      critical: 'true'
      alert_once: true
      update_thumbnail: true
      color: amber
      icon: mdi:cctv
      ios_live_view: false
      zone_filter: false
      zones: []
      labels:
      - person
      - package
      url_1: '{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4'
      url_2: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg'
      tap_action: '{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg'      
      state_entity: binary_sensor.front_door_rs
      state_filter: true
      state_filter_states:
      - 'off'
   #   cooldown: 60
```

### Frigate Config

```yaml
Na
```

### Any other information that may be helpful

Na
