### ISSUE TITLE
[Bug]: Can't get bounding boxes to appear in notifications

### ISSUE THREAD

**Issue by IsaacInsoll** [SgtBatten/HA_blueprints#118]
### Description

Hi, I've set my notification to show 'snapshot' (not 'thumbnail') but the notification that gets pushed to my iphone does *not* include the bounding box. 

When i click 'view snapshot' in notification it opens up a browser window that *does* have the bounding box but there doesn't seem to be a configuration that allows you to have the bounding box on the notification image itself. 

I've tried with the 'update image' option turned on and off without success. 

### Version

0.12.0.2

### Automation Config

```yaml
alias: Frigate - Back
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.back_door
    notify_group: ALL_DEVICES_NOTIFICATION
    base_url: <redacted>
    critical: "false"
    attachment: snapshot
    update_thumbnail: false
    labels:
      - person
    presence_filter: person.<my-name>
```
