### ISSUE TITLE
Add option for HASS agent notification[Config Support]: 

### ISSUE THREAD

**Issue by admiralroflknife** [SgtBatten/HA_blueprints#119]
### Describe the problem you are having or the outcome you are trying to achieve.

I use hass agent on my windows desktop for my home assistant integration. I'd like to be able to send a notification to it but the notification group option doesnt appear to work with it (after creating the group in configuration.yaml, the blueprint won't accept it) . Because the standard dropdown only supports mobile app I can not use that workflow either. Is there a way to get it to work with this blueprint? 

https://hassagent.readthedocs.io/en/latest/notifications/notification-usage-and-examples/

### Version

0.12.0.1

### Automation config file

```yaml
alias: Front Door - Frigate - Notify Sam someone at front door
description: Test v1 front door camera sees person
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    attachment: snapshot
    base_url: redacted
    camera: camera.frontdoor
    notify_device: 17fbb3df890673d633331fb0008a84d5
    message: "{{ label }} at front door"
    alert_once: true
    ios_live_view: true
    zone_filter: true
    zones:
      - Front_Deck
    labels:
      - person
    tap_action: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    url_1: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    url_2: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    cooldown: 171
    url_3: "{{base_url}}/lovelace"
    button_3: "Open home assistant "
```
