### ISSUE TITLE
[FAQ]: Frigate Camera input says "No Matching Entities Found"

### ISSUE THREAD

**Issue by SgtBatten** [SgtBatten/HA_blueprints#12]
### Describe the problem you are having or the outcome you are trying to achieve.

When configuring the blueprint, no entitles appear in the dropdown. 

![image](https://user-images.githubusercontent.com/24822223/232179169-5fbf3660-6e5f-43f3-b150-8b9d8562d0e1.png)

### Version

Any

### Automation config file

```yaml
alias: Frigate Notifications Beta
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: 
    notify_device: abcdefghijklmnop1234567890
```
