### ISSUE TITLE
[Bug]: Video/Clip in notification cannot be displayed

### ISSUE THREAD

**Issue by osworx** [SgtBatten/HA_blueprints#120]
### Description

Environement:
`Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2`

`Android Samsung Galaxy A02s / Version 12`

While the notification works perfectly (snapshot can be viewed), the clip cannot: showing just the media player and the "waiting" spinner .. nothing else happens.

### Version

0.12.0.1r (latest dev version)

### Automation Config

```yaml
- id: '1699612873350'
  alias: Benachrichtigung Michi verlässt Haus
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.michael
      zone_entity: zone.home
      notify_device: 4ca9e5bf0d5ef544bda70801c6756ad2
- id: '1699885619512'
  alias: Tür geöffnet > Nachricht an HA & Mobil Michi
  description: Sendet eine Benachrichtigung an HA & Mobil Michi wenn Tür geöffnet
    wurde
  trigger:
  - type: opened
    platform: device
    device_id: 85cd9e69daf7f02bf35eaa6e7fa8a672
    entity_id: 653b73648008ee55da50e61449ca8711
    domain: binary_sensor
  condition: []
  action:
  - device_id: 4ca9e5bf0d5ef544bda70801c6756ad2
    domain: mobile_app
    type: notify
    message: Tür wurde geöffnet
    title: Tür wurde geöffnet
  - service: notify.persistent_notification
    data:
      message: Tür wurde geöffnet
      title: Tür wurde geöffnet
  mode: single
- id: '1699885752803'
  alias: Tür geschlossen
  description: Sendet eine Benachrichtigung an HA wenn Tür geschlossen wurde
  trigger:
  - type: not_opened
    platform: device
    device_id: 85cd9e69daf7f02bf35eaa6e7fa8a672
    entity_id: 653b73648008ee55da50e61449ca8711
    domain: binary_sensor
  condition: []
  action:
  - device_id: 4ca9e5bf0d5ef544bda70801c6756ad2
    domain: mobile_app
    type: notify
    message: Tür wurde geöffnet
    title: Tür wurde geöffnet
  - service: notify.persistent_notification
    data:
      message: Tür wurde geöffnet
      title: Tür wurde geöffnet
  mode: single
- id: '1699955362070'
  alias: 'Waschmaschine Keller : Waschvorgang gestartet'
  description: Benachrichtigung an HA & Mobil Michi wenn Waschmaschine im Keller eingeschaltet
    wurde
  trigger:
  - type: voltage
    platform: device
    device_id: 6b4d0f9e82ffd2e61c8510603f3dcf08
    entity_id: 8e0756ec480bf5366b962d699ad20c5d
    domain: sensor
    above: 10
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: Waschmaschine eingeschaltet
  - device_id: 4ca9e5bf0d5ef544bda70801c6756ad2
    domain: mobile_app
    type: notify
    message: Waschmaschine eingeschaltet
  mode: single
- id: '1699956558892'
  alias: 'Waschmaschine Keller : Waschvorgang beendet'
  description: Sendet Nachricht an HA & Mobil Michi wenn Waschavorgang beendet ist
  trigger:
  - type: voltage
    platform: device
    device_id: 6b4d0f9e82ffd2e61c8510603f3dcf08
    entity_id: 8e0756ec480bf5366b962d699ad20c5d
    domain: sensor
    below: 10
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: Waschmaschine > Waschvorgang beendet
  - device_id: 4ca9e5bf0d5ef544bda70801c6756ad2
    domain: mobile_app
    type: notify
    message: Waschmaschine > Waschvorgang beendet
  mode: single
- id: '1700063241214'
  alias: Michael kommt nach Hause / verlässt Haus
  description: Benachrichtigung wenn Michael die Zone HOME erreicht/verlässt
  use_blueprint:
    path: panhans/zone_notification_extended.yaml
    input:
      persons:
      - person.michael
      zones:
      - zone.home
      duration: 3
      notify_device: 4ca9e5bf0d5ef544bda70801c6756ad2
      title_arriving: '{{ person }} ist angekommen'
      message_arriving: '{{ person }} hat {{ zone }} erreicht.'
      title_leaving: '{{ person }} geht'
      message_leaving: '{{ person }} verlässt {{ zone }}.'
      notification_color:
      - 250
      - 90
      - 226
      custom_action_leaving:
      - service: notify.persistent_notification
        data:
          message: Michi kommt bzw. geht
- id: '1700067363526'
  alias: Frigate Benachrichtigung (Person entdeckt)
  description: Sendet Benachrichtigung an Mobil Michi wenn Person durch Kamera entdeckt
    wird
  use_blueprint:
    path: SgtBatten/Beta.yaml
    input:
      camera: camera.torkamera
      notify_device: 4ca9e5bf0d5ef544bda70801c6756ad2
      title: Torkamera Benachrichtigung
      message: Person entdeckt ..
      alert_once: true
      attachment: snapshot.jpg
      ios_live_view: camera.torkamera
      sticky: true
      zone_filter: false
      button_2: Bild ansehen
      debug: true
      url_1: '{{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json[''after''][''camera'']
        | lower | replace(''-'',''_'')}}?token={{state_attr( ''camera.'' ~ camera,
        ''access_token'')}}'
      button_1: Aktuelles Bild
      button_3: Keine neue Benachrichtigung
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: *****
  user: *****
  password: *****

# RPI CPU SETTINGS
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  Torkamera:
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://*****/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://*****/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
    record:
      enabled:  true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: True
      timestamp: true
      retain:
        default: 5
        mode:  motion
    # mask and zone as manally defined 
    motion:
        mask:
          - 1159,368,1005,697,645,622,821,209
    zones:
      zone_0:
        coordinates: 630,235,576,73,161,183,192,300

birdseye:
  enabled: True
  mode: continuous
```
