### ISSUE TITLE
[Bug]: Settings >Mobile Device >>iPhone not detected

### ISSUE THREAD

**Issue by micAThome** [SgtBatten/HA_blueprints#121]
### Description

Trying to define an iPhone with iOS 17.x as **Mobile Device**.
But the only device I get is my own (Android Samsung):
![grafik](https://github.com/SgtBatten/HA_blueprints/assets/1905204/1c89bf5c-5aed-496f-b279-6cd3fdb45a94)

I've played around and checked all settings in HA.
Everywhere (e.g. at **Automatications**) I can select the iPhone, but not in this application ..

### Version

0.12.0.1r

### Automation Config

```yaml
- id: '1700067363526'
  alias: Frigate Benachrichtigung (Person entdeckt)
  description: Sendet Benachrichtigung an Mobiltels wenn Person durch Kamera entdeckt
    wird
  use_blueprint:
    path: SgtBatten/Beta.yaml
    input:
      camera: camera.torkamera
      notify_device: 4ca9e5bf0d5ef544bda70801c6756ad2
      title: Torkamera Benachrichtigung
      message: Person entdeckt ..
      alert_once: false
      attachment: thumbnail.jpg
      ios_live_view: camera.torkamera
      sticky: true
      zone_filter: false
      button_2: Video
      debug: true
      url_1: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
      button_1: Ansehen
      button_3: Keine neue Benachrichtigung
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
      url_2: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4'
      update_thumbnail: true
      base_url: https://*****
      cooldown: 30
      labels: []
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: ****
  user: ****
  password: ****

# RPI CPU SETTINGS
ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  Torkamera:
    ui:
      dashboard: true
    ffmpeg:
      inputs:
        - path: rtsp://****/Streaming/Channels/102
          roles:
            - detect
        - path: ****/Streaming/Channels/101
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
    record:
      enabled:  true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: True
      timestamp: true
      retain:
        default: 5
        mode:  motion
    # mask and zone as manually defined 
    motion:
        mask:
          - 1159,368,1005,697,645,622,821,209
    zones:
      zone_0:
        coordinates: 630,235,576,73,161,183,192,300

birdseye:
  enabled: True
  mode: continuous
```

**Comment by micAThome** [comment]
UPDATE: seems that HA has some problems to detect devices!
After adding a new device (integration) - here Fritzbox Tools - the mobile is also selctable in your application.

Sorry for the whole message, but maybe helpfully for all HA-novices (like I am currently) ..

**Comment by SgtBatten** [comment]
Don't really understand this one. 

The selector is simply filtered by devices that have been setup with the mobile app notify service (which is standard if the mobile apps been connected) so if that's done it should be there.

**Comment by SgtBatten** [comment]
> Fritzbox Tools -

Weird, should have nothing to do with this. 



> Now I have only to discover how you want to have that **Group setting**

You need to create a group of mobile devices. There will be plenty of examples for notify groups on the forums. Then just type the name of it here.

**Comment by micAThome** [comment]
> Don't really understand this one.
> 
> The selector is simply filtered by devices that have been setup with the mobile app notify service (which is standard if the mobile apps been connected) so if that's done it should be there.

On the iPhone is the app installed - since 24 hours.
That's why I could select it at other services in HA - irritating me, that it was not selectable in your application!
Guess HA added the device after enabling the Fritzbox tools - normally the device should be selectable after installing the mobile app, which was not the case here .. strange ..

Regarding the **Group**: as far as I could read in many docs, creating a group with persons (w. mobile phones) is in the current state of HA (as per Nov. 2023) not possible by the graphical editor (should be able through **Settings > Devices & Services >> Helper**) see: https://www.home-assistant.io/integrations/group/#notify-groups

Has to be done manually by creating a group.yaml and adding that to the configuration.yaml afterwards.
Or am I wrong (a hint in that direction would help me a lot).

**Comment by SgtBatten** [comment]
You can put yaml anywhere that is properly configured. To begin with I suggest you just put it in configuration.yaml to avoid the need for figuring out multiple files. 

```
notify:
  - name: Bill and Bob
    platform: group
    services:
      - service: mobile_app_bills_phone
      - service: mobile_app_pixel_7_pro
```      

Once created adding any of the following in the group input should work
Bill and Bob
bill_and_bob
notify.bill_and_bob
