### ISSUE TITLE
[Feature Request]: Translation

### ISSUE THREAD

**Issue by micAThome** [SgtBatten/HA_blueprints#122]
Just an assumption .. because of more users using that blueprint and some of them are not able to understand English, are there any plans to offer translations or translated texts?
I am sure that will bring more HA users to use such services like this.

If, I could offer my help for German.

**Comment by SgtBatten** [comment]
If you know how to make translations of a blueprint function i'm happy to entertain it. But i will not be able to maintain it so it's a difficult proposition.

**Comment by micAThome** [comment]
"Discovered" yesterday the lack of HomeAssistant not being able to offer localized blueprints - a shame (from my point of view).
That's why I have made this feature request: https://community.home-assistant.io/t/localized-blueprints-translating-existing/642473

Building translations should be an easy task for a software like this these days.
While the HA core has this option already, blueprints (and other) seems to have not.

I guess either this feature request will be declined or it will need a lot of time to add this possibility.

Therefore an option could be, to offer your (and others as well) blueprint in several versions: one in English and others in the language someone will translate (amd also maintain!).
Which means that such "translators" have to spend a few minutes for translating - which should be able.

For you this could end up in two (or more) directories, e.g.

* Main = https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FSgtBatten/HA_blueprints/blob/main/Frigate%20Camera%20Notifications/Stable
* Localized (e.g. de) = https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FSgtBatten/HA_blueprints/blob/main/Frigate%20Camera%20Notifications/Stable_DE

Just tell me about what you think ..

**Comment by azharkov78** [comment]
can i use variables?
Example:
```
variables:
  object_name:
    person: 🙍‍♂️
    cat: 🐱
    dog: 🐶
    car: 🚗
    truck: 🚗
    bird: 🐦
    bicycle: 🚲
    face: 👻
    license_plate: ℹ️
  camera_name:
    domofon: Домофон
    MainPTZCamera: Поворотная
    camera_3: улица
```
If i add in text mode, no new notifications.
