### ISSUE TITLE
[Config Support]: TV Notifications Dont seem to be working for me

### ISSUE THREAD

**Issue by PJGitHub9** [SgtBatten/HA_blueprints#129]
### Describe the problem you are having or the outcome you are trying to achieve.

Im trying to get tv notifications to work. For some reason I can get the blueprint to work whenever I set the device to just my phone, but when i add 'shield' the automation doesnt seem to run. I get weird errors in my HAS logs (im not sure if its related to this specific blueprint or other ones that have the same information just different camera name)

Zone Notification: Choose at step 1: Frigate Event: Error executing script. Unexpected error for repeat at pos 5: 'str' object has no attribute 'get'
Zone Notification: Choose at step 1: Frigate Event: Notify on new object: choice 1: Choose at step 1: default: Error executing script. Unexpected error for call_service at pos 1: 'str' object has no attribute 'get'
Zone Notification: Choose at step 1: Frigate Event: Notify on new object: choice 1: Error executing script. Unexpected error for choose at pos 1: 'str' object has no attribute 'get'
Zone Notification: Choose at step 1: Frigate Event: Error executing script. Unexpected error for choose at pos 4: 'str' object has no attribute 'get'
Zone Notification: Error executing script. Unexpected error for choose at pos 1: 'str' object has no attribute 'get'

### Version

0.12.0.2

### Automation config file

```yaml
#notworking
alias: Front Door - Objects
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_device: 94db483f897025ac3e1c34b6921506c7
    message: "{{ label }} detected - {{ camera_name }}"
    labels:
      - person
      - dog
      - cat
    zone_filter: true
    zones:
      - porch
      - fence
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    attachment: snapshot
    tv: true
    tv_position: bottom-right
    tv_size: medium
    notify_group: shield, PJs S23
#working - get notifications just on phone
alias: Driveway Right - Objects
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.driveway_right
    notify_device: 94db483f897025ac3e1c34b6921506c7
    message: "{{ label }} detected - {{ camera_name }}"
    labels:
      - person
      - car
      - dog
    zone_filter: true
    zones:
      - driveway
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    attachment: snapshot
    tv: true
    tv_position: bottom-right
    tv_size: medium
```
