### ISSUE TITLE
[Bug]: Sometimes thumbnail doesn't show up with Android notification

### ISSUE THREAD

**Issue by flyize** [SgtBatten/HA_blueprints#13]
### Description

Seemingly randomly, when I get an Android notification, there is no thumbnail associated with it.

### Version

0.11.0.15b

### Automation Config

```yaml
alias: "[Alert] Frigate Cat Feeder"
description: ""
use_blueprint:
  path: SgtB/frigate_0-11_notification_beta.yaml
  input:
    tv_transparency: 0%
    camera: camera.cat_feeder
    notify_device: 47119e198b28991dddf5d789f67df712
    base_url: https://nabulolol.ui.nabu.casa
    update_thumbnail: true
    tv_size: large
    tv_position: center
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera
    color: grey
```

### Any other relevant information

```yaml
Trace from failed run: https://pastebin.com/5NndWKCv
```
