### ISSUE TITLE
[Config Support]: can't view snapshots or clips via the notifications

### ISSUE THREAD

**Issue by kirilldem** [SgtBatten/HA_blueprints#131]
### Describe the problem you are having or the outcome you are trying to achieve.

Sometime back my snapshots or clips are not viewable on my phone. I get ERR_INVALID_RESPONSE error in the browser when trying open through the notification buttons. 

I get this on external and internal network. The URL it is trying to access is formatted so:

http://192.168.1.14:8123/api/frigate/notifications/XXXXXXXXXX/entrance/clip.mp4

This is the same for my external URL with correct base URL added.

I'm running latest hassio with 0.13 frigate. 

Where can I start to troubleshoot?

### Version

0.12.0.3

### Automation config file

```yaml
alias: Entrance Frigate Notifications (0.12.0.3)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.entrance
    notify_device: d3c95d3d2f8fd05b0bd3194db25b18b6
    base_url: https://ha.XXXXX.com
    message: "{{ label }} detected - {{ camera_name }}"
    alert_once: true
    color: "#cddc39"
```
