### ISSUE TITLE
[Bug]: IOS Notifications dont display 3 options

### ISSUE THREAD

**Issue by Ignattious** [SgtBatten/HA_blueprints#132]
### Description

Everything is working as expected in terms of the alerts but on IOS I don't get the 3 options for the action buttons.

Works fine on Android.

The alert is a simple message with the attached clip/snapshot which opens in a browser window.

### Version

12.0.3 / 12.0.2

### Automation Config

```yaml
alias: CCTV Alerts
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.front
    notify_device: a5a046430025524b58f2fe26237e37cd
    title: CCTV
    alert_once: true
    attachment: snapshot.jpg
    ios_live_view: camera.front
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera.
    color: "#000000"
    update_thumbnail: true
```
