### ISSUE TITLE
[Config Support]: Way to only notify on loitering events as opposed to movement

### ISSUE THREAD

**Issue by hpoon** [SgtBatten/HA_blueprints#133]
### Describe the problem you are having or the outcome you are trying to achieve.

Looking to send a notification on only loitering within the defined zone as opposed to any movement events.  I've tried configuring the loitering time option, but it seems to still send notifications on each movement.

### Version

0.12.0.2

### Automation config file

```yaml
alias: Front yard movement notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_yard
    notify_device: 1e650fd8ebeb6eb0f32e846965a882b8
    title: Front yard movement detected
    message: Front yard movement detected
    attachment: snapshot
    cooldown: 60
    tap_action: /lovelace
    button_1: View Clip
    icon: mdi:cctv
    loiter_timer: 1
    zone_filter: true
    zones:
      - Street
    labels: []
    zone_multi: true
```

### Frigate Config

```yaml
go2rtc:
  streams:
    Front_Yard_4K: xxxx
  webrtc:
    listen: ":8555"

cameras:
  Front_Yard:
    ffmpeg:
      inputs:
        - path: xxxx
          roles:
            - detect
    live:
      stream_name: Front_Yard_4K
    detect:
      width: 3840
      height: 2160
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - motorcycle
        - bird
    zones:
      Street:
        coordinates: 0,800,0,1038,0,1332,0,2160,729,2160,1798,2160,2675,2160,3247,2160,3586,2160,3840,2160,3840,1562,3584,1216,3414,1016,3231,786,3141,678,3840,795,3840,409,3704,299,3096,207,2452,169,1360,224,715,365,198,579
        objects:
          - person
          - car
          - motorcycle
```

### Any other information that may be helpful

Only included relevant parts of the config
