### ISSUE TITLE
[Config Support]: Unable to Receive Notifications (Android)

### ISSUE THREAD

**Issue by rmdrew88** [SgtBatten/HA_blueprints#134]
### Describe the problem you are having or the outcome you are trying to achieve.

I have downloaded the blueprint (v0.12.0.2), and frigate (v0.12.1 is successfully installed and configured in docker (unraid).  Both frigate and home assistant are connected to MQTT server (running on HA).  Frigate sensor status updates are accurately reflected in HA, and I can create very simple, functioning notification automations based on the sensors.  However, I am unable to receive notifications through automations created with the blueprint.  Currently, the blueprint automation config is as basic as I can make it in an attempt to try to get it to run so that I can customize from there.  I have only identified the camera entity from frigate, and the device to receive notifications, but I am still unable to trigger a notification.

### Version

12.0.2

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.2) - TEST
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door_2
    notify_device: 0336c4f869f9039b44d8b828f6d02ff1
```
