### ISSUE TITLE
[Feature Request]: IOS Interruption Level

### ISSUE THREAD

**Issue by nhadler** [SgtBatten/HA_blueprints#135]
**Describe what you are trying to accomplish and why in non technical terms**
IOS notifications offer the ability to set interruption levels beyond just critical notifications. It would be useful to be able to select time sensitive notifications for example. 

**Describe the solution you'd like**
The ability to choose `time-sensitive` instead of `critical` as an option for notifications for IOS devices.

**Additional context**
HA documentation explains the options [here](https://companion.home-assistant.io/docs/notifications/notifications-basic/#interruption-level).

**Comment by SgtBatten** [comment]
Would you mind testing this beta version. Thanks for your patience with this.

**Comment by dmgerow** [comment]
@SgtBatten unfortunately this did not work for me. I tested but enabling time-sensitive and then putting my phone in do not disturb mode. I did not get a notification while in focus mode as expected. YAML below:

```
alias: Frigate - Doorbell (SgtBatten beta)
description: ""
trace:
  stored_traces: 50
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.doorbell
    notify_group: all_mobile_devices
    base_url: <redacted>
    zone_filter: true
    zones:
      - porch
    notify_device: 7d09fc84ec882b2db09e242277d0d4fe
    presence_filter:
      - ""
    tap_action: /ccab4aaf_frigate-proxy/dashboard
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    interruption_level: time-sensitive
```

**Comment by SgtBatten** [comment]
Hmm okay. I implemented it in accordance with the docs as far as I know. Can you see any mistakes or are you able to check the notification log from the device to see what it received?

**Comment by dmgerow** [comment]
@SgtBatten yes it looks like a simple fix. here is what is being sent now
```
        push:
          sound:
            name: default
            volume: 1
            interruption-level: time-sensitive
```
Interruption level should be nested under `push` instead of `sound` like this (per [docs](https://companion.home-assistant.io/docs/notifications/notifications-basic/))
```
        push:
          sound:
            name: default
            volume: 1
          interruption-level: time-sensitive
```

Thanks again for considering this!
