### ISSUE TITLE
Notifications to Telegram

### ISSUE THREAD

**Issue by Moras360** [SgtBatten/HA_blueprints#137]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi. 
I am trying to use the Frigate Notifications blueprint to send notifications(snapshots) to Telegram. I have already setup MQTT and am running a home assistant container with docker compose. I am unsure what to enter into the : "Notification Group or Android/Fire TV (Optional)" field in the blueprint. I'm assuming that I have to enter the name I chose when I created two new entries inside of the config.yaml file (notify, telegram_bot). When I try to save the blueprint I am presented with the following error: "Message malformed: Unknown device". Any help will be appreciated

### Version

0.12.0.2

### Automation config file

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - platform: telegram
    name: telegram
    chat_id: 6449475063

telegram_bot:
  - platform: polling
    api_key: 6413761770:AAH3k0qH0ntQHY0OaBTYfv-mitxxBpLaDCg
    allowed_chat_ids:
      - 6449475063
```

### Frigate Config

```yaml
mqtt:
  host: mymqttip
  user: admin
  password: *****

ffmpeg:
  hwaccel_args: preset-vaapi
    
birdseye:
 enabled: true
 restream: true
 quality: 1
 height: 2688
 width: 1520
 mode: continuous 
    
cameras:
  HQ1_TEST:
    ffmpeg:
      inputs:
      #High Res stream for recording:
      #   - path: rtsp://ha:******@mycamip:554/cam/realmonitor?channel=1&subtype=0
      #     roles:
      #      - record
         
      #Low res stream used for live viewing:
         - path: rtsp://ha:******@mycamip:554/cam/realmonitor?channel=1&subtype=0
           roles:
            - detect
            
    detect:
      enabled:  true
      fps:      20
      width:    2688
      height:   1520

    objects:
      track:
        - person
        - car 
        - bird
        - motorcycle 
           
    snapshots:
      enabled: true
      required_zones:
        - paving
  
    record:
      enabled: false
      retain:
        days: 1
      events:
        retain:
          default: 10    
        required_zones:
        - paving  

    zones:
       paving:
         coordinates: 1827,387,2214,356,2191,234,2652,237,2688,1520,870,1520,880,580,581,525,585,446,766,399,1640,293
         objects:
           - person
           - car                    
       roof:
        coordinates: 0,1520,842,1520,833,604,0,410
        objects:
          - bird
                      
    motion:
      mask:  
         - 2688,0,2688,249,1700,224,1688,0
```
