### ISSUE TITLE
[Bug]: Unable to use notification groups

### ISSUE THREAD

**Issue by PovilasID** [SgtBatten/HA_blueprints#141]
### Description

After HA update to latest version I no longer get sent notification from group.
I am getting `Unknown device 'False'` for my group automations. I was using old 0.12.01a version, so I updated to latest beta 12.0.3 and when trying to create a new automation I could not even save it. 
I would get: "Message malformed: Unknown device 'False'"

### Version

0.12.0.3

### Automation Config

```yaml
description: ""
use_blueprint:
  path: SgtBatten/Beta1203.yaml
  input:
    camera: camera.siltnamis
    notify_group: kameros
alias: Frigate testing
```

### Any other relevant information

```yaml
Here is my notification group definition:

notify:
  - platform: html5
    vapid_pub_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    vapid_prv_key: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    vapid_email: me@me.com

  - platform: group 
    name: "Kameros"
    services:
    - service: mobile_app_phone1
    - service: mobile_app_phone2
    - service: html5_laptop_remote

```
```
