### ISSUE TITLE
[Config Support]: Notifications are not being sent / in the past it did work

### ISSUE THREAD

**Issue by Alex12358795** [SgtBatten/HA_blueprints#142]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi team,

Notifications are not being sent / nothing is happening. In the past everything was working.

I do not remember when it stopped working. I have already tried to remove and re-add the blueprint.
Snapshots and clips are being added into HA > Media > Frigate

### Version

0.12.0.2

### Automation config file

```yaml
alias: "3A: Frigate notification HA"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.3a_2
    notify_device: 8729dfed738dd1351839c679111d8074
    debug: true
    critical: "true"
```

### Frigate Config

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  host: 192.168.178.33


record:
  expire_interval: 10

go2rtc:
  streams:
    3b:
      - rtsp://***:***@192.168.178.63:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    3b_sub:
      - rtsp://***:***@192.168.178.63:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    3a:
      - rtsp://***:***@192.168.178.67:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
    3a_sub:
      - rtsp://***:***@192.168.178.67:554/cam/realmonitor?channel=1&subtype=1#backchannel=0



timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: shadow

cameras:
  3b:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/3b_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/3b
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:                 
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - 3Bfrontzone
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      3Bfrontzone:
        coordinates: 640,336,640,480,257,480,256,439,449,426
        objects:
          - person
    motion:
      mask:
        - 0,480,33,480,34,438,5,431
      threshold: 20
      contour_area: 15
    record:
      enabled: True
      retain: 
        days: 2 
        #mode: active_objects 
      events:
        retain:
          default: 5 
          mode: motion 
        pre_capture: 3 
        post_capture: 10  

  3a:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/3a_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/3a
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:                 
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.4
          threshold: 0.5
          min_area: 700
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - 3Afrontzone
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      3Afrontzone:
        coordinates: 366,409,640,346,640,480,96,480,79,367
        objects:
          - person
    motion:
      mask:
        - 0,480,33,480,34,438,5,431
      threshold: 20
      contour_area: 15
    record:
      enabled: True
      retain: 
        days: 2 
        #mode: active_objects 
      events:
        retain:
          default: 5 
          mode: motion 
        pre_capture: 3 
        post_capture: 10  
        

 

rtmp:
  enabled: false

birdseye:
  enabled: True
  restream: False
  width: 1280 
  height: 720
  quality: 1
  mode: objects

live:
  height: 640
  quality: 1
```
