### ISSUE TITLE
Frigate Notification (0.12.0.3) - Use of zones

### ISSUE THREAD

**Issue by PaulLeadbeater1** [SgtBatten/HA_blueprints#143]
### Description

I hope this is the right  place for me to submit, as it's my first feedback.
I'm using the above version of your notification blueprint and it works - without notifying stationary cars (!) or sending multiple notifications for the same event.  Well done with this update.
What is not working for me is specifying zones for detection - without a zone, objects get detected, clips sent to phone, etc. but, if I add one zone to the blueprint - no detection.
I haven't gotten my head around all your yaml code yet, so I can't see what is going wrong.
I would be grateful for a few pointers as to where to investigate my problem, unless, of course, this is actually a bug!!
Many thanks,

Paul.

### Version

0.12.0.3

### Automation Config

```yaml
alias: md_frigate_driveway
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.front_door
    notify_device: 77a846af840e2437f1198a2a396d40e6
    zone_multi: false
    zone_filter: false
    zones: []
    labels:
      - person
      - car
    cooldown: 1
    debug: true
    silence_timer: 0
    update_thumbnail: false
    video: ""
    attachment: thumbnail.jpg
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.3.19
  port: 1883
  topic_prefix: frigate
#  client_id: frigate_mqtt
  user: mqtt-user
  password: <redacted>
  stats_interval: 60
detectors:
  coral:
    type: edgetpu
    device: usb
go2rtc:
  streams:
  # front driveway
    front_door_rtsp_high:
    - rtsp://tapotc65:ribblestraxs1@192.168.3.209:554/stream1
    front_door_rtsp_low:
    - rtsp://tapotc65:ribblestraxs1@192.168.3.209:554/stream2
  # front door
    front_door_main_rtsp_high:
    - rtsp://admin:Ribblestraxs1@192.168.3.72:554/H264/ch1/main/av_stream
    front_door_main_rtsp_low:
    - rtsp://admin:Ribblestraxs1@192.168.3.72:554/H264/ch1/sub/av_stream
 # landing
    front_inside_rtsp_high:
    - rtsp://admin:L2E5743A@192.168.3.71:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    front_inside_rtsp_low:
    - rtsp://admin:L2E5743A@192.168.3.71:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
  # passageway/hall
    passageway_rtsp_low:
    - rtsp://DH7CJyZy:g5NUp6SMKGs4bry1@192.168.3.16:554/live/ch1
  # back garden
    backgarden_rtsp_high:
    - rtsp://admin:Ribblestraxs1@192.168.3.70:554/H264/ch1/main/av_stream
    backgarden_rtsp_low:
    - rtsp://admin:Ribblestraxs1@192.168.3.70:554/H264/ch1/sub/av_stream
cameras:
# Landing
  front_inside:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_inside_rtsp_low
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      - cat
      filters:
        person:
          threshold: 0.7
        cat:
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: true
      events:
        retain:
          default: 1
          mode: active_objects
    motion:
      mask:
        - 640,0,640,56,523,57,425,53,425,0
# Landing - END
# front door
  front_door_main_rtsp_low:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_door_main_rtsp_low
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
      - person
      filters:
        person:
          threshold: 0.7
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: true
      events:
        retain:
          default: 1
          mode: active_objects
    motion:
      mask:
        - 0,21,192,21,190,48,0,44
    zones:
      zone_front_door:
        coordinates: 0,58,75,55,146,55,212,58,210,0,437,0,640,0,640,214,640,480,0,480
        objects:
          - person
# front area (driveway)
  front_door:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_door_rtsp_low
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - cat
      - car
      filters:
        person:
          threshold: 0.7
          mask:
            - 167,61,333,55,572,94,640,0,463,0,240,0,0,0,0,92
        cat:
          threshold: 0.8
        car:
          threshold: 0.7
          mask:
            - 118,57,333,55,565,86,640,0,463,0,0,0,0,105,49,64
          min_area: 80000
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: true
      events:
        retain:
          default: 1
          mode: active_objects
    motion:
      mask:
        - 0,90,53,63,101,57,145,58,200,57,244,55,319,53,381,52,467,59,561,71,567,0,464,0,287,0,0,0
    zones:
      drive_far:
        coordinates: 589,163,458,169,390,165,324,164,239,165,160,164,77,159,26,155,52,132,73,112,109,85,157,72,212,60,287,58,365,61,430,65,518,79
        objects:
          - car
      drive_near:
        coordinates: 0,253,0,360,44,360,106,360,207,360,333,360,482,360,640,360,640,330,640,282,612,222,547,226,432,220,253,216,31,216
        objects:
          - car
# front area (driveway) END
# passageway / hall
  passageway:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/passageway_rtsp_low
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
      - person
      - cat
      filters:
        person:
          threshold: 0.7
        cat:
          threshold: 0.8
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: true
      events:
        retain:
          default: 1
          mode: active_objects
    zones:
      zone_0: # kitchen door
        coordinates: 88,257,91,298,211,289,176,247,123,249
      zone_1: # hallway
        coordinates: 166,316,98,324,108,360,251,360,238,309
    motion:
      mask:
        - 640,0,640,21,567,22,509,24,434,23,433,0
 #back garden 
  backgarden:
    rtmp:
      enabled: false
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/backgarden_rtsp_low
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      width: 640
      height: 480
      fps: 5
    motion:
      mask:
        - 0,0,32,0,64,0,98,0,148,0,193,0,193,47,156,47,111,44,53,42,0,47
    objects:
      track:
      - person
      - cat
      filters:
        person:
          min_score: 0.6
          threshold: 0.75
          mask:
            - 0,360,56,442,93,395,119,325,164,258,131,106,106,47,38,58,0,86
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: true
      events:
        retain:
          default: 11
          mode: active_objects
```
