### ISSUE TITLE
[Config Support]: Custom Action (Auto Trigger in Loop) incompatible with wait?

### ISSUE THREAD

**Issue by PovilasID** [SgtBatten/HA_blueprints#146]
### Describe the problem you are having or the outcome you are trying to achieve.

When I configure Custom Action (Auto Trigger in Loop) that includes a wait command I experience one or all of these problems:
- Snapshot is not attached to notification.
- Notification is sent only after the timer is over.
- Notification is not sent at all.

### Version

0.12.0.3

### Automation config file

```yaml
alias: Testing Frigate Door NEW automation
description: ""
use_blueprint:
  path: SgtBatten/Beta1203.yaml
  input:
    camera: camera.doors
    notify_device: 25758f3df45db115174a72509124f7f5
    color: "#ff9800"
    icon: mdi:cctv
    sticky: true
    channel: alarm_stream
    zone_filter: true
    zones:
      - sodas
    labels:
      - person
    button_2: Open HA
    custom_action_auto: []
    debug: true
    critical: "true"
    update_thumbnail: true
    message: Person at the door
    attachment: snapshot.jpg?bbox=1&crop=1
    notify_group: kameros
    video: ""
    custom_action_auto_multi:
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: telegram_bot.send_video
        data:
          authentication: digest
          url: >-
            http://HA-IP:8123/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4
          target: -000000000
          timeout: 500
          caption: "{{message}}"
```

### Any other information that may be helpful

I would put a wait in front of telegrams send video or my custom rclone backup clip send command because the clip would be incomplete if triggered at the time of notification. I use telegram as a clip backup. 
I had used an earlier version to provide these features for myself reliably however I never contributed them back because I was not 100 proc sure what part was one that was effective.
