### ISSUE TITLE
[Bug]: Doesn't use new home assistant icon

### ISSUE THREAD

**Issue by muddro1** [SgtBatten/HA_blueprints#148]
### Description

Very minor, but for some reason the default home assistant icon the blueprint uses is the old style. I have no idea why it's pulling out the old one instead of the new one. Have no issues with other phone notifications. 

### Version

12.0.3

### Automation Config

```yaml
alias: "1. Camera: Front Door Notification"
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    tv_transparency: 0%
    camera: camera.front_door_bell
    base_url: https://xxxxxxxx
    critical: "false"
    alert_once: true
    attachment: snapshot
    channel: Front Door
    zone_filter: false
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    tv_size: large
    tv_position: center
    color: red
    ios_live_view: false
    notify_group: both_phones
    button_2: View Stream
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    debug: true
    sound: none
    notify_device: f9045f28de5776f3a09a8b982b59141f
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    update_thumbnail: true
    android_auto: true
    url_3: custom-{{ camera }}
    button_3: Unlock the Door
    custom_action_manual:
      - service: lock.unlock
        metadata: {}
        data: {}
        target:
          entity_id: lock.front_door_lock
```
