### ISSUE TITLE
[Bug]: Switching to 0.13.0 breaks the view snapshot/view clip notification links

### ISSUE THREAD

**Issue by JBakers** [SgtBatten/HA_blueprints#149]
### Description

I updated Frigate to 0.13.0 and now the view snapshot/clip links in the notifications dont work anymore.
I get 502 bad gateway.
I think this has something to do with resolving homeassistant.local which is another problem for me (tailscale somehow doesnt like this)

so I tried adding base_url.
But then i got a 404 not found.
Links i get when adding the base url:

http://192.168.178.66:5000/api/frigate/notifications/1704738641.585322-76rqds/snapshot.jpg
http://192.168.178.66:5000/api/frigate/notifications/1704738641.585322-76rqds/zijkant/clip.mp4
(results in 404)

When I download a clip from the webinterface itself the URL is this:

http://192.168.178.66:5000/api/events/1704738641.585322-76rqds/clip.mp4?download=true

I already reinstalled both addon and integration.
Switching back to frigate 0.12.1 fixes this problem. (but 0.13.0 has a lot better object detection also at night, which I really need).

### Version

both stable and beta

### Automation Config

```yaml
alias: Frigate Zijkant Nieuw
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    #base_url: http://192.168.178.66:5000
    camera: camera.zijkant
    notify_device: 8e207b3d5cd18918042f48defd666ad0
    zone_filter: true
    zones:
      - zijkant
    labels:
      - person
      - cat
      - dog
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: core-mosquitto
  port: 1883
  user: XXX
  password: XXX
  topic_prefix: frigate
  
database:
  path: /config/frigate.db

#ffmpeg:
#  hwaccel_args: preset-vaapi

record:
  enabled: True
  #retain:
  # days: 0
  # mode: motion
  events:
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 60
      
detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  bounding_box: true
  enabled: true

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - mouse
    - car
    - motorcycle
    - bicycle
    # - bus
    - bird
    - cat
    - dog
    # - horse
    # - sheep
    # - cow

go2rtc:
  streams:
    Schuur:
      - rtsp://XXX:XXX@192.168.178.191:554/Streaming/Channels/101
    Speelkamer:
      - rtsp://XXX:XXX@192.168.178.190:554/Streaming/Channels/101
    Oprit:
      - rtsp://XXX:XXX@192.168.178.193:554/Streaming/Channels/101
    Babyfoon:
      - rtsp://XXX:XXX@192.168.178.103:8554/Streaming/Channels/101
    Test:
      - rtsp://XXX:XXX@192.168.178.192:8554/Streaming/Channels/101
      
 
cameras:
  Schuur:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.178.191:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://XXX:XXX@192.168.178.191:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 480
      
  Speelkamer:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.178.190:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://XXX:XXX@192.168.178.190:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 480

    objects:
      filters:
        person:
          min_area: 3000
        bicycle:
          mask:
            - 0,480,640,480,640,0,0,0
        car:
          mask:
            - 0,480,640,480,640,0,0,0
        cat:
          mask:
            - 0,480,640,480,640,0,0,0
        dog:
          mask:
            - 0,480,640,480,640,0,0,0
        motorcycle:
          mask:
            - 0,480,640,480,640,0,0,0

  Oprit:
    ffmpeg:
      inputs:
#        - path: rtsp://XXX:XXX@192.168.178.193:554/Streaming/Channels/101
#          roles:
#            - record
        - path: rtsp://XXX:XXX@192.168.178.193:554/Streaming/Channels/101
          roles:
            - detect
            
    zones:
      oprit:
       coordinates: 1920,1080,0,1080,834,391,1676,357,1703,0,1920,0
      straat:
       coordinates: 806,367,1619,334,1646,0,0,0,0,1080

    detect:
      width: 1920
      height: 1080

  Babyfoon:
    ffmpeg:
      output_args:
       record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://XXX:XXX@192.168.178.103:8554/Streaming/Channels/101
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      
  Zijkant:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@192.168.178.192:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://XXX:XXX@192.168.178.192:554/Streaming/Channels/101
          roles:
            - detect
    objects:
      filters: 
        person:
          min_area: 4000
          mask:
            - 269,560,278,720,222,720,120,369,73,58,94,0,176,0
            - 584,267,620,267,613,181,587,178
        car:
          mask:
            - 1280,720,1280,99,0,226,0,720
    motion:
      mask:
        - 888,226,817,206,810,87,893,29        

    zones:
      zijkant:
       coordinates: 1056,720,331,720,269,222,539,185
       
    detect:
      width: 1280
      height: 720
```
