### ISSUE TITLE
[Bug]: Critical Notification not working with template

### ISSUE THREAD

**Issue by raydenl** [SgtBatten/HA_blueprints#150]
### Description

I'm using a template for critical notifications that returns true/false, but I am never getting a critical alert (iOS) using this. I have confirmed when it's returning true, using the Developer tools template helper. If I just use a hard-coded 'true' value for the Critical Notification value it works. I'm not sure if it's an issue with this particular template, or all templates.

### Version

0.12.0.2

### Automation Config

```yaml
alias: Frigate office notifications
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.office
    notify_device: eb5214a261cb24111086c006fad07a05
    base_url: https://hass.myinstancename.online/
    notify_group: parents_mobiles
    critical: >-
      {{'22:30' <= states('sensor.time') <= '23:59' or '00:00' <=
      states('sensor.time') < '06:00'}}
```
