### ISSUE TITLE
[Config Support]: cant select camera from drop-down menu

### ISSUE THREAD

**Issue by nixxon94** [SgtBatten/HA_blueprints#151]
### Describe the problem you are having or the outcome you are trying to achieve.

I have Frigate and EMQX as broker working fine. Snapshots and recordings are displayed in the frigate tab.
I have a single camera called 'garage'

The drop-down menu of the blueprint says no cameras/ entities detected.
What am I missing?

### Version

2024.1.3

### Automation config file

```yaml
n.a.
```

### Frigate Config

```yaml
mqtt:
  host: a0d7b954-emqx
  user: frigate
  password: Password1

detectors:
    coral:
        type: edgetpu
        device: usb

cameras:
    garage:
        ffmpeg:
            inputs:
                - path: rtsp://admin:VFGYAG@192.168.178.73:554/H.264
                  roles:
                    - detect
                    - record
        snapshots:
            enabled: True
        detect:
            enabled: True
        objects:
            track:
                - person
        record:
            enabled: True
            retain:
                days: 7
                mode: motion
            events:
                retain:
                    default: 14
                    mode: active_objects
```
