### ISSUE TITLE
Issue with notification thumbnail link on IOs companion app

### ISSUE THREAD

**Issue by tonysystem76** [SgtBatten/HA_blueprints#154]
### Describe the problem you are having or the outcome you are trying to achieve.

So I have the notifications working with the companion app, and a thumbnail pops up with the notification. However, when I click on the notification it goes to a white screen with the error "Event not found"

### Version

0.12.0.2

### Automation config file

```yaml
mqtt:
  enabled: True
  host: 192.168.0.5
  port: 1883
  user: user
  password: password

go2rtc:
  streams:
    computer_camera:
      - rtsp://user:password!@192.168.0.229:554/cam/realmonitor?channel=1&subtype=0
    computer_camera_sub:
      - rtsp://user:password!@192.168.0.229:554/cam/realmonitor?channel=1&subtype=1
cameras:
  computer_camera:
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      inputs:
        - path: rtsp://127.0.0.1:8554/computer_camera
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/computer_camera_sub
          input_args: preset_rtsp_restream
          roles:
             - record
    objects:
      track:
        - person
        - cat
    detect:
      enabled: True
      width: 640
      height: 480
    record:
      enabled: False
      retain:
        days: 2
        mode: motion
detectors:
    cpu1:
      type: cpu
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.0.5
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60
```
