### ISSUE TITLE
[Bug]: Custom Action (Manual trigger) got error 404

### ISSUE THREAD

**Issue by Emilef22** [SgtBatten/HA_blueprints#157]
### Description

I set a custom action (manual trigger) on my notifications to unlock my door but when I click on the trigger on my cellphone notification, I get a black page with error 404. 

### Version

0.12.0.3

### Automation Config

```yaml
alias: Frigate Notif Reolink cell 2
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.reolink
    message: "{{ label }} detected - {{ camera_name }}"
    critical: "true"
    silence_timer: 0
    button_3: View Clip
    url_3: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    tv: false
    tv_position: top-right
    tv_transparency: 25%
    debug: true
    notify_device: 5ee986a4b28d548f0d5c289c29c4b2da
    attachment: snapshot.jpg
    android_auto: true
    custom_action_manual:
      - service: lock.unlock
        data: {}
        metadata: {}
        target:
          entity_id: lock.avant_2
        enabled: true
    tv_duration: 5
    url_1: app://com.mcu.reolink
    button_1: Reolink App
    url_2: custom-{{ camera }}
    button_2: Débarrer porte
    tap_action: custom-{{ camera }}
```

### Any other relevant information

```yaml
I've tried with another action, like turn on a light, and I get the same error 404.
I've also tried with the base url set in the automation and I got the same problem.
```
