### ISSUE TITLE
[Bug]: Zone Filter Disallowing Events that Should Be Sent

### ISSUE THREAD

**Issue by wraith1385** [SgtBatten/HA_blueprints#158]
### Description

I have a zone for my doorbell called porch.  When I turn on the zone filter and select porch as the zone, notifications no longer get sent even though I can see the events in the Frigate gui.  

### Version

0.12.0.2

### Automation Config

```yaml
alias: Doorbell Motion
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.doorbell
    notify_device: 64597986e2ec6e8c14750c46a3ab326d
    attachment: snapshot
    cooldown: 90
    zone_filter: true
    zones:
      - porch
    labels: []
```

### Frigate Config

```yaml
# yaml-language-server: $schema=http://ccab4aaf-frigate-fa:5000/api/config/schema.json

database:
  path: /config/frigate.db
  
mqtt:
  host: core-mosquitto
  port: 1883
  user: *******
  password: *******

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-ubiquiti
    rtmp: preset-rtmp-ubiquiti # recommend using go2rtc instead

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
      # Optional: Enable birdseye view (default: shown below)
  enabled: True
      # Optional: Restream birdseye via RTSP (default: shown below)
      # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
      # Optional: Width of the output resolution (default: shown below)
  width: 1280
      # Optional: Height of the output resolution (default: shown below)
  height: 720
      # Optional: Encoding quality of the mpeg1 feed (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
      # Optional: Mode of the view. Available options are: objects, motion, and continuous
      #   objects - cameras are included if they have had a tracked object within the last 30 seconds
      #   motion - cameras are included if motion was detected in the last 30 seconds
      #   continuous - all cameras are included always
  mode: objects

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  retain:
    default: 10
    objects:
      person: 15
  quality: 80

detect:
  fps: 5
  enabled: True
    # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
    # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
    # Optional: Configuration for stationary object tracking
  stationary:
      # Optional: Frequency for confirming stationary objects (default: same as threshold)
      # When set to 1, object detection will run to confirm the object still exists on every frame.
      # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
      # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
      # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
      # This can help with false positives for objects that should only be stationary for a limited amount of time.
      # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
      # car at the default.
      # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
      #          There are very few situations where you would want it disabled. It is NOT recommended to
      #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
        # Optional: Default for all object types (default: not set, track forever)
      default: 3000
        # Optional: Object specific values
      objects:
        person: 1000
    # Optional: Milliseconds to offset detect annotations by (default: shown below).
    # There can often be latency between a recording and the detect process,
    # especially when using separate streams for detect and record.
    # Use this setting to make the timeline bounding boxes more closely align
    # with the recording. The value can be positive or negative.
    # TIP: Imagine there is an event clip with a person walking from left to right.
    #      If the event timeline bounding box is consistently to the left of the person
    #      then the value should be decreased. Similarly, if a person is walking from
    #      left to right and the bounding box is consistently ahead of the person
    #      then the value should be increased.
    # TIP: This offset is dynamic so you can change the value and it will update existing
    #      events, this makes it easy to tune.
    # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0
  
record:
  enabled: True
  sync_recordings: True
  retain:
    days: 0
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 15
      mode: motion

objects:
        # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat
    - car

cameras:
  bedroom:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/WYjjoiQGqGA5aJuS?enableSrtp
          roles:
            - detect
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/EyTwaGcG1N0bJMc1?enableSrtp
          roles:
            - detect
    motion:
      mask:
        - 1600,128,1600,693,627,722,0,612,0,126
    record:
      events:
        required_zones:
          - porch
    snapshots:
      required_zones:
        - porch
    zones:
      porch:
        coordinates: 1535,935,0,621,0,1200,1600,1200
  entryway:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/zibxWbSV6oKnJP8U?enableSrtp
          roles:
            - detect
  kitchen:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/o3vIHiXpRI9htPCX?enableSrtp
          roles:
            - detect
  living_room:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/YskQUWIojTzZKPjM?enableSrtp
          roles:
            - detect
  office:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/w9KLU5o9R80VLhQI?enableSrtp
          roles:
            - detect
  spare_bedroom:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/VHCvQD7V9wmjHxp8?enableSrtp
          roles:
            - detect
  stairs:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/lEHbqsWwfoAujTBZ?enableSrtp
          roles:
            - detect
```
