### ISSUE TITLE
Unable to get notifications to work.

### ISSUE THREAD

**Issue by navarrolux** [SgtBatten/HA_blueprints#159]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,
I am relatively new to HA and Frigate.
Recently I migrated my instance of Frigate to a new server.
surprisingly everything seems to be working (recordings and events). 

Since the I moved so a new server the IP address changed and I had to reintegrate Frigate to HA.
I was able to reconfigure my camas and I can see them in my dashboard (live feed and recordings).

The issue comes when using the blueprint to send notifications.
The automation do not fire.
Here is what I have tried:
- Reimported the blueprint
- recreated the automation (selecting the new camera entities)
- Simplifies the automation so there are no conditions
- Restarted HA.

Please help, I'm at a loss.
Thanks in advance.

### Version

0.12.0.2

### Automation config file

```yaml
#This is the bare-bones notification automation.
alias: "[test]frigate notif"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.backyard_camera_2
    notify_device: 5a2133bf81120d6d055e4a41a728fa16
```
