### ISSUE TITLE
[Not receiving Notification]: Not receiving notification on IOS mobile

### ISSUE THREAD

**Issue by Frazou1** [SgtBatten/HA_blueprints#162]
### Description

Just setup the last stable version of Blueprint for notification and i dont receive any notification but i see the automation fired

### Version

12.0.2

### Automation Config

```yaml
alias: Notif-Cam_Arriere
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.cam_ext_arriere
    notify_device: 719c7bb8a919fd359eee8bcbf3d50dad
    base_url: https://frazhome.zapto.org
    message: "{{ label }} detected - {{ camera_name }}"
    alert_once: true
    attachment: snapshot
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    ios_live_view: true
    zone_filter: true
    labels:
      - person
    critical: "true"
```
