### ISSUE TITLE
[Bug]: Images not showing on FireTV 

### ISSUE THREAD

**Issue by mattbruman** [SgtBatten/HA_blueprints#164]
### Description

Using the newest blueprint tried the Beta too 
![image](https://github.com/SgtBatten/HA_blueprints/assets/43623584/7d0043c5-c5f5-4741-aa9b-804916db58bf)
I am getting the notification on my FireTV just fine but the image is not showing. The images show on my HA App fine.
Frigate version 0.13.1-34fb1c2

### Version

0.12.0.3

### Automation Config

```yaml
alias: "Frigate Back Person Lab Projector "
description: ""
use_blueprint:
  path: SgtBatten/Beta2.yaml
  input:
    camera: camera.back
    notify_device: 648fc34ebce520883d085d6d959bd19a
    notify_group: lab_fire_tv
    title: Person detected
    message: A Person was detected on the back camera.
    attachment: snapshot.jpg?bbox=1
    tv: true
    tv_size: medium
    tv_duration: 15
    tv_position: bottom-right
    labels:
      - person
    tv_transparency: 50%
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  user: [REDACTED]
  password: "[REDACTED]"
  host: 192.168.1.10
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

# Optional: birdseye configuration
birdseye:
# Optional: Enable birdseye view (default: shown below)
  enabled: True
# Optional: Width of the output resolution (default: shown below)
  width: 1920
# Optional: Height of the output resolution (default: shown below)
  height: 1080
# Optional: Encoding quality of the mpeg1 feed (default: shown below)
# 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
# Optional: Mode of the view. Available options are: objects, motion, and continuous
#   objects - cameras are included if they have had a tracked object within the last 30 seconds
#   motion - cameras are included if motion was detected in the last 30 seconds
#   continuous - all cameras are included always
  mode: motion

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  events:
    retain:
      default: 1
      mode: active_objects
      objects:
        dog: 1
        car: 2

go2rtc:
  streams:
    front_right:
    - rtsp://[REDACTED]@192.168.1.113:554/h264Preview_01_main
    - "ffmpeg:front_right#video=h264"
    front_right_sub:
    - rtsp://[REDACTED]@192.168.1.113:554/h264Preview_01_sub
    - "ffmpeg:front_right_sub#video=h264"
    back:
    - rtsp://[REDACTED]@192.168.1.247:554/h264Preview_01_main
    - "ffmpeg:back#video=h264"
    back_sub:
    - rtsp://[REDACTED]@192.168.1.247:554/h264Preview_01_sub
    - "ffmpeg:back_sub#video=h264"
    front:
    - rtsp://[REDACTED]@192.168.1.48:554/h264Preview_01_main
    - "ffmpeg:front#video=h264"
    front_sub:
    - rtsp://[REDACTED]@192.168.1.48:554/h264Preview_01_sub
    - "ffmpeg:front_sub#video=h264"
    front_doorbell:
    - rtsp://[REDACTED]@192.168.1.98:554/h264Preview_01_main
    - "ffmpeg:front_doorbell#video=h264"
    garage-door:
    - rtsp://[REDACTED]@192.168.1.185:554/h264Preview_01_main
    - "ffmpeg:garage-door#video=h264"
    side:
    - rtsp://[REDACTED]@192.168.1.50:554/h264Preview_01_main
    - "ffmpeg:side#video=h264"
    #side_doorbell:
    #- rtsp://[REDACTED]@192.168.1.141:994/doorbell
    #- "ffmpeg:side_doorbell#video=h264"


ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  front_right:
    birdseye:
      mode: continuous
    ffmpeg:
      hwaccel_args: preset-vaapi
      #output_args:
        #record: preset-record-generic-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/front_right
        #input_args: preset-rtsp
        roles:
          - record
      - path: rtsp://127.0.0.1:8554/front_right_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1

    motion:
      mask:
      - 577,99,725,61,914,36,1032,44,1182,153,1436,379,1536,279,1536,0,0,0,0,303
    zones:
      walkway:
        coordinates: 
          390,392,524,283,728,193,921,160,894,79,656,82,543,129,470,155,432,170,335,215,288,245
        objects:
        - person
      driveway_entrance:
        coordinates: 893,128,1077,140,997,57,860,44
        objects:
        - car
      driveway:
        coordinates: 1481,576,1062,576,900,114,1072,133
        objects:
        - person
        - car
    objects:
      track:
      - person
      - car
      filters:
        car:
          mask:
          - 0,0,1536,0,1536,576,1482,576,1007,51,867,50,1015,576,0,576
        person:
          threshold: 0.81
          mask:
          - 1059,80,691,73,321,204,0,348,0,0,1111,0,1536,0,1536,459
          - 819,343,787,87,509,124,550,384
  front:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/front
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/front_sub
        input_args: preset-rtsp-restream
        roles:
          - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask:
      - 0,0,1431,0,1920,0,1920,227,1319,243,816,338,0,728
    zones:
      driveway:
        coordinates: 1779,331,1896,315,1886,233,965,315,842,384,1036,369
        objects:
        - car
        - person
      driveway_entrance:
        coordinates: 927,378,1001,269,682,333,489,428
        objects:
        - car
      porch:
        coordinates: 1920,329,1920,799,1259,789,1094,636,1183,483,1323,392,1540,306
        objects:
        - person
      walkway:
        coordinates: 995,549,1232,735,1341,581,1282,353,1038,355
        objects:
        - person

    objects:
      track:
      - person
      - car
      filters:
        car:
          mask:
          - 0,1080,1920,1080,1920,302,1453,351,1107,366,683,402,574,427,0,0
          - 0,0,1920,0,1920,197,1920,227,1797,250,704,335,0,717
        person:
          threshold: 0.80
          mask:
          - 0,0,0,726,837,323,1856,218,1851,162,1920,0

  garage-door:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/garage-door
        roles:
        - detect
        - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      stationary:
        interval: 30
        threshold: 20
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask:
      - 0,0,963,0,1149,0,1198,50,1013,132,252,516,0,919
    objects:
      track:
      - person
      - car
      filters:
        person:
          threshold: 0.80
          mask:
          - 1156,71,1135,0,0,0,0,743,319,655,247,513

  side:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: preset-rtsp-restream
      inputs:
      - path: rtsp://127.0.0.1:8554/side
        roles:
        - detect
        - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true

    motion:
      mask:
      - 0,497,0,0,2560,0,2560,363,2328,50,1726,0,1472,0,1455,274,1376,370,670,387
    zones:  
      driveway_entrance:
        coordinates: 2159,0,2332,255,1882,222,1906,0
        objects:
          - car
      side_door:
         coordinates: 1512,0,2180,44,2271,167,1911,187,1747,817,1399,777
         objects:
          - person
    objects:
      track:
      - person
      - car
      filters:
        car:
          threshold: 0.80
          mask:
          - 0,0,2560,0,2560,336,2307,45,1901,0,1027,1440,0,1440,25,615
        person:
          threshold: 0.80
          mask:
          - 1916,0,2285,52,2443,228,2560,408,2560,0
  back:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/back
        input_args: preset-rtsp-restream
        roles:
        - record
      - path: rtsp://127.0.0.1:8554/back_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1536 # <---- update for your camera's resolution
      height: 576 # <---- update for your camera's resolution 
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask:
      - 0,0,1537,0,1536,576,1163,576,1347,266,990,97,780,37,666,43,472,87,461,171,99,327,115,410,0,517
    zones:
      backyard:
        coordinates: 696,576,1074,576,1228,254,1122,153,909,68,723,33,652,58,572,66,477,145,545,417
      gate:
        coordinates: 603,576,542,423,453,240,316,263,89,576
    objects:
      track:
      - person
      - dog
      filters:
        dog:
          mask:
          - 867,59,1232,212,1330,0,1113,0,759,0
        person:
          threshold: 0.80
          mask:
          - 94,331,466,177,470,62,811,37,1242,181,1325,0,0,0,0,506,109,421

  front_doorbell:
    birdseye:
      mode: objects
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/front_doorbell
        input_args: preset-rtsp-restream
        roles:
          - record
          - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
      stationary:
        interval: 1
        threshold: 50
    snapshots: # <----- Enable snapshots
      enabled: true
    record:
      enabled: true
      retain:
        days: 1
    motion:
      mask:
      - 0,680,0,0,2560,0,2560,713,1253,508,1054,1163,941,1185,501,1288,0,1381
    objects:
      track:
      - person
      - car
      filters:
        car:
          threshold: 0.80
          mask:
          - 0,1331,911,1199,2560,1177,2560,649,0,546
        person:
          threshold: 0.80
          mask:
          - 0,867,2560,919,2560,1195,1574,1205,0,1134


#  side_doorbell:
#    birdseye:
#      mode: objects
#    ffmpeg:
#      hwaccel_args: preset-vaapi
#      output_args:
#        record: preset-record-generic-audio-copy
#      inputs:
##      - path: rtsp://127.0.0.1:8554/side_doorbell
#        input_args: preset-rtsp-restream
#        roles:
#          - record
#          - detect
#    detect:
#      enabled: true # <---- disable detection until you have a working camera feed
#      width: 1080 # <---- update for your camera's resolution
#      height: 1920 # <---- update for your camera's resolution
#      stationary:
#        interval: 1
#        threshold: 50
#    snapshots: # <----- Enable snapshots
#      enabled: true
#    record:
#      enabled: true
#      retain:
#        days: 1
#    motion:
#      mask:
#      - 0,680,0,0,513,0,725,0,1080,0,1080,679,414,808,430,1077,0,1070
#    objects:
#      track:
#      - person
#      - car
#      filters:
#        car:
#          threshold: 0.75
#          mask:
#          - 295,1096,439,1070,452,915,0,921,0,1101
#        person:
#          threshold: 0.80
#          mask:
#          - 0,945,447,949,450,1143,222,1130,0,1113

#  garage:
#    ffmpeg:
#      inputs:
#        - path: rtsp://[REDACTRED]@192.168.1.223:554/h264Preview_01_main
#          roles:
#            #- detect
#            - rtmp
#            - record
#      output_args:
#        record: -vf v360=fisheye:flat:id_fov=180:d_fov=90:roll=-20:pitch=30:rorder=rpy -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -ar 44100 -c:a aac
#        rtmp: -vf v360=fisheye:flat:id_fov=180:d_fov=90:roll=-20:pitch=30:rorder=rpy -f flv -ar 44100 -c:a aac
#        detect: -vf v360=fisheye:flat:id_fov=180:d_fov=90:roll=-20:pitch=30:rorder=rpy -f rawvideo -pix_fmt yuv420p
#    detect:
#      enabled: True # <---- disable detection until you have a working camera feed
#      width: 1920 # <---- update for your camera's resolution
#      height: 1080 # <---- update for your camera's resolution
#      stationary:
#        interval: 0
#        threshold: 10
#    record:
#      enabled: True
#      retain:
#        days: 1
#    objects:
#      track:
#        - person
```
