### ISSUE TITLE
Cannot select notify group

### ISSUE THREAD

**Issue by Dropbear67** [SgtBatten/HA_blueprints#165]
### Describe the problem you are having or the outcome you are trying to achieve.

I have defined a notify group in yaml called "familygroup" which is made up of 3 devices.
When I try and enter the name familygroup in the "Notification Group or Android/Fire TV (Optional)" input and save the automation I get

message malformed: unknown device '

### Version

Frigate Notifications (0.12.0.2)

### Automation config file

```yaml
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_group: familygroup
alias: AAA
```

### Any other information that may be helpful
```yaml
notify:
  - name: "FamilyGroup"
    platform: group
    services:
      - service: mobile_app_biggiphone13
        data:
          data:
            ttl: 0
            priority: high
      - service: mobile_app_biggipad
        data:
          data:
            ttl: 0
            priority: high
      - service: mobile_app_blah3
        data:
          data:
            ttl: 0
            priority: high
```
