### ISSUE TITLE
[Config Support]: [HELP-DEBUG]: ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by hardwareadictos** [SgtBatten/HA_blueprints#167]
### Describe the problem you are having or the outcome you are trying to achieve.

Hey!! I was using this blueprint till november 2023, now i decided to reenable my automations on HA to continue using them but for some reason i get ERR_INVALID_RESPONSE on chrome (as it doesn't open directly on HA companion Android app). Tested on various Android / iOS devices with the same result.

I have the BASE URL pointing to the my Nginx Proxy Manager.

Just want to know what i broke and how if i only updated Home Assistant and the blueprint as it was working some months ago.

Thanks in advance :)

### Version

0.12.0.2

### Automation config file

```yaml
alias: "XXXXXXXXX"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.reolink_xxxxxxx
    notify_device: 8467ba7a158dade72e6403d556b3d394
    base_url: https://homeassistant.xxxx.xxx
    message: Una persona ha sido detectada en {{camera_name}}.
    update_thumbnail: true
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: xxx.xxx.xxxx
  port: 1883
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"
  topic_prefix: frigate

detectors:
  cpu1:
    type: cpu

cameras:
  reolink-xxxxx: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.106/h264Preview_01_main # reolink-xxxx
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.106/h264Preview_01_sub # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: False
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 5
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 7
        mode: all

  reolink-xxxxx: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.108/h264Preview_01_main # reolink-xxxx
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.108/h264Preview_01_sub # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: False
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 5
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 7
        mode: all

  reolink-xxxxx: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.105/h264Preview_01_main # reolink-xxxx
          roles:
            - record
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.105/h264Preview_01_sub # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: False
      width: 2560 # <---- update for your camera's resolution
      height: 1440 # <---- update for your camera's resolution
      fps: 5
    snapshots: # <----- Enable snapshots
      enabled: True
      retain:
        default: 30
    record:
      enabled: True
      retain:
        days: 7
        mode: all

live:
  height: 720
  quality: 15

birdseye:
  enabled: True
  mode: continuous

#ffmpeg:
#  hwaccel_args: preset-nvidia-h264

database:
  path: /db/frigate.db
```

### Any other information that may be helpful

![imagen](https://github.com/SgtBatten/HA_blueprints/assets/20403906/7942c2a2-02d6-448d-b0f0-445f38a79036)

I'm using frigate 0.13.1-34fb1c2
