### ISSUE TITLE
[Config Support]: thumbnail to android tv

### ISSUE THREAD

**Issue by rayzorben** [SgtBatten/HA_blueprints#168]
### Describe the problem you are having or the outcome you are trying to achieve.

I am running the notifications for android and sending camera alerts to the tv but I just get a message. Is it possible to get an image such as the camera?

### Version

12.0.3

### Automation config file

```yaml
alias: Front Porch TV Notify
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.front_porch
    notify_device: c7e4c6705edd8ab9377eeced80d5757f
    notify_group: living_room_android_tv
    attachment: thumbnail.jpg
    update_thumbnail: true
    video: ""
    zone_filter: true
    zones:
      - front_porch_area
    tv_position: bottom-right
    tv_duration: 5
    tv: true
    tv_transparency: 50%
    labels:
      - person
    ios_live_view: camera.front_porch

```
