### ISSUE TITLE
[Bug]: 0.13.2 - iOS Notifications Fail

### ISSUE THREAD

**Issue by Rustymage** [SgtBatten/HA_blueprints#169]
### Description

Since updating Frigate from v0.12 to v0.13.2 the iOS notifications do not function. I have updated the Frigate HA to v5.0.1.

The Blueprint is 12.0.2 and while it fires with no error, I get no notifications as it does not fire the notify section, despite doing so with Frigate v0.12.

I am happy to provide details that can assist.

Thanks in advance!

### Version

12.0.2

### Automation Config

```yaml
alias: Frigate Door Camera
description: ""
use_blueprint:
  path: SgtBatten/Stable_12.yaml
  input:
    camera: camera.doorcam
    notify_device: efd32475a94ea72a1976819f56c9d327
    notify_group: anthony_karen
    base_url: https://{{URL}}
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    ios_live_view: false
    zone_filter: true
    zones:
      - doorway
    labels:
      - person
    alert_once: true
    update_thumbnail: true
    tv_interrupt: false
    debug: false
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.141
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: {{PASSWORD}}
database:
  path: /db/frigate.db
birdseye:
  enabled: False

objects:
  track:
    - person
    - cat 
    - dog
    - car
    - package

record:
  enabled: True
  events:
    retain:
      default: 14
      mode: active_objects

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 14

rtmp:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

cameras:
  FrontCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{{PASSWORD}}@192.168.2.6:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
#        - path: rtsp://admin:{{PASSWORD}}@192.168.2.6:554/cam/realmonitor?channel=1&subtype=0
#          roles:
#            - record
    detect:
      width: 640
      height: 360
      fps: 5
      annotation_offset: 0
    record:
      events:
        required_zones:
          - driveway
          - frontdoor
          - frontgarden
#          - road
#          - entrance
    snapshots:
      bounding_box: True
      required_zones:
        - driveway
        - frontdoor
        - frontgarden
#        - road
        - entrance
    motion:
      mask:   
        - 640,360,640,325,394,329,401,360
#        - 0,0,345,0,416,0,423,34,404,63,269,71,197,86,134,102,0,133
    zones:
      driveway:
        coordinates: 453,121,488,95,509,33,582,61,533,194,497,241,356,155
        objects:
          - person
#          - car
          - cat
          - dog
      frontdoor:
        coordinates: 527,195,583,81,640,96,580,218,544,263,481,233
        objects:
          - person
          - dog
          - cat
          - package
      frontgarden:
        coordinates: 59,222,75,360,225,360,351,282,435,226,385,192,315,141,220,80,58,127
        objects:
          - dog
          - cat
      road:
        coordinates: 0,105,209,64,418,31,338,0,211,0,157,28,0,82
        objects:
          - car
  DoorCam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{{PASSWORD}}@192.168.2.123:554/h264Preview_01_sub
          roles:
            - detect
#        - path: rtsp://admin:{{PASSWORD}}@192.168.2.123:554/h264Preview_01_main
#          roles:
#            - record
    record:
      events:
        required_zones:
          - doorway
#          - driveway
          - frontgarden
    snapshots:
      bounding_box: True
      required_zones:
        - doorway
#        - driveway
        - frontgarden
    zones:  
        doorway:
          coordinates: 0,360,236,360,298,360,480,360,480,297,363,237,255,227,180,294,82,275,0,208
          objects:
            - person
            - dog
            - package
        frontgarden:
          coordinates: 145,209,217,221,256,231,216,270,171,304,123,291,81,266,34,230
          objects:
            - person
            - dog
            - cat
#        driveway:
#          coordinates: 254,217,333,216,389,220,370,304,197,290
#          objects:
#            - car
    motion:
          mask:    
            - 51,293,0,263,34,230,164,299,121,336
            - 145,360,144,337,0,339,0,360,51,360
            - 25,60,153,0,480,0,480,323,480,360,480,327,379,225,295,224,134,213,23,219
    detect:
      width: 480
      height: 360
      fps: 5
      annotation_offset: 0  
  SideCam:
   ffmpeg:
     inputs:
       - path: rtsp://tapocamera:{{PASSWORD}}@192.168.2.107/stream2
         roles:
           - detect
#       - path: rtsp://tapocamera:{{PASSWORD}}@192.168.2.107/stream1
#         roles:
#           - record
   record:
      events:
        required_zones:
           - sidegate
   snapshots:
     bounding_box: True
     required_zones:
        - sidegate
   zones:  
       sidegate:
         coordinates: 178,360,481,360,640,360,640,168,566,145,454,110,294,85,292,0,176,0,108,0
         objects:
           - person
           - cat
           - dog
   motion:
         mask:    
           - 241,22,239,0,0,0,0,22
           - 640,0,640,168,397,104,307,95,193,68,235,0
   detect:
     width: 640
     height: 360
     fps: 5
     annotation_offset: 0

  GarageCam:
   ffmpeg:
     inputs:
       - path: rtsp://192.168.1.182:8554/drive-cam
         roles:
           - detect
   record:
      events:
        required_zones:
           - entrance
#           - road
   snapshots:
     bounding_box: True
     required_zones:
        - entrance
#        - road
   zones:
       driveway:
         coordinates: 640,360,640,360,640,182,444,177,68,170,0,234,0,360
         objects:
           - person
           - car
           - dog
           - cat
       road:
         coordinates: 0,125,449,121,428,77,274,68,0,99
         objects:
           - car
       entrance:
         coordinates: 0,195,640,211,567,158,0,141
         objects:
           - car
           - person
   motion:
         mask:
           - 640,59,640,0,0,0,0,0,0,84
           - 0,125,468,133,428,77,274,68,0,99
           - 444,329,640,327,640,360,460,360
   detect:
     width: 640
     height: 360
     fps: 5
     annotation_offset: 0

  Gardencam:
   ffmpeg:
     inputs:
       - path: rtsp://admin:{{PASSWORD}}@192.168.2.132:554/cam/realmonitor?channel=1&subtype=1
         roles:
           - detect
#       - path: rtsp://admin:{{PASSWORD}}@192.168.2.132:554/cam/realmonitor?channel=1&subtype=0
#         roles:
#           - record
   record:
      events:
        required_zones:
           - backgarden
   snapshots:
     bounding_box: True
     required_zones:
        - backgarden
   zones:
       backgarden:
         coordinates: 0,360,640,360,640,105,619,73,452,32,231,26,118,64,0,118
         objects:
           - person
           - cat
           - dog
   motion:
         mask:
           - 133,60,247,30,401,33,640,75,640,28,640,0,0,0,0,114
           - 0,360,189,360,186,329,0,328
   detect:
     width: 640
     height: 360
     fps: 5
     annotation_offset: 0
```
