### ISSUE TITLE
[Bug]: Can't view clips or snapshots

### ISSUE THREAD

**Issue by Spazholio** [SgtBatten/HA_blueprints#17]
### Description

I have filled out the "Base URL (Optional)" field with https://ha.mydomain.net/.  This resolves both inside and outside of my network and has been my HA URL for years.

Whenever a notification comes in, I can tap and hold and I'll see the live preview of the camera (which I must say is REALLY swank and I love it).  But if I try to "View Clip" or "View Snapshot" I'll either see the play button with a line through it or a broken image icon, respectively.  Also, I've set the color to `amber` but no colors are different anywhere so I'm not entirely certain what that does.

I *have* to be doing something wrong, I just don't know what it is.  Help?

### Version

v0.11.0.16

### Automation Config

```yaml
alias: Motion Detection - Driveway
description: Created 16APR2023
use_blueprint:
  path: SgtBatten/frigate_0.11_notification.yaml
  input:
    tv_transparency: 0%
    camera: camera.driveway
    notify_group: movement_on_cameras
    base_url: https://ha.mydomain.net/
    alert_once: true
    update_thumbnail: true
    color: amber
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    ios_live_view: true
    debug: false
    tv_size: large
    tv_position: center
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.230
  user: homeassistant
  password: [PASS]
logger:
  default: info
birdseye:
  mode: continuous
  enabled: true
record:
  expire_interval: 5
  enabled: true
  retain:
    days: 1
    mode: all
  events:
    #max_seconds: 300
    pre_capture: 5
    post_capture: 5
    retain:
      default: 7
      mode: active_objects
snapshots:
  enabled: true
  retain:
    default: 7
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://[USER:PASS]!@192.168.1.106:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- detect
        - path: rtsp://[USER:PASS]!@192.168.1.106:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      track:
        - person
        - vehicle
        - animal
    snapshots:
      enabled: true
      timestamp: true
      crop: false
      #retain:
        #default: 6
    detect:
      width: 720
      height: 576
    #detect:
      #width: 2560
      #height: 1920
    motion:
      mask:
        - 1280,0,1280,344,837,335,669,338,615,369,352,383,0,411,0,0,751,0
  Front_Door:
    ffmpeg:
      inputs:
        - path: rtsp://[USER:PASS]!@192.168.1.107:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            #- detect
        - path: rtsp://[USER:PASS]!@192.168.1.107:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      track:
        - person
        - vehicle
        - animal
    snapshots:
      enabled: true
      timestamp: true
      crop: false
    #detect:
      #width: 2560
      #height: 1920
    detect:
      width: 720
      height: 576
    motion:
      mask:
        - 343,230,343,261,424,264,436,180,353,167
  Driveway:
    detect:
      width: 708
      height: 480
    #detect:
      #width: 3840
      #height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://[USER:PASS]@192.168.1.108:554/live
          roles:
            - record
            #- detect
        - path: rtsp://[USER:PASS]@192.168.1.108:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      track:
        - person
        - vehicle
        - animal
    record:
      events:
        required_zones:
          - driveway_entrance
          - entire_driveway
    snapshots:
      required_zones:
        - driveway_entrance
        - entire_driveway
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
    motion:
      mask:
        - 0,0,80,117,534,65,578,0
    zones:
      driveway_entrance:
        coordinates: 87,395,139,476,146,580,0,603,0,285
        objects:
          - person
          - vehicle
          - animal
      entire_driveway:
        coordinates: 614,720,772,720,846,662,1083,143,608,0,293,0,56,0,83,153,0,247,0,616,105,571
        objects:
          - person
          - animal
          - vehicle
  Back_Deck:
    detect:
      width: 708
      height: 480
    #detect:
      #width: 2592
      #height: 1944
    ffmpeg:
      inputs:
        - path: rtsp://[USER:PASS]@192.168.1.109:554/live
          roles:
            - record
            #- detect
        - path: rtsp://[USER:PASS]@192.168.1.109:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      track:
        - person
        - animal
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #retain:
        #default: 4
    motion:
      frame_alpha: 0.3 #Hopefully reduce detection of shadows
      mask:
        - 0,0,0,224,436,100,796,21,1008,89,873,0,766,0
        - 568,638,800,686,813,434,833,430,587,432
        - 1280,720,1061,720,1088,499,1183,191,1280,247
  Side_Yard:
    detect:
      width: 704
      height: 480
    #detect:
      #width: 3840
      #height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://[USER:PASS]@192.168.1.111:554/live
          roles:
            - record
            #- detect
        - path: rtsp://[USER:PASS]@192.168.1.111:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      track:
        - person
        - animal
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #retain:
        #default: 4
    motion:
      mask:
        - 0,0,744,0,558,266,373,497,133,651,0,667
  Front_Yard:
    detect:
      width: 704
      height: 480
    #detect:
      #width: 3840
      #height: 2160
    ffmpeg:
      inputs:
        - path: rtsp://[USER:PASS]@192.168.1.110:554/live
          roles:
            - record
            #- detect
        - path: rtsp://[USER:PASS]@192.168.1.110:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      track:
        - person
        - animal
        - vehicle
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      #retain:
        #default: 4
    motion:
      mask:
        - 479,367,439,253,401,175,333,164,432,113,444,0,0,0,0,287,0,411,140,295,172,308,170,419,271,496
        - 891,0,782,51,735,124,587,178,484,201,409,123,415,0
model:
  labelmap:
    1: vehicle
    2: vehicle
    3: vehicle
    5: vehicle
    7: vehicle
    15: animal
    16: animal
    17: animal
    18: animal
    19: animal
    20: animal
    21: animal
    22: animal
    23: animal
    24: animal
ffmpeg:
  input_args: preset-rtsp-generic
  hwaccel_args: preset-intel-qsv-h264

detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3
```
