### ISSUE TITLE
[Bug]: No Notifications after Updating to Frigate 13 and Integration 5

### ISSUE THREAD

**Issue by dfoley4** [SgtBatten/HA_blueprints#171]
### Description

After updating my Frigate installation and HASS integration I no longer receive notifications on my TV or iPhone. I suspect that something has changed in the update to create this problem as Frigate is still detecting events and the automation is still triggering but the notifications aren't being received.

### Version

12.0.3

### Automation Config

```yaml
alias: Frigate Doorbell Notification
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.doorbell
    notify_group: home_group
    base_url: https://afhktdl2p1w8nlejnytcxnwgau3iob9r.ui.nabu.casa/
    title: Doorbell Notification
    alert_once: true
    attachment: snapshot.jpg
    update_thumbnail: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    zone_filter: false
    labels:
      - person
      - cat
      - dog
    tv: true
    tv_position: top-right
    notify_device: 88b5e8850e40720e1cfedaf7ed857df3
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    zones: []
    custom_filter: "false"
    debug: true
    color: "#000000"
    silence_timer: 0
    url_3: /lovelace
    button_3: Open Home Assistant
    icon: mdi:cctv
    ios_live_view: camera.doorbell
```
