### ISSUE TITLE
[Bug]: TitleHere

### ISSUE THREAD

**Issue by PatSloan** [SgtBatten/HA_blueprints#174]
### Description

Notification on Android set to use HA alarm_streem category.  This caused the wrong notification sounds on Android. 

I have the notification set to a custom HA notification category via the blueprint. 

![image](https://github.com/SgtBatten/HA_blueprints/assets/19332597/698ab064-11aa-483c-98dc-aedf4ee54144)

### Version

0.12.0.3b

### Automation Config

```yaml
alias: Alert - doorbell
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'spotted' }} {% if
      enteredzones %} in the {{ enteredzones | join(', ') | replace('_',' ')
      }}{% endif %} via {{ camera_name }} cam.
    camera: camera.doorbell
    notify_device: f5a7041bcf577e4bb92cf59bd60c45fc
    notify_group: all_devices
    title: Eye
    update_thumbnail: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    android_auto: true
    channel: HA
    zone_filter: true
    zones:
      - doorbell_zone
      - porch_zone
      - driveway_zone
    attachment: snapshot.jpg?bbox=1
    silence_timer: 5
    base_url: http://100.78.89.141:8123
    alert_once: true
    critical: "true"
    icon: mdi:cctv
```

### Frigate Config

```yaml
n/a
```
