### ISSUE TITLE
[Issue]: Zone based notifications not triggering properly

### ISSUE THREAD

**Issue by dfoley4** [SgtBatten/HA_blueprints#185]
### Description

I have zone filters enabled for my garage camera but instead of triggering for my desired zones, it filters out all notifications. Any ideas on how to get it to function properly? I want to get notifications if there's a car in the driveway but not for one in the road but I don't want to filter out all road cars from recordings. 

### Version

0.12.0.3

### Automation Config

```yaml
alias: Frigate Garage
description: Sends notifications for garage camera
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.garage
    notify_device: 88b5e8850e40720e1cfedaf7ed857df3
    notify_group: home_group
    base_url: https://afhktdl2p1w8nlejnytcxnwgau3iob9r.ui.nabu.casa/
    title: Garage Notification
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera{% if enteredzones %} in the {{ enteredzones |
      join(', ') | replace('_',' ') }}{% endif %}.
    attachment: snapshot.jpg
    update_thumbnail: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    color: "#000000"
    ios_live_view: camera.garage
    zone_filter: true
    zones:
      - driveway
      - front_yard_left
      - front_yard_right
    labels:
      - car
      - dog
      - person
      - cat
    cooldown: 0
    button_3: Open Home Assistant
    url_3: /lovelace
    tv: true
    tv_position: top-right
    tv_duration: 15
```

### Frigate Config

```yaml
garage:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://XXXXX/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://XXXXX/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 0,332,0,487,994,446,1920,464,1920,294
        person:
          mask:
            - 0,445,1920,399,1920,0,0,0
            - 253,512,235,512,236,472,261,472
            - 1138,514,1175,515,1169,438,1129,440
    zones:  
      driveway:
        coordinates: 1086,549,891,1080,0,1080,0,891,437,754,797,554
        objects:
          - suitcase
          - person
          - dog
          - cat
          - car
```
