### ISSUE TITLE
[Issue]: Restricting events notifications to specific zones not working

### ISSUE THREAD

**Issue by asemev** [SgtBatten/HA_blueprints#188]
### Description

My issue might be the same as #185 but i'm not sure, so i wanted to post it here anyways.

- I installed a new camera at my front door.
- At the end of the entrance, there is a pavement
- I configured a zone for only detecting persons entering my home entrance, walking towards my door. So anybody just walking past my home along the pavement should be ignored.
- I made sure the zone is very separated from the pavement and also added intertia=3. (so the bottom middle of the detection box does not fall into the zone)
- I also added required zone in the notification (0.12.0.2). I also tested the beta 0.12.0.3c and same results.
- Despite all my efforts for several hours, HA still keeps sending me a notification whenever someone just walks on the pavement.
- Pls note that i dont want to mask the pavement area because then it half of the image of the person is blacked out when they start walking towards my door.
- I posted a few screenshots so you can see my zone area and the people walking on the pavement
- i also get an error when i click on "View Clip or View Snapshot in the Android notification. Screenshot below.
- So looks like Frigate is working properly (as the events are not in the timeline view) but the notifications are still firing and firing wrongly even though the motion and person is not in the zone (and in fact far away from the zone).
- Hope these can help you improve the notification engine further.

![image](https://github.com/SgtBatten/HA_blueprints/assets/30929896/7e92460a-c075-4e0c-b7e6-ddd006989a7f)
![image](https://github.com/SgtBatten/HA_blueprints/assets/30929896/19ca747e-c919-4203-96cf-21a70463e0e1)
![image](https://github.com/SgtBatten/HA_blueprints/assets/30929896/62a803fc-0b2a-401c-8f83-bfa07aae8063)
![image](https://github.com/SgtBatten/HA_blueprints/assets/30929896/ddbb959a-4fa4-4db3-992d-5218af6722ac)
![image](https://github.com/SgtBatten/HA_blueprints/assets/30929896/f03dc76e-8ec2-43e5-a9b9-c837fdd8784f)

Thank you very much!

### Version

0.12.0.2

### Automation Config

```yaml
alias: Frigate - Door Person
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.door
    notify_device: e00c1c0945954b1f084708607893d66f
    zones:
      - zone_0
    labels:
      - person
    cooldown: 10
    silence_timer: 10
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: 'usb'
    num_threads: 4
mqtt:
  host: 
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user:
  password: 
#ffmpeg:
#  hwaccel_args:
#    - '-c:v'
#    - h264_v4l2m2m

#ffmpeg:
#  hwaccel_args: preset-rpi-64-h264

cameras:
#  Garage:
#    ffmpeg:
#      inputs:
#        - path: 'rtsp://
#          global_args: '-hide_banner -loglevel error'
#          roles:
#            - detect
#            - record
#    detect:
#     width: 1920
#      height: 1080
#      fps: 5
#    motion:
#      mask: >-
#        -0,0,1920,0,1920,1080,1490,1080,1659,694,690,270,121,417,345,1080,0,1080
#    snapshots:
#      enabled: true
#      timestamp: true
#      bounding_box: true
#      crop: false
#      height: 175
#      retain:
#        default: 10
#        objects:
#          person: 10
#    mqtt:
#      enabled: true
#      timestamp: true
#      bounding_box: true
#      crop: true
#      height: 270
#    objects:
#      track:
#        - person
#
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          min_score: 0.5
#          threshold: 0.7
#          mask: >-
#            -2,1,1920,0,1920,1080,1490,1080,1678,653,547,227,533,73,354,86,370,292,116,340,285,1012,680,1014,678,1080,0,1080
#    zones:
#      car:
#        coordinates: 343,1058,1477,1080,1654,683,776,252,123,394
#    record:
#      enabled: true
#      retain: 
#        days: 3
#        mode: motion 
#      events:
#        retain:
#          default: 3
#          mode: active_objects

  Package:
    ffmpeg:
      inputs:
        - path: 
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 0,1080,1920,1080,1350,547,1408,891,1081,899,1105,544,1307,523,1920,1080,1920,0,0,0

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 10

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person

    zones:
      box:
        coordinates: 1128,888,1408,891,1356,564,1073,535
    record:
      enabled: true
      retain: 
        days: 3
        mode: motion 
      events:
        retain:
          default: 3
          mode: active_objects

  Door:
    ffmpeg:
      inputs:
        - path: 
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
    record:
      enabled: true
      retain: 
        days: 10
        mode: motion 
      events:
        required_zones:
          - entire_yard
        retain:
          default: 10
          mode: active_objects
    snapshots:
      required_zones:
        - zone_0
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 10
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
    zones:
      zone_0:
        coordinates: 235,1080,1920,1080,1734,387,502,324
        inertia: 3
        objects:
          - person
database:
  path: /media/frigate.db
logger:
  default: info
  logs:
    frigate.mqtt: error
```
