### ISSUE TITLE
[Config Support]: Notification Group or Android/Fire TV (Optional)

### ISSUE THREAD

**Issue by abeksis** [SgtBatten/HA_blueprints#191]
### Describe the problem you are having or the outcome you are trying to achieve.

Notification Group or Android/Fire TV (Optional)

Do I need to provide the full address? Like notify.frigate_mobile_notify?

And under Base URL (Optional) should I provide the full articles plus https?

### Version

Frigate Notifications (0.12.0.3d)

### Automation config

```yaml
alias: Frigate Notifications to Mobile Tv
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.front_gate
    notify_group: notify.frigate_mobile_notify
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    attachment: snapshot.jpg?bbox=1
    zone_filter: false
    zones: []
    tv: true
    tv_position: bottom-left
    notify_device: 0f960a98a486e2df944fb7d70d303fc8
    tv_interrupt: true
    labels:
      - person
    tv_transparency: 25%
    url_1: "{{base_url}}/lovelace"
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    alert_once: false
    update_thumbnail: false
    base_url: frigate.abeksis.site
    sticky: true
    debug: true
    video: ""
    color: "#f44336"
    ios_live_view: camera.front_gate
```
