### ISSUE TITLE
[Issue]: Error sending notification in ios app

### ISSUE THREAD

**Issue by efrainsalasmty** [SgtBatten/HA_blueprints#192]
### Description

This is the error:

Choose at step 1: Frigate Event: Notify on new object: choice 1: Choose at step 1: choice 1: Error executing script. Error for device at pos 1: Unable to find notify service for webhook ID

Notes:
In Home assistant notifications settings (ios settings) has 2 cuestionable things the first one is Push ID "Not registered for remote notifcations"

### Version

SgtBatten/Stable.yaml

### Automation Config

```yaml
id: '1711640186992'
alias: NotifyCamaraFrontal
description: ''
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frontal
    notify_device: a15eed14ed717b319bf7de09e59fdea8
    attachment: snapshot
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.100.11
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 300

record:
  expire_interval: 10

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  frontal:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://admin:Prime109@192.168.100.7:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 3840
      height: 2160
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        cat:
          min_score: 0.8
          threshold: 0.5
        dog:
          min_score: 0.8
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false  # Corrección del valor
      retain:
        default: 5
    record:
      enabled: true  # Corrección del valor
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 1
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
  porche:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        cat:
          min_score: 0.8
          threshold: 0.5
        dog:
          min_score: 0.8
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false  # Corrección del valor
      height: 500
      retain:
        default: 5
    record:
      enabled: true  # Corrección del valor
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 1
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
  patio:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=4&subtype=1
          roles:
            - detect
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=4&subtype=0
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - bicycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false  # Corrección del valor
      height: 500
      retain:
        default: 5
    record:
      enabled: true  # Corrección del valor
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 2
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
  pasillo:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=3&subtype=1
          roles:
            - detect
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=3&subtype=0
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - bicycle
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false  # Corrección del valor
      height: 500
      retain:
        default: 5
    record:
      enabled: true  # Corrección del valor
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 3
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
  techo:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=2&subtype=1
          roles:
            - detect
        - path: rtsp://wolty:Prime109@@192.168.100.20:554/cam/realmonitor?channel=2&subtype=0
          roles:
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        max_frames:
          objects:
            person: 100
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
      filters:
        cat:
          min_score: 0.8
          threshold: 0.5
        dog:
          min_score: 0.8
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false  # Corrección del valor
      height: 500
      retain:
        default: 5
    record:
      enabled: true  # Corrección del valor
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 4
          mode: active_objects
        pre_capture: 5
        post_capture: 15
    ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 4
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
detectors:
  cpu1:
    type: cpu
    num_threads: 2

rtmp:
  enabled: false

birdseye:
  enabled: false  # Corrección del valor
  width: 1280
  height: 720
  quality: 1
  mode: objects
```
