### ISSUE TITLE
[Issue]: Notification sent but Presence filter person was home

### ISSUE THREAD

**Issue by saschabrockel** [SgtBatten/HA_blueprints#193]
### Description

It sends a notification while it should not. The person was at home at this time. It happens randomly sometimes. I cannot see any pattern yet.

### Version

0.12.0.2

### Automation Config

```yaml
alias: Kamera - Papa Schlafzimmer - Frigate Notifications (0.12.0.2)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.papa_schlafzimmer
    notify_device: 9544dc2deb9ccc0acb20338639131160
    color: red
    icon: mdi:cctv
    button_1: Clip
    button_2: Foto
    button_3: Stumm (30 Min)
    channel: Motion
    title: Bewegung in {{ camera_name }}
    message: >-
      {{ label }} {{ 'ist aktuell' if loitering else 'erkannt' }} - {{
      camera_name }} um {{ now().strftime('%H:%M:%S') }}.
    critical: "true"
    base_url: https://xxx.xxx.de
    loiter_timer: 1
    ios_live_view: true
    notify_group: smartphones
    presence_filter: person.papa
```
