### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by Linkra62** [SgtBatten/HA_blueprints#195]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi All ,
Hope you are well , 
 I am trying to get notify only when my alarm pannel is in night mode  so i am playing with the state filter but without any luck .
i enabled the state Filter , chose the entity but what do i need to put in the State Filter States section ? 
Otherwise the blueprint is amazing .
Thanks for your help

### Version

Frigate Notifications (0.12.0.2)

### Automation config

```yaml
alias: Frigate Notifications (0.12.0.2)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.devant2
    notify_device: 53a6e0cbcc335b321a1bd8129a356ce5
    title: test
    attachment: snapshot
    state_entity: automation.mode_nuit_a_20h
    state_filter: true
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera.
    labels: []
    zone_filter: false
    state_filter_states: []
    zone_multi: false
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.180
  user: MQTT_USER
  password: toto

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion

cameras:
  Maxine : # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
          - path: rtsp://admin:toto@192.168.1.130:8554/Streaming/Channels/101
            roles:
              - record
              - detect
    detect:
          width: 1280
          height: 720
          fps: 5
    objects:
      track:
        - cat
  Devant1: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:NNBPLD@192.168.1.131/h264
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
  Devant2: # <--- this will be changed to your actual camera later
    enabled: True
    ffmpeg:
      inputs:
          - path: rtsp://admin:@192.168.1.90/user=admin_password=tlJwpbo6_channel=0_stream=0.sdp?real_stream
            roles:
              - record
              - detect
    detect:
          width: 1280
          height: 720
          fps: 5
    objects:
      track:
        - person
        - car
    snapshots:
      enabled : true
      timestamp: true
      bounding_box: true
      retain:
        default: 7
```
