### ISSUE TITLE
[Config Support]: Not receiving notification after a day from Hikvision DVR.

### ISSUE THREAD

**Issue by rnkhq** [SgtBatten/HA_blueprints#198]
### Describe the problem you are having or the outcome you are trying to achieve.

For a long time since, I didnt receive notifications from the blueprint, I thought maybe it wont work for me. But for some reason I interchanged a camera cable on the 8 Port Hikvision DVR from one port to another and it started to send me notifications! and as sometime passed, it stoped sending me notification. I tried another port and it again started to send me notification. Currently only one of my camera sends me notification without any issues and also all the other cameras detects and records clips but dont notify me. What can be the cause?

### Version

0.12.0.1

### Automation config

```yaml
alias: "Motion Garage "
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_all_occupancy
    id: occupied
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.garage_all_occupancy
    to: "off"
    id: not occupied
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
      - binary_sensor.garage_motion
    to: "on"
    id: Motion
    enabled: true
  - platform: state
    entity_id:
      - binary_sensor.garage_motion
    to: "off"
    id: No Motion
    enabled: true
    for:
      hours: 0
      minutes: 0
      seconds: 5
  - platform: state
    entity_id:
      - switch.sonoff_10005ce1b5
    to: "off"
    id: Turn Off
    enabled: true
    from: "on"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.openweathermap_cloud_coverage
        attribute: unit_of_measurement
        state: ">80"
        for:
          hours: 0
          minutes: 1
          seconds: 0
        enabled: true
      - condition: time
        before: sensor.sun_next_rising
        after: "01:00:00"
        enabled: true
action:
  - alias: Light Turn off pattern to avoid re-motion trigger
    if:
      - condition: trigger
        id:
          - Turn Off
    then:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.garage_motion
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
        enabled: true
      - type: turn_off
        device_id: 3cf2df48e962c5668874c7ad69f1c43e
        entity_id: 381f223649611abd8b0090ee6018c12a
        domain: switch
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
        enabled: true
      - service: switch.turn_on
        target:
          entity_id:
            - switch.garage_motion
        data: {}
      - service: notify.mobile_app_rownak_op
        metadata: {}
        data:
          message: Garage off
  - alias: occupied and motion
    if:
      - condition: trigger
        id:
          - occupied
          - Motion
    then:
      - type: turn_on
        device_id: 3cf2df48e962c5668874c7ad69f1c43e
        entity_id: 381f223649611abd8b0090ee6018c12a
        domain: switch
      - service: notify.mobile_app_rownak_op
        metadata: {}
        data:
          message: Garage on
  - alias: Both not occupied and no motion
    if:
      - condition: trigger
        id:
          - No Motion
          - not occupied
    then:
      - if:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.garage_motion
                state: "off"
              - condition: state
                entity_id: binary_sensor.garage_all_occupancy
                state: "off"
        then:
          - type: turn_off
            device_id: 3cf2df48e962c5668874c7ad69f1c43e
            entity_id: 381f223649611abd8b0090ee6018c12a
            domain: switch
mode: single
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.0.192
  user: mqtt-users
  password: mqtt-users

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264


birdseye:
  enabled: false

go2rtc:
  streams:
    Roof_Top:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/201
    Main_Door:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/801
    First_Floor:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/101
    East_Road:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/301
    Ground_Floor:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/401
    Garage:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/501
    Front_Yard:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/601
    North_Road:
    - rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/701

cameras:
  Main_Door:
    ffmpeg:
      inputs:
      - path: rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/801
        input_args: preset-rtsp-restream
        roles:
        - detect
    live:
      stream_name: Main_Door
    record:
      enabled: true
      retain:
        days: 30
        mode: active_objects
      events:
        pre_capture: 5
        post_capture: 5
        objects:
        - person
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      retain:
        default: 60
    motion:
      mqtt_off_delay: 1
      # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 10)
      # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
      # make motion detection more sensitive to smaller moving objects.
      # As a rule of thumb:
      #  - 10 - high sensitivity
      #  - 30 - medium sensitivity
      #  - 50 - low sensitivity
      contour_area: 100
    # default lightning_threshold:
      # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
      #           needs to recalibrate. (default: 0.8)
      # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
      # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching a doorbell camera.
      lightning_threshold: 1
    # default threshold value
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: 30)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 100
      mask:
      - 591,62,591,28,0,28,0,60

  Garage:
    ffmpeg:
      inputs:
      - path: rtsp://admin:nsrassatadaas562@192.168.0.114/streaming/channels/501
        input_args: preset-rtsp-restream
        roles:
        - detect
    live:
      stream_name: Garage
    record:
      enabled: true
      retain:
        days: 30
        mode: active_objects
      events:
        pre_capture: 5
        post_capture: 5
        objects:
        - person
        retain:
          default: 30
          mode: active_objects
    snapshots:
      enabled: true
      retain:
        default: 60
    motion:
      mask:
      - 608,67,612,32,0,31,0,67
      - 680,549,882,552,882,512,682,512
      mqtt_off_delay: 1
    # Contours are outlines of detected objects in an image. Increasing this value will filter out smaller areas of motion,
      # making the detection more sensitive to larger moving objects. Conversely, decreasing it will increase sensitivity to smaller movements.
      contour_area: 100
    # default lightning_threshold:
      # Threshold Adjustment: Increase the lightning_threshold parameter to a higher value,
      # such as 0.5 or 0.6, to make the system less sensitive to sudden changes in lighting caused by the IR mode switching on.
      lightning_threshold: 1
    # This parameter is the threshold value used in the CV2 thresholding function to determine if a pixel change is significant enough to be considered motion.
      # The value typically ranges from 1 to 255, with higher values making the motion detection less sensitive to small pixel changes.
      threshold: 130
```
