### ISSUE TITLE
Zone filter

### ISSUE THREAD

**Issue by bregol** [SgtBatten/HA_blueprints#2]
I have an alert set up with a filter to only alert for a single zone "zonedriveway".  In the blueprint utilization I have the filter turned on:
```
    zone_filter: true
    zones:
      - zonedriveway
```

However, with a short couple tests, it was not triggering when I entered the zone.  I didn't test thoroughly, but I think it triggered when I left the zone rather than when I entered it.

I was able to get the zone filter to work properly when I enabled the zone_multi option:
```
    zone_filter: true
    zone_multi: true
    zones:
      - zonedriveway
```

Haven't had time to dig more into it, but wanted to share this potential bug.
