### ISSUE TITLE
[Config Support]: Automation not triggering

### ISSUE THREAD

**Issue by nicklozon** [SgtBatten/HA_blueprints#224]
### Describe the problem you are having or the outcome you are trying to achieve.

Automation is not triggering - "No traces found".

### Version

0.12.0.4a

### Automation config

```yaml
alias: Front Event
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.camera_1
    notify_device: 2567b4e4d70f814e46f6adda5be6addf
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.1.133
  user: ********
  password: ********

ffmpeg:
  hwaccel_args: preset-rpi-64-h264
  output_args:
    record: preset-record-generic-audio-copy

rtmp:
  enabled: false

go2rtc:
  streams:
    camera_1:
    - rtsp://****:****@192.168.1.236:554/Streaming/Channels/101

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    objects:
    - person
    - dog
    - cat
    - cup
    retain:
      default: 30
      mode: motion

motion:
  threshold: 40

cameras:
  camera_1:
    ffmpeg:
      inputs:
      - path: rtsp://****:****@192.168.1.236:554/Streaming/Channels/101
        roles:
        - audio
        - record
      - path: rtsp://****:****@192.168.1.236:554/Streaming/Channels/102
        roles:
        - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 6
    live:
      stream_name: camera_1
    record:
      events:
        required_zones:
        - front
        - sidewalk
    zones:
      front:
        coordinates: 0,720,0,215,58,167,348,162,641,181,918,213,1280,286,1280,720
      sidewalk:
        coordinates: 
          1125,157,905,106,591,60,451,51,306,52,179,63,0,87,0,164,175,152,458,155,820,190,994,221,1074,233,1280,285,1280,211
    motion:
      mask:
      - 629,720,626,554,411,513,280,496,87,468,0,472,0,720
      - 201,56,391,43,578,54,835,89,1130,156,1280,207,1280,0,0,0,0,90
```

### Any other information that may be helpful

Home Assistant version: 2024.6.1
Frigate Version: 0.13.2
Mosquitto (MQTT) version: 6.4.1
Enable the unauthenticated notification event proxy: ✅

Proof of events:
![image](https://github.com/SgtBatten/HA_blueprints/assets/487421/8eef3dc4-7794-4445-9e93-3e9e1866e6f2)

Proof of MQTT working properly:
`mosquitto_sub -h 192.168.1.133 -p 1883 -u ******** -P ******** -t frigate/events`
![image](https://github.com/SgtBatten/HA_blueprints/assets/487421/332aba55-9a27-4c49-9468-5e7155dd405f)

Thank-you kindly for your work on this application and your assistance.
