### ISSUE TITLE
[Config Support]: group notifications

### ISSUE THREAD

**Issue by bozzio83** [SgtBatten/HA_blueprints#229]
### Describe the problem you are having or the outcome you are trying to achieve.

I have a group notification setup to send to multiple devices on different apps. One is telegram, another is signal and another is the ha app and when testing the service it works.  But in this blueprint I can't get it to fire the notifications.

I should say normal device notifications work well. I was just hoping to make a telegram or signal group for my family to have all notifications in one place.

### Version

0.12.0.4

### Automation config

```yaml
alias: telegram test2
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    notify_group: artemiss
    camera: camera.frontdoor_2
    notify_device: ec1235dda196d323e5476b48f3009568
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    color: "#000000"
    android_auto: true
    base_url: https://***.******.com
```
