### ISSUE TITLE
[Bug]: TV notifications not honoring zone filters

### ISSUE THREAD

**Issue by w1ll1am23** [SgtBatten/HA_blueprints#23]
### Description

I have two identical automation setup. One to send my phone, a notification and one to send my Android TV. A notification the zone filters are working for the phone notification and not the Android TV notification. 

### Version

0.11.0.16

### Automation Config

```yaml
alias: Frigate driveway TV notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.frontdoor
    notify_device: 09726b3238ec63f644a4c3ed6dc0b7e6
    base_url: https://domain.com
    message: "{{ label }} detected - {{ camera_name }}"
    alert_once: true
    update_thumbnail: true
    zone_filter: true
    zones:
      - driveway
    debug: true
    tv_size: large
    state_filter: true
    state_entity: lock.front_door
    state_filter_states:
      - locked
    tap_action: /ccab4aaf_frigate-proxy/dashboard
    button_1: View Clip
    url_1: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    url_2: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    tv_position: bottom-right
    color: grey
    tv: true
    tv_duration: "5"
    notify_group: living_room_tv
```

### Frigate Config

```yaml
frontdoor:
    record:
      enabled: True
      retain:
        days: 1
        mode: motion
    zones:
      driveway:
        coordinates: 470,82,400,79,318,95,322,139,386,165,507,130,593,120
      street:
        coordinates: 570,91,640,113,640,76,471,33,378,21,335,22,317,36
      door:
        coordinates: 124,386,286,320,241,21,165,38,99,64,25,88,81,275
        objects:
          - person
    objects:
      track:
        - person
        - dog
        - cat
        - car
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      inputs:
        - path: http://192.168.x.x/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password
          roles:
            - record
        - path: http://192.168.x.x/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=password
          roles:
            - detect
    detect:
      width: 640
      height: 480
```
