### ISSUE TITLE
[Config Support]: Automation not triggered

### ISSUE THREAD

**Issue by macnug** [SgtBatten/HA_blueprints#230]
### Describe the problem you are having or the outcome you are trying to achieve.

after several attempts i wasn't able to trigger the automation

### Version

0.12.0.4a

### Automation config

```yaml
alias: prova frigate
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.entrata_frigate
    notify_device: d58f4405464d53c8fa4dd26e3abecb8c
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  client_id: xxxxx
  user: xxxxx
  password: xxxxxxxxx
  stats_interval: 60


detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /media/frigate/frigate.db

model:
    # Optional: path to the model (default: automatic based on detector)
#  path: /edgetpu_model.tflite
    # Optional: path to the labelmap (default: shown below)
#  labelmap_path: /labelmap.txt
    # Required: Object detection model input width (default: shown below)
  width: 320
    # Required: Object detection model input height (default: shown below)
  height: 320

timestamp_style:
    # Optional: Position of the timestamp (default: shown below)
    #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: tr
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
    # Optional: Effect of lettering (default: shown below)
    #           None (No effect),
    #           "solid" (solid background in inverse color of font)
    #           "shadow" (shadow for font)
  effect: shadow


logger:
  default: info
  logs:
    frigate.event: debug

#environment_vars:
#  EXAMPLE_VAR: value

birdseye:
  enabled: true
  width: 1920
  height: 1080
  quality: 8
  mode: continuous

ui:
  live_mode: webrtc
  timezone: Europe/Rome
  use_experimental: true #False
  time_format: browser
  date_style: short
  time_style: medium
  strftime_fmt: '%d/%m/%Y %H:%M'

go2rtc:
  streams:
    Entrata:
    - rtsp://xxxxx:xxxxxxxx@192.168.1.101/live
    Entrata_sub:
    - rtsp://xxxxx:xxxxxxxx@192.168.1.101:554/cam/realmonitor?channel=1&subtype=1
    Loggiato:
    - rtsp://xxxxx:xxxxxxxx@192.168.1.100/live
    Loggiato_sub:
    - rtsp://xxxxxx:xxxxxxxx@192.168.1.100:554/cam/realmonitor?channel=1&subtype=1
    Piscina:
    - rtsp://xxxxx:xxxxxxxx@192.168.1.108/live
    Piscina_sub:
    - rtsp://xxxxxx:xxxxxxxx@192.168.1.108:554/cam/realmonitor?channel=1&subtype=1

################################################################################  

cameras:
  Entrata:
    ffmpeg:
      input_args: preset-rtsp-udp
      inputs:
      - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.1.101/live
        roles:
        - record
        - detect
  #      - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.1.101:554/cam/realmonitor?channel=1&subtype=1
 #         roles:
 #           - detect

    best_image_timeout: 60

    rtmp:
      enabled: false

    motion:
      mask:
      - 1920,295,1920,0,1314,0,1325,65
      improve_contrast: true

    detect:
      enabled: true
      max_disappeared: 25
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      enabled: true
      retain:
        days: 0

      events:
        pre_capture: 10
        post_capture: 10
        objects:
        - person
        - cat
        - bird
        - dog
        retain:
          default: 10

    live:
      height: 1080
      quality: 1

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 1080
      retain:
        default: 15

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      required_zones: []

    objects:
      track:
      - person
      - bird
      - cat
      - dog
      filters:
        person:
          threshold: 0.75
          mask:
          - 1280,269,1280,0,871,0,880,94
        bird:
          threshold: 0.70
          mask:
          - 1280,269,1280,0,871,0,880,94
        cat:
          threshold: 0.70
          mask:
          - 1280,269,1280,0,871,0,880,94
        dog:
          threshold: 0.70
          mask:
          - 1280,269,1280,0,871,0,880,94
      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below

########################################################################################################################
  Loggiato:
    ffmpeg:
      input_args: preset-rtsp-udp
      inputs:
      - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.1.100/live
        roles:
        - record
        - detect
#        - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.1.100:554/cam/realmonitor?channel=1&subtype=1
#          roles: 
#            - detect
#            - record
    best_image_timeout: 60

    rtmp:
      enabled: false

    motion:
      mask:
      - 0,361,0,713,0,1080,502,1080,524,977,562,1080
      - 934,96,1899,91,1875,21,943,26

      improve_contrast: true

    detect:
      enabled: true
      width: 1920
      height: 1080
      max_disappeared: 25
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      enabled: true
      retain:
        days: 0

      events:
        #max_seconds: 300
        pre_capture: 10
        post_capture: 10
        objects:
        - person
        - cat
        - bird
        - dog
        retain:
          default: 10

    live:
      height: 1080
      quality: 1

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 1080
      retain:
        default: 15


    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      required_zones: []

    objects:
      track:
      - person
      - bird
      - cat
      - dog
      filters:
        person:
          threshold: 0.75

        bird:
          threshold: 0.70

        cat:
          threshold: 0.70

        dog:
          threshold: 0.70

      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below

########################################################################################################################
  Piscina:
    ffmpeg:
      input_args: preset-rtsp-udp
      inputs:
      - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.1.108/live
        roles:
        - record
        - detect
#        - path: rtsp://xxxxxxxx:xxxxxxxx@192.168.1.108:554/cam/realmonitor?channel=1&subtype=1
#          roles: 
#            - detect
    best_image_timeout: 60

    rtmp:
      enabled: false

    zones:
      dentro_piscina:
        coordinates: 964,1487,1622,1439,2688,1170,2688,277,531,987,329,1454
        objects:
        - person
        - bird
      bordo_piscina:
        coordinates: 572,994,2612,339,2452,40,369,774

    motion:
      mask:
      - 2688,44,2003,44,2032,143,2688,143
      - 0,865,0,307,0,0,1155,0,649,316


      improve_contrast: true

    detect:
      enabled: true
      max_disappeared: 25
      fps: 5
      stationary:
        interval: 10
        threshold: 50

    record:
      enabled: true
      retain:
        days: 0

      events:
        pre_capture: 10
        post_capture: 10
        objects:
        - person
        - cat
        - dog
        - bird
        retain:
          default: 10

    live:
      height: 1080
      quality: 1

    snapshots:
      enabled: true
      clean_copy: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 1080
      retain:
        default: 15

    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 1080
      required_zones: []

    objects:
      track:
      - person
      - cat
      - dog
      - bird
      filters:
        person:
          threshold: 0.80

        bird:
          threshold: 0.70

        cat:
          threshold: 0.70

        dog:
          threshold: 0.70

      # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object.
      # NOTE: This mask is COMBINED with the object type specific mask below


########################################################################################################################
```

### Any other information that may be helpful

Seems that even if the mqtt mosquitto broker is working the automation doens't trigger the service notify on the iphones. 
I have several other automation with service notify and the notification works perfectly.

I try to use the blueprint in order to have the snapshot and the shortcut to the clip because with yaml automation the notification works but the attachment don't.

Any help is much appreciated and thanks for  your time!
