### ISSUE TITLE
[Issue]: Automation not triggering

### ISSUE THREAD

**Issue by AriaGen** [SgtBatten/HA_blueprints#235]
### Description

Quite recently, the automation, after no updates decided to stop working altogether.
So, after a quick, delete all automations, sync the latest version on the script, and make new automations, I seem to have them back, Sort of. It seems to be hit and miss if it triggers. At first, after a bit of experimenting, I thought it was car_ui being the problem, but looking at a trace of a recent one, it seems to just pass everything altogether. Admittedly, I'm a bit crap at reading the information, so can anyone advise what pushes this route to skip it?

![image](https://github.com/SgtBatten/HA_blueprints/assets/59332818/320d02d0-f0ec-4c02-8330-62aa33eb301c)

![image](https://github.com/SgtBatten/HA_blueprints/assets/59332818/e5e494f1-4312-49db-84bd-9fea5cbb3c77)

### Version

Stable (0.12.0.4a)

### Automation Config

```yaml
alias: Frigate Notify Driveway
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.driveway
    notify_device: b9f3d9b9daf157a885d488754d315016
    base_url: https://hass**
    title: Frigate
    color: "#f44336"
    icon: mdi:cctv
    channel: Driveway
    zone_filter: true
    zones:
      - driveway_zone
      - caverswall_zone
      - edenhurst_zone
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci
mqtt:
  enabled: True
  host: 192.168.1.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: ***
  stats_interval: 30

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 15
  # Optional: enables detection for the camera (default: True)
  enabled: True
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 8
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 150
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 15
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 150

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 3
    # Optional: Per object retention days
    objects:
      person: 3
  # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
  quality: 100

cameras:
  driveway: 
    ffmpeg:
        inputs:
        - path: rtsp://***@192.168.1.5:554/Streaming/Channels/102/
          roles:
            - detect
            - record
            - audio
        output_args:
          record: preset-record-generic-audio-aac
    objects:
      track:
        - person
        - umbrella
        - bicycle
      #  - car
      filters:
        person:
           min_area: 100
           max_area: 300000
           threshold: 0.65
        umbrella:
           min_area: 5000
           max_area: 400000
           threshold: 0.65
        bicycle:
           min_area: 5000
           max_area: 400000
           threshold: 0.65
        car:
           min_area: 2000
           max_area: 500000
           threshold: 0.50
           mask:
            - 626,720,1280,720,1280,0,502,0,759,248
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 3
          mode: active_objects
        objects:
          - person
          - umbrella
          - bicycle
  #        - car
        required_zones:
          - driveway_zone
          - caverswall_zone
    snapshots:
      required_zones:
        - driveway_zone
        - caverswall_zone
        - caverswall_ext_zone
        - edenhurst_zone
    zones:
      driveway_zone:
         coordinates: 238,720,1254,720,1131,614,995,583,1051,386,829,338,725,385,152,532
         #coordinates: 238,720,1254,720,1179,442,1126,418,834,376,152,532
         objects:
           - person
           #- car
      door_zone:
         coordinates: 1210,341,1086,315,1023,582,1136,629
         #coordinates: 238,720,1254,720,1179,442,1126,418,834,376,152,532
         objects:
           - person
           #- car
      caverswall_zone:
         coordinates: 166,460,677,360,698,297,802,283,802,219,147,348
         objects:
           - person
           - bicycle
        #   - car
      caverswall_ext_zone:
         coordinates: 1048,210,1056,255,822,270,758,209
         objects:
           - person
           - bicycle
        #   - car
      edenhurst_zone:
         coordinates: 125,180,570,171,671,230,115,297
         objects:
           - person
           - bicycle
        #   - car
    motion:
      mask:
        - 0,0,0,72,1280,72,1280,0
        #- 751,385,865,441,936,364,829,331
    audio:
  # Optional: Enable audio events (default: shown below)
      enabled: True
  # Optional: Configure the amount of seconds without detected audio to end the event (default: shown below)
  #   max_not_heard: 30
  # Optional: Configure the min rms volume required to run audio detection (default: shown below)
  # As a rule of thumb:
  #    - 200 - high sensitivity
  #    - 500 - medium sensitivity
  #    - 1000 - low sensitivity
  #   min_volume: 500
  # Optional: Types of audio to listen for (default: shown below)
      listen:
      #  - bark
      #  - fire_alarm
        - scream
        - speech
        - yell
      #  - car_alarm
        - alarm
      #  - siren
    mqtt:
      timestamp: False
      bounding_box: True
      crop: True
      quality: 100
      height: 720
    birdseye:
      order: 1

birdseye:
  enabled: false
  restream: false
  width: 1280 
  height: 720
  quality: 1
  mode: continuous
  layout:
    max_cameras: 4

telemetry:
  version_check: True
```
