### ISSUE TITLE
no longer getting notifications 

### ISSUE THREAD

**Issue by ForTheRush** [SgtBatten/HA_blueprints#236]
### Describe the problem you are having or the outcome you are trying to achieve.

ive been using this automation for a while now, and with the update to the 14 beta, my notifications are pretty much broken. About 2/3 of the time I don't receive anything, even when a person is standing directly in front of the camera in a required zone waving their arms. 

The other 1/3 of the time I get notifications when there isn't anyone there, it sees a car drive by (outside of the zone and not a object specified in the object filter). 

To test, I have the reolink app set up to notify me on person detection doorbell press. The reolink app has always been super slow on the notifications (one of the many reasons I moved to frigate in the first place).  On the rare occasion I do get a frigate notification, I've already received the push and email from reolink at 5-10+ seconds prior. 

This automation has always been great in the past, like I'm usually notified within seconds of a person starting to enter a zone, now nothing. 

Due to this I've tried editing the config a bunch of different ways and nothing seems to work. 

### Version

0.14.0-beta3 with 0.12.0.4a 

### Automation config

```yaml
alias: frigate front door notification test
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door_camera
    notify_device: 3e468c9f3d5acd51229761ae0a8a2434
    base_url: https://xxxxxxx.ui.nabu.casa
    title: Alert
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    update_sub_label: false
    critical: "true"
    attachment: snapshot.jpg
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    zones:
      - stairs_1
      - catwalk
    labels:
      - person
      - cat
    cooldown: 0
    silence_timer: 0
    initial_delay: 2
    button_3: "reolink "
    url_3: app://com.mcu.reolink
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.9
  port: 1883
  user: mqttuser
  password: mqttpass
  topic_prefix: frigate
  client_id: frigate

tls:
  enabled: false

environment_vars:
  LIBVA_DRIVER_NAME: radeonsi

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://c2bd7e58145124215bbddd0994433418


database:
  path: /config/frigate.db

objects:
  track:
    - person
    - cat
    - car
    - amazon
    - fedEx
    - ups

snapshots:
  enabled: true
  clean_copy: false
  timestamp: false
  bounding_box: true
  crop: false
  required_zones:
    - stairs_1
    - door_zone_1
    - kays_spot
    - usual_spot
  retain:
    default: 2
    objects:
      person: 3
  quality: 80

detect:
  enabled: true
  fps: 5
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50


motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 100

go2rtc:
  streams:
    front_door_camera_main:
      - rtsp://frigateuser:frigatePassword@192.168.1.178:554/h264Preview_01_main
      - ffmpeg:front_door_camera_main#audio=opus
    front_door_camera_sub:
      - rtsp://frigateuser:frigatePassword@192.168.1.178:554/h264Preview_01_sub
      - ffmpeg:front_door_camera_sub#audio=opus
    car_view_camera_main:
      - rtsp://frigateuser:frigatePassword@192.168.1.210:554/h264Preview_01_main
      - ffmpeg:car_view_camera_main#audio=opus
    car_view_camera_sub:
      - rtsp://frigateuser:frigatePassword@192.168.1.210:554/h264Preview_01_sub
      - ffmpeg:car_view_camera_sub#audio=opus
    court_camera_main:
      - rtsp://frigateuser:frigatepassword@192.168.1.223/stream1
      - ffmpeg:court_camera_main#audio=opus
    court_camera_sub:
      - rtsp://frigateuser:frigatepassword@192.168.1.223/stream2
      - ffmpeg:court_camera_sub#audio=opus

cameras:
  front_door_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_door_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: front_door_camera_main
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 1
          mode: active_objects
          objects:
            person: 2
            car: 2

    detect:
      width: 2560
      height: 1440
      enabled: true

    audio:
      enabled: true
    ui:
      order: 0

    zones:
      stairs_1:
        coordinates: 0.827,1,0.831,0.382,0.651,0.393,0.645,0.121,0.32,0.113,0.319,1,0.593,1
        inertia: 3
        objects:
          - cat
          - fedEx
          - person
      catwalk:
        coordinates: 
          0.838,0.578,0.815,0.212,0.955,0.214,0.947,0.402,0.965,0.598,1,1,0.83,1,0.843,0.828,0.927,0.79,0.922,0.582
        inertia: 3
        objects: person
    motion:
      mask:
        - 0.064,0.269,0.081,0.887,0.287,0.953,0.248,0.614,0.28,0.19
        - 0.693,0,0.695,0.077,0.268,0.072,0.266,0
        - 0.833,0.588,0.92,0.603,0.915,0.786,0.829,0.811
      threshold: 42
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones:
          - stairs_1
          - catwalk
      detections:
        required_zones: stairs_1
    objects:
      filters:
        person:
          mask: 0.369,0.698,0.388,0.694,0.39,0.817,0.371,0.824
  car_view_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/car_view_camera_main
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/car_view_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 1
          mode: active_objects
          objects:
            car: 2
            person: 2
    detect:
      width: 2560
      height: 1440
      enabled: true

    audio:
      enabled: false
    live:
      stream_name: car_view_camera_main
    zones:
      usual_spot:
        coordinates: 0.573,0.258,0.468,0.247,0.466,0.334,0.583,0.347
        inertia: 3
        objects:
          - car
          - person
        loitering_time: 3
      Usual_spot_2:
        coordinates: 0.473,0.341,0.458,0.478,0.589,0.5,0.587,0.359
        loitering_time: 5
        objects:
          - car
          - person
        inertia: 3
      Kay's_spot:
        coordinates: 0.265,0.409,0.312,0.49,0.324,0.352,0.287,0.32
        inertia: 5
        objects: car
      kays_spot_2:
        coordinates: 0.18,0.358,0.196,0.465,0.25,0.413
    motion:
      mask:
        - 0.667,0,0.688,0.09,0.318,0.096,0.324,0.021
        - 0,0.661,0,1,1,1,1,0.642
        - -0.011,0.292,0,0.859,0.096,0.969,0.096,0.281,0.425,0.201,0.359,0.012,0.009,0.008
      threshold: 60
      contour_area: 30
      improve_contrast: false
    ui:
      order: 1
    review:
      detections:
        required_zones:
          - usual_spot
          - Kay's_spot
      alerts:
        required_zones:
          - usual_spot
          - Kay's_spot
          - kays_spot_2
    objects:
      filters:
        car:
          mask:
            - 0.36,0.634,0.409,0.619,0.403,0.706,0.36,0.695
            - 0.392,0.398,0.426,0.422,0.423,0.344,0.387,0.33
  court_camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/court_camera_main?mp4
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/court_camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      retain:
        days: 0
        mode: active_objects
      events:
        retain:
          default: 0
          mode: active_objects
          objects:
            person: 0.5
            cat: 1
    detect:
      width: 1920
      height: 1080
      enabled: true
    audio:
      enabled: false
    ui:
      order: 2
    live:
      stream_name: court_camera_sub
    zones:
      bed:
        coordinates: 0.926,0.462,0.683,0.428,0.409,0.656,0.684,0.878
        inertia: 3
        objects:
          - cat
          - person
      bedroom_door:
        coordinates: 0.063,0.612,0.208,0.847,0.179,0.429,0.164,0.17,0.063,0.133
        inertia: 3
        objects:
          - person
          - cat
      cat_tree:
        coordinates: 0,0,0.06,0,0.07,0.673,0,0.614
        inertia: 3
        objects: cat
    motion: {}
    review:
      detections:
        required_zones:
          - cat_tree
          - bedroom_door
version: 0.14
camera_groups:
  my_cams:
    order: 1
    icon: LuAlignHorizontalDistributeStart
    cameras:
      - car_view_camera
      - court_camera
      - front_door_camera
```
