### ISSUE TITLE
[Issue]: websocket notifications no message 

### ISSUE THREAD

**Issue by Mikescotland** [SgtBatten/HA_blueprints#237]
### Description

When having companion app on FCM notifications all is good, however when switching to websocket, frigate Notifications come with title but no message.
FCM:
DOORCAM
A person detected.
<picture>
Websocket:
DOORCAM
<picture>
This happens only with frigate notifications, any other notification has normal message showing. 
When digging into notifications flow I can see that frigate Notifications inserts line "subject" into websocket notification and it's empty. 

### Version

0.12. 0.4a

### Automation Config

```yaml
alias: Frigate doorcam notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.doorcam
    notify_device: xx
    notify_group: ALL_DEVICES
    base_url: https://xxx
    title: Doorcam
    message: A {{label}} detected at front door
    critical: "true"
    attachment: snapshot.jpg?crop=1
    update_thumbnail: true
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else 'cctv'}}
    zone_filter: true
    zones:
      - entrance
    cooldown: 15
    silence_timer: 10
    button_3: Silence 10 mins
    android_auto: false
    video: ""
    alert_once: true
    sticky: true
    button_1: Video
    button_2: Snapshot
```
