### ISSUE TITLE
[Config Support]: Completely lost on how to create a notification group

### ISSUE THREAD

**Issue by ReticentRobot** [SgtBatten/HA_blueprints#239]
### Describe the problem you are having or the outcome you are trying to achieve.

I currently am duplicating every notification so that I get a notification on my phone and my wife gets a notification on hers.  I'd like to combine them all so that I can alert us both with a single notification.  I'm looking at the Group documentation for Home Assistant, but none of the groups seem to include our phones as a selectable device.  Are there any step by step instructions on how to do this?  Thanks!

### Version

0.12.0.4a

### Automation config

```yaml
alias: Backyard B - Person - Robert (Frisbee Golf)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.backyard_b
    notify_device: 948bad1cb3bfb425eb562c0a2d796b7c
    base_url: https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/
    title: Frisbee Golfer(s)
    message: Person detected in the Frisbee Golf
    critical: "false"
    alert_once: true
    attachment: snapshot.jpg
    update_thumbnail: true
    color: "#ff9800"
    labels:
      - person
    zones:
      - Frisbee_Golf
    button_2: View Live
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    button_3: Open Home Assistant
    url_3: "{{base_url}}/lovelace"
    cooldown: 10
    silence_timer: 10
    loiter_timer: 5
    zone_filter: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    sticky: true
```

**Comment by ReticentRobot** [comment]
Okay, I think I figured out that you have to do it in YAML in the configuration.yaml file, but I'm not sure how to figure out how to reference our phones in this.  I'm pretty sure how I have it below is not going to work, but where do I find the text to use here?

```
#phone app notification group for notifying both phones
notify:
  - name: MOBILE_PHONES
    platform: group
    services:
      - service: Robert's Phone
      - service: Michelle's Phone
```

![image](https://github.com/user-attachments/assets/1468e5b8-c0b8-4256-b6e9-768aac864e09)
