### ISSUE TITLE
[Config Support]: New setup, Notification not working.

### ISSUE THREAD

**Issue by Sevyn13** [SgtBatten/HA_blueprints#244]
### Describe the problem you are having or the outcome you are trying to achieve.

Set up the automation, clicked run and no notification comes to phone. Walked in front of doorbell and no notification comes to phone.

### Version

0.12.0.4a

### Automation config

```yaml
alias: Notify Person Detected at Doorbell
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frigate_doorbell
    notify_device: 62cb2eb1f22685012ec81f969bfdd19b
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    ios_live_view: camera.frigate_doorbell
    android_auto: true
    channel: Cameras
    labels:
      - person
    tap_action: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    tv_position: top-right
    title: Doorbell Camera
    base_url: https://ha.zirlott.net
```

### Frigate Config

```yaml
mqtt:
  host: core-mosquitto
  user: ********
  password: *********
  topic_prefix: frigate
  client_id: frigate

database:
  path: /config/frigate.db

birdseye:
  enabled: True
  mode: continuous
  restream: True
  
audio:
  enabled: True
  listen:
    - bark
    - fire_alarm

objects:
  track:
    - person
    # - car
    - motorcycle
    - cat
    - dog
    - horse
  filters:
    person:
      threshold: 0.75
    car:
      threshold: 0.75
    motorcycle:
      threshold: 0.75
    cat:
      threshold: 0.75
    dog:
      threshold: 0.75
    horse:
      threshold: 0.6

record:
  enabled: True
  #sync_recordings: True
  events:
    pre_capture: 15
    post_capture: 15
    retain:
      default: 30
      mode: active_objects
      objects:
        dog: 7
        cat: 7
        horse: 7

snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  retain:
    default: 180
  quality: 100

timestamp_style:
  position: "bl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

ffmpeg:
  output_args:
      record: preset-record-generic-audio-aac

ui:
  live_mode: webrtc
  time_format: "24hour"
  date_style: full
  time_style: medium

rtmp:
  enabled: True

#-------------------Go2RTC---------------------#
go2rtc:
  streams:
    Doorbell:
      - rtsp://********:*******@10.10.5.1:554/Preview_01_main
      - "ffmpeg:https://10.10.5.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*******&password=********#video=copy#audio=copy#audio=opus"
    Doorbell_sub:
      - rtsp://********:********@10.10.5.1/Preview_01_sub
      - "ffmpeg:http://10.10.5.1/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*********&password=*********"
    
#-------------------CAMERAS-------------------#
cameras:
  Doorbell:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - rtmp
    live:
      stream_name: Doorbell
    detect:
      enabled: True
    webui_url: "https://10.10.5.1"
```
