### ISSUE TITLE
[Config Support]: can't get notifications to work for Frigate on HAOS

### ISSUE THREAD

**Issue by chienb** [SgtBatten/HA_blueprints#245]
### Describe the problem you are having or the outcome you are trying to achieve.

first time using HA and successfully installed Frigate without any issues. Events recording are working properly as well. However, using the Blueprint for Frigate notification doesn't seem to work - manually running the automation doesn't show anything on my iphone. All the devices and entities were able to be discovered. MQTT also seems to be running fine.

`2024-07-22 15:38:05: New client connected from 172.30.33.2:47077 as frigate (p2, c1, k60, u'mqtt').`

`Enable the unauthenticated notification event proxy` is checked.

### Version

0.12.0.4a

### Automation config

```yaml
alias: Front Door - Frigate Notifications (0.12.0.4a)
description: Front Door
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door_2_2
    notify_device: 871a42775eeb44ae6c5cc5ec505578fe
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    ios_live_view: camera.front_door_2_2
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: *

go2rtc:
  streams:
    front_door:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh
      camera.front_door
    side_yard:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh
      camera.side_yard

cameras:
  front_door:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/front_door?video
        input_args: preset-rtsp-restream-low-latency
        roles:
        - detect
        - audio
        - record
        - restream
    zones:
      zone_0:
        coordinates: 410,1097,1095,1104,900,786,615,778
  side_yard:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/side_yard?video
        input_args: preset-rtsp-restream-low-latency
        roles:
        - detect
        - audio
        - record
        - restream

record:
  enabled: true
  retain:
    days: 0
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 30
```
