### ISSUE TITLE
[Issue]: Notification Message only appears if a video notification is able to be created

### ISSUE THREAD

**Issue by ReticentRobot** [SgtBatten/HA_blueprints#246]
### Description

I'm only getting Title, Icon, and Subtitle fields on my notifications unless a video notification is created.  The Message Notification field only shows on the video notification.

### Version

0.12.0.4a

### Automation Config

```yaml
alias: Front Yard A
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frontyard_a
    notify_device: d1360cde879525c8f878834ebb804e10
    base_url: https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/
    title: >-
      Front Yard Camera B - {{'Person' if label == 'Person' else 'Dog' if label
      == 'Dog' else 'Cat' if label == 'Cat' else 'Bird' if label == 'Bird' else
      'Vehicle' if label == 'Car'}}
    message: >-
      {{'Person' if label == 'Person' else 'Dog' if label == 'Dog' else 'Cat' if
      label == 'Cat' else 'Bird' if label == 'Bird' else 'Vehicle' if label ==
      'Car'}} in Front Yard
    critical: "false"
    alert_once: true
    attachment: snapshot.jpg
    update_thumbnail: true
    color: "#ff9800"
    labels:
      - bird
      - person
      - cat
      - car
      - dog
    zones:
      - Driveway
      - Sidewalk
      - Street
      - Lawn
    button_2: View Live
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    button_3: Open Home Assistant
    url_3: /ccab4aaf_frigate-proxy/dashboard
    cooldown: 10
    silence_timer: 10
    loiter_timer: 5
    zone_filter: true
    subtitle: >-
      {{'Woof!' if label == 'Dog' else 'Meow!' if label == 'Cat' else 'Tweet!'
      if label == 'Bird' else 'Vroom!' if label == 'Car'}}
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'bird' if label == 'Bird' else 'car' if
      label == 'Car' else 'homeassistant'}}
    sticky: true
    notify_group: mobile_phones
    group: "{{camera}}"
    debug: true
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.1.102
  user: mqtt-client
  password: password

detectors:
  coral_usb:
    type: edgetpu
    device: usb
  coral_pci:
    type: edgetpu
    device: pci

go2rtc:
  streams:
    frontyard_a:
      - rtsp://admin:password@192.168.1.67:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_b#audio=opus
    frontyard_a_sub:
      - rtsp://admin:password@192.168.1.67:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_a:
      - rtsp://admin:password@192.168.1.70:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_b#audio=opus
    backyard_a_sub:
      - rtsp://admin:password@192.168.1.70:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_b:
      - rtsp://admin:password@192.168.1.64:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_b#audio=opus
    backyard_b_sub:
      - rtsp://admin:password@192.168.1.64:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_c:
      - rtsp://admin:password@192.168.1.65:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_c#audio=opus
    backyard_c_sub:
      - rtsp://admin:password@192.168.1.65:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    backyard_d:
      - rtsp://admin:password@192.168.1.68:554/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - ffmpeg:backyard_c#audio=opus
    backyard_d_sub:
      - rtsp://admin:password@192.168.1.68:554/cam/realmonitor?channel=1&subtype=1#backchannel=0
    front_doorbell:
      - ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password=qXPf3pAz#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.30/Preview_01_sub
    front_doorbell_sub:
      - ffmpeg:http://192.168.1.30/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password=qXPf3pAz

cameras:
  frontyard_a:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontyard_a
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontyard_a_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontyard_a?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.336,0,0,0,0,0.32,0.225,0.225,0.249,0.33,0.167,0.381,0.209,0.476,0.541,0.537,0.626,0.425,0.552,0.32,0.599,0.165,0.519,0
        - 0.513,0,0.572,0.222,0.746,0.285,1,0.413,1,0
        - 0.806,0.475,0.894,0.466,1,0.515,1,1,0.962,1,0.933,0.865,0.952,0.812,0.747,0.557,0.71,0.499
      threshold: 35
      contour_area: 20
      improve_contrast: 'true'
    zones:
      Sidewalk:
        coordinates: 
          0.07,0.467,0.177,0.402,0.26,0.582,0.458,0.768,0.659,0.9,0.828,0.996,0.495,0.999,0.208,0.722
        objects:
          - person
          - bird
          - cat
          - dog
      Driveway:
        coordinates: 0.145,0.232,0,0.284,0,0.508,0.41,0.286,0.224,0.246
        inertia: 3
      Street:
        coordinates: 0.569,0.219,0.528,0.313,1,0.529,1,0.4
        inertia: 3
      Lawn:
        coordinates: 
          1,0.518,0.631,0.349,0.433,0.279,0.144,0.43,0.236,0.589,0.528,0.821,0.815,0.996,1,1
        inertia: 3
    review:
      alerts:
        required_zones:
          - Sidewalk
          - Driveway
          - Street
          - Lawn
      detections:
        required_zones:
          - Sidewalk
          - Driveway
          - Street
          - Lawn
  backyard_a:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_a
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_a_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_a?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask: 
        0.511,0.407,0,0.371,0,0.001,0.559,0,0.56,0.149,0.602,0.156,0.601,0.295,0.534,0.314
  backyard_b:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_b
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_b_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_b?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask: 
        0,0.293,0,0,0.401,0.001,0.401,0.14,0.476,0.086,0.525,0.112,0.592,0.07,0.624,0.087,0.662,0.074,0.721,0.123,0.818,0.052,0.857,0.266,0.797,0.512,0.719,0.583,0.654,0.424,0.637,0.349,0.377,0.354,0.353,0.476,0.323,0.371,0.279,0.315,0.155,0.377,0.111,0.351,0.103,0.329,0.074,0.319,0.042,0.268
    zones:
      Frisbee_Golf:
        coordinates: 0.055,0,0.044,0.297,0.309,0.228,0.768,0.172,0.821,0
      Backyard:
        coordinates: 1,0.16,0,0.416,0.016,1,1,1,1,0.696
  backyard_c:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_c
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_c_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_c?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask: 
        0.538,0.287,0.674,0.285,0.678,0.153,0.704,0.075,0.882,0.128,0.884,0,0,0,0.001,0.373,0.089,0.371,0.091,0.233,0.101,0.126,0.147,0.071,0.335,0.019,0.524,0.029,0.537,0.141
  backyard_d:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard_d
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_d_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/backyard_d?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.108,0.784,0.169,0.74,0.239,0.722,0.283,0.762,0.288,0.814,0.189,0.878,0.13,0.862
        - 0.017,0.296,0.061,0.284,0.063,0.228,0.12,0.243,0.12,0.204,0.132,0.155,0.294,0.153,0.317,0.179,0.324,0.22,0.452,0.202,0.451,0.158,0.481,0.128,0.551,0.115,0.592,0.157,0.593,0.182,0.802,0.191,0.784,0.17,0.745,0.163,0.719,0.134,0.673,0.17,0.635,0.167,0.638,0.002,0.095,0,0.055,0.122,0,0.109,0.001,0.17,0.019,0.178
  front_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub?audio
          input_args: preset-rtsp-restream
          roles:
            - audio
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
    record:
      enabled: true
      retain:
        days: 30
        mode: all
    snapshots:
      enabled: true
    motion:
      mask:
        - 0.739,0,0.511,0.373,0.506,0.612,0.458,0.714,0.409,1,0.867,1,1,1,1,0.58,1,0,0.916,0
        - 0.539,0.458,0.544,0.496,0.368,0.49,0.374,0.455
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      zone_0:
        coordinates: 0,1,0,0.227,0.376,0.333,0.51,0.378,0.518,0.588,0.597,1
        inertia: 3
    review:
      alerts:
        required_zones: zone_0
      detections:
        required_zones: zone_0
version: 0.14

detect:
  stationary:
    interval: 50
    threshold: 50

objects:
  track:
    - bird
    - car
    - cat
    - dog
    - package
    - person

```
```


### Any other relevant information

```yaml
Executed: July 25, 2024 at 1:12:01 PM
Result:
params:
  domain: logbook
  service: log
  service_data:
    name: Frigate Notification
    message: |-
      DEBUG: 
        Info:
          fps: 5, 
          frigate event id: 1721931120.969942-565m9u, 
          object (formatted): car (Car),
        Config: 
          camera(formatted): frontyard_a(Frontyard A), 
          Base URL: https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa, 
          critical: False, 
          alert once: True, 
          Update Thumbnails: True, 
          Video: https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4, 
          Target: group (input/formatted): mobile_phones/mobile_phones, 
          cooldown: 10s, 
          loiter timer: 5s, 
          initial delay: 0s, 
          color: #ff9800, 
          sound: default, 
          android_auto: False, 
          Group: frontyard_a, 
          Channel: , 
          Sticky: True, 
          Title: Front Yard Camera B - Vehicle, 
          Message: Vehicle in Front Yard,
          Subtitle: Vroom!, 
          tap_action: https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4, 
          button 1 Text/URL/Icon: View Clip (https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4) , 
          button 2 Text/URL/Icon: View Live (https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/camera_proxy_stream/camera.frontyard_a?token=None) , 
          button 3 Text/URL/Icon: Open Home Assistant (/ccab4aaf_frigate-proxy/dashboard) , 
          icon: mdi:car
          tv: False, 
          tv_position: center, 
          tv_size: large, 
          tv_duration: 10, 
          tv_transparency: 0%, 
          tv_interrupt: False, 
        Filters: 
          Zones: 
            zone filter toggle on: True, 
            Multi-Zone toggle on: False, 
            Required zones: ['Driveway', 'Sidewalk', 'Street', 'Lawn'], 
            Entered Zones: [], 
            Zone Filter TEST: FAIL, 
          Required objects TEST: 
            Input: ['bird', 'person', 'cat', 'car', 'dog'], 
            TEST: PASS
          presence entity (not home):
            Entity: 
            TEST:  PASS, 
          disabled times: [], 
          State Filter: 
            state filter toggle on: False, 
            state filter entity: , 
            required states: [], 
            State Filter TEST: PASS,
          Custom Filter: True
  target: {}
running_script: false
```

```
Iteration 1
Executed: July 25, 2024 at 1:12:01 PM
Result:
params:
  domain: logbook
  service: log
  service_data:
    name: Frigate Notification
    message: |-
      DEBUG (in loop): 
        Send Notification: False
        Info: 
          sublabel: None, 
          image: "https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/snapshot.jpg"
          Title: Front Yard Camera B - Vehicle
          message: Vehicle in Front Yard
          iOS sound: disabled by alert once, 
          Android Sound: disabled by alert once, 
          iOS url: /api/frigate/notifications/1721931120.969942-565m9u/snapshot.jpg
          video: "https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4"
          critical: False, 
        Triggers: 
          New Snapshot: False 
          Presence Changed: False, 
          Stationary Moved: True, 
          Entered Zones Changed: False, 
          sublabel changed: False, 
        Conditions: 
          Loitering: False
            or
          Filters: 
            Zones: 
              Zone Filter Enabled: True, 
              Multi Zone Enabled: False, 
              Required Zones: ['Driveway', 'Sidewalk', 'Street', 'Lawn'], 
              Last Zones: [], 
              Entered zones: 0 - [], 
              TEST: FAIL, 
            Object Filter: 
              Input: ['bird', 'person', 'cat', 'car', 'dog'], 
              TEST: PASS, 
            Presence entity (not home):
              Entity: , 
              TEST:  PASS, 
            Time Filter:
              Disabled times: [], 
              TEST: PASS
            State Filter: 
              state filter toggle on: False, 
              state filter entity: , 
              required states: [], 
              TEST: PASS, 
            Custom Filter: PASS,
  target: {}
running_script: false
Iteration 2
Executed: July 25, 2024 at 1:12:01 PM
Result:
params:
  domain: logbook
  service: log
  service_data:
    name: Frigate Notification
    message: |-
      DEBUG (in loop): 
        Send Notification: False
        Info: 
          sublabel: None, 
          image: "https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/snapshot.jpg"
          Title: Front Yard Camera B - Vehicle
          message: Vehicle in Front Yard
          iOS sound: disabled by alert once, 
          Android Sound: disabled by alert once, 
          iOS url: /api/frigate/notifications/1721931120.969942-565m9u/snapshot.jpg
          video: "https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4"
          critical: False, 
        Triggers: 
          New Snapshot: False 
          Presence Changed: False, 
          Stationary Moved: False, 
          Entered Zones Changed: True, 
          sublabel changed: False, 
        Conditions: 
          Loitering: False
            or
          Filters: 
            Zones: 
              Zone Filter Enabled: True, 
              Multi Zone Enabled: False, 
              Required Zones: ['Driveway', 'Sidewalk', 'Street', 'Lawn'], 
              Last Zones: [], 
              Entered zones: 1 - ['street'], 
              TEST: FAIL, 
            Object Filter: 
              Input: ['bird', 'person', 'cat', 'car', 'dog'], 
              TEST: PASS, 
            Presence entity (not home):
              Entity: , 
              TEST:  PASS, 
            Time Filter:
              Disabled times: [], 
              TEST: PASS
            State Filter: 
              state filter toggle on: False, 
              state filter entity: , 
              required states: [], 
              TEST: PASS, 
            Custom Filter: PASS,
  target: {}
running_script: false
Iteration 3
Executed: July 25, 2024 at 1:12:12 PM
Result:
params:
  domain: logbook
  service: log
  service_data:
    name: Frigate Notification
    message: |-
      DEBUG (in loop): 
        Send Notification: False
        Info: 
          sublabel: None, 
          image: "https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/snapshot.jpg"
          Title: Front Yard Camera B - Vehicle
          message: Vehicle in Front Yard
          iOS sound: disabled by alert once, 
          Android Sound: disabled by alert once, 
          iOS url: /api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4
          video: "https://lk429i4ietkmp22jttn8hcebg21youzv.ui.nabu.casa/api/frigate/notifications/1721931120.969942-565m9u/frontyard_a/clip.mp4"
          critical: False, 
        Triggers: 
          New Snapshot: False 
          Presence Changed: False, 
          Stationary Moved: False, 
          Entered Zones Changed: False, 
          sublabel changed: False, 
        Conditions: 
          Loitering: False
            or
          Filters: 
            Zones: 
              Zone Filter Enabled: True, 
              Multi Zone Enabled: False, 
              Required Zones: ['Driveway', 'Sidewalk', 'Street', 'Lawn'], 
              Last Zones: ['street'], 
              Entered zones: 1 - ['street'], 
              TEST: FAIL, 
            Object Filter: 
              Input: ['bird', 'person', 'cat', 'car', 'dog'], 
              TEST: PASS, 
            Presence entity (not home):
              Entity: , 
              TEST:  PASS, 
            Time Filter:
              Disabled times: [], 
              TEST: PASS
            State Filter: 
              state filter toggle on: False, 
              state filter entity: , 
              required states: [], 
              TEST: PASS, 
            Custom Filter: PASS,
  target: {}
running_script: false
```
```
