### ISSUE TITLE
[Issue]: No trigger for audio detect only camera

### ISSUE THREAD

**Issue by longhtran91** [SgtBatten/HA_blueprints#248]
### Description

I have a camera that points at the baby bassinet and on Frigate I only configure for crying audio detection only. I could never get the automation to trigger when there is crying sound detected. I can see in the logbook that crying sound is detected
<img width="342" alt="Screenshot 2024-07-27 at 10 24 09 PM" src="https://github.com/user-attachments/assets/2196dc59-8658-44f9-9fea-b20c4e0cf206">

As soon as, I add to track person object for the camera. It will trigger the automation with label Person

### Version

0.12.0.4a

### Automation Config

```yaml
alias: Frigate Baby Bassinet
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.baby_bassinet
    notify_device: d50ae4e1f1351cd252adbc2379819954
    base_url: https://ha.domain.com
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    critical: "true"
    ios_live_view: camera.baby_bassinet
    debug: true
    notify_group: family_phones
```

### Frigate Config

```yaml
camera:
  baby_bassinet:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
      - path: rtsp://127.0.0.1:8554/baby_bassinet
        input_args: preset-rtsp-restream
        roles:
        - record
        - audio
    motion:
      mask:
      - 1374,55,1868,55,1868,22,1374,22
    objects:
      track: []  
    audio:
      min_volume: 200
      listen:
      - crying
      filters:
        crying:
          threshold: 0.6
```
