### ISSUE TITLE
[Feature Request]: Generative AI - LLM Vision

### ISSUE THREAD

**Issue by patrik-malina** [SgtBatten/HA_blueprints#249]
Great work @SgtBatten and thank you for your time on this. Ifyou could consider next:

As new version LLM Vision (before GPT vision) supports Frigate Event ID, you could implement this new feature.
Please visit: https://github.com/valentinfrlch/ha-llmvision

**Comment by SgtBatten** [comment]
Happy for you to have a crack at it. I don't have much time any more.

**Comment by valentinfrlch** [comment]
Hey just came accross this. 
I have created a blueprint to send notifications with an AI summary and a video preview of frigate events.
See this page for more info: https://llm-vision.gitbook.io/examples/examples/automations#frigate-event-summary

I can submit a PR if you like.

**Comment by SgtBatten** [comment]
Yes please. this looks amazing and something i;ve not had time to implement.

**Comment by valentinfrlch** [comment]
So the blueprints work but I'm still adding new features. I also haven't tested this on android yet. I can for sure add them now but I will probably forget to submit a PR every time I update them.

**Comment by stalakerob** [comment]
Another idea: optionally use LLM Vision to verify objects detected by frigate. This would help to reduce false positives significantly. Unfortunately I don't have the skills to modify this blueprint accordingly.

Example code:
`   - service: llmvision.image_analyzer
      data:
        model: claude-3-5-sonnet-20241022
        message: >
          {% if object == 'person' %}
            Are there any persons in this image? Ignore boxes with labels. Answer with yes or no. The answer must be a single word.
          {% endif %}
        image_file: /media/snapshots/{{id}}.jpg
        target_width: 1280
        detail: low
        max_tokens: 50
        temperature: 0.2
        provider: 01JATCRQA65HDXTG0H0QBJ0FMP
        include_filename: true
      response_variable: response

    - service: input_number.set_value
      target:
        entity_id: input_number.frigate_false_postive
      data_template:
        value: >-
          {% if response.response_text == 'Yes' %}
            0
          {% else %}
            1
          {% endif %}
`

**Comment by SgtBatten** [comment]
frigate 0.15 has AI descriptions and frigate plus has custom models. I still will look at this but working on releasing 0.14 blueprint first

**Comment by stalakerob** [comment]
This is working with Frigate 0.14. It sends the frigate snapshot to a LLM Vision service (Anthropic in the example above) and checks if the AI also recognizes a person. This reduces false positive notifications.

**Comment by SgtBatten** [comment]
> This would help to reduce false positives significantly. Unfortunately I don't have the skills to modify this blueprint accordingly.

you wouldnt need to add it to the blueprint, simply have this service trggered by mqtt and then generate a boolean with true if its a person. then use that boolean in ther state filter option.

**Comment by stalakerob** [comment]
I thought about this but as far as I know you cannot prioritise one automation over another for the same trigger. So you would I make sure that the person boolean is set before the blueprint based automation runs?

So for now I took over the blueprint based automation and modified the yaml:

`…..
##### Blueprint code
        - alias: Notify on new object
          choose:
          - conditions:
            - condition: template
              value_template: '{{ zones_satisfied }}'
            - condition: template
              value_template: '{{ not initial_home }}'
            - condition: template
              value_template: '{{ not state_only or states(input_entity)|lower in
                states_filter }}'
            - condition: template
              value_template: '{{ custom_filter }}'
            sequence:
            - choose:
              - conditions:
                - condition: template
                  value_template: '{{ not notify_group_target }}'
                sequence:
##### Added code starts here
                - target: # set false positive helper to false
                    entity_id: input_number.frigate_false_postive
                  data:
                    value: 0
                  action: input_number.set_value
                - if:
                  - condition: template 
                    value_template: '{{ is_state(''input_boolean.llm_vision_check'',''on'') }}' # if LLM Vision check enabled
                  then:
                    sequence:
                    - data_template:
                        id: '{{id}}'
                      action: shell_command.get_frigate_snapshot # Download snapshot to {{id}}.jpg file in /media/snapshots
                    - data:
                        model: claude-3-5-sonnet-20241022
                        message: Are there any persons in this image? Ignore boxes
                          with labels. Answer with yes or no. The answer must be a
                          single word.
                        image_file: /media/snapshots/{{id}}.jpg
                        target_width: 1280
                        detail: low
                        max_tokens: 50
                        temperature: 0.2
                        provider: 0123TCRQA65H1XTG0Y0QBJPPMX
                        include_filename: true
                      response_variable: response
                      action: llmvision.image_analyzer
                    - target:
                        entity_id: input_number.frigate_false_postive
                      data_template:
                        value:
                         "{% if response.response_text == 'Yes' %} # true positive
                           0
                          {% else %} # false positive
                           1
                         {% endif %}"
                      action: input_number.set_value

                - condition: template # check if false positive 
                  value_template: '{{ states(''input_number.frigate_false_postive'')
                    | int == 0 }}'
##### Added Code ends here

##### Blueprint code continues`

**Comment by innovatorgit** [comment]
+1 very interested in adding LLM Vision into the Frigate Notification BP.

**Comment by nkm8** [comment]
Throwing in my own opinion on this feature - Frigate already supports native AI image processing for use in semantic search: https://docs.frigate.video/configuration/genai

Instead of duplicating the image processing by re-sending the image from HA to an LLM, it would be great if the blueprint was updated to support processing the description updates provided by Frigate: https://docs.frigate.video/integrations/mqtt#frigatetracked_object_update

**Comment by deverelo** [comment]
I've been messing around today to try and adjust this blueprint.
I don't think I have it done in the best way but it works right now (single iPhone receiving notification, 3 cameras)
Yaml is doing my head in and making a mess.

I added another 'repeat until' **before** the last one in the automation, it's a stripped down version of the original final update sequence, and I think it needs the final update turned on:
```
    - repeat:
        sequence:
          - wait_for_trigger:
              #deverelo
              - trigger: mqtt
                topic: '{{mqtt_tracked_object_update_topic}}'
                payload: '{{ id }}'
                value_template: '{{ value_json[''id''] }}'
                #/deverelo
            timeout:
              minutes: "{{timeout}}"
            continue_on_timeout: false
          - variables:
              # use the subsequent attchment variable if set
              attachment_2: !input attachment_2
              attachment: "{{iif(attachment_2, attachment_2, attachment)}}"
              event: "{{ wait.trigger.payload_json }}"
              type: "{{event['type']}}"
              # import the title and message again so any sublabel, object or zone changes are captured.
              title: !input title
              #deverelo
              message_2: '{{event[''description'']}}'
              message: '{{iif(message_2, message_2, message)}}'
              #/deverelo
              subtitle: !input subtitle

              critical_input: !input critical
              critical: "{{ true if critical_input == 'true' else true if critical_input == True else false }}"
              tts: !input tts

              # update is used to determine if we should play a sound. if it returns true, we should be silent.
              silent_update: "{{ alert_once or (not presence_changed and not zone_updated and not object_updated and not sub_label_updated) }}"
```
Added this additional topic:
```
    mqtt_topic:
      name: MQTT Topic (Advanced)
      description: The MQTT topic Frigate sends review messages in.
      default: frigate/reviews
    #deverelo
    mqtt_tracked_object_update_topic:
      name: MQTT Tracked Object Update Topic (Advanced)
      description: The MQTT topic Frigate sends update messages in for GenAI descriptions.
      default: frigate/tracked_object_update
    #/deverelo
```
and this added this in trigger_variables:
```
trigger_variables:
  mqtt_topic: !input mqtt_topic
  #deverelo
  mqtt_tracked_object_update_topic: !input mqtt_tracked_object_update_topic
  #/deverelo
```
