### ISSUE TITLE
[Config Support]: No notification on Android device

### ISSUE THREAD

**Issue by mikoday** [SgtBatten/HA_blueprints#25]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello, I receive notification from this automation, but not from blueprint automation. How can I debug this issue?
No logbook events found in the Logbook.

`alias: Test Camera`
`description: ""`
`trigger:`
`  - platform: mqtt`
`    topic: frigate/events`
`action:`
`  - device_id: 6dce10ffd83a731196bd0099e43709e2`
`    domain: mobile_app`
`    type: notify`
`    message: Person at back door!`
`    title: Test MQTT Notification`
`mode: single`

### Version

0.12.0.1

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.basement
    notify_device: 6dce10ffd83a731196bd0099e43709e2
    labels:
      - person
    debug: true
    tv_size: large
```

### Frigate Config

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
mqtt:
  host: homeassistant
  port: 1883
  topic_prefix: frigate_basement
  client_id: frigate_basement
  user: admin
  password: <redacted>
  stats_interval: 60
cameras:
  basement:
    ffmpeg:
      inputs:
        # High resolution stream 1920x1080
        - path: rtsp://192.168.0.3:554/rtsp_live0
          roles:
            - record
        # Low resolution stream 640x480
        - path: rtsp://192.168.0.3:554/rtsp_live1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 30
    objects:
      track:
        - person
        - car
        - bicycle
        - motorcycle
        - dog
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: false
      height: 175
      required_zones: []
      retain:
        default: 10
        objects:
          person: 15
```
