### ISSUE TITLE
[Issue]: Silence Doesn't Work

### ISSUE THREAD

**Issue by Spectre5** [SgtBatten/HA_blueprints#250]
### Description

I've added the silence (for 30 min) option to my configuration, but it doesn't seem to work.  I still get constant notifications (my kid playing in the yard).

### Version

0.12.0.3c (beta)

### Automation Config

```yaml
alias: Front Door (Frigate)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.front_door_2
    notify_device: 2a8c732783abae83f6b29b02bf31ebba
    state_filter: false
    update_thumbnail: true
    attachment: snapshot.jpg?bbox=1
    button_1: Clip
    button_2: Snapshot
    button_3: Silence (30 min)
    alert_once: true
```

### Frigate Config

```yaml
Not Relevant
```

### Any other relevant information

Here is my log from home assisstant, though I have no idea if this is relevant to this automation or something else.  I just pushed silence a few more times and didn't notice any new entries, so probably not related.

```
2024-08-03 17:26:02.306 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif((update or sound == 'none'), 0, volume) }}'
2024-08-03 17:28:08.736 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif(update, 'none', sound) }}'
2024-08-03 17:28:08.736 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif((update or sound == 'none'), 0, volume) }}'
2024-08-03 17:29:26.905 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif(update, 'none', sound) }}'
2024-08-03 17:29:26.905 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'update' is undefined when rendering '{{ iif((update or sound == 'none'), 0, volume) }}'
```

**Comment by SgtBatten** [comment]
It only silences new events, not the ongoing one

**Comment by Spectre5** [comment]
It seemed to still be new events though - I don't think it was an update to the current event since I kept getting whole new pop up notifications - and also ones from a friend.  I thought they were all new events since they would go in and out of view of the camera.  Maybe I just don't understand the distinction well enough.  If that is the case, then is it possible to stop all notifications from the entire camera for some time?

**Comment by SgtBatten** [comment]
To check if it's working, next time you hit silence, go into the automations pagE and co firm the automation in question is disabled. 

Also you may want to try the newer release in case it is an old bug.

**Comment by Spectre5** [comment]
I just walked out to trigger it, then silenced the notifications and HA still shows the automation enabled.  I then waited about 10 minutes and walked out again and got a notification.  So it does seem to not work for me for some reason.  I'll try updating to the new blueprint.  Is there any easier way to do that besides removing the entire automation and re-creating it from the new blueprint?

**Comment by Spectre5** [comment]
Now with 0.12.0.4 Beta, I still have the same issue.  If I trigger an alert, hit "silence", the automation in HA remained enabled.  And new notifications still come during that 30 minutes window too.  I waited 5 minutes and had someone else walk outside and got another notification.

**Comment by Spectre5** [comment]
Probably not related to this silencing issue, but the log entries I put in the OP are related to this automation, for what its worth.  Those come from these lines in the update notification:

```yaml
                                    push:
                                      sound:
                                        name: "{{ iif(update, 'none', sound) }}"
                                        volume: "{{ iif((update or sound == 'none'), 0, volume) }}"
                                        critical: "{{ iif(critical, 1, 0) }}"
                                    entity_id: "{{ios_live_view}}"
```
