### ISSUE TITLE
[Config Support]: Does not seem to want to be added to HASS Supervized

### ISSUE THREAD

**Issue by leonbrag** [SgtBatten/HA_blueprints#254]
### Describe the problem you are having or the outcome you are trying to achieve.

When I click add, I get this:

![image](https://github.com/user-attachments/assets/fd67b025-e078-44a3-9038-dc3ab8559968)

### Version

2024.08.0

### Automation config

```yaml
cannot even get it added
```

### Frigate Config

```yaml
Relevant part, integration with MQTT works

mqtt:
  enabled: true
  host: 192.168.4.33
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
  topic_prefix: frigate
  port: 1883
```
