### ISSUE TITLE
[Config Support]: Custom "Notification sound" on iOS

### ISSUE THREAD

**Issue by musapinar** [SgtBatten/HA_blueprints#258]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,
How does "notification sound" setting work ?
![2024-08-13_03h33_21](https://github.com/user-attachments/assets/5bfa60e7-c8cf-43ee-a004-45e06dfb4c80)

It is not yet documented as far as I can see, except this:

```
    sound:
      name: Notification Sound - iOS only (Optional)
      description: You can specify a sound file on your device that will play for the notifications. You will need to import the sound file into Home Assistant.
      default: default
      selector:
        select:
          options:
            - default
            - none
          custom_value: true
```

I imported the sound within the root path. No success.
Tried within /www/ as well.
Tried with ```sound: /homeassistant/mixkit-gaming-lock-2848.wav```.
etc. No joy.
![2024-08-13_03h36_38](https://github.com/user-attachments/assets/018ad54c-939e-44ce-95e6-0c60259a3239)

Thank you

### Version

0.12.0.4a

### Automation config

```yaml
- id: '1723502560176'
  alias: Porche
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.porche_2
      notify_device: 7ebed67d640b24ff8f3a9789d9b22094
      attachment: snapshot.jpg?bbox=1
      update_thumbnail: true
      tv: false
      base_url: https://redacted.redacted.com
      sound: mixkit-gaming-lock-2848.wav
```

### Frigate Config

```yaml
I believe Frigate Config is irrelevant. I will poste if necessary.
```
