### ISSUE TITLE
[Feature Request]: Add Signal Messenger (Already did legwork)

### ISSUE THREAD

**Issue by ghzgod** [SgtBatten/HA_blueprints#259]
Hey SgtBatten, wonderful blueprint!

I noticed you have IOS notifications and Telegram now too.  Any chance we can add signal messenger?

I added new variables to your blueprint

  frigate_url:
    name: Frigate (http://x.x.x.x:xxxx)
    description: "The url for your Frigate instance."
    default: ''
  signal_service_name:
    name: Signal Service Name
    description: "The name of your Signal service in configuration.yaml (CASE-SENSITIVE)."
    default: ''
    
  I wish I could choose notification services that exist in the config.yaml versus typing it out.
  
  The other thing is I cannot get the notifcation working with 
  
  `'{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'`
  
  but I can if I use the following and allow my frigate url in the config yaml like so 

  ```
  allowlist_external_urls:
    - "http://x.x.x.x:xxxx"
  ```  

  `http://{{ frigate_url }}/clips/{{trigger.payload_json['after']['camera'] | lower }}-{{trigger.payload_json['after']['id'] }}.jpg`
  
  
  
  The full action for signal is 

```  
action: notify.{{signal_service_name}}
metadata: {}
data:
  title: '{{title}}'
  message: '{{message}}'
  data:
    urls: 
      -  http://{{ frigate_url }}/clips/{{trigger.payload_json['after']['camera'] | lower }}-{{trigger.payload_json['after']['id'] }}.jpg
 ```

 Now this isn't working exactly.  I can get signal notifications but no attachment of the image
 
 but this automation I created does work (for reference)
 
 ```
alias: Frigate Test
description: ""
trigger:
  - platform: mqtt
    topic: frigate/events
    enabled: false
condition: []
action:
  - data:
      message: >
        {{ now().strftime('%H:%M %A %d %B %Y') }} {{
        trigger.payload_json['after']['label'] | title }} Detected on {{
        trigger.payload_json['after']['camera'] | title }} camera
      data:
        urls:
          - >-
            http://x.x.x.x:xxxx/clips/{{
            trigger.payload_json['after']['camera'] | lower }}-{{
            trigger.payload_json['after']['id'] }}.jpg
    action: notify.signal
  - data:
      message: >
        {{ now().strftime('%H:%M %A %d %B %Y') }} {{
        trigger.payload_json['after']['label'] | title }} Detected on {{
        trigger.payload_json['after']['camera'] | title }} camera
      data:
        urls:
          - >-
            http://x.x.x.x:xxxx/clips/{{
            trigger.payload_json['after']['camera'] | title }}-{{
            trigger.payload_json['after']['id'] }}.jpg
    action: notify.signal
mode: single
```
 I have spent 5-6 hours on this but I know its not optimal.  Anything you can do or suggest is great and I appreciate you!

**Comment by ghzgod** [comment]
Nevermind got this working with your original template. NO NEED TO MODIFY the original blueprint

For those that are curious

1. Make sure you have signal notify service setup and tested to make sure it sends notifications.  I have a group chat with myself called "Frigate" in signal messenger, and the group ID of that chat (look up signal-cli on github for docs) is what I send my messages to.  My config.yaml looks like this

```
notify:
  - name: signal
    platform: signal_messenger
    url: "http://ip:port" # the URL where the Signal Messenger REST API is listening (docker service for me)
    number: "+COUNTRYCODE PHONENUMBER" # the sender number
    recipients:
      - "group.XXXXX
```

2. Edit configuration.yaml to have (RESTART AFTER YOU DO THIS)

```
homeassistant:
  allowlist_external_urls:
    - "http://IP:PORT" # Replace with home assistant ip:port
```

When you are creating your automation blueprint, add that same http://IP:PORT under Base URL (Optional) field

Under blueprint Custom Action (Auto Trigger) field add this 

```
action: notify.signal
metadata: {}
data:
  title: "{{title}}"
  message: "{{message}}"
  data:
    verify_ssl: false
    urls:
      - >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}
```

Cheers!

**Comment by SgtBatten** [comment]
Nice one!

Do you only have access to HA externally using IP:port?

Most of us have something like homeassistant.mydomain.com setup which is typically used for the base url. I'm just curious if that works or you need the io port specifically.

**Comment by ghzgod** [comment]
> Nice one!
> 
> Do you only have access to HA externally using IP:port?
> 
> Most of us have something like homeassistant.mydomain.com setup which is typically used for the base url. I'm just curious if that works or you need the io port specifically.

I run it in a docker so I specify local ip and docker port.  But you can use external domain too.

**Comment by zutewas** [comment]
The blueprint with signal messenger works not for me.

I set the **Base URL (Optional)**  to ` https://homeassistant.my.world` and **Custom Action (Auto Trigger)** to 


```
action: notify.signal_myphone
metadata: {}
data:
  title: "{{title}}"
  message: "{{message}}"
  data:
    verify_ssl: false
    urls:
      - >-
        {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}
```

Signal Messenger notifications are working  if I use it like this in a automation 

```
data:
  message: Motion detect ( {{trigger.payload_json['after']['camera']}} )
  data:
    verify_ssl: false
    urls:
      - >-
        https://homeassistant.my.world/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
    text_mode: styled
action: notify.signal_myphone
```

If I use the blueprint with description of @ghzgod the I get this error in traces of the automation from blueprint:

`Error: 404 Client Error: Not Found for url: https://homeassistant.my.world/api/frigate/notifications/1741548131.483585-77wa0i/https://homeassistant.my.world/api/frigate/notifications/1741548131.483585-77wa0i/thumbnail.jpg`

Why are the URL twice and not correct?
