### ISSUE TITLE
[Issue]: Template variable warning: 'update' is undefined when rendering '{{ iif(update, 'none', sound) }}'

### ISSUE THREAD

**Issue by Uschinator** [SgtBatten/HA_blueprints#263]
### Description

After the Notification on my iPhone i get following warning in the Logs:

Logger: homeassistant.helpers.template
Quelle: helpers/template.py:2651
Erstmals aufgetreten: 08:28:45 (8 Vorkommnisse)
Zuletzt protokolliert: 08:33:54

Template variable warning: 'update' is undefined when rendering '{{ iif(update, 'none', sound) }}'
Template variable warning: 'update' is undefined when rendering '{{ iif((update or sound == 'none'), 0, volume) }}'

### Version

0.12.0.4a

### Automation Config

```yaml
alias: "Automatisch: Person Driveway erkannt..."
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.driveway_cam
    notify_device: 3bf2e573e90e180104d80893df32832d
    notify_group: notify.Frigate_Notify_Group
    title: Verdächtige Person...
    message: ...in der Auffahrt!
    alert_once: false
    update_thumbnail: false
    zones:
      - driveway_detection_zone
    labels:
      - person
    cooldown: 120
    silence_timer: 5
    tap_action: /lovelace/cams
    update_sub_label: false
    attachment: thumbnail.jpg
    zone_filter: true
    debug: false
    sound: none
    volume: 0
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.0.xxx
  user: mqtt
  password: mqtt
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 15

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: false
  restream: false
  mode: objects
objects:
  track:
    - person
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.66
      min_score: 0.66
cameras:
### Driveway Camera ###
  Driveway_CAM:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.0.xxx:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user:password@192.168.0.xxx:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - Driveway_Detection_Zone
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 14
          mode: active_objects
    motion:
      mask:
        - 575,62,430,44,427,74,53,82,52,41,0,42,0,0,640,0,640,480,492,480
    zones:
      Driveway_Detection_Zone:
        coordinates: 640,480,640,37,229,21,234,143,147,144,145,27,0,27,0,480

### Woodway Camera ###
    review:
      alerts:
        required_zones:
          - Driveway_Detection_Zone
  Woodway_CAM:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.0.xxx:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://user:password@192.168.0.xxx:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - Woodway_Detection_Zone
      retain:
        default: 14
    record:
      enabled: true
      events:
        retain:
          default: 14
          mode: active_objects
    motion:
      mask:
        - 366,0,0,0,0,131
    zones:
      Woodway_Detection_Zone:
        coordinates: 564,480,611,279,640,32,522,21,522,0,261,96,0,156,0,480
    review:
      alerts:
        required_zones:
          - Woodway_Detection_Zone
version: 0.14
camera_groups:
  Home:
    order: 1
    icon: LuWarehouse
    cameras:
      - Driveway_CAM
      - Woodway_CAM
```

### Any other relevant information

```yaml
Logger: homeassistant.helpers.template
Quelle: helpers/template.py:2651
Erstmals aufgetreten: 08:28:45 (8 Vorkommnisse)
Zuletzt protokolliert: 08:33:54

Template variable warning: 'update' is undefined when rendering '{{ iif(update, 'none', sound) }}'
Template variable warning: 'update' is undefined when rendering '{{ iif((update or sound == 'none'), 0, volume) }}'
```
