### ISSUE TITLE
[Config Support]: Fire TV (I am missing something)

### ISSUE THREAD

**Issue by jagauthier** [SgtBatten/HA_blueprints#266]
### Describe the problem you are having or the outcome you are trying to achieve.

I configured an automation for my phone - works great.  Now I am trying to do one to a Fire TV device.  I configured it like I think I should.. but it's not working - and I get an error in the trace.

### Version

0.12.0.4a

### Automation config

```yaml
alias: Frigate Notifications (0.12.0.4a)
description: Front Door - TV
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_device: 08888f7f21e4f6eeacc1a4bd391ef175
    notify_group: Jason's TV
    message: "{{camera_name}}: Movement was detected: {{label}}"
    tv: true
    tv_position: bottom-left
    base_url: https://ha.secrets.org
```

### Frigate Config

```yaml
I left this blank, because I am getting notification to my mobile (android)
```

### Any other information that may be helpful

I set my Fire TV to a DHCP assigned address. I installed the Fire TV notification app. I installed the Android companion app (not required, but confirmed notifications work - then removed)

I added the TV using the nfandroidtv - which was just the name "Jason's TV" and the IP address.

Then I triggered it, and nothing. So I looked at the trace and I see this error:

```
Executed: August 23, 2024 at 3:32:17 PM
Error: Template rendered invalid service: notify.jason's_tv
Result:

choice: 2
```

I'm not sure what else I need to do.
