### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by DanielCastroNexo** [SgtBatten/HA_blueprints#268]
### Describe the problem you are having or the outcome you are trying to achieve.

Everything is working exceptionally well; however, I’m having trouble getting the custom action (manual trigger) to work. I might be making a configuration error.

### Version

Frigate Notifications (0.12.0.4e)

### Automation config

```yaml
alias: Varanda
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.cam7
    notify_device: 3fXXXXXXXXXXXXXXXXXXXXXXXX9b
    base_url: https://paXXXXXXXXXXXXXXXXXXXXXXlst.ui.nabu.casa/
    update_sub_label: false
    ios_live_view: camera.cam7
    labels:
      - person
    silence_timer: 60
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    url_1: custom-{{ camera }}
    button_1: Ligar luzes varanda
    url_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    button_2: Ver clipe
    button_3: Silenciar novas notificações
    custom_action_manual:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.sonoff_1000e4946d
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: pci:0

database:
  path: /config/frigate.db

mqtt:
  host: 10.1.1.2
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: XXXXXXXXXX
  password: XXXXXXXXX
  stats_interval: 60

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  width: 704
  height: 480
  fps: 5
  enabled: true

snapshots:
  enabled: true
  timestamp: false
  retain:
    default: 7

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: active_objects
    pre_capture: 5
    post_capture: 5

birdseye:
  enabled: true
  mode: objects

go2rtc:
  streams:
    cam1_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.106:554/cam/realmonitor?channel=1&subtype=0
    cam1_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.106:554/cam/realmonitor?channel=1&subtype=1
    cam2_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.107:554/cam/realmonitor?channel=1&subtype=0
    cam2_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.107:554/cam/realmonitor?channel=1&subtype=1
    cam3_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.120:554/cam/realmonitor?channel=1&subtype=0
    cam3_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.120:554/cam/realmonitor?channel=1&subtype=1
    cam4_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.174:554/cam/realmonitor?channel=1&subtype=0
    cam4_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.174:554/cam/realmonitor?channel=1&subtype=1
    cam5_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.175:554/cam/realmonitor?channel=1&subtype=0
    cam5_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.175:554/cam/realmonitor?channel=1&subtype=1
    cam6_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.176:554/cam/realmonitor?channel=1&subtype=0
    cam6_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.176:554/cam/realmonitor?channel=1&subtype=1
    cam7_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.177:554/cam/realmonitor?channel=1&subtype=0
    cam7_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.177:554/cam/realmonitor?channel=1&subtype=1
    cam8_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.178:554/cam/realmonitor?channel=1&subtype=0
    cam8_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.178:554/cam/realmonitor?channel=1&subtype=1
    cam9_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.179:554/cam/realmonitor?channel=1&subtype=0
    cam9_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.179:554/cam/realmonitor?channel=1&subtype=1
    cam10_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.180:554/cam/realmonitor?channel=1&subtype=0
    cam10_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.180:554/cam/realmonitor?channel=1&subtype=1
    cam11_principal:
      - rtsp://admin:123654Rubaiyat@10.1.1.181:554/cam/realmonitor?channel=1&subtype=0
    cam11_sub:
      - rtsp://admin:123654Rubaiyat@10.1.1.181:554/cam/realmonitor?channel=1&subtype=1

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam1_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam1_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.65,0.04,0.65,0.092,0.966,0.088,0.966,0.037
        - 0.403,0,0.398,0.331,1,0.589,1,0
        - 0.068,0.322,0.402,0.255,0.404,0,0.001,0.003,-0.001,0.995,0.117,0.993,0.075,0.841,0.071,0.406
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
          mask: 0.822,0.311,0.949,0.35,0.894,0.76,0.769,0.709
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam2_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.651,0.1,0.646,0.034,0.969,0.029,0.969,0.098
        - 0.216,0.998,0.157,0.539,0.148,0.442,0.147,0.396,0.149,0.342,0.544,0.259,0.703,0.272,0.999,0.382,0.998,0.005,0.001,0.003,0.002,0.993
        - 0.659,0.259,0.658,0.397,0.747,0.439,0.749,0.277
        - 0.935,0.334,0.925,0.461,0.98,0.492,0.991,0.351
        - 0.507,0.332,0.543,0.341,0.547,0.259,0.487,0.267,0.488,0.337
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam3_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam3_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.728,0.103,0.728,0.032,0.979,0.039,0.982,0.103
        - 0.085,0.199,0.511,0.085,0.636,0.172,0.681,0.152,0.681,0.244,0.726,0.267,0.757,0.307,0.761,0.002,0,0,0,1,0.154,0.997,0.034,0.731,0.024,0.621,0.016,0.269,0.015,0.215
        - 0.082,0.205,0.239,0.452,0.642,0.174,0.516,0.082
        - 0.829,0.341,0.856,0.396,0.902,0.409,0.914,0.351,0.885,0.339,0.881,0.285,0.841,0.284
        - 0.76,0.204,0.823,0.242,0.867,0.245,1,0.275,0.998,0,0.759,0
        - 0.882,0.245,0.896,0.311,0.943,0.334,0.962,0.267
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        car:
          min_score: 0.55
          threshold: 0.7
          mask: 
            0.19,0.866,0.319,0.997,0.997,0.995,0.997,0.314,0.761,0.239,0.75,0.311,0.763,0.452,0.604,0.304
        motorcycle:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam4:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam4_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam4_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.721,0.1,0.718,0.021,0.978,0.021,0.979,0.103
        - 0,0,0,0.563,0.346,0.247,0.336,0
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
  cam5:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam5_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam5_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.728,0.1,0.727,0.032,0.975,0.031,0.976,0.098
        - 0.53,0.002,0.532,0.285,0.644,0.269,0.644,-0.002
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
  cam6:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam6_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam6_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask: 0.73,0.096,0.726,0.022,0.977,0.031,0.979,0.101
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
  cam7:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam7_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam7_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.732,0.113,0.726,0.041,0.977,0.037,0.978,0.108
        - -0.001,0.442,0.272,0.274,0.314,0,0,0
        - 1,0.735,0.709,0.364,0.691,0.369,0.668,0.336,0.647,0.322,0.65,0.259,0.629,0.259,0.615,0.28,0.609,0.339,0.603,0.384,0.584,0.444,0.567,0.501,0.547,0.499,0.573,0.382,0.589,0.245,0.503,0.242,0.481,0.432,0.407,0.399,0.436,0.232,0.344,0.209,0.276,0.27,0.316,0.002,1,0
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        car:
          min_score: 0.55
          threshold: 0.7
          mask: 
            0.243,0.694,0.364,0.99,0.841,0.985,0.65,0.319,0.651,0.257,0.627,0.257,0.617,0.277,0.606,0.366,0.567,0.496,0.546,0.506,0.317,0.424
        motorcycle:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam8:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam8_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam8_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.71,0.083,0.71,0.044,0.969,0.044,0.969,0.083
        - 0.526,0.998,0.209,0.668,0.164,0.519,0.155,0.459,0.265,0.344,0.243,0.265,0.204,0.249,0.217,0.129,0.248,0.085,0.316,0.068,0.402,0.045,0.406,0,0,0,0,1
        - 0.284,0.265,0.63,0.686,0.68,0.573,0.741,0.648,0.785,0.519,0.83,0.409,0.912,0.169,0.973,0,0.84,0,0.405,0,0.404,0.038,0.473,0.048,0.503,0.075,0.545,0.052,0.785,0.272,0.804,0.29,0.778,0.386,0.503,0.145,0.443,0.132
        - 0.59,1,0.639,0.831,0.692,0.74,0.755,0.741,0.785,0.634,0.85,0.696,0.9,0.748,0.902,0.853,0.999,0.927,0.998,0.997
        - 0.849,0.362,0.947,0.477,0.925,0.506,0.94,0.551,0.944,0.598,0.974,0.654,0.998,0.681,1,0,0.966,0
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
          mask: 0.367,0.494,0.421,0.585,0.436,0.512,0.416,0.498,0.388,0.448
        car:
          min_score: 0.55
          threshold: 0.7
        motorcycle:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam9:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam9_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam9_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: 'true'
      mask:
        - 0.732,0.103,0.727,0.037,0.982,0.042,0.98,0.108
        - 0.001,0.658,0.08,0.641,0.131,0.646,0.171,0.848,0.215,0.843,0.23,0.78,0.394,0.696,0.477,0.699,0.521,0.504,0.512,0.386,0.509,0.002,0,0
        - 1,0.876,0.678,0.513,0.615,0.534,0.585,0.472,0.554,0.464,0.547,0.414,0.51,0.411,0.507,0.003,1,0
        - 0.002,0.82,0.048,0.805,0.075,0.896,0.014,0.927
        - 0.243,0.846,0.247,0.937,0.274,0.953,0.308,0.943,0.313,0.891,0.288,0.843
      threshold: 30
      contour_area: 10
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        car:
          min_score: 0.55
          threshold: 0.7
          mask: 
            0.583,1,0.536,0.661,0.523,0.508,0.517,0.414,0.554,0.421,0.566,0.452,0.578,0.475,0.598,0.497,0.866,1
        motorcycle:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam10:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam10_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam10_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.72,0.088,0.721,0.039,0.979,0.041,0.978,0.093
        - 0.364,0.374,0.04,0.983,0,0.997,0.001,0.005,0.38,0
        - 0.465,0.402,0.462,0,0.999,0.003,1,0.803,0.78,0.918,0.659,0.756,0.561,0.753,0.472,0.749
        - 0.368,0.26,0.463,0.242,0.46,0,0.383,0
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        car:
          min_score: 0.55
          threshold: 0.7
          mask: 0.071,0.993,0.374,0.341,0.382,0.285,0.462,0.285,0.488,0.763,0.465,0.993
        motorcycle:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
  cam11:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam11_principal
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam11_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      improve_contrast: true
      mask:
        - 0.729,0.096,0.726,0.041,0.976,0.042,0.977,0.1
        - 0,0.342,0.057,0.179,0.05,0.14,0.052,0.087,0.08,0.085,0.084,0.13,0.113,0.152,0.152,0.132,0.191,0.129,0.193,0.078,0.271,0.098,0.265,0.359,0.283,0.386,0.312,0.371,0.299,0.239,0.314,0.169,0.329,0.154,0.346,0.152,0.337,0.349,0.356,0.352,0.358,0.255,0.379,0.165,0.399,0.109,0.451,0.127,0.4,0.434,0.449,0.462,0.458,0.354,0.485,0.13,0.522,0.162,0.577,0.185,0.579,0.142,0.608,0.135,0.639,0.154,0.648,0.182,0.685,0.249,0.704,0.311,0.662,0.337,0.661,0.437,0.72,0.596,0.801,0.593,0.935,0.646,0.909,0.733,0.862,0.753,0.861,0.831,0.862,0.9,0.907,0.888,0.941,0.815,0.999,0.531,1,0,0.001,0.002
    objects:
      track:
        - person
        - car
        - motorcycle
        - cat
        - dog
      filters:
        person:
          min_score: 0.55
          threshold: 0.7
        car:
          min_score: 0.55
          threshold: 0.7
          mask: 
            0.002,0.346,0.058,0.182,0.052,0.132,0.052,0.085,0.078,0.087,0.082,0.119,0.116,0.154,0.13,0.202,0.127,0.993,0,1
        motorcycle:
          min_score: 0.55
          threshold: 0.7
        cat:
          min_score: 0.55
          threshold: 0.7
        dog:
          min_score: 0.55
          threshold: 0.7
version: 0.14
camera_groups:
  birdeye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

### Any other information that may be helpful

I can silence new notifications and view the clip through both buttons. What I can’t do is activate the custom action (turn on the balcony lights).
