### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by paulr1970** [SgtBatten/HA_blueprints#27]
### Describe the problem you are having or the outcome you are trying to achieve.

No Notifications sent to iphone/ipad

### Version

0.12.0.1

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: frontcam
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.frontcam
    tv_size: large
    tv_position: center
    notify_device: fd1b71c6bd19e7a3c0609a9dd32f1a81
    color: grey
    debug: true
```

### Frigate Config

```yaml
mqtt:
  enabled: False
  host: homeassistant.local
  user: m##qtt
  password: #####
  
detectors:
  coral:
    type: edgetpu
    device: usb
    
cameras:
 # rear:
 #   ffmpeg:
 #     inputs:
 #       - path: rtsp://#####:######@192.168.0.79:554/cam/realmonitor?channel=1&subtype=3
 #         roles:
 #           - detect
 #   rtmp:
 #     enabled: False
  frontcam:
    ffmpeg:
      inputs:
        - path: rtsp://#####:####!@192.168.0.78:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - clips
      output_args:
          detect: -f rawvideo -pix_fmt yuv420p
          record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp:
      enabled: False
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution    
      fps: 5
      stationary:
          interval: 0
          threshold: 50
    objects:
      track:
        - person
        - cat
        
    motion:
      mask:
        - 755,154,399,153,175,169,0,282,0,0,1158,0,1164,209

    zones:
      zone_0:
       coordinates: 0,371,190,180,474,149,1280,153,1280,720,0,720
    
  Birdcam:
    ffmpeg:
      inputs:
        - path: rtsp://#####:######@192.168.0.85/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - clips
      output_args:
          detect: -f rawvideo -pix_fmt yuv420p
          record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp:
      enabled: False
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    objects:
      track:
        - bird
    motion:
      mask:
        - 302,720,0,720,0,479,0,302,0,0,188,0
        - 1280,720,1280,0,954,0,1032,276,990,514,1008,646,1010,720
 
        
 
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - bird
    
        # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 5
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 5
        bird: 2
        motorcycle: 1
        

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 5
```

### Any other information that may be helpful

Enable the unauthenticated notification event proxy enabled.
Other notifications work from HA just cant get frigate to work.
