### ISSUE TITLE
[Issue]: iOS Notifications result in 404

### ISSUE THREAD

**Issue by tibmeister** [SgtBatten/HA_blueprints#275]
### Description

After the recent Home Assistant 2024.9.0 update, the notifications seems broke, resulting in 404 errors in the iOS notifications.  Using the trace, the URL there opens in the browser with the message of "Event not found"

### Version

0.12.0.4d

### Automation Config

```yaml
alias: Jody Frigate Yard NW
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.keo_yardnw
    notify_device: 870885142f7fcbbaa0d659fc5533e504
    alert_once: true
    attachment: snapshot
    update_thumbnail: true
    ios_live_view: true
    silence_timer: 10
    cooldown: 120
    url_2: "{{base_url}}/lovelace"
    button_1: View Snapshot
    url_1: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_2: Open Home Assistant
    loiter_timer: 5
    debug: true
```
