### ISSUE TITLE
[Issue]: Cannot zoom in snapshot

### ISSUE THREAD

**Issue by phlundblom** [SgtBatten/HA_blueprints#278]
### Description

I have been using 0.12.0.2 blueprint for quite a while, working just fine (thanks for that!)

Just tried out the 0.12.0.4e beta to evaluate the new new review notifications from Frigate. There's things to say about that but what I noticed is that I cannot zoom in the video that is opened when I tap on the notification. This works fine in 0.12.0.2.

Notifications goes to Android 14 and everything else looks the same when playing back the clip, except it is not possible to zoom in the video.

### Version

0.12.0.4e

### Automation Config

```yaml
alias: Kameraevent baksidan NG
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.redacted
    notify_device: cc132820f45e79d724643a2110884cd9
    message: >-
      NG {{ 'Bil' if label == 'Car' else 'Cykel' if label == 'Bicycle' else
      'Motorcykel' if label == 'Motorcycle' else 'Katt' if label == 'Cat' else
      label}} detekterad på {{camera_name | lower}}
```

**Comment by SgtBatten** [comment]
Can you go back to the previous version you say worked and try it with frigate 0.14. 

0.12.0.4e is not using anything frigate 0.14 specific. The 0.14 review version is not published yet and is only in #216

**Comment by phlundblom** [comment]
Yes, I actually have both blueprints installed. Didn't want to risk moving to beta. So, in 0.12.02 with 0.14 Frigate zooming works fine.

**Comment by SgtBatten** [comment]
I cant even find a 12.0.2 in the commit history. it went from 1 to 3 in the commit i found. what on earth did i do lol

**Comment by SgtBatten** [comment]
Can you upload the 0.12.0.2 to pastebin and paste the link here please.

**Comment by SgtBatten** [comment]
Actually never mind, i went back to 0.12.0.1 and the urls we are using are the same. it doesnt make sense that the bahviour is different from a code perspective.

**Comment by phlundblom** [comment]
Hmm, strange. Can I provide any other information on the issue? Seems strange, the playback UI looks the same and so on. Guess it is some kind of web component? Are there any parameters on the URLs?

**Comment by phlundblom** [comment]
What is the best way to access the URL? On my Pixel 8 it opens up in it's own window, full screen with black around the video.

**Comment by SgtBatten** [comment]
How are you opening it. Is it the tap action (anywhere on the notification) or using one of the 3 action buttons at the bottom?

Also please share your Configs for both.

**Comment by phlundblom** [comment]
Just the tap action on the notification.

Is it full config for both notification and Frigate you are referring to?

**Comment by SgtBatten** [comment]
just both automations. access the config by editing the automation in yaml mode within HA.

**Comment by phlundblom** [comment]
Configuration for 0.12.0.2:

```
alias: Notification to XXX upon cam events
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.redacted
    notify_device: cc132820f45e79d724643a2110884cd9
    base_url: https://<base_url_to_ha>
    update_thumbnail: true
    labels:
      - person
      - car
      - bicycle
      - motorcycle
      - cat
    message: >-
      {{ 'Bil' if label == 'Car' else 'Cykel' if label == 'Bicycle' else
      'Motorcykel' if label == 'Motorcycle' else 'Katt' if label == 'Cat' else
      label}} detekterad på {{camera_name | lower}}
    color: grey
    cooldown: 60
    alert_once: true
```

Configuration for 0.12.0.4e:

```
alias: Kameraevent XXX NG
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.redacted
    notify_device: cc132820f45e79d724643a2110884cd9
    message: >-
      NG {{ 'Bil' if label == 'Car' else 'Cykel' if label == 'Bicycle' else
      'Motorcykel' if label == 'Motorcycle' else 'Katt' if label == 'Cat' else
      label}} detekterad på {{camera_name | lower}}
```
