### ISSUE TITLE
[Config Support]: issue with a notification

### ISSUE THREAD

**Issue by Coltonc188** [SgtBatten/HA_blueprints#279]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello, 
I have notifcations for alerts setup on all of my cameras around my house, and for some reason I'm having issues on my doorbell, its worked at some point, but after the last update to this version, I cant get the doorbell to send me a notification anymore.

In the automation, it says it worked and says something was sent, but nothing shows up on on my phone.  I went as far as deleting the automation, copying one of my other ones, and just changing the camera to my doorbell to see if that would fix it, and am still having the issue.

In the frigate UI I can see the event taking place there, but for some reason the notification is just not sending.

So i'm not sure what is going on....

### Version

0.12.0.2

### Automation config

```yaml
alias: Camera Doorbell Notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.doorbell
    notify_device: 578b2569b5a3055a395d36e2b3ac8603
    notify_group: all_devices
    base_url: https://REDACTED.com
    critical: "true"
    zones:
      - Path to Door
      - Front Yard
      - Front Porch
    labels:
      - person
      - dog
      - cat
      - car
    zone_filter: true
    update_thumbnail: true
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera{{ ' in the ' + entered_zones if entered_zones
      else '.'}}
    cooldown: 60
    silence_timer: 120
    alert_once: true
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.10
  port: 1883
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb
    num_threads: 3


record:
  enabled: true
  expire_interval: 60

  retain:
    days: 0
    mode: all

  events:
    pre_capture: 0
    post_capture: 0


    retain:
      default: 10


snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  required_zones:
    - Driveway towards Street
    - Driveway towards garage
    - Path to Door
    - Front Yard
    - Path to Front Door
    - Front Yards
    - Trampoline
    - Front Porch
cameras:
  Driveway:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/tdFaCjVhXwRGP4E2?enableSrtp # <----- Update for your camera
          roles:
            - detect
    zones:
      Driveway towards garage:
        coordinates: 1142,593,139,720,96,308,635,260
      Front Yard:
        coordinates: 787,255,1135,244,670,75,243,87
      Path_to_Door:
        coordinates: 0.189,0.13,0.608,0.351,0.519,0.354,0.159,0.146
        inertia: 3
        loitering_time: 0
      Driveway_towards_Street:
        coordinates: 0.898,0.808,1,0.665,1,0.453,0.892,0.347,0.505,0.36
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - dog
        - cat
    detect:
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        required_zones:
          - Driveway towards garage
          - Front Yard
          - Path_to_Door
          - Driveway_towards_Street
  Front:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/jIo8xiZtfnl4nfss?enableSrtp # <----- Update for your camera
          roles:
            - detect
    motion:
      mask: 0,0,0,0.319,0.272,0.127,0.463,0.202,0.488,0.164,0.503,0.102,0.55,0
    zones:
      Front_Porch:
        coordinates: 0.872,0.235,0.859,0.279,0.835,0.333,0.87,0.352,0.938,0.407,0.956,0.284
        inertia: 3
        loitering_time: 0
      Path_to_Door:
        coordinates: 0.858,0.281,0.838,0.317,0.736,0.274,0.731,0.062,0.767,0.078,0.811,0.249
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - dog
        - cat

    detect:
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        required_zones:
          - Front_Porch
          - Path_to_Door

  Kitchen:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/GqAWupQ6ggQf8CWG?enableSrtp # <----- Update for your camera
          roles:
            - detect

    objects:
      track:
        - person
        - car
        - dog
        - cat

    detect:
      width: 640
      height: 360
      fps: 5

  Playroom:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/TTeUGlHugXKLaTsQ?enableSrtp # <----- Update for your camera
          roles:
            - detect

    objects:
      track:
        - person
        - dog

    detect:
      width: 640
      height: 360
      fps: 5

  Back_Yard:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/1l3jJVzilUpbyMa8?enableSrtp # <----- Update for your camera
          roles:
            - detect
    motion:
      mask:
        - 1920,754,1832,575,1744,391,1625,194,1561,118,1580,0,1920,0
    zones:
      Side Fence:
        coordinates: 
          1348,1080,1920,1080,1920,820,1795,516,1736,408,1669,289,1613,214,1586,171,1356,133
      Trampoline:
        coordinates: 0.006,0.749,0.697,0.969,0.702,0.147,0.267,0.067,0.003,0.196
        loitering_time: 0
    objects:
      track:
        - person
        - dog
        - cat

    detect:
      width: 1920
      height: 1080
      fps: 5

    review:
      alerts:
        required_zones:
          - Side Fence
          - Trampoline

  Back_Patio:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/NgCgbCDh4UA1jvrx?enableSrtp # <----- Update for your camera
          roles:
            - detect

    objects:
      track:
        - person
        - dog
        - cat

    detect:
      width: 1280
      height: 720
      fps: 5

    zones:
      Doggy_Door:
        coordinates: 0.783,0.17,0.992,0.193,0.988,0.411,0.776,0.384
        loitering_time: 0
      Patio:
        coordinates: 0.075,0.716,0.437,0.995,0.992,0.994,0.993,0.469,0.492,0.241
        loitering_time: 0
      Rocks/Tree:
        coordinates: 0.001,0.113,0.003,0.702,0.649,0.035,0.193,0.006
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - Doggy_Door
          - Patio
          - Rocks/Tree

  Back_Gate:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/9FEKmao9DyZrXvnM?enableSrtp # <----- Update for your camera
          roles:
            - detect
    objects:
      track:
        - person
        - dog
        - cat

    detect:
      width: 1280
      height: 720
      fps: 5

    review:
      alerts:
        required_zones:
          - Gate

    motion:
      mask: 0,0,0,0.348,0.167,0
    zones:
      Gate:
        coordinates: 0.15,0.043,0.678,0.009,1,0.249,0.991,0.964,0,1,0,0.364
        loitering_time: 0


        inertia: 3
  Doorbell:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsps://192.168.1.41:7441/JLxtJDZYrsUZPl6g?enableSrtp   # <----- Update for your camera
          roles:
            - detect
    motion:
      mask: 0,0.276,1,0.343,1,0,0,0
    zones:
      Front_Porch:
        coordinates: 0.613,0.884,0.624,1,0,1,0,0.86,0.242,0.734
        inertia: 3
        loitering_time: 0
      Path_to_Front_Door:
        coordinates: 
          0.502,0.836,0.523,0.778,0.686,0.774,0.876,0.743,1,0.689,0.951,0.668,0.725,0.701,0.419,0.693,0.342,0.769
        inertia: 3
        loitering_time: 0
      Front_Yard:
        coordinates: 0.212,0.659,0.688,0.695,0.938,0.656,0.747,0.598,0.354,0.538,0.234,0.592
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
        - car
        - dog
        - cat
      filters:
        person:
          min_score: 0.8
        car:
          min_score: 0.8
          mask: 
            1,0.458,0.19,0.426,0.007,0.408,0,0.506,0.055,0.522,0.319,0.537,0.396,0.547,0.496,0.56,0.589,0.571,0.701,0.582,0.786,0.592,0.896,0.605,1,0.602
    detect:
      width: 1600
      height: 1200
      fps: 5

    review:
      alerts:
        required_zones:
          - Front_Porch
          - Path_to_Front_Door
          - Front_Yard

version: 0.14
```
