### ISSUE TITLE
[Config Support]: Blueprint does not send a notification to Android mobile

### ISSUE THREAD

**Issue by rafian** [SgtBatten/HA_blueprints#28]
### Describe the problem you are having or the outcome you are trying to achieve.

I have installed Frigate in a Openmediavault Server in docker, it's configured and running. 
Mosquitto broker addon in home assistant installed and configured. 
Frigate integration in HA installed and working. I can view the cameras, toggle detections, snapshots, recordings, etc
MQTT integration in HA installed and configured with the same user and password. Broker: localhost
Enable the unauthenticated notification event proxy --> Enabled.
Frigate notification blueprint installed and automation created with one camera. 

Problem: I'm not recieving notifications to Android mobile (Didn't check in IOS). In fact, the automation was never activated. When I pass in front of the camera, it detects me, make a snapshot and a recording in frigate.

PS: I had installed the Frigate addon in the passt. Now it's uninstalled. Maybe it has something to do, idk.

### Version

0.12.0.1

### Automation config file

```yaml
alias: Notificacion Intruso detectado Pasillo
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.pasillo_2
    notify_device: 3353cbff554355eefe31298f6bd48eb0
    message: Persona detectada
    attachment: thumbnail
    color: red
    ios_live_view: false
    labels: []
    url_3: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    button_3: View Stream
    title: Intruso detectado en el pasillo
    critical: "false"
    update_thumbnail: false
    loiter_timer: 0
    debug: true
    base_url: http://fakeforgithub.dyndns.org:8123
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.24
  port: 1883
  user: Rafa2
  password: fakeforgithub

cameras:
  comedor:
    ffmpeg:
      inputs:
        - path: rtsp://rafa:fakeforgithub@192.168.1.32:88/videoMain
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1920
      height: 1080
    snapshots:
      enabled: True
    record:
      enabled: True

  balcon:
    ffmpeg:
      inputs:
        - path: rtsp://foscam:fakeforgithub@192.168.1.16:88/videoMain
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1920
      height: 1080
    snapshots:
      enabled: True
    record:
      enabled: True

  pasillo:
    ffmpeg:
      inputs:
        - path: rtsp://foscam:fakeforgithub@192.168.1.17:88/videoMain
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1920
      height: 1080
    snapshots:
      enabled: True
    record:
      enabled: True


go2rtc:
  streams:
    comedor:
      - rtsp://rafa:fakeforgithub@192.168.1.32:88/videoMain
    balcon:
      - rtsp://foscam:fakeforgithub@192.168.1.16:88/videoMain
    pasillo:
      - rtsp://foscam:fakeforgithub@192.168.1.17:88/videoMain

  webrtc:
    candidates:
      - 192.168.1.234:8555


detectors:
  coral:
    type: edgetpu
    device: usb
```

### Any other information that may be helpful

I had installed the Frigate addon in the passt. Now it's uninstalled. Maybe it has something to do, idk.
I read in some forums that someone has the Frigate addon disabled and not uninstalled and he was having problem.
In my case the addon is already uninstall
