### ISSUE TITLE
[Config Support]: Android not being sent the notification.

### ISSUE THREAD

**Issue by Handrail9** [SgtBatten/HA_blueprints#281]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello, I am trying to set up notifications, but I can't seem to get the blueprint working. I did not customize the blueprint past giving it the camera and device to send the notification to. I'm not sure what I need to provide so please be very in depth with where to get more information if you need more information. I appreciate the help in advance

### Version

Frigate Notifications 0.12.0.4d

### Automation config

```yaml
alias: Camera
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.my_camera
    notify_device: c4689b943f537a61aa15f548b0fee1f2
    base_url: https://homeassistant.domain.changed
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.1.80
  user: redacted
  password: redacted

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  my_camera: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.81:8080/video/h264
          roles:
            - detect
    detect:
      enabled: true
    zones:
      Zone:
        coordinates: 0.435,0.964,0.445,0.515,0.162,0.515,0.159,0.97
        loitering_time: 20
        objects: person
    motion:
      mask: 0.435,0.966,0.444,0.521,0.164,0.515,0.157,0.967
    record: # <----- Enable recording
      enabled: True
version: 0.14
```

### Any other information that may be helpful

Frigate, MQTT and Home Assistant are all run in Docker.
I tried referencing[ this guide ](https://simplepush.io/blog/frigate-nvr-push-notification-guide)when I could not get it to work reading the official Frigate documentation but it did not fix the issue.

**Comment by SgtBatten** [comment]
Any traces? screenshot the trace tree if there is. If not, mqtt probably isnt configured in a way that home assistant is getting the messages from frigate

**Comment by SgtBatten** [comment]
wait also you dont have the record roll defined

**Comment by Handrail9** [comment]
> wait also you dont have the record roll defined for your camera in frigate

Thanks for catching that, I've added `- record` under `- detect` and restarted Frigate &  HA. 

> Any traces? screenshot the trace tree if there is. If not, mqtt probably isnt configured in a way that home assistant is getting the messages from frigate

I had tried manually running the automation in HA to test the notification and didn't receive anything. This trace is what shows up when I hit run, when I make a new one and walk in front of the camera myself it's blank after.

Here's the trace: 
![Screenshot_20240914_010419](https://github.com/user-attachments/assets/47549df4-11ed-4e2c-bfb0-c18b79dd6c02)

What can I post to verify if MQTT is configured correctly? I'm a little dull and am not sure which parts will be important to debugging.

**Comment by SgtBatten** [comment]
you cant manually trigger it by pressing run, nothing will happen. You need to walk in front of the camera as you mentioned. 

To check on mqtt you need to install something like mqtt explorer in home asisstant and then look for the frigate/events channel. if frigate events arent showing up in the mqtt explorer then HA isnt recieving the messages.

**Comment by Handrail9** [comment]
> To check on mqtt you need to install something like mqtt explorer in home asisstant and then look for the frigate/events channel. if frigate events arent showing up in the mqtt explorer then HA isnt recieving the messages.

Okay, I've got MQTT explorer installed on my main PC and I went ahead and reset the MQTT password just to make sure that wasn't the issue. I'm out of the house for the next couple days but other people will be there so I'll check back in when I have an update. (Either when I can test it when I get back or if theres a ping sent to my phone while im gone)

**Comment by JBakers** [comment]
I got the same problem, the automation triggers when I walk in front of one of the cameras configured.
I just dont get an notification.
Here the most recent trace:
```
{
  "trace": {
    "last_step": "action/0/then/0/choose/2/sequence/6/repeat/sequence/2/choose/0/sequence/1",
    "run_id": "c1a7f7c7b21fd0480980fe4082ad2aef",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2024-09-19T19:07:41.244574+00:00",
      "finish": "2024-09-19T19:08:02.876794+00:00"
    },
    "domain": "automation",
    "item_id": "1726772787626",
    "trigger": "mqtt topic frigate/events",
    "trace": {
      "trigger/1": [
        {
          "path": "trigger/1",
          "timestamp": "2024-09-19T19:07:41.245270+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.frigate_nieuw",
              "state": "on",
              "attributes": {
                "id": "1726772787626",
                "last_triggered": "2024-09-19T19:06:33.851578+00:00",
                "mode": "parallel",
                "current": 0,
                "max": 10,
                "friendly_name": "Frigate NIEUW"
              },
              "last_changed": "2024-09-19T19:06:30.878638+00:00",
              "last_reported": "2024-09-19T19:06:33.852646+00:00",
              "last_updated": "2024-09-19T19:06:33.852646+00:00",
              "context": {
                "id": "01J85TVMFTWTR5XX5RH4GKNJY3",
                "parent_id": "01J85TVMFT8JYHA4CD9RCKWD21",
                "user_id": null
              }
            },
            "trigger": {
              "id": "frigate-event",
              "idx": "1",
              "alias": null,
              "platform": "mqtt",
              "topic": "frigate/events",
              "payload": "{\"before\": {\"id\": \"1726772860.815976-iopzxz\", \"camera\": \"Zijkant\", \"frame_time\": 1726772860.815976, \"snapshot\": null, \"label\": \"person\", \"sub_label\": null, \"top_score\": 0.0, \"false_positive\": true, \"start_time\": 1726772860.815976, \"end_time\": null, \"score\": 0.76171875, \"box\": [458, 252, 615, 477], \"area\": 35325, \"ratio\": 0.6977777777777778, \"region\": [64, 0, 640, 576], \"stationary\": false, \"motionless_count\": 0, \"position_changes\": 0, \"current_zones\": [], \"entered_zones\": [], \"has_clip\": false, \"has_snapshot\": false, \"attributes\": {}, \"current_attributes\": []}, \"after\": {\"id\": \"1726772860.815976-iopzxz\", \"camera\": \"Zijkant\", \"frame_time\": 1726772861.014856, \"snapshot\": {\"frame_time\": 1726772861.014856, \"box\": [457, 208, 610, 473], \"area\": 40545, \"region\": [56, 0, 640, 584], \"score\": 0.67578125, \"attributes\": []}, \"label\": \"person\", \"sub_label\": null, \"top_score\": 0.71875, \"false_positive\": false, \"start_time\": 1726772860.815976, \"end_time\": null, \"score\": 0.67578125, \"box\": [457, 208, 610, 473], \"area\": 40545, \"ratio\": 0.5773584905660377, \"region\": [56, 0, 640, 584], \"stationary\": false, \"motionless_count\": 1, \"position_changes\": 0, \"current_zones\": [], \"entered_zones\": [], \"has_clip\": false, \"has_snapshot\": false, \"attributes\": {}, \"current_attributes\": []}, \"type\": \"new\"}",
              "qos": 0,
              "description": "mqtt topic frigate/events",
              "payload_json": {
                "before": {
                  "id": "1726772860.815976-iopzxz",
                  "camera": "Zijkant",
                  "frame_time": 1726772860.815976,
                  "snapshot": null,
                  "label": "person",
                  "sub_label": null,
                  "top_score": 0,
                  "false_positive": true,
                  "start_time": 1726772860.815976,
                  "end_time": null,
                  "score": 0.76171875,
                  "box": [
                    458,
                    252,
                    615,
                    477
                  ],
                  "area": 35325,
                  "ratio": 0.6977777777777778,
                  "region": [
                    64,
                    0,
                    640,
                    576
                  ],
                  "stationary": false,
                  "motionless_count": 0,
                  "position_changes": 0,
                  "current_zones": [],
                  "entered_zones": [],
                  "has_clip": false,
                  "has_snapshot": false,
                  "attributes": {},
                  "current_attributes": []
                },
                "after": {
                  "id": "1726772860.815976-iopzxz",
                  "camera": "Zijkant",
                  "frame_time": 1726772861.014856,
                  "snapshot": {
                    "frame_time": 1726772861.014856,
                    "box": [
                      457,
                      208,
                      610,
                      473
                    ],
                    "area": 40545,
                    "region": [
                      56,
                      0,
                      640,
                      584
                    ],
                    "score": 0.67578125,
                    "attributes": []
                  },
                  "label": "person",
                  "sub_label": null,
                  "top_score": 0.71875,
                  "false_positive": false,
                  "start_time": 1726772860.815976,
                  "end_time": null,
                  "score": 0.67578125,
                  "box": [
                    457,
                    208,
                    610,
                    473
                  ],
                  "area": 40545,
                  "ratio": 0.5773584905660377,
                  "region": [
                    56,
                    0,
                    640,
                    584
                  ],
                  "stationary": false,
                  "motionless_count": 1,
                  "position_changes": 0,
                  "current_zones": [],
                  "entered_zones": [],
                  "has_clip": false,
                  "has_snapshot": false,
                  "attributes": {},
                  "current_attributes": []
                },
                "type": "new"
              }
            },
            "mqtt_topic": "frigate/events",
            "type": "new",
            "input_camera": [
              "camera.oprit",
              "camera.zijkant"
            ],
            "input_camera_name": [
              "Zijkant",
              "Oprit"
            ],
            "camera": "Zijkant",
            "camera_name": "Zijkant",
            "input_base_url": "",
            "base_url": "",
            "update_sub_label": true,
            "input_client_id": "",
            "client_id": "",
            "attachment": "snapshot.jpg?bbox=1&crop=1",
            "alert_once": false,
            "update_thumbnail": true,
            "ios_live_view": "",
            "android_auto": true,
            "notify_group": "",
            "notify_group_target": "",
            "zone_only": true,
            "input_zones": [
              "Zijkant_Zone",
              "Oprit_Zone"
            ],
            "zones": [
              "Zijkant_Zone",
              "Oprit_Zone"
            ],
            "zone_multi": false,
            "zone_order_enforced": false,
            "input_labels": [
              "person",
              "dog",
              "cat",
              "package"
            ],
            "labels": [
              "person",
              "dog",
              "cat",
              "package"
            ],
            "presence_entity": "",
            "disable_times": [],
            "cooldown": 30,
            "loitering": false,
            "loiter_timer": 0,
            "initial_delay": 0,
            "fps": 5,
            "state_only": false,
            "input_entity": "",
            "input_states": [],
            "states_filter": [],
            "color": "
```
And my frigate:

```
mqtt:
  host: 192.168.178.66
  port: 1883
  topic_prefix: frigate
  user: REDACTED
  password: REDACTED
  enabled: true
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 8
    mode: motion
  events:
    pre_capture: 5
    post_capture: 10
    retain:
      default: 300
      mode: active_objects
#      objects:
#        person: 180
#        car: 14

snapshots:
  bounding_box: true
  enabled: true

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bicycle
    - cat
    - dog
#  - bird
#  - mouse

go2rtc:
  streams:
    Schuur:
      - rtsp://user:pass@1.1.1.11:554/Streaming/Channels/101
    Speelkamer:
      - rtsp://user:pass@1.1.1.10:554/Streaming/Channels/101
    Oprit:
      - rtsp://user:pass@1.1.1.13:554/Streaming/Channels/101
    Babyfoon:
      - rtsp://user:pass@1.1.1.14:8554/Streaming/Channels/101
    Zijkant:
      - rtsp://user:pass@1.1.1.12:554/Streaming/Channels/101


cameras:

  Schuur:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.11:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@1.1.1.11:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 480
    objects:
      filters:
        bicycle:
          mask:
            - 0,480,0,0,640,0,640,480
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'

      mask: 0.429,0.051,0.475,0.052,0.475,0.098,0.428,0.103
  Speelkamer:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.10:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@1.1.1.10:554/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 480
    motion:
      mask: 0.958,0.975,0.993,0.977,0.991,0.944,0.959,0.942
      threshold: 60
      contour_area: 20
      improve_contrast: 'true'
    objects:
      filters:
        person:
          min_area: 3000
        bicycle: {}
        car: {}
        cat: {}
        dog: {}
        motorcycle: {}
    zones:
      Speelkamer_Zone:
        coordinates: 0.002,0.007,0.003,0.993,0.994,0.995,0.994,0.005
        loitering_time: 0
    review:
      detections: {}
  Oprit:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.13:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@1.1.1.13:554/Streaming/Channels/102
          roles:
            - detect
    zones:
      Oprit_Zone:
        coordinates: 
          1,1,0,1,0,0.676,0.27,0.646,0.265,0.323,0.448,0.316,0.694,0.324,0.743,0.034,1,0.081
        inertia: 3
        loitering_time: 0
      Straat_Zone_1:
        coordinates: 0.739,0,0.685,0.313,0.515,0.307,0.261,0.31,0.277,0.635,0,0.669,0,0
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        car:
          mask: 0.306,1,0.895,1,1,0.823,1,0.556,0.725,0.294,0.577,0.292,0.253,0.291
    detect:
      width: 640
      height: 480

    motion:
      mask: 1,0.035,0.952,0.035,0.956,0,1,0
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'

    review:
      alerts:
        required_zones:
          - Oprit_Zone
          - Straat_Zone_1
  Babyfoon:
    ui:
      order: 4
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://user:pass@1.1.1.14:8554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@1.1.1.14:8554/Streaming/Channels/102
          roles:
            - detect
    detect:
      width: 640
      height: 360

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'

  Zijkant:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@1.1.1.12:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://user:pass@1.1.1.12:554/Streaming/Channels/102
          roles:
            - detect
    objects:
      filters:
        person:
          min_area: 4000
          mask: 0.182,0.796,0.208,1,0.147,1,0.099,0.626,0.068,0.177,0.136,0.108
    zones:
      Buren_Zone:
        coordinates: 0.384,0.311,0.754,0.998,0.999,0.99,1,0,0.687,0,0.686,0.257
        inertia: 3
        loitering_time: 0
      Zijkant_Zone:
        coordinates: 0.746,1,0.21,1,0.176,0.674,0.149,0.337,0.38,0.31
        inertia: 3
        loitering_time: 0
      Straat_Zone_2:
        coordinates: 0.159,0,0.148,0.354,0.697,0.266,0.681,0.005
        inertia: 3
        loitering_time: 0
        objects: person
    detect:
      width: 640
      height: 480

    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
      mask: 0.428,0.946,0.426,0.993,0.482,0.992,0.48,0.944
    review:
      alerts:
        required_zones: Zijkant_Zone
version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye

```

**Comment by Handrail9** [comment]
> To check on mqtt you need to install something like mqtt explorer in home asisstant and then look for the frigate/events channel. if frigate events arent showing up in the mqtt explorer then HA isnt recieving the messages.

Hello, I'm back. I went ahead and tried the "walk in front of the camera" test today and it doesn't seem to be producing any results. I'm pretty sure however that both Frigate and HA are connected to MQTT correctly. I'm using the MQTT-Explorer
AppImage as I'm using Home Assistant in Docker and the addon for MQTT-Explorer isn't available on the Docker version AFAIK. Publishing a test to MQTT from home assistant shows that HA is able to connect, and Frigate seems to have been publishing as well. Attaching a screenshot of what I'm able to see. What steps can I take from here to troubleshoot, and I appreciate your patience :)
![image](https://github.com/user-attachments/assets/87ccddd3-09f3-47ce-83e2-8d74bf30e026)

**Comment by SgtBatten** [comment]
events topic is all that matters which i cant see in the screenshot there, but otherwise yes it does look to be connected

**Comment by Handrail9** [comment]
Sure thing
```
alias: Camera
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.camera
    notify_device: c4619b843f537a64aa15f578b0fee4f3
    base_url: https://changed-this
    mqtt_topic: frigate/events
```

```
mqtt:
  enabled: true
  host: 192.168.1.80
  user: USERNAME
  password: PASSWORD

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  moto_cricket: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.128:8080/video/h264
          roles:
            - record
            - detect
    detect:
      enabled: true
    zones:
      Zone:
        coordinates: 0.435,0.964,0.445,0.515,0.162,0.515,0.159,0.97
        loitering_time: 20
        objects: person
    motion:
      mask: 0.435,0.966,0.444,0.521,0.164,0.515,0.157,0.967
    record: # <----- Enable recording
      enabled: True
version: 0.14
```

I am noticing that there is no events topic in MQTT explorer. Is there anything I should change to get that to exist?
