### ISSUE TITLE
[Issue]: MultiCamera Beta alerts dont match camera

### ISSUE THREAD

**Issue by JoshuaSeidel** [SgtBatten/HA_blueprints#285]
### Description

a car passes my doorbell, and then gets identified on my driveway camera... the alert says "a car has been detected on the doorbell" the apple watch thumbnail and clip shows from the driveway camera

### Version

0.12.0.4I

### Automation Config

```yaml
alias: "Frigate Notifications "
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.driveway
      - camera.doorbell
    notify_device: 0fce7692dbc619c242f66452044447da
    attachment: snapshot.jpg
    update_thumbnail: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    ios_live_view: camera.driveway
    zone_filter: false
    zones:
      - porch
      - parking
    labels: []
    notify_group: seidels
    base_url: https://ha.mydomain.com
    alert_once: true
    cooldown: 60
```

### Frigate Config

```yaml
let me know if needed (will create a sanitized version
```

### Any other relevant information

```yaml
just a bug for the new feature your working on. very excited about this. will cut down on my automations
```
