### ISSUE TITLE
[Issue]: State filter with input_select entity ends in "TEST : FAIL"

### ISSUE THREAD

**Issue by LHommeQuAVuLOurs** [SgtBatten/HA_blueprints#286]
### Description

Hello @SgtBatten and thank you very much for this wonderful blueprint !

I may have misunderstood the "state filter" feature so I don't know if the following behavior is a bug or the result of a misusage.

I've configured my automation with a state filter based on an input select. It should notify my if the input_select is in state "Absent" or "Nuit" (away or night) but the debug shows "TEST: FAIL" : 

State Filter: state filter toggle on: True, state filter entity: input_select.mode_de_surveillance, required states: ['Absent', 'Nuit'], TEST: FAIL

![image](https://github.com/user-attachments/assets/8ae7aa18-cc29-4d2b-b368-18bb338f1e90)

The same automation with the state filter disabled works just fine.
I've tried with a single value but the test still fails
I've tried in lowercase but the test still fails.

Am I missing something obvious ? 

Have a good day !

### Version

0.12.0.4d

### Automation Config

```yaml
alias: Frigate - xxx notif
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.xxx
    notify_device: xxx
    title: Surveillance
    message: >-
      {{ label }} {{ 'immobile' if loitering else 'détécté' }} par la caméra  {{
      camera_name }} {% if enteredzones %}({{ enteredzones | join(', ') |
      replace('_',' ') }}){% endif %}.
    attachment: snapshot.jpg?bbox=1&crop=1
    update_thumbnail: true
    video: ""
    icon: mdi:cctv
    android_auto: true
    sticky: true
    custom_action_manual:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.xxx
    button_1: Light
    url_1: custom-{{ camera }}
    url_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    button_2: Clip
    url_3: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    button_3: Live
    update_sub_label: false
    alert_once: true
    labels:
      - person
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    channel: Frigate
    state_filter: true
    state_entity: input_select.mode_de_surveillance
    state_filter_states:
      - Absent
      - Nuit
    debug: true
```
