### ISSUE TITLE
Wrapper object is not callable

### ISSUE THREAD

**Issue by blueharford** [SgtBatten/HA_blueprints#288]
### Description

Notifications stopped working

### Version

0.14.0.1a

### Automation Config

```yaml
alias: Frigate Backyard Notifications
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.backyard
    notify_device: 0fce7692dbc619c242f66452044447da
    attachment: snapshot.jpg?bbox=1&crop=1
    update_thumbnail: true
    video: ""
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    zone_filter: true
    zones:
      - back-steps
      - yard
      - patio
    labels: []
    notify_group: seidels
    base_url: https://**.*****.com
    alert_once: true
    cooldown: 45
    debug: true
    disable_times:
      - "23"
      - "22"
    tts: false
    redacted: true
    mqtt_topic: frigate/reviews
    tts_helper: input_text.frigate_notifications_tts
    message: A {{ label }} was detected in the {{ zones(0) | title }}.
    sound: News_Flash.caf
    tap_action: /ccab4aaf_frigate-proxy/dashboard
    button_1: Open Frigate
    url_1: /ccab4aaf_frigate-proxy/dashboard

```

**Comment by blueharford** [comment]
![IMG_3795](https://github.com/user-attachments/assets/bc203a39-27fa-46e5-b7b4-d056a0e86b94)

**Comment by blueharford** [comment]
```yaml
choose:
  - alias: Silence New Object Notifications
    conditions:
      - condition: trigger
        id: silence
    sequence:
      - target:
          entity_id: '{{ this.entity_id }}'
        data:
          stop_actions: false
        action: automation.turn_off
      - delay:
          minutes: 30
      - target:
          entity_id: '{{ this.entity_id }}'
        action: automation.turn_on
  - alias: Custom Action Manual
    conditions:
      - condition: trigger
        id: custom
    sequence: []
  - alias: Frigate Event
    conditions:
      - condition: trigger
        id: frigate-event
    sequence:
      - variables:
          event: '{{ trigger.payload_json }}'
          detections: '{{ event[''after''][''data''][''detections''] }}'
          review_id: '{{event[''after''][''id'']}}'
          id: '{{ detections[0] }}'
          objects: '{{ event[''after''][''data''][''objects''] }}'
          sub_labels: '{{ event[''after''][''data''][''sub_labels''] }}'
          label: >-
            {% set data = namespace(labels=[]) %}  {% for obj in objects %}
              {% if "-verified" in obj %}
              {% else %}
                {% set data.labels = data.labels + [obj] %}
              {% endif %}
            {% endfor %} {% set data.labels = data.labels + sub_labels %}  {{
            data.labels | unique | list | sort | join(", ") | title }}
          initial_home: '{{ presence_entity != '''' and is_state(presence_entity, ''home'') }}'
          after_zones: '{{ event[''after''][''data''][''zones''] }}'
          zone_multi_filter: >-
            {{zone_only and zone_multi and after_zones|length and zones and
            zones |reject('in', after_zones) |list |length == 0 }}
          title: ''
          message: A {{ label }} was detected in the {{ zones(0) | title }}.
          subtitle: ''
          tap_action: /ccab4aaf_frigate-proxy/dashboard
          button_1: Open Frigate
          button_2: View Snapshot
          button_3: Silence New Notifications
          url_1: /ccab4aaf_frigate-proxy/dashboard
          url_2: >-
            {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg
          url_3: silence-{{ camera }}
          icon_1: ''
          icon_2: ''
          icon_3: ''
          critical_input: 'false'
          critical: >-
            {{ true if critical_input == 'true' else true if critical_input ==
            True else false }}
          custom_filter: true
          icon: >-
            mdi:{{'account-outline' if label == 'Person' else 'dog' if label ==
            'Dog' else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
            'home-assistant'}}
          group: '{{camera}}-frigate-notification'
          channel: ''
          video: ''
          custom_action: []
      - alias: 'Debug: write to Log'
        choose:
          - conditions:
              - '{{debug}}'
            sequence:
              - data_template:
                  name: Frigate Notification
                  message: |
                    DEBUG: 
                      Info:
                        fps: {{fps}}, 
                        Frigate Review id: {{review_id}}{{', Frigate client ID: ' + client_id if client_id else ''}}, 
                        Frigate Detections: {{detections}}
                        Objects: {{label}},
                        Sub Labels: {{sub_labels | join(', ')}}
                      Config: 
                        camera(formatted): {{camera}}({{camera_name}}), 
                        Base URL: {{base_url}}, 
                        critical: {{critical}}, 
                        alert once: {{alert_once}}, 
                        Update Thumbnails: {{update_thumbnail}}, 
                        Video: {{video}}, 
                        Target: {{'group (input/formatted): ' + notify_group + '/' + notify_group_target + ', ' if notify_group else 'Mobile Device'}}
                        cooldown: {{cooldown}}s, 
                        initial delay: {{initial_delay}}s, 
                        color: {{color}}, 
                        sound: {{sound}}, 
                        android_auto: {{android_auto}}, 
                        Group: {{group}}, 
                        Channel: {{channel}}, 
                        Sticky: {{sticky}}, 
                        Title: {{title}}, 
                        Message: {{message}},
                        Subtitle: {{subtitle}}, 
                        tap_action: {{tap_action}}, 
                        button 1 Text/URL/Icon: {{iif(button_1, button_1, 'unset')}} ({{url_1}}) {{icon_1}}, 
                        button 2 Text/URL/Icon: {{button_2}} ({{url_2}}) {{icon_2}}, 
                        button 3 Text/URL/Icon: {{button_3}} ({{url_3}}) {{icon_3}}, 
                        icon: {{icon}}
                        tv: {{ tv }}, 
                        tv_position: {{tv_position}}, 
                        tv_size: {{tv_size}}, 
                        tv_duration: {{tv_duration}}, 
                        tv_transparency: {{tv_transparency}}, 
                        tv_interrupt: {{tv_interrupt}}, 
                      Filters: 
                        Zones: 
                          zone filter toggle on: {{zone_only}}, 
                          Multi-Zone toggle on: {{zone_multi}}, 
                          Required zones: {{input_zones}}, 
                          Entered Zones: {{after_zones}}, 
                          Zone Filter TEST: {{'PASS (Multi)' if zone_multi_filter else 'PASS' if ( not zone_only or not zone_multi and zones|select('in', after_zones)|list|length ) else 'FAIL (Multi)' if zone_multi else 'FAIL' }}, 
                        Required objects TEST: 
                          Input: {{input_labels}}, 
                          TEST: {{'PASS' if not labels|length or object in labels else 'FAIL'}}
                        presence entity (not home):
                          Entity: {{presence_entity}}
                          TEST:  {{'PASS' if not initial_home else 'FAIL'}}, 
                        disabled times: {{disable_times}}, 
                        State Filter: 
                          state filter toggle on: {{state_only}}, 
                          state filter entity: {{input_entity}}, 
                          required states: {{input_states}}, 
                          State Filter TEST: {{'PASS' if not state_only or states(input_entity) in states_filter else 'FAIL' }},
                        Custom Filter: {{custom_filter}}
                action: logbook.log
      - alias: Delay for image
        choose:
          - conditions:
              - '{{initial_delay > 0}}'
              - '{{trigger.payload_json[''type''] == ''new'' }}'
            sequence:
              - delay:
                  seconds: '{{initial_delay}}'
      - alias: Custom Action Auto
        choose:
          - conditions:
              - '{{ custom_action |length > 0 }}'
              - >-
                {{ not zone_only or (not zone_multi and zones|select('in',
                after_zones)|list|length > 0) or (zone_multi and
                after_zones|length > 0 and zones |reject('in', after_zones)
                |list |length == 0) }}
              - '{{ not initial_home }}'
              - '{{ not state_only or states(input_entity) in states_filter }}'
            sequence: []
      - alias: Notify on new object
        choose:
          - conditions:
              - >-
                {{ not zone_only or (not zone_multi and zones|select('in',
                after_zones)|list|length > 0) or (zone_multi and
                after_zones|length > 0 and zones |reject('in', after_zones)
                |list |length == 0) }}
              - '{{ not initial_home }}'
              - '{{ not state_only or states(input_entity) in states_filter }}'
              - '{{ custom_filter }}'
            sequence:
              - choose:
                  - conditions: '{{ not notify_group_target }}'
                    sequence:
                      - device_id: 0fce7692dbc619c242f66452044447da
                        domain: mobile_app
                        type: notify
                        title: '{{title}}'
                        message: '{{message}}'
                        data:
                          tag: '{{ id }}'
                          group: '{{ group }}'
                          color: '{{color}}'
                          subject: '{{subtitle}}'
                          image: >-
                            {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}{{'&'
                            if '?' in attachment else '?'}}format=android
                          video: '{{video}}'
                          clickAction: '{{tap_action}}'
                          ttl: 0
                          priority: high
                          notification_icon: '{{icon}}'
                          sticky: '{{sticky}}'
                          channel: '{{''alarm_stream'' if critical else channel}}'
                          car_ui: '{{android_auto}}'
                          subtitle: '{{subtitle}}'
                          url: '{{tap_action}}'
                          attachment:
                            url: >-
                              {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}
                          push:
                            sound:
                              name: '{{sound}}'
                              volume: '{{ iif(sound == ''none'', 0, volume) }}'
                              critical: '{{ iif(critical, 1, 0) }}'
                          entity_id: '{{ios_live_view}}'
                          actions:
                            - action: URI
                              title: '{{button_1}}'
                              uri: '{{url_1}}'
                              icon: '{{icon_1}}'
                            - action: URI
                              title: '{{button_2}}'
                              uri: '{{url_2}}'
                              icon: '{{icon_2}}'
                            - action: '{{ ''URI'' if ''/'' in url_3 else url_3 }}'
                              title: '{{button_3}}'
                              uri: '{{url_3}}'
                              icon: '{{icon_3}}'
                              destructive: true
                  - conditions: '{{ tv }}'
                    sequence:
                      - data:
                          title: '{{title}}'
                          message: '{{message}}'
                          data:
                            tag: '{{ id }}'
                            group: '{{ group }}'
                            color: '{{color}}'
                            subject: '{{subtitle}}'
                            clickAction: '{{tap_action}}'
                            ttl: 0
                            priority: high
                            notification_icon: '{{icon}}'
                            sticky: '{{sticky}}'
                            channel: '{{''alarm_stream'' if critical else channel}}'
                            car_ui: '{{android_auto}}'
                            image:
                              url: >-
                                {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg
                            fontsize: '{{tv_size}}'
                            position: '{{tv_position}}'
                            duration: '{{tv_duration}}'
                            transparency: '{{tv_transparency}}'
                            interrupt: '{{tv_interrupt}}'
                            timeout: 30
                            subtitle: '{{subtitle}}'
                            url: '{{tap_action}}'
                            attachment:
                              url: >-
                                {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}
                            push:
                              sound:
                                name: '{{sound}}'
                                volume: '{{ iif(sound == ''none'', 0, volume) }}'
                                critical: '{{ iif(critical, 1, 0) }}'
                            entity_id: '{{ios_live_view}}'
                            actions:
                              - action: URI
                                title: '{{button_1}}'
                                uri: '{{url_1}}'
                                icon: '{{icon_1}}'
                              - action: URI
                                title: '{{button_2}}'
                                uri: '{{url_2}}'
                                icon: '{{icon_2}}'
                              - action: '{{ ''URI'' if ''/'' in url_3 else url_3 }}'
                                title: '{{button_3}}'
                                uri: '{{url_3}}'
                                icon: '{{icon_3}}'
                                destructive: true
                        action: notify.{{ notify_group_target }}
                default:
                  - data:
                      title: '{{title}}'
                      message: '{{message}}'
                      data:
                        tag: '{{ id }}'
                        group: '{{ group }}'
                        color: '{{color}}'
                        subject: '{{subtitle}}'
                        image: >-
                          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}{{'&'
                          if '?' in attachment else '?'}}format=android
                        video: '{{video}}'
                        clickAction: '{{tap_action}}'
                        ttl: 0
                        priority: high
                        notification_icon: '{{icon}}'
                        sticky: '{{sticky}}'
                        channel: '{{''alarm_stream'' if critical else channel}}'
                        car_ui: '{{android_auto}}'
                        subtitle: '{{subtitle}}'
                        fontsize: '{{tv_size}}'
                        position: '{{tv_position}}'
                        duration: '{{tv_duration}}'
                        transparency: '{{tv_transparency}}'
                        interrupt: '{{tv_interrupt}}'
                        url: '{{tap_action}}'
                        attachment:
                          url: >-
                            {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}
                        push:
                          sound:
                            name: '{{sound}}'
                            volume: '{{ iif(sound == ''none'', 0, volume) }}'
                            critical: '{{ iif(critical, 1, 0) }}'
                        entity_id: '{{ios_live_view}}'
                        actions:
                          - action: URI
                            title: '{{button_1}}'
                            uri: '{{url_1}}'
                            icon: '{{icon_1}}'
                          - action: URI
                            title: '{{button_2}}'
                            uri: '{{url_2}}'
                            icon: '{{icon_2}}'
                          - action: '{{ ''URI'' if ''/'' in url_3 else url_3 }}'
                            title: '{{button_3}}'
                            uri: '{{url_3}}'
                            icon: '{{icon_3}}'
                            destructive: true
                    action: notify.{{ notify_group_target }}
```

**Comment by SgtBatten** [comment]
Your second post is the blueprint, there is zero information in it so I will delete it

Is it to do with the TTS stuff? I need more information

**Comment by blueharford** [comment]
```yaml
alias: Frigate Backyard Notifications
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.backyard
    notify_device: 0fce7692dbc619c242f66452044447da
    attachment: snapshot.jpg?bbox=1&crop=1
    update_thumbnail: true
    video: ""
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    zone_filter: true
    zones:
      - back-steps
      - yard
      - patio
    labels: []
    notify_group: seidels
    base_url: https://ha.joshuaseidel.com
    alert_once: true
    cooldown: 45
    debug: true
    disable_times:
      - "23"
      - "22"
    tts: false
    redacted: true
    mqtt_topic: frigate/reviews
    tts_helper: input_text.frigate_notifications_tts
    message: A {{ label }} was detected in the {{ zones(0) | title }}.
    sound: News_Flash.caf
    tap_action: /ccab4aaf_frigate-proxy/dashboard
    button_1: Open Frigate
    url_1: /ccab4aaf_frigate-proxy/dashboard
```
