### ISSUE TITLE
[Issue]: No Small Thumbnail/Preview for iOS notifications

### ISSUE THREAD

**Issue by mattthewclayton** [SgtBatten/HA_blueprints#290]
### Description

I just switching to using this automation, and while it covers 99% of what I want (and thanks for all the hard work), I noticed I could not get the iOS notifications to have the small thumbnail along with the notification

![IMG_2742](https://github.com/user-attachments/assets/c411f50b-fdc7-4831-91fb-e1405b52177d)

This image shows both the desired and undesired behaviour.

I found by deleting the "video:" fields from all the relevant "data" fields of the blueprint it fixed the issue.

I presume it's something to do with the "video:" field taking priority over the "image": field, even if it's empty. (which could even be a bug in the iOS companion app to be honest).

I am not sure if it's possible to dynamically provide different keys to the data field via templates - but I thought I would report in case you are aware of how to do it.

### Version

0.12.0.4d

### Automation Config

```yaml
alias: CCTV - Front
description: New CCTV automation
trace:
  stored_traces: 50
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front
    notify_device: 082365bf5f4e2f7fc019afead1cdd079
    base_url: https://deleted/
    video: ""
    zone_filter: true
    zones:
      - land
    labels:
      - person
    cooldown: 0
    critical: >-
      {{ 'true' if ( is_state("alarm_control_panel.house","armed") and (
      now().hour < 6 or now().hour >= 22 ) ) and
      is_state("input_boolean.critical_notifications", "on") else 'false' }}
    attachment: snapshot.jpg?crop=1
    button_2: View Live
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    update_thumbnail: false
    alert_once: true
    notify_group: matt
    tv: true
    state_filter: true
    state_entity: input_boolean.camera_notifications_all
    state_filter_states:
      - "On"
```

**Comment by SgtBatten** [comment]
Thanks, I have heard of this before such as in #45 

Could you test a different idea for me. 

Instead of removing video, what happens if you remove all areas where we have 

```
attachment:
   url: blah blah blah
```

**Comment by mattthewclayton** [comment]
@SgtBatten  ah, I did search for similar issues, but missed that one.

Right, I figured it out..

It's an issue with the attachment: url: handling, probably a bug in the ios app. It appears that it's not detecting the filetype of the url and seems to be ignoring the attachment field when it should actually override the image/video settings (according to  https://companion.home-assistant.io/docs/notifications/notification-attachments#configuration )

I fixed it, in my usecase by just adding content-type like so:

```
attachment:
     url: blah blah blah
     content-type: jpeg
```

**Comment by mattthewclayton** [comment]
FYI - i was testing using the Actions tab in the Developer Tools with this snippit, just commenting out different things and trying different values:

This also works for video (a thumbnail gets generated)

```
action: notify.matt
data:
  message: test
  title: test
  data:
    image: "https://<removed>/snapshot.jpg?crop=1&format=android"
    video: "https://<removed>/clip.mp4"
    attachment:
      url: "https://<removed>/clip.mp4"
      content-type: mpeg4
```
