### ISSUE TITLE
[Config Support]: HA Blueprint automation does not trigger the Actions

### ISSUE THREAD

**Issue by kevinm2** [SgtBatten/HA_blueprints#293]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello, 

I am getting a lot of raccoons digging in the grass area to eat warms. So, I am trying to deter them by activating the sprinkler zone for 1 minute (using Shelly 2 PM relay), when Frigate detects “motion”, or objects in the “back2_zone2” zone!

I tried the regular automation without success! 

So, I started using “Blueprint, Frigate Notifications (0.12.0.4d)”.  It worked fine last night.  But today, when I changed the time from 1 minute to 3o seconds, it did not work anymore. Of course, I tried putting it back to 1 minute, with no luck. I re-started, and rebooted the system, with no luck.

FYI: I can turn on and off the “Shelly 2 PM relay” from HA with no issues. As for hardware I am using a Coral TPU attached to an OptiPlex 3050, 8GB RAM, and 250GB NVMe.

Is there a cache in FA that could affect this process?  After revising any automation should the system be restarted, or rebooted?
I would appreciate your feedback.  Thank you

Here are my settings and yaml code in “Blueprint, Frigate Notifications (0.12.0.4d)” for your reference:

Frigate Notifications:
Frigate Camera: Camera7
Mobile Device: My Mobile name
MQTT: frigate/events

Notification Customizations
Notification Message: Motion in Back Grass Area!
Subtitle: Sprinkler in The Back Yard Went On
Critical Notification (Optional): false
Attachment: Thumbnail

Filters:
Zone Filter on/off (Optional): true (selected)
Required Zones (Optional - Enabled Above): back2_zone2
Object Filter (Optional): dog, cat, raccoon, person, package, car, bird
Cooldown (Optional): 30 (did not change, it shows as 30 seconds)
Silence New Object Notifications (Optional): 30 (did not change, it shows as 30 minutes)
Loitering Notifications (Optional): 0 (did not change, it shows as 0 seconds)
Delay initial notification (Optional): 0 (did not change, it shows as 0 seconds)

Action Buttons and URLS:
USED: Custom Action (Auto Trigger):
- Turn on Shelly Plus 2PM - Grass: 
    Device: Shelly Plus 2PM - ####-2
    Action:  Turn on Shelly Plus 2PM - Grass - ####-1
- Delay for 1:00 minute
- Turn off Shelly Plus 2PM - Grass: 
    Device: Shelly Plus 2PM - ####-2
    Action:  Turn off Shelly Plus 2PM - Grass - ####-1

### Version

0.12.0.4d

### Automation config

```yaml
alias: "**Frigate dog detect back2_zone2  WORKS"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.camera7
    labels:
      - dog
      - cat
      - raccoon
      - person
      - package
      - car
      - bird
    custom_action_manual: []
    zone_multi: false
    zones:
      - back2_zone2
    debug: false
    update_sub_label: false
    notify_device: *****
    custom_action_auto:
      - type: turn_off
        device_id: *****
        entity_id: *****
        domain: switch
        enabled: false
      - delay:
          hours: 0
          minutes: 0
          seconds: 30
          milliseconds: 0
        enabled: false
      - type: turn_on
        device_id: *****
        entity_id: *****
        domain: switch
        enabled: false
      - type: turn_on
        device_id: *****
        entity_id: *****
        domain: switch
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - type: turn_off
        device_id: *****
        entity_id: *****
        domain: switch
    zone_filter: true
    message: Motion in Back Grass Area!
    subtitle: Sprinkler in The Back Yard Went On
    custom_action_auto_multi: []
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: debug
  logs:
    frigate.event: debug

mqtt:
  host: HOST_IP
  user: USER_NAME
  password: PASSWORD

cameras:
  #--------------------------------
  # <------ Name the camera 1 BEGIN
  #--------------------------------
  camera1:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=1&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - car
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    zones:
      front1_zone1:
        coordinates: 
          0.005,0.988,0.005,0.229,0.111,0.259,0.152,0.229,0.204,0.234,0.207,0.364,0.367,0.347,0.439,0.34,0.448,0.323,0.496,0.3,0.598,0.299,0.807,0.386,0.926,0.457,0.995,0.469,0.995,0.99
        loitering_time: 0
        objects:
          - car
          - person
        inertia: 3
    motion:
      mask:
        - 0.99,0.011,0.992,0.342,0.932,0.393,0.89,0.392,0.784,0.346,0.661,0.278,0.599,0.217,0.622,0.104,0.621,0.007
        - 0.005,0.009,0.614,0,0.613,0.111,0.591,0.217,0.466,0.244,0.315,0.218,0.315,0.168,0.28,0.145,0.275,0.212,0.141,0.211,0.08,0.226,0.006,0.208
    review:
      alerts:
        required_zones: front1_zone1
      detections:
        required_zones: front1_zone1

  #--------------------------------
  # <------ Name the camera 2 BEGIN
  #--------------------------------
  camera2:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=2&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
            #- clips
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=2&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
        #- car
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          #- car
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    # Optional: Configuration clips
    #clips:
    #  enabled: true
    #  retain:
    #    default: 2

    zones:
      front2_zone1:
        coordinates: 
          0.002,0.993,0.004,0.096,0.114,0.019,0.191,0.004,0.608,0.004,0.834,0.131,0.994,0.229,0.992,0.983
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      mask:
        - 0.645,0.011,0.992,0.016,0.992,0.211
        - 0.677,0.453,0.842,0.415,0.811,0.677,0.46,0.682
    review:
      alerts:
        required_zones: front2_zone1
      detections:
        required_zones: front2_zone1

  #--------------------------------
  # <------ Name the camera 3 BEGIN
  #--------------------------------
  camera3:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=3&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
            #- clips
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=3&subtype=0
          input_args: preset-rtsp-restream
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6
        dog:
          min_area: 5000
          min_score: 0.6 # Orig 0.5
          threshold: 0.85 # Orig 0.6
        cat:
          min_area: 5000
          min_score: 0.6 # Orig 0.5
          threshold: 0.85 # Orig 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - dog
          - cat
          - bird
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    # Optional: Configuration clips
    #clips:
    #  enabled: true
    #  retain:
    #    default: 2

    zones:
      front3_zone1:
        coordinates: 
          0.004,0.988,0.006,0.139,0.141,0.102,0.284,0.091,0.453,0.115,0.661,0.155,0.677,0.093,0.742,0.092,0.742,0.184,0.792,0.227,0.919,0.392,0.911,0.478,0.979,0.234,0.995,0.252,0.995,0.423,0.901,0.68,0.771,0.991
        loitering_time: 4 # Orig 0
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
    motion:
      mask:
        - 0.739,0,0.124,0.011,0.137,0.026,0.325,0.022,0.464,0.026,0.573,0.052,0.64,0.06,0.686,0.056,0.692,0.014,0.741,0.021,0.747,0.158,0.915,0.341,0.955,0.209,0.915,0.166,0.921,0.084,0.921,0
        - 0.782,0.984,0.995,0.991,0.997,0.455
    review:
      alerts:
        required_zones: front3_zone1
      detections:
        required_zones: front3_zone1

  #--------------------------------
  # <------ Name the camera 4 BEGIN
  #--------------------------------
  camera4:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=4&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=4&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    zones:
      side1_zone1:
        coordinates: 
          0.005,0.724,0.005,0.991,0.764,0.99,0.849,0.585,0.893,0.249,0.897,0.193,0.771,0.102,0.585,0.028,0.331,0.049,0.177,0.092,0.056,0.165,0.176,0.379,0.484,0.211,0.516,0.245,0.5,0.593,0.235,0.887,0.128,0.613
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      mask:
        - 0.576,0.015,0.796,0.108,0.797,0.085,0.883,0.134,0.875,0
        - 0.772,0.991,0.995,0.993,0.997,0.004,0.879,0.001,0.887,0.125,0.902,0.188,0.851,0.616
        - 0.509,0.261,0.495,0.588,0.237,0.871,0.108,0.55,0.006,0.65,0.005,0.187,0.05,0.169,0.17,0.395,0.476,0.228
        - 0.004,0.006,0.006,0.153,0.22,0.043,0.414,0
    review:
      alerts:
        required_zones: side1_zone1
      detections:
        required_zones: side1_zone1

  #--------------------------------
  # <------ Name the camera 5 BEGIN
  #--------------------------------
  camera5:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=5&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=5&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    zones:
      side2_zone1:
        coordinates: 
          0.747,1,0.677,0.863,0.56,0.608,0.435,0.333,0.438,0.16,0.313,0.17,0.317,0.124,0.292,0.121,0.303,0.356,0.273,1
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      mask:
        - 0.008,0.009,0.283,0.007,0.994,0.012,0.994,0.12,0.347,0.122,0.288,0.095,0.297,0.353,0.267,0.988,0.005,0.988
        - 0.443,0.17,0.5,0.211,0.61,0.295,0.787,0.448,0.993,0.685,0.992,0.99,0.752,0.991,0.441,0.336
    review:
      alerts:
        required_zones: side2_zone1
      detections:
        required_zones: side2_zone1

  #--------------------------------
  # <------ Name the camera 6 BEGIN
  #--------------------------------
  camera6:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=6&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=6&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - dog
          - cat
          - bird
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    zones:
      back1_zone1:
        coordinates: 
          0.003,0.991,0.005,0.055,0.133,0.004,0.189,0.006,0.185,0.132,0.387,0.122,0.426,0.105,0.471,0.168,0.391,0.163,0.574,0.999
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
      back1_zone2:
        coordinates: 0.994,0.474,0.93,0.378,0.853,0.295,0.764,0.213,0.643,0.202,0.995,0.629
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
      back1_zone3:
        coordinates: 0.995,0.991,0.998,0.822,0.862,0.994
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
      back1_zone4:
        coordinates: 0.395,0.06,0.555,0.082,0.622,0.126,0.723,0.205,0.638,0.191,0.479,0.163
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
    motion:
      mask:
        - 0.527,0.008,0.995,0.009,0.995,0.417,0.765,0.18,0.651,0.098,0.569,0.048,0.283,0.036,0.283,0.007
        - 0.399,0.169,0.63,0.199,0.933,0.571,0.918,0.611,1,0.78,0.992,0.82,0.951,0.872,0.847,0.985,0.59,1,0.481,0.542
    review:
      alerts:
        required_zones:
          - back1_zone1
          - back1_zone2
          - back1_zone3
          - back1_zone4
      detections:
        required_zones:
          - back1_zone1
          - back1_zone2
          - back1_zone3
          - back1_zone4


        
  #--------------------------------
  # <------ Name the camera 7 BEGIN
  #--------------------------------
  camera7:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=7&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=75&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - dog
          - cat
          - bird
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    zones:
      back2_zone1:
        coordinates: 
          0.005,0.993,0.005,0.476,0.048,0.687,0.15,0.686,0.175,0.493,0.235,0.215,0.671,0.192,0.819,0.356,0.994,0.563,0.994,0.994
        loitering_time: 0
        objects: 
          - person
          - dog
          - cat
          - bird
        inertia: 3
      back2_zone2:
        coordinates: 
          0.108,0.115,0.195,0.087,0.305,0.068,0.483,0.069,0.5,0.052,0.556,0.06,0.659,0.178,0.22,0.196,0.249,0.125,0.082,0.171
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
          - bird
        inertia: 3
    motion:
      mask: 
        0.005,0.007,0.993,0,0.995,0.228,0.994,0.54,0.656,0.154,0.567,0.051,0.497,0.042,0.479,0.056,0.245,0.06,0.091,0.105,0.005,0.204
    review:
      alerts:
        required_zones:
          - back2_zone1
          - back2_zone2
      detections:
        required_zones:
          - back2_zone1
          - back2_zone2

  #--------------------------------
  # <------ Name the camera 8 BEGIN
  #--------------------------------
  camera8:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=8&subtype=1
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://admin:PASSWORD@IP:554/cam/realmonitor?channel=85&subtype=0
          roles:
            - record

    detect:
      width: 1270 # <- optional, by default Frigate tries to automatically detect resolution
      height: 720 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 5
      stationary:
        interval: 20
        threshold: 50

    # object track ????
    objects:
      track:
        - person
        - dog
        - cat
        - bird
      filters:
        person:
          min_area: 5000
          min_score: 0.5
          threshold: 0.6

    # Optional: Record configuration
    record:
      enabled: true
      retain:
        days: 3
        mode: active_objects #options: all motion active_objects
      events:
        pre_capture: 20
        post_capture: 20
        retain:
          default: 3
          mode: active_objects #options: All motion active_objects
          # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
          - dog
          - cat
          - bird
        #  Optional: Per object retention days
        #  objects: 4
        #  person: 7

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 3

    zones:
      back3_zone1:
        coordinates: 
          0.001,0.988,0.005,0.539,0.407,0.135,0.416,0.004,0.881,0.007,0.885,0.04,0.907,0.072,0.998,0.172,0.995,0.993
        loitering_time: 0
        objects: 
          - person
          - dog
          - cat
          - bird
        inertia: 3
    motion:
      mask: 0.751,0.037,0.904,0.036,0.905,0.082,0.751,0.082
    review:
      alerts:
        required_zones: back3_zone1
      detections:
        required_zones: back3_zone1
        
version: 0.14
```
