### ISSUE TITLE
[Config Support]: how to remove unused action buttons

### ISSUE THREAD

**Issue by ivanjx** [SgtBatten/HA_blueprints#294]
### Describe the problem you are having or the outcome you are trying to achieve.

i noticed that there are 3 action buttons but i only need 1. how can i remove the rest of them?

### Version

0.12.0.4d

### Automation config

```yaml
alias: Frigate Notifications (0.12.0.4d)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.cam1
    notify_group: notify_all
    base_url: https://x.net
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera.
    critical: "false"
    alert_once: true
    zone_filter: true
    zones:
      - alert
      - alert_before
    zone_multi: true
    notify_device: af3d39be4d596c77f821d381679f88cd
    silence_timer: 0
    cooldown: 0
    title: Home Assistant
    update_sub_label: false
    attachment: snapshot.jpg?crop=1
    update_thumbnail: true
    url_3: custom-{{ camera }}
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_1: Download Clip
    button_3: .
    group: "{{camera}}-frigate-notification"
    url_2: custom-{{ camera }}
    button_2: .
```

**Comment by SgtBatten** [comment]
try setting all the values to `""` in yaml mode. note sure if it will work

**Comment by ivanjx** [comment]
i tried this:
```yml
    button_1: View Snapshot
    url_1: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_2: ""
    button_3: ""
```

it seems to work but it adds an extra empty button below

![photo_6078077640029356828_y](https://github.com/user-attachments/assets/c2b9e0c6-485e-4e1b-a8d7-d06b8fe4e215)

**Comment by ivanjx** [comment]
this is on android:

![WhatsApp Image 2024-10-13 at 16 21 03](https://github.com/user-attachments/assets/f5acba68-bc18-46dc-9e9b-d7000838da39)

**Comment by SgtBatten** [comment]
Not looking good. But I note you didn't set url 2 and url 3 which you'll need to as they have a default value.

**Comment by ivanjx** [comment]
setting the urls to empty makes the null buttons go away on android but on ios the 1 extra button still exists

**Comment by ivanjx** [comment]
```yml
    button_1: View Snapshot
    url_1: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_2: ""
    url_2: ""
    button_3: View Clip
    url_3: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
```


![photo_6084521727355895542_y](https://github.com/user-attachments/assets/ebb88623-245b-4212-a32e-a19255898da9)

**Comment by ivanjx** [comment]
```yml
    button_3: View Snapshot
    url_3: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_2: ""
    url_2: ""
    button_1: ""
    url_1: ""
```

![photo_6084521727355895549_y](https://github.com/user-attachments/assets/69269521-a4d8-495d-9d5e-4363af985946)
