### ISSUE TITLE
[Feature Request]: option for ordered multi-zone filter

### ISSUE THREAD

**Issue by ivanjx** [SgtBatten/HA_blueprints#295]
**Describe what you are trying to accomplish and why in non technical terms**
i want to be able to get notifications if somebody is entering into my yard and going in front of my front door but ignore if somebody is leaving instead.

**Describe the solution you'd like**
i have 2 zones for my goal like below:

![image](https://github.com/user-attachments/assets/ccabffce-afa6-47b6-ad80-3e6b3a439a43)

i added both the purple and green zones into the filter zones and enabled multi-zone option. works fine on detecting people coming in but also detects people coming out.

**Describe alternatives you've considered**
i set the green zone's loitering time to 5 seconds in the frigate config since usually people going out would not be waiting there but detecting by the order of the zones they are coming in is much better and faster.

**Additional context**

**Comment by SgtBatten** [comment]
The beta version has an option to enforce the zone order.

**Comment by ivanjx** [comment]
the beta feature does not seem to work. here is the frigate object lifecycle:

![Screenshot from 2024-10-18 12-53-19](https://github.com/user-attachments/assets/df26da2b-ede5-438d-9cdc-ef06e985fa0c)
![Screenshot from 2024-10-18 12-53-22](https://github.com/user-attachments/assets/ab279773-6384-402c-96a7-8c1632185522)
![Screenshot from 2024-10-18 12-53-25](https://github.com/user-attachments/assets/fb28de9a-e266-4a71-aeea-2a5fb48641a9)
![Screenshot from 2024-10-18 12-53-28](https://github.com/user-attachments/assets/e3f83d28-6cfc-403f-997c-13341d142bca)

```yml
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.cam1
    notify_group: notify_all
    base_url: https://x
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera.
    critical: "false"
    alert_once: false
    zone_filter: true
    zones:
      - alert_before
      - alert
    zone_multi: true
    zone_order_enforced: true
    notify_device: af3d39be4d596c77f821d381679f88cd
    silence_timer: 0
    cooldown: 0
    title: Home Assistant
    update_sub_label: false
    attachment: snapshot.jpg?crop=1
    update_thumbnail: false
    tap_action: /lovelace
    button_1: View Snapshot
    url_1: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_2: ""
    url_2: ""
    button_3: ""
    url_3: ""
    group: Camera Notification
    initial_delay: 1
```
