### ISSUE TITLE
[Feature Request]: Silence Notifications based on 'no motion for X mins'

### ISSUE THREAD

**Issue by mattthewclayton** [SgtBatten/HA_blueprints#296]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set 'silence notifications' to block new notifications until 'no motion for X mins'.

**Describe the solution you'd like**
For example, If I am working in the garden, and i get lots of notifications to my phone - i want to select 'silence notifications' - i would like this to stop notifying until there has been no motion for X mins. This way, if I am working in the garden for an hour or the whole day, I do not get lots of notifications and i don't have to keep selecting 'silence notifications' every Y minutes. 

**Describe alternatives you've considered**
In the past I have used HA's 'wait_for_trigger' using one of the binary_sensors created by frigate integration (in my case binary_sensor.land_person_occupany) - you can wait for this to be off for X mins e.g:

```
          - wait_for_trigger:
              - platform: state
                entity_id:
                  - binary_sensor.land_person_occupancy
                to: "off"
                for:
                  hours: 0
                  minutes: 30
                  seconds: 0
```

**Additional context**
I could also see this similar method being useful in some use cases for the 'cooldown' timer..
