### ISSUE TITLE
[Config Support]: Beta yaml seems to still sending notifications for events that don't exist

### ISSUE THREAD

**Issue by aaronjrodrigues** [SgtBatten/HA_blueprints#298]
### Describe the problem you are having or the outcome you are trying to achieve.

I used to be getting notifications that didn't exist in frigate in the stable firmware, after shifting to the beta firmware it seems to still be the case. With some images bring a 404 screen. Does anyone know what the reason for this?

### Version

0.12.04o

### Automation config

```yaml
alias: Frigate Notifications (0.12.0.4o)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.aaron_backdoor
      - camera.aaron_room
      - camera.clothing_line
      - camera.dish_side
      - camera.entryway
      - camera.garage
      - camera.garden
      - camera.imou_garden
      - camera.kitchen_garden
      - camera.kitchen_side
      - camera.open_area
      - camera.rudolf_backyard
    notify_device: dca55410330127c18d5a4d25ee9e1b93
    notify_group: cameras
    message: "{{ label }} detected - {{ camera_name }}"
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    base_url: https://home.aaronrodrigues.com
    labels:
      - person
```
