### ISSUE TITLE
[Issue]: Notifications not working on Samsung Galaxy S22 Ulta

### ISSUE THREAD

**Issue by jessevallaro** [SgtBatten/HA_blueprints#299]
### Description

Setup the blueprint and the simple notification found here for android: https://docs.frigate.video/guides/ha_notifications/

The simple notification works, but the blueprint one does not, it opens "minimized" is how i would describe it, clicking it moves the carrot icon to point down, but it does not expand.. I enabled detailed notifications in my phones settings thinking that was the culprit, but it was not. 

![image](https://github.com/user-attachments/assets/126e19e3-e81b-409b-a098-5a38d4aac4a1)
![image](https://github.com/user-attachments/assets/482621ef-f2d1-414c-ad5a-4bb2bd002326)
![image](https://github.com/user-attachments/assets/5ba7a678-dec4-4b72-8131-3fb5ac608c43)

### Version

0.12.0.4e

### Automation Config

```yaml
alias: Frigate Notification for Jesse
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frontdoor
    notify_device: 2bc6ec0a344a2c3a81a89f3566d68327
    base_url: https://{redacted}
    video: ""
    sticky: true
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt
  password: {redacted, but working}
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
  hwaccel_args: preset-rpi-64-h265
go2rtc:
  streams:
    frontdoor:
      - ffmpeg:http://10.1.0.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={redacted}#video=copy#audio=copy#audio=opus#hardware
      - rtsp://admin:{redacted}@10.1.0.3/Preview_01_sub
    frontdoor_sub:
      - ffmpeg:http://10.1.0.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={redacted}
audio:
  enabled: True
  listen:
    - bark
    - fire_alarm
    - scream
    - speech
    - yell
    - siren
    - civil_defense_siren
    - doorbell
    - door
    - engine_starting
    - engine
    - emergency_vehicle
    - police_car
    - fire
    - fart
    - footsteps
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        #- path: rtsp://127.0.0.1:8554/frontdoor?video=copy&audio=copy&audio=opus
        - path: rtsp://127.0.0.1:8554/frontdoor?video&audio
          input_args: preset-rtsp-restream
          roles:
            - audio
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
objects:
  track:
    - car
    - person
    - bicycle
    - motorcycle
    - bus
    - bird
    - cat
    - dog
    - bear
    - backpack
version: 0.14
```

### Any other relevant information

```yaml
Debug info below, URl redacted, but i tested each URL and they open correctly in a browser:

Frigate Notification DEBUG: Info: fps: 5, frigate event id: 1729693118.759146-ae5tu2, object (formatted): car (Car), Config: camera(formatted): frontdoor(Frontdoor), Base URL: https://{redacted}, critical: False, alert once: False, Update Thumbnails: False, Video: , Target: Mobile Device cooldown: 30s, loiter timer: 0s, initial delay: 0s, color: #03a9f4, sound: default, android_auto: False, Group: frontdoor-frigate-notification, Channel: , Sticky: True, Title: , Message: A Car was detected on the Frontdoor camera., Subtitle: , tap_action: https://{redacted}/api/frigate/notifications/1729693118.759146-ae5tu2/frontdoor/clip.mp4, button 1 Text/URL/Icon: View Clip (https://{redacted}/api/frigate/notifications/1729693118.759146-ae5tu2/frontdoor/clip.mp4) , button 2 Text/URL/Icon: View Snapshot (https://{redacted}/api/frigate/notifications/1729693118.759146-ae5tu2/snapshot.jpg) , button 3 Text/URL/Icon: Silence New Notifications (silence-frontdoor) , icon: mdi:homeassistant tv: False, tv_position: center, tv_size: large, tv_duration: 10, tv_transparency: 0%, tv_interrupt: False, Filters: Zones: zone filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Entered Zones: [], Zone Filter TEST: PASS, Required objects TEST: Input: , TEST: PASS presence entity (not home): Entity: TEST: PASS, disabled times: [], State Filter: state filter toggle on: False, state filter entity: , required states: [], State Filter TEST: PASS, Custom Filter: True triggered by automation Frigate Notification for Jesse mqtt topic frigate/events
```
