### ISSUE TITLE
[Issue]: Help \ advice needed. 

### ISSUE THREAD

**Issue by Sharma230777** [SgtBatten/HA_blueprints#302]
### Description

First of all thank you for your effort and sharing this blueprint. Much appreciated. I am a newbie and I apologise for my limited knowledge. The issue I am having is that when I am connected to my wifi I can see the snapshot and the clip. Works perfectly.
However when I am not connected to my wifi I get the notification but neither the clip nor the snapshot open. 

I would much appreciate your uidance.

### Version

Frigate Notifications (0.12.0.4e)

### Automation Config

```yaml
mqtt:

  enabled: true
  host: 192.168.100.222
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: MQTT-USER
  password: XXXXXXX
  stats_interval: 300


record:
  expire_interval: 10

timestamp_style:
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

go2rtc:
  # go2rtc is to prevent multiple streams from the camera. Go2rtc pulls the stream from the camera and is able to multiply it to other
  # services, minimizing unnecessary data transfer.
  streams:
    Driveway:
      - rtsp://ZZZZ:XXXXX@192.168.100.26:554/cam/realmonitor?channel=1&subtype=1
      - rtsp://ZZZZ:XXXX@192.168.100.26:554/cam/realmonitor?channel=1&subtype=0

    

      #- "ffmpeg:back#audio=aac"  


cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://ZZZZ:XXXX@192.168.100.26:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

        - path: rtsp://ZZZZ:XXXX@192.168.100.26:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - car


      filters:
        car:
          mask: 0.21,0.354,0.324,0.349,0.344,0.515,0.214,0.517
        dog:
          mask: 0.497,0.65,0.543,0.65,0.547,0.724,0.495,0.72
        person:
          mask: 0.36,0.54,0.405,0.536,0.419,0.695,0.367,0.694
    zones:
      drivewayzone1:
        coordinates: 
          0.237,0.155,0.318,0.15,0.39,0.428,0.515,0.61,0.794,0.661,0.798,0.983,0.021,0.978,0.089,0.591,0.189,0.277
        loitering_time: 0
        objects:
          - car
          - dog
          - person

    motion:
      mask:
        - 0.359,0,0.991,0.006,0.994,0.514,0.526,0.548,0.416,0.371
        - 0.196,0.001,0.355,0.007,0.369,0.086,0.22,0.081
    review:
      alerts:
        required_zones: drivewayzone1
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - drivewayzone1
      crop: true
      height: 500
      retain:
        default: 3

    record:
      enabled: true


version: 0.14
```

### Frigate Config

```yaml
alias: Frigate Driveway Human Motion Lidha Phone (Yes)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.driveway
    notify_device: 5af34128b71810c6ae0709539d3fb012
    base_url: http://192.168.100.222:8123
    message: Hi Lidha there is a person in the driveway
    update_sub_label: false
    attachment: snapshot.jpg?bbox=1
    update_thumbnail: false
    zone_filter: true
    zones:
      - drivewayzone1
    labels:
      - person
    sticky: true
    alert_once: false
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    color: "#009688"
```

### Any other relevant information

```yaml
None
```
