### ISSUE TITLE
[Issue]: Notification not coming back online after silencing

### ISSUE THREAD

**Issue by rykr** [SgtBatten/HA_blueprints#305]
### Description

I click Silence new notifications on my iPhone.  I see that the automation is disabled on HA but it never re-enables.

### Version

0.12.0.4p

### Automation Config

```yaml
alias: House Rear
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.house_rear
    notify_device: 6d7c6682adbe734c1362b9a6b70fa2fd
    message: "Motion detected behind main house "
    icon: mdi:cctv
    sound: motion-detected.wav
    notify_group: notify.parents_mobile_devices
```
