### ISSUE TITLE
[Issue]: iOS Notification not occuring

### ISSUE THREAD

**Issue by Tan-tan-san** [SgtBatten/HA_blueprints#307]
### Description

iOS Notifications not occurring for this blueprint for iOS anymore. I have other android devices that are still getting the alerts with snapshots, but none of my iOS devices are getting them. They're able to get other automation alerts on other sensors, but not with this blueprint.

### Version

0.12.0.4o

### Automation Config

```yaml
alias: front door iphone
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.frontdoor
    notify_device: 655f6f7f5fd88bf452a1d3828be6c3ef
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.7
  user: mqtt
  password: Dmcs1234

detectors:
  rknn:
    type: rknn
    core_mask: 0b111

model: # required
  # name of yolov8 model or path to your own .rknn model file
  # possible values are:
  #- default-yolov8n
  # - default-yolov8s
  # - default-yolov8m
  # - default-yolov8l
  # - default-yolov8x
  # - /config/model_cache/rknn/your_custom_model.rknn
  #path: default-yolov8l
  path: /config/model_cache/rknn/default-yolov8l-rk3588.rknn
  # width and height of detection frames
  width: 320
  height: 320
  # pixel format of detection frame
  # default value is rgb but yolov models usually use bgr format
  input_pixel_format: bgr # required
  # shape of detection frame
  input_tensor: nhwc

cameras:
  backdoor:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        #- path: rtsp://admin:admin@192.168.1.91:554/stream1
        - path: rtsp://admin:123456@192.168.1.96:554/1/h264major
          roles:
            - detect
            - record
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
          objects:
            person: 7
            bicycle: 7
            car: 7
            bird: 7
            cat: 7
            dog: 7
        objects:
          - person
    detect:
      width: 1280
      height: 720
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 7
          bicycle: 7
          car: 7
          bird: 7
          cat: 7
          dog: 7
  driveway:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://admin:admin@192.168.1.92:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
          objects:
            person: 7
            bicycle: 7
            car: 7
            bird: 7
            cat: 7
            dog: 7
        objects:
          - person
          - dog
          - cat
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 7
          bicycle: 7
          car: 7
          bird: 7
          cat: 7
          dog: 7

  frontdoor:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://admin:admin@192.168.1.95:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
          objects:
            person: 7
            bicycle: 7
            car: 7
            #bird: 7
            #cat: 7
            #dog: 7
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 7
          bicycle: 7
          car: 7
          bird: 7
          cat: 7
          dog: 7
    motion:
      mask:
        - 0,127,646,51,680,0,0,0
        - 1566,0,1200,482,1920,1080,1920,0
        - 242,953,559,924,540,501,310,70,85,304    
        - 1364,791,1199,749,1072,531,1087,444,1264,145,1518,144
        - 1142,430,1137,606,1056,538,1076,417
        - 233,0,261,374,85,460,52,0,155,0
        - 1178,419,1155,625,1028,532,1073,362,1086,369
    zones:
      zone_0:
        coordinates: 1462,586,1200,482,1252,207,1537,231
    objects:
      filters:
        person:
          mask:
            - 1028,459,1165,645,1021,1080,414,1080,314,0,972,0,1576,0
 #  yi-chicken:
#     mqtt:
#       timestamp: False
#       bounding_box: False
#       crop: True
#       height: 500
#     ffmpeg:
#       hwaccel_args: preset-rk-h264
#       output_args:
#         record: preset-record-generic-audio-aac
#       inputs:
#         - path: rtsp://192.168.1.122/ch0_0.h264
#           roles:
#             - detect
#             - record
#     detect:
#       width: 1920
#       height: 1080
#     record:
#       enabled: True
#       retain:
#         days: 30
#         mode: motion
#       events:
#         pre_capture: 15
#         post_capture: 15
#         retain:
#           default: 14
#           mode: active_objects
#           objects:
#             person: 7
#             bicycle: 7
#             car: 7
#             bird: 7
#             cat: 7
#             dog: 7
#     snapshots:
#       enabled: True
#       timestamp: True
#       bounding_box: True
#       retain:
#         default: 14
#         objects:
#           person: 7
#           bicycle: 7
#           car: 7
#           bird: 7
#           cat: 7
#           dog: 7

  #Boys-room:
     #mqtt:
       #timestamp: False
       #bounding_box: False
       #crop: True
       #height: 500
     #ffmpeg:
       #hwaccel_args: preset-rk-h264
       #output_args:
         #record: preset-record-generic-audio-aac
       #inputs:
         #- path: rtsp://@192.168.1.104/ch0_0.h264
           #roles:
             #- detect
             #- record
#     detect:
#       width: 1280
#       height: 720
#     record:
#       enabled: False
#       retain:
#         days: 30
#         mode: motion
#       events:
#         pre_capture: 15
#         post_capture: 15
#         retain:
#           default: 14
#           mode: active_objects
#           objects:
#             person: 7
#             bicycle: 7
#             car: 7
#             bird: 7
#             cat: 7
#             dog: 7
#     snapshots:
#       enabled: False
#       timestamp: True
#       bounding_box: True
#       retain:
#         default: 14
#         objects:
#           person: 7
#           bicycle: 7
#           car: 7
#           bird: 7
#           cat: 7
#          dog: 7
  
  Garage:
      mqtt:
        timestamp: False
        bounding_box: False
        crop: True
        height: 500
      ffmpeg:
        hwaccel_args: preset-rk-h264
        #output_args:
          #record: preset-record-generic-audio-aac
        inputs:
          - path: rtsp://@192.168.1.102/ch0_0.h264
            roles:
              - detect
              - record
      detect:
        width: 1280
        height: 720
      record:
        enabled: True
        retain:
          days: 30
          mode: motion
        events:
          pre_capture: 15
          post_capture: 15
          retain:
            default: 14
            mode: active_objects
            objects:
              person: 7
              bicycle: 7
              car: 7
              bird: 7
              cat: 7
              dog: 7
      snapshots:
        enabled: True
        timestamp: True
        bounding_box: True
        retain:
          default: 14
          objects:
            person: 7
            bicycle: 7
            car: 7
            bird: 7
            cat: 7
            dog: 7
  Girls-room:
    #mqtt:
      #timestamp: False
      #bounding_box: False
      #crop: True
      #height: 500
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://admin:admin@192.168.1.94:554/stream1
          roles:
            - detect
            #- record
    record:
      enabled: False
      retain:
        days: 30
        mode: motion
      #events:
        #pre_capture: 15
        #post_capture: 15
        #retain:
          #default: 14
          #mode: active_objects
          #objects:
            #person: 7
            #bicycle: 7
            #car: 7
            #bird: 7
            #cat: 7
            #dog: 7
        #objects:
          #- person
    detect:
      width: 1280
      height: 720
    #snapshots:
      #enabled: False
      #timestamp: True
      #bounding_box: True
      #retain:
        #default: 14
        #objects:
          #person: 7
          #bicycle: 7
          #car: 7
          #bird: 7
          #cat: 7
          #dog: 7
  Sideyard:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
    ffmpeg:
      hwaccel_args: preset-rk-h264
      inputs:
        - path: rtsp://admin:admin@192.168.1.91:554/stream1
          roles:
            - detect
            - record
    record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        pre_capture: 15
        post_capture: 15
        retain:
          default: 14
          mode: active_objects
          objects:
            person: 7
            bicycle: 7
            car: 7
            bird: 7
            cat: 7
            dog: 7
        objects:
          - person
    detect:
      width: 1280
      height: 720
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 14
        objects:
          person: 7
          bicycle: 7
          car: 7
          bird: 7
          cat: 7
          dog: 7
```

### Any other relevant information

```yaml
This had been working before. I updated from the version 'e' of the blueprint in hopes this would fix the issue. I've removed the companion app, all blueprints with this device and the device entirely from HA. I even rebooted HA and tried to reconfigure what I had before and still no luck in getting it to work.
```
