### ISSUE TITLE
[Config Support]: Notifications Not Sending

### ISSUE THREAD

**Issue by DevScientist** [SgtBatten/HA_blueprints#310]
### Describe the problem you are having or the outcome you are trying to achieve.

I've tried changing up multiple variables but get the same trace in my automations where it looks like the whole thing is being ignored. The notification does not get delivered. What's going on?

### Version

0.12.0.4p

### Automation config

```yaml
alias: Frigate Test
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.backdoor
    notify_device: 4f0ceb808347bc621f60c53b080f6358
    critical: "true"
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
```

### Any other information that may be helpful

![trace](https://github.com/user-attachments/assets/9191b320-6138-4872-a540-36c2ba2433b9)
