### ISSUE TITLE
[Config Support]: How to get TTS to work?

### ISSUE THREAD

**Issue by Iceman248** [SgtBatten/HA_blueprints#311]
### Describe the problem you are having or the outcome you are trying to achieve.

I just installed the new 0.14.0.1d beta for Frigate 0.14, read about TTS features, but nothing plays. Is there something I am missing about how to get it to work?

### Version

0.14.0.1d

### Automation config

```yaml
alias: Frigate Notifications (0.14.0.1d)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.front
      - camera.back
    notify_device: bb343b353a3dda8c12457d011937417c
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    alert_once: true
    attachment: snapshot.jpg?crop=1
    update_thumbnail: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    tap_action: /ccab4aaf_frigate/dashboard
    sticky: true
    tts_helper: input_text.tts_alerts_frigate_notifications
```
