### ISSUE TITLE
[Config Support]:  Notification shows no image and 404 error for clip

### ISSUE THREAD

**Issue by KATPWR** [SgtBatten/HA_blueprints#312]
### Describe the problem you are having or the outcome you are trying to achieve.

Notification does not show thumbnail or screen shot, when trying to view clip gives a 404 error. Clips cannot be viewed in home assistant media, but I can see the thumbnails and open images.  Clips can be watched after downloading when outside or inside home network.

### Version

0.12.0.4e

### Automation config

```yaml
alias: Frigate Notifications v1
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door_cam
    notify_device: 256f057a0cb863691d3ba6a1ff297f48
    alert_once: true
    update_thumbnail: true
    cooldown: 90
    base_url: ha.*MYDOMAIN*.com
    attachment: snapshot.jpg
    color: "#f44336"
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
```

### Frigate Config

```yaml
auth:
  ###RESET ADMIN PASSWORD
  #reset_admin_password: true
  failed_login_rate_limit: 1/second;5/minute;20/hour
  trusted_proxies:
    - 172.18.0.0/16 # <---- this is the subnet for the internal docker compose network
    - 192.168.0.153/32 # Home Assistant
# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  #restream: true

detectors:
  nvidia_2070:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-640.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640

snapshots: # <----- Enable snapshots
  enabled: true
  timestamp: false
  bounding_box: true
  #retain:
    #default: 10

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-copy

mqtt:
  host: mqtt5
  user: user
  password: pass
  port: 1883

go2rtc:
  streams:
    front_door_cam:
      - rtsp://X:Y0@192.168.0.199:554//h264Preview_01_main
      #- "ffmpeg:front_door_cam#audio=opus"
    front_door_cam_sub:
      - rtsp://X:Y@192.168.0.199:544//h264Preview_01_sub
      #- "ffmpeg:front_door_cam_sub#audio=opus"
    canidates:
      - 192.168.0.150:8555
      - stun:8555

cameras:
  front_door_cam:
    ffmpeg:
      inputs:
        #- path: rtsp://192.168.0.150:8554/front_door_cam
        - path: rtsp://X:Y@192.168.0.199:554//h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
        #- path: rtsp://172.0.0.1:8554/front_door_cam_sub
        - path: rtsp://X:Y@192.168.0.199:554//h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            #- audio #if using noise activation
    detect:
      enabled: true
      #width: 640
      #height: 480
      fps: 5
      stationary:
        #interval: 50
        threshold: 50

    zones:
      driveway:  #drive way
        coordinates: 0.875,0.687,1,0.709,1,1,0.897,1,0.751,0.884,0.741,0.835,0.698,0.713,0.76,0.655
        inertia: 3
        loitering_time: 0
      driveway_enterance:
        coordinates: 0.7,0.713,0.75,0.65,0.669,0.61,0.59,0.624
        obejects:
          - car
        inertia: 3
        loitering_time: 0
      walkway:
        coordinates: 
          0.675,0.849,0.757,0.897,0.891,1,0.311,1,0.453,0.815,0.698,0.722,0.705,0.746,0.668,0.786
        objects: person
        inertia: 3
        loitering_time: 0
      front_yard:  #front yard
        coordinates: 224,438,295,394,444,344,361,296,172,304,0,287
        objects:
          - person
      side_yard:  #side yard
        coordinates: 0.691,0.613,0.908,0.683,1,0.63,0.823,0.598
        objects: person
        inertia: 3
        loitering_time: 0
    motion:
      mask: 
        0,1,0.315,1,0.343,0.949,0.313,0.881,0.28,0.773,0.01,0.621,0.01,0.602,0.441,0.627,0.767,0.592,0.858,0.585,0.955,0.615,1,0.619,1,0,0,0,0,0.602
    review:
      alerts:
        required_zones:
          - driveway_enterance
          - walkway
          - front_yard
          - side_yard
          - driveway
objects:
  track:
    - person
    #- car
  #mask:
  filters:
    person:
      min_area: 1250 #width*height size good for driveway and yard
      max_area: 300000 #width*height
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.5
      threshold: 0.6
      #mask: 

record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: all
    objects:
      - person
      - car
      #retain:
      #default: 30
      #mode: motion
review:
  alerts:
    required_zones:
      - driveway_enterance
      - walkway
      - front_yard
      - side_yard
version: 0.14
```

### Any other information that may be helpful

Home assistant on proxmox VM
Frigate, MQTT, and Traefik running in Docker on a separate server 

Frigate logs from portainer

> 2024-11-08 22:25:32.497343336  192.168.0.153 - - [08/Nov/2024:22:25:32 -0500] "GET /api/front_door_cam/latest.jpg HTTP/1.1" 200 97025 "-" "HomeAssistant/2024.11.1 aiohttp/3.10.10 Python/3.12" "-"
2024-11-08 22:41:35.242021918  192.168.0.153 - - [08/Nov/2024:22:41:35 -0500] "GET /api/config HTTP/1.1" 200 10421 "-" "HomeAssistant/2024.11.1 aiohttp/3.10.10 Python/3.12" "-"
2024-11-08 22:40:54.235418871  192.168.0.153 - - [08/Nov/2024:22:40:54 -0500] "GET /api/events/1731078132.14843-j0gr6h/clip.mp4?download=true HTTP/1.1" 200 7353916 "https://ha.*MYDOMAIN*.com/lovelace/default_view?external_auth=1" "Mozilla/5.0 (Linux; Android 14; Pixel 6 Build/AP2A.240905.003.F1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Mobile Safari/537.36" "IP CELL, 192.168.0.150"
2024-11-08 22:41:36.415006112  192.168.0.153 - - [08/Nov/2024:22:41:36 -0500] "GET /api/front_door_cam/recordings/summary?timezone=America/New_York HTTP/1.1" 200 4496 "-" "HomeAssistant/2024.11.1 aiohttp/3.10.10 Python/3.12" "-"
2024-11-08 22:41:35.937242621  192.168.0.153 - - [08/Nov/2024:22:41:35 -0500] "GET /api/front_door_cam/recordings/summary?timezone=America/New_York HTTP/1.1" 200 4496 "-" "HomeAssistant/2024.11.1 aiohttp/3.10.10 Python/3.12" "-"
2024-11-08 22:41:24.494793681  127.0.0.1 - - [08/Nov/2024:22:41:24 -0500] "" 400 0 "-" "-" "-"
2024-11-08 22:40:48.551923194  192.168.0.153 - - [08/Nov/2024:22:40:48 -0500] "GET /api/events?cameras=front_door_cam&after=1731078000&before=1731085199&limit=10000&include_thumbnails=0 HTTP/1.1" 200 2990 "-" "HomeAssistant/2024.11.1 aiohttp/3.10.10 Python/3.12" "-"
2024-11-08 22:41:51.322207529  192.168.0.212 - - [08/Nov/2024:22:41:51 -0500] "GET /api/config HTTP/1.1" 200 10421 "http://192.168.0.150:5000/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "-"
08 22:41:51.322579445  192.168.0.212 - - [08/Nov/2024:22:41:51 -0500] "GET /api/profile HTTP/1.1" 200 18 "http://192.168.0.150:5000/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "-"

**Comment by SgtBatten** [comment]
Copy the url that opens when you try to view the clip. Can you open it on your PC?

**Comment by KATPWR** [comment]
I'm not sure what you mean buy the URL for the clip, the external URL does work on desktop. After pressing any of the action buttons on the notification I get this.  it acts the same regardless if on my home network or outside my network
![462540576_8578369898878489_4121402991511140976_n](https://github.com/user-attachments/assets/3a76b762-04d9-4e55-aa2b-d1033ee46299)
If I refresh the external URL it will pull up home assistant in the app.

I'm curious if its an issue with Treafik proxy on how the notification try to access HA/Frigate 

Traefik proxy config for Home Assistant

```
http:
  routers:
     home-assistant:
     service: home-assistant   
     entryPoints:
         - https
      rule: "Host(`ha.local.*MYDOMAIN*.com`)"
      middlewares:
        - default-headers
        - https-redirect
        - ip-whitelist
      tls:
        certResolver: cloudflare

    home-assistant-remote:
      service: home-assistant   
      entryPoints:
        - https
      rule: "Host(`ha.*MYDOMAIN*.com`)"
      middlewares:
        - default-headers
        - https-redirect
        #- authentik@docker #breaks app pushes to browser
      tls:
        certResolver: cloudflare
     
  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: "http://192.168.0.153:8123" #must be IP
        passHostHeader: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
```
