### ISSUE TITLE
[Issue]: IOS browser cannot open MP4 video, you can view snapshots

### ISSUE THREAD

**Issue by guoqiang881245** [SgtBatten/HA_blueprints#313]
### Description

My automation configuration is finished, IOS can not preview the local video, you can preview the snapshot, blueprint automation script in which I configured the camera and the phone to send notifications。The link to the video can be opened normally in PC Google browser 。URL:http://192.168.124.210:8123/api/frigate/notifications/1731126614.016001-mpc1m1/my_camera1/clip.mp4?external_auth=1

https://github.com/user-attachments/assets/49ccc118-37ef-407a-8725-ad63b777648d

https://github.com/user-attachments/assets/8d7ad7d4-0e47-4cdd-8ab4-f5164136437e

### Version

0.12.0.4e

### Automation Config

```yaml
alias: New automation
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.my_camera1
    notify_device: 48e032f90a45fb55a88694d53d894a4a
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.124.210
  port: 1883
  user: mqtt
  password: Qwe669


detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

#ffmpeg:
#  hwaccel_args: preset-vaapi
#  hwaccel_args: preset-intel-qsv-h264

record:
  enabled: True
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 30
      mode: motion  

snapshots:
  enabled: True
  retain:
    default: 30      



cameras:
  my_camera1: # <------ Name the camera
    enabled: true     
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://192.168.124.100:554/stream1 # <----- The stream you want to use for detection
          roles:
            - detect                       
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
    live:
      stream_name: face 
go2rtc:
  streams:
    face: #摄像头名称
      - rtsp://192.168.124.100:554/stream1
version: 0.14
```
