### ISSUE TITLE
[Feature Request]: Telegram bot integration

### ISSUE THREAD

**Issue by uvera** [SgtBatten/HA_blueprints#314]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to send notifications to telegram

**Describe the solution you'd like**
A way to specify notify target which is based on telegram platform/integration

**Describe alternatives you've considered**
None yet

**Additional context**
As I understood from docs
```yaml
actions:
  - action: notify.NOTIFIER_NAME
    data:
      title: "Send an images"
      message: "That's an example that sends an image."
      data:
        photo:
          - url: http://192.168.1.28/camera.jpg
```
We need to specify photo property for notification payload

This needs to be added to notify service payload
```yaml
                                  photo:
                                    - url: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
```

The thing is we cannot target base_url here as that's the web panel UI url:port combination.
We need a way to specify URL that is from API port (5000) so that telegram integration can download the image and send it via tg bot.
https://docs.frigate.video/integrations/api/#get-apicamera_namelabelsnapshotjpg
