### ISSUE TITLE
[Bug]: cameras with _1 suffix no longer trigger automation

### ISSUE THREAD

**Issue by pdx0** [SgtBatten/HA_blueprints#32]
### Description

cameras configured in frigate with an _n suffix no longer trigger the automation

### Version

0.12.0.1a

### Automation Config

```yaml
alias: phone 1 cat
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.phone_1
    notify_device: 
    base_url: 
    critical: "false"
    alert_once: true
    update_thumbnail: true
    video: /api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    color: green
    icon: mdi:cat
    labels:
      - cat
```

### Frigate Config

```yaml
cameras:
  phone_1:
    ffmpeg:
      inputs:    
        - path: rtsp://127.0.0.1:8554/phone_1
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record  
...
```
