### ISSUE TITLE
[Config Support]: Android Notifications not sending, rest of automation functioning

### ISSUE THREAD

**Issue by anxiousintrovert** [SgtBatten/HA_blueprints#325]
### Describe the problem you are having or the outcome you are trying to achieve.

My automations using the blueprint do trigger, but for the life of me i cannot figure out why the traces never send a notification. I have tried quite a few suggestions and at this point i can only assume me going over this 50 times means I'm missing something incredibly obvious. Even device automations like turn on a light seem to function, just no notification at all. Any thoughts?

Frigate Version: 0.14
Blueprint Version: I have tried 12.0.4e as well as beta version 0.12.0.5c

`

![image](https://github.com/user-attachments/assets/21813531-c9f5-438e-a7f8-be3808c78ebb)
![image](https://github.com/user-attachments/assets/5b132788-33e1-4133-b2ab-c2ccdd2f5154)
![image](https://github.com/user-attachments/assets/eb57a7a3-ce23-447a-a9cc-e4d66bd21690)

Logbook Entries for the last trace before it ends.

`
Frigate Notification DEBUG (in loop): Send Notification: False Info: sublabel: None, image: "REDACTED/api/frigate/notifications/1733088340.318615-zy4e9p/thumbnail.jpg" Title: message: A Person was detected on the Deck camera. iOS sound: Critical, Android Sound: enabled, iOS url: REDACTED/api/frigate/notifications/1733088340.318615-zy4e9p/thumbnail.jpg video: "" critical: True, tts: False Triggers: New Snapshot: False - Disabled Presence Changed: False, Stationary Moved: False, Entered Zones Changed: False - Disabled, sublabel changed: False, Conditions: Loitering: 0 or Filters: Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Last Zones: ['back_deck'], Entered Zones: 1 - ['back_deck'], TEST: PASS , Object Filter: Input: ['dog', 'person'], TEST: PASS, Presence entity (not home): Entity: [''], TEST: PASS, Time Filter: Disabled times: [], TEST: PASS State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: PASS, triggered by automation Deck test mqtt topic frigate/events`

### Version

12.0.4e

### Automation config

```yaml
Automation Yaml:
`alias: Deck test
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.deck
    notify_device: DEVICEID
    base_url: http://WANIP
    critical: "true"
    video: ""
    android_auto: true
    sticky: true
    labels:
      - dog
      - person
    debug: true
    cooldown: 0
```

### Frigate Config

```yaml
deck: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWD@LOCALIP/cam/realmonitor?channel=4&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:PASSWD@LOCALIP/cam/realmonitor?channel=4&subtype=0
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
    record:
      enabled: true
    zones:
      Back_Deck:
        coordinates: 
          0.839,0.178,0.684,0.998,0,0.996,0,0.676,0.256,0.402,0.391,0.118,0.442,0.1,0.51,0.15,0.58,0.104,0.713,0.106,0.799,0.106
        loitering_time: 0
        inertia: 3
        objects:
          - dog
          - person
      SepticField:
        coordinates: 0.2,0.189,0.083,0.18,0.001,0.232,0.002,0.345
        loitering_time: 0
        inertia: 3
        objects: dog
    review:
      alerts:
        required_zones:
          - SepticField
          - Back_Deck
      detections: {}
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true'
```

### Any other information that may be helpful

Config for the camera in Frigate:
` deck: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWD@LOCALIP/cam/realmonitor?channel=4&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://admin:PASSWD@LOCALIP/cam/realmonitor?channel=4&subtype=0
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920
      height: 1080
    record:
      enabled: true
    zones:
      Back_Deck:
        coordinates: 
          0.839,0.178,0.684,0.998,0,0.996,0,0.676,0.256,0.402,0.391,0.118,0.442,0.1,0.51,0.15,0.58,0.104,0.713,0.106,0.799,0.106
        loitering_time: 0
        inertia: 3
        objects:
          - dog
          - person
      SepticField:
        coordinates: 0.2,0.189,0.083,0.18,0.001,0.232,0.002,0.345
        loitering_time: 0
        inertia: 3
        objects: dog
    review:
      alerts:
        required_zones:
          - SepticField
          - Back_Deck
      detections: {}
    motion:
      threshold: 40
      contour_area: 10
      improve_contrast: 'true' `
