### ISSUE TITLE
[Issue]: Notification is not sent when "Person" object filter is selected.  If the Object Filter is left blank, the notification is sent.

### ISSUE THREAD

**Issue by bluezclouds** [SgtBatten/HA_blueprints#328]
### Description

When MQTT topic /frigate/reviews is defined, notifications are not sent if "person" is selected in Object Filter.  If Object Filter is left blank notifications are sent.

Trace when "person" filter is defined:

![Screenshot from 2024-12-07 15-03-07](https://github.com/user-attachments/assets/cd25f26c-e98d-4ed9-a689-888a8dd2ca20)

### Version

0.12.0.5c

### Automation Config

```yaml
This does NOT send a notification:

alias: PS Frigate Front Door Alert
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.ps_front_door
    notify_device: 68a8883fb782ae29cffbb4587647c579
    mqtt_topic: frigate/reviews
    message: Someone at PS Front Door
    labels:
      - person
    debug: true
    attachment: thumbnail.jpg
    sticky: true

This sends a notification:

alias: PS Frigate Front Door Alert
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.ps_front_door
    notify_device: 68a8883fb782ae29cffbb4587647c579
    mqtt_topic: frigate/reviews
    message: Someone at PS Front Door
    labels: []
    debug: true
    attachment: thumbnail.jpg
    sticky: true
```

### Frigate Config

```yaml
mqtt:
  host: 10.0.0.118
  port: 1883
  enabled: true
  user: user
  password: password
  topic_prefix: frigate

#database:
#  path: /config/frigate.db

detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    PS_Front_Door: rtsp://user:password@10.0.0.220:554/stream1
    PS_Back_Patio: rtsp://user:password@10.0.0.221:554/stream2

birdseye:
  enabled: true
  quality: 10
  mode: continuous

cameras:

  PS_Front_Door:
    enabled: true
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: preset-vaapi
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://user:password@10.0.0.220:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - record
            - rtmp

    detect:
      enabled: true
      fps: 5
      width: 960
      height: 540
    objects:
      track:
        - person

      filters:
        person:
          min_score: 0.5
          threshold: 0.57
          min_area: 5000
          max_area: 220000

          mask:
            - 0.022,0.736,0.018,0.562,0,0.525,0.001,0.746
            - 0.002,0.753,0.07,0.714,0.078,0.558,0.002,0.552
            - 0.201,0.505,0.371,0.485,0.368,0.732,0.26,0.736
      mask: 0.002,0.753,0.07,0.714,0.078,0.558,0.002,0.552
    motion:
      threshold: 19
      contour_area: 10
      improve_contrast: 'true'
      mask:
        - 0.052,0.537,0.038,0.557,0.014,0.615,0.029,0.702,0.048,0.767,0.082,0.835,0.153,0.928,0.23,0.901,0.254,0.808,0.274,0.732,0.256,0.659,0.236,0.567,0.237,0.495,0.25,0.478,0.26,0.429,0.266,0.296,0.295,0.115,0.328,0.124,0.329,0.048,0.328,0,0.001,0,0,0.046,0.027,0.049,0.003,0.198,0,0.405,0.013,0.448,0.047,0.477
        - 0.322,0.486,0.231,0.503,0.242,0.623,0.268,0.747,0.307,0.747,0.32,0.555
        - 0.429,0.631,0.367,0.653,0.39,0.74,0.434,0.744,0.445,0.679
  PS_Back_Patio:
    enabled: true
    ui:
      order: 2
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp:user:password@10.0.0.221:554/stream1
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - record
            - rtmp

    detect:
      enabled: true
      fps: 5
      width: 960
      height: 540

    objects:
      track:
        - person

      filters:
        person:
          min_score: 0.5
          threshold: 0.57
          min_area: 5000
          max_area: 120000
      mask: 0.173,0.016,0.138,0.469,0.138,0.992,0.002,0.998,0,0

    motion:
      mask:
        - 0.002,0.047,0.327,0.043,0.324,0,0.002,0.006
        - 0.758,0.277,0.756,0.158,0.71,0.144,0.669,0.166,0.655,0.213,0.67,0.284,0.711,0.354,0.749,0.322
        - 0.814,0.467,0.777,0.29,0.77,0.171,0.812,0.185,0.83,0.249,0.831,0.412,0.908,0.379,0.935,0.471,0.891,0.509,0.816,0.523
        - 0.48,0.488,0.563,0.418,0.602,0.331,0.619,0.269,0.627,0.184,0.688,0.094,0.713,0,0.22,0.004,0.177,0.047,0.162,0.091,0.178,0.213,0.172,0.343,0.203,0.493,0.287,0.495,0.294,0.189,0.353,0.18,0.353,0.521,0.372,0.55,0.427,0.572,0.466,0.613
        - 0.711,0.518,0.69,0.381,0.611,0.371,0.584,0.428,0.587,0.501,0.592,0.541,0.659,0.556
      threshold: 20
      contour_area: 10
      improve_contrast: 'true'

record:
  enabled: true
  events:
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 10

snapshots:
  enabled: true

version: 0.14
```

### Any other relevant information

```yaml
MQTT log for event:

2024-12-07T15:02:32: Received PINGREQ from frigate
2024-12-07T15:02:32: Sending PINGRESP to frigate
2024-12-07T15:02:33: Received PUBLISH from frigate (d0, q0, r0, m0, 'frigate/events', ... (1483 bytes))
2024-12-07T15:02:33: Sending PUBLISH to frigate (d0, q0, r0, m0, 'frigate/events', ... (1483 bytes))
2024-12-07T15:02:33: Received PUBLISH from frigate (d0, q0, r0, m0, 'frigate/PS_Front_Door/all', ... (1 bytes))
2024-12-07T15:02:33: Sending PUBLISH to 0z2YAy7znwyUntYq3Xjo3l (d0, q0, r0, m0, 'frigate/PS_Front_Door/all', ... (1 bytes))
2024-12-07T15:02:33: Sending PUBLISH to frigate (d0, q0, r0, m0, 'frigate/PS_Front_Door/all', ... (1 bytes))
2024-12-07T15:02:33: Received PUBLISH from frigate (d0, q0, r0, m0, 'frigate/PS_Front_Door/person', ... (1 bytes))
2024-12-07T15:02:33: Sending PUBLISH to 0z2YAy7znwyUntYq3Xjo3l (d0, q0, r0, m0, 'frigate/PS_Front_Door/person', ... (1 bytes))
2024-12-07T15:02:33: Sending PUBLISH to frigate (d0, q0, r0, m0, 'frigate/PS_Front_Door/person', ... (1 bytes))
2024-12-07T15:02:33: Received PUBLISH from frigate (d0, q0, r1, m0, 'frigate/PS_Front_Door/person/snapshot', ... (11503 bytes))
2024-12-07T15:02:33: Sending PUBLISH to 0z2YAy7znwyUntYq3Xjo3l (d0, q0, r0, m0, 'frigate/PS_Front_Door/person/snapshot', ... (11503 bytes))
2024-12-07T15:02:33: Sending PUBLISH to frigate (d0, q0, r0, m0, 'frigate/PS_Front_Door/person/snapshot', ... (11503 bytes))
```
