### ISSUE TITLE
[Feature Request]: Support alternative notification systems like ntfy

### ISSUE THREAD

**Issue by schklom** [SgtBatten/HA_blueprints#329]
**Describe what you are trying to accomplish and why in non technical terms**

I don't have Google on my phone, so I can't get HA notifications for now.
I have setup a custom notification configuration for ntfy in my HA config file, and would prefer to use it, it is this for now, but can be amended (see below). Alternatively, I would love to be able to specify the ntfy URL and token directly instead.

```yaml
notify:
  - name: "ntfy"
    platform: rest
    method: GET
    # https://docs.ntfy.sh/publish
    resource: "https://ntfy.sh/homeassistantXXXXX/publish"
    headers:
      Actions: "view, Open Home-Assistant, homeassistant://navigate"
    data:
      title: "{{ title if title is defined else 'Home-Assistant' }}"
      priority: "{{ priority if priority is defined else 'default' }}"
      tags: "{{ tags if tags is defined else 'house' }}"
```

**Describe the solution you'd like**
Not rely on HA native notification system.
Either use ones setup in `notify` section, or make ntfy available from the Blueprint.

**Describe alternatives you've considered**

**Additional context**
