### ISSUE TITLE
[Config Support]: Not triggering 

### ISSUE THREAD

**Issue by ChristiaanW123** [SgtBatten/HA_blueprints#330]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi,

For some reason, the whole blueprint is not starting. It should be watching a binary sensor (doorbell press), but the automation shows "Triggered: never". 

### Version

(0.12.0.4e)

### Automation config

```yaml
alias: Frigate Notifications (0.12.0.4e)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.reolink
    notify_device: 27015f6acb20dba2800f9d917eff20b9
    base_url: https:/xxx.nl
    title: Bezoek!
    message: Er is een bezoek aan de voordeur
    subtitle: Er is aangebeld
    update_thumbnail: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    icon: mdi:cctv
    ios_live_view: camera.reolink
    state_entity: binary_sensor.voordeur_visitor
    state_filter_states:
      - "on"
    state_filter: true
```
