### ISSUE TITLE
[Config Support]: Can I make the notification text longer?

### ISSUE THREAD

**Issue by jagauthier** [SgtBatten/HA_blueprints#331]
### Describe the problem you are having or the outcome you are trying to achieve.

This may be a specific android issue.  But I've implemented more thorough text descriptions and I want to read them all.

![Screenshot_20241220_213347_Firefox](https://github.com/user-attachments/assets/6409298a-8045-4b17-9202-0bf7ffbe30d9)

The text isn't long enough.  I'm not sure where this might be getting limited.   Could it be due to the image also, because I can get text messages longer than this and read them by expanding the notification.

### Version

stable (latest)

### Automation config

```yaml
alias: Camera - Front Door - Jason Phone
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_device: 4326f853999c593ea3007cb6f0f6f227
    message: "{{camera_name}}: {{detail_message}}"
    presence_filter:
      - ""
    mqtt_topic: motion/llm
```
