### ISSUE TITLE
[Config Support]: State filter doesn't recognize Alarmo armed states.

### ISSUE THREAD

**Issue by vlpower** [SgtBatten/HA_blueprints#332]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi!

I'm trying to use this blueprint to send screenshot notifications from my cameras, which works perfectly unless I turn on the State Filter, I have Alarmo as the Entity (alarm_control_panel.alarmo), and in the Alarm Filter States filed I have manually inserted "Armed away" and "Armed night", without the commas. The available states for that entity don't show up automatically in the dropdown menu, I'm not sure if that's normal. Hopefully you can point me in the right direction so I can get the notifications only when my Alarm system is armed away or armed night. Thank you!

### Version

0.12.0.4e

### Automation config

```yaml
alias: Frigate Notifications Cochera
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.cochera
    notify_device: a303ca4d93330f93b94da44dc00abac9
    state_entity: alarm_control_panel.alarmo
    state_filter_states:
      - Armed away
      - Armed night
    state_filter: true
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.100.185
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: L55*6gy0JZqg
  stats_interval: 300

record:
  enabled: true
  retain:
    days: 7
    mode: active_objects
  events:
    retain:
      default: 7
      mode: active_objects
      objects:
        person: 14

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 30

go2rtc:
  streams:
    frente:
      - rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=1&subtype=0
    cochera:
      - rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=2&subtype=0
    patio:
      - rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=3&subtype=0
    techo:
      - rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=4&subtype=0
cameras:
  frente:
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
      input_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - vaapi
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
      mask: 0.487,1,0.131,0.513,0.077,0.548,0.003,0.194,0.001,0.002,0.998,0.002,0.999,0.998
    motion:
      mask: 0.998,0.995,0.487,0.995,0.13,0.513,0.079,0.545,0.004,0.194,0.002,0,0.998,0
  cochera:
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=2&subtype=0
          roles:
            - detect
      input_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - vaapi
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
    motion:
      mask: 0.697,0.047,0.697,0.091,0.967,0.094,0.965,0.042
    zones:
      Zona_Cochera:
        coordinates: 0,0.096,0.24,0.004,0.244,0.148,0.669,0.15,0.702,0.106,1,0.102,1,1,0.007,0.992
        loitering_time: 2
        objects: person
        inertia: 3
  patio:
    detect:
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=3&subtype=0
          roles:
            - detect
      input_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - vaapi
    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
    motion:
      mask: 0.696,0.045,0.696,0.091,0.968,0.091,0.969,0.039
  techo:
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 50
        threshold: 50
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp://admin:*Vato1029*@192.168.100.200:554/cam/realmonitor?channel=4&subtype=0
          roles:
            - detect
      input_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - vaapi
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.5
          threshold: 0.6
          min_area: 700
      mask: 0,0,0,1,0.998,0.994,1,0
    motion:
      mask: 0.696,0.038,0.695,0.098,0.972,0.092,0.971,0.036
    zones:
      Zona_Techo:
        coordinates: 
          0.852,0.982,0.947,0.719,0.591,0.281,0.425,0.162,0.235,0.158,0.207,0.114,0.092,0.13,0.059,0.485,0.082,0.998
        inertia: 3
        loitering_time: 2
        objects: person
version: 0.14
```
