### ISSUE TITLE
[Config Support]: Disable triggers when at home

### ISSUE THREAD

**Issue by kennym** [SgtBatten/HA_blueprints#333]
### Describe the problem you are having or the outcome you are trying to achieve.

My alerts are working perfectly, but I would like to disable trigger an automation when my phone is detected being at home - is that possible?

### Version

0.12.0.4e

### Automation config

```yaml
alias: Detección Costado
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.costado
    notify_device: 857b293c04b95d1b696a23b49b4f5af7
    debug: false
    update_thumbnail: false
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    base_url: http://umbrel.tail016e4.ts.net:8123
```
