### ISSUE TITLE
[Config Support]: Custom Action (Manual trigger) - don't work

### ISSUE THREAD

**Issue by pkacp1** [SgtBatten/HA_blueprints#334]
### Describe the problem you are having or the outcome you are trying to achieve.

On my iOS device I receive notification, but Custom Action (Manual trigger) button (setup to trigger script) is doing nothing. Once I tap it, notification closes and nothing is happening. 

Is Custom Action (Manual trigger) feature working correct or needs some investigation? 

### Version

0.12.0.4e

### Automation config

```yaml
alias: AAAA - Frigate TEST
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.kamera_przed_garazem
    notify_device: 460d9e0a8d92eae07fcbc125c936a86e
    base_url: http://homeassistant.local:8123/
    message: Osoba wykryta przed komem
    update_thumbnail: false
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_1: Pokaż nagranie
    button_2: Brama
    custom_action_manual:
      - action: script.brama_garazowa
        metadata: {}
        data: {}
    update_sub_label: false
    url_2: custom-{{ camera }}
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.114
  user: xxxxxx
  password: xxxxxxx

cameras:

  Kamera_przed_garazem:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxx@192.168.1.20:554
          roles:
            - detect
     
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: True
      retain:
        days: 1
  

  Domofon_BRAMA_MAIN:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxx@192.168.1.108:554/h264Preview_01_main
          roles:
            - detect

detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
```
