### ISSUE TITLE
[Issue]: "Invalid color-value: #03a9f4" for Android TV notifications

### ISSUE THREAD

**Issue by mnoorenberghe** [SgtBatten/HA_blueprints#335]
### Description

The `color` parameter for Android TV notifications must be one of: `grey`, `black`, `indigo`, `green`, `red`, `cyan`, `teal`, `amber` or `pink`but currently the default is `#03a9f4` and the dropdown has other invalid values.

```
Logger: homeassistant.components.nfandroidtv.notify
Source: components/nfandroidtv/notify.py:129
integration: Notifications for Android TV / Fire TV

Invalid color-value: #03a9f4
```

### Version

0.12.0.4e

### Automation Config

```yaml
alias: My Camera
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.foo
    ...
```

### Frigate Config

```yaml
N/A
```

### Any other relevant information

```yaml
https://www.home-assistant.io/integrations/nfandroidtv#color

color:
  description: "Has to be one of: `grey`, `black`, `indigo`, `green`, `red`, `cyan`, `teal`, `amber` or `pink`."
  default: "`grey`"
  type: string
```
