### ISSUE TITLE
[Issue]: Notify to Group not working

### ISSUE THREAD

**Issue by GitWally** [SgtBatten/HA_blueprints#336]
### Description

Notify to a Group does not work any more, for none of my cameras.
I have a group (ALL_Androids) made of 2 mobile phones: one gets notified (but it is also the mandatory Mobile Device), the other one is silent.
For the sake of completeness the non-notified phone was changed during last weeks, and recently I started using the last version (0.12.0.4e): cannot say which one is the main cause.

But if i send a notification to the same group from Developer Tools > Actions both are notified properly.
Automations based on this blueprint are the only not working.

### Version

0.12.0.4e

### Automation Config

```yaml
alias: HikVision_D2_Frigate
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.d2frigate
    notify_device: a71601c86bdcabccae0984d59905338f
    notify_group: All_Androids
    message: "{{ camera_name }} detected a {{ label }}."
    critical: "true"
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    android_auto: true
    sticky: true
    labels:
      - person
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    button_1: Snapshot
    button_2: Clip
    url_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    url_1: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_3: Silence New
    color: "#f44336"
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.1.108
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: MQTTUser
  password: mqttpassword123
  stats_interval: 60



detectors:
  coral:
    type: edgetpu
    device: usb



# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db



# https://docs.frigate.video/guides/getting_started#step-8-enable-snapshots-optional
snapshots:
# Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: true
# Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: false
# Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
# Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
# Optional: crop the snapshot (default: shown below)
  crop: false
## Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
#  required_zones: []
# Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 10
      car: 7



birdseye:
  enabled: true
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: false
  # Optional: Width of the output resolution (default: shown below)
#  width: 1280
  # Optional: Height of the output resolution (default: shown below)
#  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects



# https://docs.frigate.video/configuration/record#object-specific-retention
# https://docs.frigate.video/configuration/index#full-configuration-reference
record:
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  retain:
    days: 0
    mode: all
  alerts:
    retain:
      days: 5
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 5
    pre_capture: 5
    post_capture: 5
cameras:
###########
# D2 Camera
###########
  D2Frigate:
    # Optional: Enable/Disable the camera (default: shown below).
    # If disabled: config is used but no live stream and no capture etc.
    # Events/Recordings are still viewable.
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://dispuser:dispuserpassword@192.168.1.207:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://dispuser:dispuserpassword@192.168.1.207:554/Streaming/Channels/101/
          roles:
            - record
# https://docs.frigate.video/configuration/hardware_acceleration
      hwaccel_args: preset-vaapi
    detect:
      enabled: true      # Detection On / Off
      width: 640
      height: 360
      fps: 4
    zones:
      D2_Door:
        coordinates: 0,360,640,360,640,0,545,0,492,162,0,228
        objects:
          - person
        filters:
          person:
            threshold: 0.65
            min_score: 0.6
            min_area: 2000
      D2_Garden:
        coordinates: 0,0,0.85,0,0.768,0.451,0,0.636
        objects: person
        filters:
          person:
            threshold: 0.65
            min_score: 0.6
            min_area: 600

        inertia: 3
        loitering_time: 0
    snapshots:
      enabled: true
      clean_copy: false
      timestamp: false
      bounding_box: true
      crop: false
    motion:
      improve_contrast: true
      mask:
        - 210,0,206,34,168,29,142,29,93,31,41,31,0,31,0,0,74,0
    birdseye:
      mode: objects
    record:
      enabled: true

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      #crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      #height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
    review:
      alerts: {}
      detections:
        required_zones:
          - D2_Door
          - D2_Garden
go2rtc:
  streams:
## THIS INCREASES VOL AND PREVENTS THE AUDIO COMING OUT FROM THE CAMERA SOUNDING MUFFLED
## Source https://www.youtube.com/watch?v=upXyBVMR4RM

version: 0.15-0
```

### Any other relevant information

```yaml
{
  "trace": {
    "last_step": "action/0/choose/2/sequence/6/repeat/sequence/2/choose/0/sequence/1",
    "run_id": "1075e4f5337820b1e39699ccc1115c95",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2025-01-04T13:27:43.815578+00:00",
      "finish": "2025-01-04T13:27:59.960266+00:00"
    },
    "domain": "automation",
    "item_id": "1668611083781",
    "trigger": "mqtt topic frigate/events",
    "trace": {
      "trigger/0": [
        {
          "path": "trigger/0",
          "timestamp": "2025-01-04T13:27:43.817006+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.hikvision_d2_frigate",
              "state": "on",
              "attributes": {
                "id": "1668611083781",
                "last_triggered": "2025-01-04T13:27:08.929865+00:00",
                "mode": "parallel",
                "current": 1,
                "max": 10,
                "friendly_name": "HikVision_D2_Frigate"
              },
              "last_changed": "2025-01-04T06:48:49.825041+00:00",
              "last_reported": "2025-01-04T13:27:36.060808+00:00",
              "last_updated": "2025-01-04T13:27:08.929898+00:00",
              "context": {
                "id": "01JGRQZ1W1K0P3ZWVY5NE4VB6H",
                "parent_id": null,
                "user_id": null
              }
            },
            "trigger": {
              "id": "frigate-event",
              "idx": "0",
              "alias": null,
              "platform": "mqtt",
              "topic": "frigate/events",
              "payload": "{\"before\": {\"id\": \"1735997263.260227-jbajv6\", \"camera\": \"D2Frigate\", \"frame_time\": 1735997263.260227, \"snapshot\": null, \"label\": \"person\", \"sub_label\": null, \"top_score\": 0.0, \"false_positive\": true, \"start_time\": 1735997263.260227, \"end_time\": null, \"score\": 0.76171875, \"box\": [478, 94, 503, 138], \"area\": 1100, \"ratio\": 0.5681818181818182, \"region\": [320, 0, 640, 320], \"active\": true, \"stationary\": false, \"motionless_count\": 0, \"position_changes\": 0, \"current_zones\": [], \"entered_zones\": [], \"has_clip\": false, \"has_snapshot\": false, \"attributes\": {}, \"current_attributes\": [], \"pending_loitering\": false, \"max_severity\": \"alert\"}, \"after\": {\"id\": \"1735997263.260227-jbajv6\", \"camera\": \"D2Frigate\", \"frame_time\": 1735997263.508183, \"snapshot\": {\"frame_time\": 1735997263.508183, \"box\": [471, 94, 499, 140], \"area\": 1288, \"region\": [320, 0, 640, 320], \"score\": 0.74609375, \"attributes\": []}, \"label\": \"person\", \"sub_label\": null, \"top_score\": 0.7109375, \"false_positive\": false, \"start_time\": 1735997263.260227, \"end_time\": null, \"score\": 0.74609375, \"box\": [471, 94, 499, 140], \"area\": 1288, \"ratio\": 0.6086956521739131, \"region\": [320, 0, 640, 320], \"active\": true, \"stationary\": false, \"motionless_count\": 1, \"position_changes\": 0, \"current_zones\": [], \"entered_zones\": [], \"has_clip\": false, \"has_snapshot\": false, \"attributes\": {}, \"current_attributes\": [], \"pending_loitering\": false, \"max_severity\": \"alert\"}, \"type\": \"new\"}",
              "qos": 0,
              "description": "mqtt topic frigate/events",
              "payload_json": {
                "before": {
                  "id": "1735997263.260227-jbajv6",
                  "camera": "D2Frigate",
                  "frame_time": 1735997263.260227,
                  "snapshot": null,
                  "label": "person",
                  "sub_label": null,
                  "top_score": 0,
                  "false_positive": true,
                  "start_time": 1735997263.260227,
                  "end_time": null,
                  "score": 0.76171875,
                  "box": [
                    478,
                    94,
                    503,
                    138
                  ],
                  "area": 1100,
                  "ratio": 0.5681818181818182,
                  "region": [
                    320,
                    0,
                    640,
                    320
                  ],
                  "active": true,
                  "stationary": false,
                  "motionless_count": 0,
                  "position_changes": 0,
                  "current_zones": [],
                  "entered_zones": [],
                  "has_clip": false,
                  "has_snapshot": false,
                  "attributes": {},
                  "current_attributes": [],
                  "pending_loitering": false,
                  "max_severity": "alert"
                },
                "after": {
                  "id": "1735997263.260227-jbajv6",
                  "camera": "D2Frigate",
                  "frame_time": 1735997263.508183,
                  "snapshot": {
                    "frame_time": 1735997263.508183,
                    "box": [
                      471,
                      94,
                      499,
                      140
                    ],
                    "area": 1288,
                    "region": [
                      320,
                      0,
                      640,
                      320
                    ],
                    "score": 0.74609375,
                    "attributes": []
                  },
                  "label": "person",
                  "sub_label": null,
                  "top_score": 0.7109375,
                  "false_positive": false,
                  "start_time": 1735997263.260227,
                  "end_time": null,
                  "score": 0.74609375,
                  "box": [
                    471,
                    94,
                    499,
                    140
                  ],
                  "area": 1288,
                  "ratio": 0.6086956521739131,
                  "region": [
                    320,
                    0,
                    640,
                    320
                  ],
                  "active": true,
                  "stationary": false,
                  "motionless_count": 1,
                  "position_changes": 0,
                  "current_zones": [],
                  "entered_zones": [],
                  "has_clip": false,
                  "has_snapshot": false,
                  "attributes": {},
                  "current_attributes": [],
                  "pending_loitering": false,
                  "max_severity": "alert"
                },
                "type": "new"
              }
            },
            "input_camera": "camera.d2frigate",
            "camera": "d2frigate",
            "mqtt_topic": "frigate/events",
            "camera_name": "D2frigate",
            "input_base_url": "",
            "base_url": "",
            "update_sub_label": true,
            "input_client_id": "",
            "client_id": "",
            "attachment": "thumbnail.jpg",
            "alert_once": false,
            "update_thumbnail": false,
            "ios_live_view": "",
            "android_auto": true,
            "notify_group": "ALL_Androids",
            "notify_group_target": "all_androids",
            "zone_only": false,
            "input_zones": [],
            "zones": [],
            "zone_multi": false,
            "input_labels": [
              "person"
            ],
            "labels": [
              "person"
            ],
            "presence_entity": [
              ""
            ],
            "disable_times": [],
            "cooldown": 30,
            "loitering": false,
            "loiter_timer": 0,
            "initial_delay": 0,
            "fps": 5,
            "state_only": false,
            "input_entity": "",
            "input_states": [],
            "states_filter": [],
            "color": "
```
