### ISSUE TITLE
[Issue]: Telegram notifications not working - sends via companion app

### ISSUE THREAD

**Issue by italicize9610** [SgtBatten/HA_blueprints#337]
### Description

I filled in my Telegram Chat ID and Telegram Base URL (http://homeassistant.local:8123) - however, notifications still revert to the companion app. This is on the latest beta 0.14.0.2d.

### Version

 0.14.0.2d

### Automation Config

```yaml
alias: Frigate
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.e1upstairs
      - camera.doorbell
      - camera.e1downstairs
      - camera.e1livingroom
    notify_device: c729c68c363fb3c41480230b72a2445f
    base_url: https://REDACTED.ui.nabu.casa
    title: "{{ label }} detected"
    update_thumbnail: true
    group: "{{camera}}"
    android_auto: true
    url_3: app://com.mcu.reolink
    button_3: Reolink
    button_2: Snapshot
    button_1: Stream
    sticky: true
    cooldown: 0
    url_1: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    attachment: snapshot.jpg?bbox=1
    silence_timer: 0
    telegram_base_url: http://homeassistant.local:8123
    notify_telegram_chat_id: "REDACTED - but works for other Telegram notifications via telegram_bot"
```
