### ISSUE TITLE
notification issues: not notifying on correct zones, adding object to filter fully stops it

### ISSUE THREAD

**Issue by balajeek** [SgtBatten/HA_blueprints#34]
### Description

I have the camera called 'driveway', with two zones marked, one for the driveway alone and another outside the driveway (that includes lawn, the road)

First started creating an automation, with just the camera name and tested it, I was all getting all notifications of vehicles, persons and so tagged zone_road and zone_driveway.

Then i added the zone in the automations to notify only when zone_driveway is triggered.
Issues: i still get zone_road and zone_driveway.

Then i added the object filter so i can be notifed only when Person is detected.
Issues: no notifications at all were coming, completed stopped.  I tried it few times to remove object filter and add it again, it seem whenever anything i add to the object filter i get no notifications.  

I also made sure the zone markings are not touching each other and are defined in the correct areas.

Finally, when i browse thru the snapshots, it seem tagged appropriated with clips tagged as zone_road, zone_driveway or some clips with both, and some with person and so.

### Version

(0.11.1-2eada21)

### Automation Config

```yaml
alias: Frigate Notifications (0.12.0.1a) - Driveway
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.driveway
    notify_device: 08dbf356d6b4e693f57da44c7f209c0f
    zones:
      - zone_driveway
    labels: []
    zone_filter: true
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    silence_timer: 15
    cooldown: 60
    zone_multi: false
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.100
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

database:
  path: /media/frigate/clips/frigate.db

cameras:
  driveway:
    ui:
      order: 1
    ffmpeg:
      hwaccel_args: []
      inputs:
        - path: rtsp:<url here>
          roles:
            - detect
            - rtmp
            - record
            - clips
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - animal
        - vehicle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: true
      retain:
        default: 7
        objects:
          person: 3
          animal: 2
          vehicle: 3
    record:
      enabled: true
      retain:
        days: 7
      events:
        #post_capture: 10
        retain:
          default: 1
          objects:
            person: 1
            animal: 1
            vehicle: 1
    motion:
      mask:
        - 322,718,1051,907,1079,1030,1920,1029,1920,1080,1562,1080,1443,1080,1358,1080,957,1080,0,1080,0,700
        - 0,0,0,336,1920,405,1920,213,1920,0,0,0
    zones:
      zone_driveway:
        coordinates: 1554,598,1920,681,1920,986,1746,1042,1375,1042,1184,948,932,834,812,812,721,781,594,762,226,736,0,755,0,562
      zone_road:
        coordinates: 1658,377,1895,417,1895,510,1494,551,1018,547,561,556,34,542,45,391

detectors:
  coral:
    type: edgetpu
    device: usb
```
