### ISSUE TITLE
[Issue]: Beta stopped working

### ISSUE THREAD

**Issue by Herpgon** [SgtBatten/HA_blueprints#340]
### Description

So it seems the beta blueprint stopped working for me today.  I tested by creating a simple identical automation with the stable version and the beta version. The stable works and the beta does not.  I am using the beta primarily for the zone_order_enforced filter to only alert me when someone approaches my front door. 

Another note is that it appears that the beta automations are triggering even when nothing is happening on camera. I see that last triggered is always less than 5 minutes but I receive no notification.

 Let me know if there are any other details I can provide.

### Version

0.12.0.5c

### Automation Config

```yaml
alias: Person approaching front door
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_door
    notify_device: a89e808cd1d6f39700e220d27f29b20c
    base_url: https://home.mydomain.com
    zone_filter: true
    zones:
      - entryway
      - frontofdoor
    zone_multi: true
    zone_order_enforced: true
```

**Comment by SgtBatten** [comment]
> triggered is always less than 5 minutes but I receive no notification

triggered does not mean notification. it means object detected. 

Check the debug output

**Comment by Herpgon** [comment]
Frigate isn't detecting any objects at the time.  I enabled debugging and read your guide but I am still a bit confused on how to read the log to get a better indication of what is going on.  To me it looks like it just gets to an early step and then it stops.
![Screenshot 2025-01-10 193437](https://github.com/user-attachments/assets/2c8bcde9-962d-4f72-8c0e-1f7cfc4a38f4)

**Comment by SgtBatten** [comment]
I mean, it did though because it sent an mqtt message. 

Click the top asterix (right one) and go to changed variables to see the mqtt message. 

Click the square on row 5 (again right one because it's the main path) to see what condition was false

**Comment by Herpgon** [comment]
So I created 2 automations exactly the same. 1 stable and 1 for beta.

### Stable:
```
alias: 0.12.0.4e TEST
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.front_room
    notify_device: a89e808cd1d6f39700e220d27f29b20c
    base_url: https://<domain>
    zone_filter: true
    zones:
      - kitchen
```
<img width="584" alt="0 12 0 4e_working" src="https://github.com/user-attachments/assets/d31853d2-dca4-474a-86ac-b8ea6ba64bdc" />

### Beta:
```
alias: 0.12.0.5c
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_room
    notify_device: a89e808cd1d6f39700e220d27f29b20c
    base_url: https://<domain>
    zone_filter: true
    zones:
      - kitchen
```
<img width="536" alt="Screenshot 2025-01-10 235604" src="https://github.com/user-attachments/assets/d50b7915-40ad-4ec5-8148-e455d6706905" />


The stable blueprint works properly.  Could it be related to the payload parameter in the step config of the beta blueprint automation being only new and not specifying a camera?

**Comment by Herpgon** [comment]
I realized that you updated both of the blueprints and I have added both into home assistant and now both version are producing the same problem.

**Comment by SgtBatten** [comment]
Yeah I broke something today but the current issue doesn't give any partial trace. 

Yours is a partial trace

**Comment by Herpgon** [comment]
I just tested with version 0.14.0.2o and it seems like its working again.  There is quite a delay for the zone order enforcing filter though. 

![Image](https://github.com/user-attachments/assets/25f6ff23-57d6-49b6-abe7-3a9c03e6dc4e)

**Comment by SgtBatten** [comment]
We are reliant on mqtt updates from frigate which seem very rare. I rarely ever see any type other than new and end meaning it does indeed take a longer time to get updates. 

What was this event like in order to get updates?

**Comment by Herpgon** [comment]
I'm not sure I understand the question.  If you are asking what I am trying to accomplish I just set up a quick test on a camera with 2 zones. I walk from one zone to the other in order I specified and want to receive a notification.  

I have a question about the mqtt_topic.  I see you are setting it to frigate/reviews but when I use MQTT explorer I don't see that topic. Just frigate/events and the camera names.  Is this supposed to be frigate/events?

Below is my blueprint config.  

```
id: '1737232433926'
alias: Frigate Notifications (0.14.0.2o)
description: ''
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ''
    camera:
      - camera.front_room
    review_severity: alert
    notify_device: a89e808cd1d6f39700e220d27f29b20c
    base_url:
    zone_filter: true
    zones:
      - kitchen
      - stairs
    zone_multi: true
    zone_order_enforced: true
    debug: true
    mqtt_topic: frigate/reviews
```

I really appreciate your hard work on this blueprint. Thanks for helping troubleshoot.

**Comment by SgtBatten** [comment]
Frigate reviews is new as if frigate version 0.14 and provides better event tuning. Going forward th ebkueoront won't work with events. I mean maybe again one day but it's not the plan. 

My question was asking what was happening in that detection, because you got more than one mqtt message in the loop which I am finding extremely rare in the reviews topic. In fact, you had 2 updates which I've never seen. So I wanted to know what the video is about.

**Comment by Herpgon** [comment]
I just walked from one end of the room to the other. (Zone kitchen to zone stairs). No one else in the frame. Here is the frigate config for the camera. I wonder if its because I have alerts and detections enabled for it which after reading the frigate docs seems to be redundant. 
  ```
front_room:
    ui:
      order: 3
    enabled: true
    detect:
      enabled: true
      width: 1920
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_room
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion: {}
    zones:
      stairs:
        coordinates: 
          0.207,0.011,0.151,0.395,0.141,0.739,0.208,0.852,0.264,0.847,0.36,0.745,0.436,0.54,0.462,0.278,0.461,0.1,0.441,0.014
        loitering_time: 0
      kitchen:
        coordinates: 
          0.69,0.177,0.608,0.465,0.621,0.673,0.772,0.708,0.836,0.628,0.836,0.32,0.806,0.191
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - kitchen
          - stairs
      detections:
        required_zones:
          - kitchen
          - stairs
```
