### ISSUE TITLE
Error on executing blueprint

### ISSUE THREAD

**Issue by B0ndo2** [SgtBatten/HA_blueprints#343]
### Description

```
Something unexpected happened
Executed: January 12, 2025 at 9:32:45 PM
Error: UndefinedError: 'dict object' has no attribute 'frame_time'
Result:

choice: 2
```

Also the variable label is ignored in the message for some reason (see second screenshot) 
Import link for 0.14 is invalid

![image](https://github.com/user-attachments/assets/a8e1f256-e6a5-4137-a4e6-10beeea6f094)
![image](https://github.com/user-attachments/assets/28a74ced-eb97-4ab9-a983-d679d9b7b525)

### Version

0.12.0.4e

### Automation Config

```yaml
alias: Person on driveway
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.driveway
    notify_device: ce4b49d257102751164b07a42d966233
    labels: []
    mqtt_topic: frigate/reviews
    debug: true
    update_sub_label: false
    message: " A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the {{ camera_name }} camera."
    attachment: snapshot.jpg
```
```


### Frigate Config

_No response_

### Any other relevant information

_No response_
