### ISSUE TITLE
[Issue]: Face recognition does not work with version 0.14.0.2j 

### ISSUE THREAD

**Issue by stalakerob** [SgtBatten/HA_blueprints#345]
### Description

When using the blueprint v 0.14.0.2j  {{label}} is not replaced by the person detected by double take. When using BP v 0.12.0.6 this works fine. Using frigate version 0.14.1-f4f3cfa and frigate integration for HA v 5.7.0 and an Samsung Galaxy Android smart phone.

The Frigate review MQTT message seems to contain the correct data:

`{
  "type": "end",
  "before": {
    "id": "1736949049.723856-sedbtx",
    "camera": "WZ_Cam",
    "start_time": 1736949049.723856,
    "end_time": null,
    "severity": "alert",
    "thumb_path": "/media/frigate/clips/review/thumb-WZ_Cam-1736949049.723856-sedbtx.webp",
    "data": {
      "detections": [
        "1736949002.725292-ed1vbb",
        "1736948553.725394-3deu5u"
      ],
      "objects": [
        "person-verified",
        "person"
      ],
      "sub_labels": [
        "robert"
      ],
      "zones": [],
      "audio": []
    }
  },
  "after": {
    "id": "1736949049.723856-sedbtx",
    "camera": "WZ_Cam",
    "start_time": 1736949049.723856,
    "end_time": 1736949148.751695,
    "severity": "alert",
    "thumb_path": "/media/frigate/clips/review/thumb-WZ_Cam-1736949049.723856-sedbtx.webp",
    "data": {
      "detections": [
        "1736949002.725292-ed1vbb",
        "1736948553.725394-3deu5u"
      ],
      "objects": [
        "person-verified",
        "person"
      ],
      "sub_labels": [
        "robert"
      ],
      "zones": [],
      "audio": []
    }
  }
}`

### Version

0.14.0.2j 

### Automation Config

```yaml
- id: '1736940798700'
  alias: Frigate Cams Notifications 0.14
  description: ''
  use_blueprint:
    path: SgtBatten/Beta-0-14-0-2j.yaml
    input:
      presence_filter:
      - ''
      notify_device: e6c82b15ba65685f396d41bea44cbf5a
      base_url: https://xxxxxxxxxxxxxx.yyyyyy.zzz:8123
      message: '{{ label }} wurde von {{ camera }} erkannt'
      camera:
      - camera.carport_cam
      - camera.garten_cam2
      - camera.garten_cam
      - camera.wz_cam
      video: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4'
      attachment: snapshot.jpg?bbox=1
      android_auto: true
      sticky: true
      custom_filter: '{{ is_state(''input_boolean.cam_alarm_notifications'',''on'')
        and (is_state(''input_boolean.home_precense'', ''off'') or is_state(''input_boolean.frigate_cam_alarms_override'',
        ''on'') or is_state(''input_boolean.surveillance_time'',''on'')) }}'
```
