### ISSUE TITLE
[Config Support]: Shared Cooldown for all Blueprint automations created

### ISSUE THREAD

**Issue by RyanPieters** [SgtBatten/HA_blueprints#348]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,

I seem to be having trouble getting two notifications popping off at once. I did some trial and error and it very much seems that the "cooldown" within the UI is shared across all automations that I create.

I had a look in source and it looked like a name could be assigned for each cooldown. I tried that, but alas, I got the same result.

Testing:
I have two cameras and have set up an automation for each of them, notifying a device on a 30 second cooldown.

Running like a lunatic between the cameras, I immediately get the notification for the first, but it seems the second one only arrives 30 seconds later, even though they are two separate cameras on two separate automations.

I hope the above makes sense, and I appreciate any assistance on the matter.

### Version

0.12.0.6

### Automation config

```yaml
##Front Yard One
description: ""
alias: Frigate Notifications (0.12.0.6)
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_yard_1
    notify_device: xxx19f46e5d6xxxba8fxxxd41ebfxxxx ##Hidden some chars
    cooldown: 30

##FY2 is duplicated, with only camera being updated.
```

### Frigate Config

```yaml

```
