### ISSUE TITLE
[Feature Request]: Is it possible to add audio only review/event to trigger notification? Frigate 0.14 blueprint

### ISSUE THREAD

**Issue by longhtran91** [SgtBatten/HA_blueprints#355]
**Describe what you are trying to accomplish and why in non technical terms**
I have a camera that's used for watching the bassinet and I only configured it for crying detection. The crying detection is labeled as alert in Frigate 0.14. I want to be notified when there are alerts of this camera (crying detection only) . Here is the camera
```
  baby_bassinet:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/baby_bassinet
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
    motion:
      mask:
        - 1374,55,1868,55,1868,22,1374,22
    review:
      alerts:
        labels:
          - crying
    audio:
      min_volume: 600
      listen:
        - crying
      filters:
        crying:
          threshold: 0.8 #no min_score
    objects:
      track: [] 
```

Here is an example of the event in mqtt
```
{
    "type": "end",
    "before": {
        "id": "1737757739.861891-zmzexc",
        "camera": "baby_bassinet",
        "start_time": 1737757739.861891,
        "end_time": null,
        "severity": "alert",
        "thumb_path": "/media/frigate/clips/review/thumb-baby_bassinet-1737757739.861891-zmzexc.webp",
        "data": {
            "detections": [],
            "objects": [],
            "sub_labels": [],
            "zones": [],
            "audio": [
                "crying"
            ]
        }
    },
    "after": {
        "id": "1737757739.861891-zmzexc",
        "camera": "baby_bassinet",
        "start_time": 1737757739.861891,
        "end_time": 1737757742.569357,
        "severity": "alert",
        "thumb_path": "/media/frigate/clips/review/thumb-baby_bassinet-1737757739.861891-zmzexc.webp",
        "data": {
            "detections": [],
            "objects": [],
            "sub_labels": [],
            "zones": [],
            "audio": [
                "crying"
            ]
        }
    }
}
```

Here is my current configuration in the blueprint
```
alias: Baby Bassinet Crying 0.14
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.baby_bassinet
    notify_device: d50ae4e1f1351cd252adbc2379819954
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/event_preview.gif
    review_severity:
      - alert
    attachment_2: ""
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_3: /ui-lovelace-minimalist/cctv
    button_3: Open Home Assistant
    base_url: https://ha.domain.com
```
