### ISSUE TITLE
[Bug]: Notification is sent again and again even when "mute for x hours" is used

### ISSUE THREAD

**Issue by heisenberg2980** [SgtBatten/HA_blueprints#36]
### Description

I am not sure if this is due to some issue with my config, but every time I receive a notification with a false positive because Frigate considers something (e.g. a jacket in a chair) a person, the same notification keep coming again and again, even after I click the "mute for 2 hours".

I have confirmed the "mute for 2 hours" disables the automation, but after debugging it, it seems the issue is the blueprint contains a repeat loop that keep sending the notification again and again as the event (false person) is still there.

### Version

0.12.0.1

### Automation Config

```yaml
alias: Someone detected in Kitchen
description: ""
use_blueprint:
  path: SgtBatten/frigate_notification.yaml
  input:
    tv_transparency: 0%
    camera: camera.dahua_6
    notify_device: adc34abb277ac8cfb8227a9cdf8fcdaf
    alert_once: true
    update_thumbnail: true
    state_entity: alarm_control_panel.ha_alarm
    state_filter: true
    state_filter_states:
      - armed_night
      - armed_away
    cooldown: 300
    tv_size: large
    tv_position: center
    color: grey
    silence_timer: 120
    button_3: Silence 2hours
```
