### ISSUE TITLE
[Issue]: No camera vissible

### ISSUE THREAD

**Issue by aavosnl** [SgtBatten/HA_blueprints#362]
### Description

There are no camera's visible in the tab frigate entities . Frigate is running perfectly (three camera's)  

### Version

0.12.0.6

### Automation Config

```yaml
none
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: xxx.xxx.xxx.x
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: homeassistantfrigate
  password: ************
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args: preset-vaapi
objects:
  track:
    - person
    - dog
    - cat
    - car
    - bicycle
    - motorcycle
cameras:
  SchuurAchter:
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@xxx.xxx.xxx.x
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
      stationary:
        interval: 1
        threshold: 50
    record: # <----- Enable recording
      enabled: true

      retain:
        days: 1
      events:
        retain:
          default: 1
    motion: {}
    zones:
      platte_dak_achterzijde:
        coordinates: 
          0.247,0.423,0.463,0.429,0.464,0.405,0.659,0.415,0.655,0.233,0.455,0.225,0.246,0.228
        loitering_time: 0
        objects: person
        inertia: 3
      raam-muur-bijkeuken:
        coordinates: 0.464,0.409,0.668,0.418,0.669,0.567,0.669,0.806,0.46,0.817,0.464,0.49
        loitering_time: 0
        inertia: 3
        objects: person
      tuindeuren_achterzijde:
        coordinates: 0.266,0.457,0.45,0.463,0.444,0.756,0.295,0.746,0.265,0.746
        loitering_time: 0
        inertia: 3
        objects: person
      Dakkapel_achterzijde:
        coordinates: 0.329,0.181,0.57,0.185,0.57,0,0.329,0
        loitering_time: 0
        objects: person
    objects:
      filters:
        person:
          mask: 
            0.002,0.996,0.003,0.73,0.172,0.664,0.189,0.56,0.251,0.548,0.253,0.425,0.249,0.229,0.248,0.005,0.644,0.004,0.654,0.232,0.675,0.426,0.841,0.518,0.957,0.583,0.997,0.613,0.999,0.997,0.512,0.99
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true

    review:
      alerts: {}
  Achterzijde1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@xxx.xxx.xxx.x
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 1
      events:
        retain:
          default: 1
    motion:
      threshold: 30
      contour_area: 20
      improve_contrast: 'true'
    zones:
      achtertuin:
        coordinates: 0.004,0.781,0.123,0.818,0.347,0.38,0.649,0.406,0.698,0.997,0.004,0.995
        loitering_time: 0
        objects: person
    objects:
      filters:
        person:
          mask: 0.004,0.781,0.122,0.823,0.348,0.381,0.647,0.408,0.698,0.997,0.002,0.996
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true

    review:
      alerts: {}
  Voorzijde:
    ffmpeg:
      inputs:
        - path: rtsp://admin:******@xxx.xxx.xxx.x
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 720
    record: # <----- Enable recording
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 2
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: 'true'
    zones:
      Tuin_voorzijde:
        coordinates: 0.003,0.695,0.612,0.388,0.893,0.712,0.797,0.855,0.886,0.997,0.001,0.999
        loitering_time: 0
        objects:
          - person
          - dog
        inertia: 3
    objects:
      filters:
        person:
          mask: 0.002,0.676,0.553,0.408,0.859,0.758,0.799,0.856,0.888,0.997,0.003,0.999
        car:
          mask: 0.002,0.531,0.999,0.153,0.998,0.004,0.002,0.003
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true





    review:
      alerts: {}
      detections: {}
version: 0.14
camera_groups:
  alles:
    order: 1
    icon: LuAirVent
    cameras:
      - Achterzijde1
      - SchuurAchter
      - Voorzijde
```

### Any other relevant information

```yaml

```
