### ISSUE TITLE
[Issue]: Snapshot not displayed on IOS in stable version 0.14.0.2w

### ISSUE THREAD

**Issue by Kambara1** [SgtBatten/HA_blueprints#364]
### Description

![Image](https://github.com/user-attachments/assets/53d6bdcc-329f-4ba3-8514-971409e5c069)

Currently I have no preview snapshot in the latest stable release (0.14.0.2w) on IOS. Same config works in version 0.12.0.6 which I'm currently using.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: deurbel_detect
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera:
      - camera.voordeur
    notify_device: REDACTED
    tap_action: /lovelace/front-door
    icon: mdi:doorbell-video
    title: Bewegingsalarm - Deurbel
    attachment: snapshot.jpg
    url_2: custom-{{ this.entity_id }}
    button_2: Oprit verlichting
    notify_group: all_phones
    message: >-
      A {{ label | lower }} {{ 'is loitering' if loitering else 'was detected'
      }} on the {{ camera_name | lower }} camera -
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}.
    url_1: /lovelace/front-door
    button_1: Open Home Assistant
    custom_action_manual:
      - action: script.oprit_lights
        data: {}
    debug: false
    presence_filter:
      - ""
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
