### ISSUE TITLE
[Config Support]: Unable to view notification clips/snapshots remotely (Nabu Casa)

### ISSUE THREAD

**Issue by petercoxphoto** [SgtBatten/HA_blueprints#369]
### Describe the problem you are having or the outcome you are trying to achieve.

I'm using the Nabu Casa remote access for HA, and Frigate is installed on a separate machine. I'm unable to view media associated with notifications through this blueprint as HA is not exposed to the internet directly, so the base URL only works locally.

As all the media for these events is stored in the HA Media section, is there no way to use that through the Nabu Casa system to make them available remotely?

### Version

0.14.0.2w

### Automation config

```yaml
alias: Frigate Notifications
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.driveway
      - camera.front_door
      - camera.north_field
      - camera.observatory
      - camera.side_door
    notify_device: 30bb8a42491f1d1a3a35745669647132
    base_url: http://homeassistant.lab
    alert_once: true
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    final_update: false
```

### Frigate Config

```yaml

```
