### ISSUE TITLE
custon action not working

### ISSUE THREAD

**Issue by kiloptero** [SgtBatten/HA_blueprints#372]
### Description

go directly to the ha app. 

### Version

0.14.0.2.w

### Automation Config

```yaml
just testing a message


alias: frigate not
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.comedero
      - camera.entradacasasub
      - camera.lenovopieza
      - camera.reolinkduo21
    notify_device: 0f9bb4768279fe312ad33b1b2b6c462b
    base_url: https://url. myhouse
    message: >-
      {{ label }}{{ ' was' if type == 'end' else '' }} detected on the {{
      camera_name }} camera{{' in the ' if after_zones|length}}{{ after_zones |
      join(', ') | replace('_', ' ' ) | title }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}.
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/thumbnail.jpg"
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    button_1: View snapshop
    button_2: view video
    url_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_3: custom-{{ this.entity_id }}
    button_3: custom action
    custom_action_manual:
      - action: notify.mobile_app_iphoneandres
        metadata: {}
        data:
          message: hola
    icon_1: sfsymbols:photo
    icon_2: sfsymbols:video
    icon_3: sfsymbols:text
    attachment_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
