### ISSUE TITLE
[Config Support]: Nothing is Triggering

### ISSUE THREAD

**Issue by CommittotheIndian** [SgtBatten/HA_blueprints#375]
### Describe the problem you are having or the outcome you are trying to achieve.

I believe I've set everything up according to the instructions but nothing is triggering. I can't use the [Help Me Help You](https://github.com/SgtBatten/HA_blueprints/issues/351)  because it never triggers at all.

I've gone with the most basic blueprint, still doesn't work.
I've tested an automation just listening to the mqtt topic- frigate to basically send a test message, it works.

According to MQTT explorer, Frigate (on a separate server) is sending out MQTT just fine. The camera and all attributes are in HA via the integration & proxy.

The only bottleneck I'm hitting right now is the blueprint.

I'm out of ideas.

I understand this says Driveway, but the sidewalk zone is part of Doorbell and the Doorbell camera is further up in the tree, I didn't get a pic for.
![Image](https://github.com/user-attachments/assets/1e54de2a-dcd6-4976-b14d-641d22e50b2a)

![Image](https://github.com/user-attachments/assets/16e33e95-f7c6-43d3-b9b9-f34ed2e3d246)

![Image](https://github.com/user-attachments/assets/28716cc0-c86d-41e4-8c2f-9fa07b00442c)

### Version

(0.14.0.2w)

### Automation config

```yaml
alias: Frigate Test
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.doorbell
    notify_device: eebc60cb22d8f30f8c93b6f982cd6693
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/thumbnail.jpg"
    debug: true
    review_severity:
      - alert
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 10.10.10.10
  port: 1883
  user: ***
  password: *****


detectors:
  coral:
    type: edgetpu
    device: usb #pc1 after the switch

go2rtc:
  streams:
    doorbell:
      - ffmpeg:http://10.200.200.158/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=****&password=****#video=copy#audio=copy#audio=opus
      #- rtsp://10.200.200.158/Preview_01_sub
    doorbell_sub:
      - ffmpeg:http://10.200.200.158/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=****&password=****
  ffmpeg:
    bin: ffmpeg
    volume: -af "volume=30dB"


cameras:
  doorbell: # <--- this will be changed to your actual camera later
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://****:****@10.200.200.158:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
    motion:
      threshold: 25
    zones:
      sidewalk_zone:
        coordinates: 
          0.026,0.262,0.208,0.3,0.201,0.616,0.289,0.594,0.33,0.295,0.677,0.284,0.714,0.64,0.807,0.629,0.825,0.625,0.916,0.623,0.924,0.672,0.922,0.757,0.894,0.816,0.806,0.8,0.768,0.995,0.119,0.999,0.022,0.766
        inertia: 3
        loitering_time: 0
        objects: person
    snapshots:
      enabled: true
      retain:
        default: 2

    review:
      alerts: {}
  driveway: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps
          1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
      inputs:
        - path: rtsp://****:****@10.200.200.30/H264/ch1/sub/av_stream # <----- Update for your camera
          roles:
            - detect
    detect:
      width: 640 # <- optional, by default Frigate tries to automatically detect resolution
      height: 480 # <- optional, by default Frigate tries to automatically detect resolution
      fps: 10
      stationary:
        interval: 50
        threshold: 50
    objects:
      track:
        - person
        - car
        - bicycle
    zones:
      driveway_zone:
        coordinates: 
          0.12,0.292,0.196,0.243,0.245,0.241,0.319,0.242,0.402,0.258,0.467,0.265,0.535,0.273,0.583,0.281,0.627,0.295,0.718,0.318,0.77,0.328,0.852,0.357,0.886,0.377,0.964,0.411,1,0.564,1,0.763,1,0.867,1,1,0.778,0.999,0.812,0.805,0.388,0.523,0.204,0.377,0.095,0.436,0.051,0.361
        inertia: 3
        loitering_time: 0
        objects:
          - person
      just_driveway:
        coordinates: 0.321,0.238,0.574,0.273,0.387,0.511,0.205,0.381,0.257,0.302
        loitering_time: 0
        objects:
          - car
          - bicycle
    snapshots:
      enabled: true
      retain:
        default: 2
    motion:
      mask: 
        0.041,0.325,0.075,0.298,0.139,0.248,0.181,0.222,0.245,0.212,0.31,0.205,0.374,0.202,0.488,0.212,0.6,0.232,0.647,0.247,0.681,0.25,0.808,0.286,0.92,0.335,0.966,0.401,0.997,0.406,0.998,0.001,0,0.001,0,0.342
    review:
      alerts:
        required_zones: driveway_zone
version: 0.14
```
