### ISSUE TITLE
[Issue]: Notifications are missing message text on Android

### ISSUE THREAD

**Issue by jakepi84** [SgtBatten/HA_blueprints#376]
### Description

This appears to have started in the last 48 hours, since 2/7/25, and I am not sure what triggered it. The notifications do not seem to have message text anymore. I get a preview image and action buttons, grouping is working, but the message is blank on the device. This is happening on two different Android devices. I am really stuck scratching my head on this one. The logbook shows that the notification does have data in the message field.

Other automatons, with notifications, do show message text.

I have tried using both stable and beta blueprint. This was happening with Frigate v0.15-rc2 and updated this morning to v0.15, both have the same result. My Frigate HACS integration is v5.7.0. I have also checked my MQTT logs, nothing seems out of sort there either.

### Version

0.14.0.3e

### Automation Config

```yaml
alias: Indoor Frigate Notifications
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.livingroom_cam
      - camera.kitchen_cam
      - camera.garage_cam
    base_url: https://homeassistant.jakepi.net
    notify_device: 0e641a5e815acb02af723b175608885c
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.4.253
  user: mqueue
  password: <REDACTED>

tls:
  enabled: false

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h264

detectors:
  ov:
    type: openvino
    device: GPU

objects:
  track:
    - car
    - person
    - dog
    - cat
    - bird
    - horse
    - face
    - license_plate
    - amazon
    - fedex
    - ups
    - package
    - mouse
    - bear


model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 10
detect:
  enabled: true
  width: 1920
  height: 1080
  #stationary:
  #  interval: 100
  #  threshold: 20
audio: # <- enable audio events for all camera
  enabled: true
  listen:
    - bark
    - fire_alarm
    - scream
    - yell

review:
  alerts:
    labels:
      - cat
      - dog
      - person
      - car
      - package
      - bird
      - mouse
      - horse
      - bear
      - fire_alarm

go2rtc:
  streams:
    Driveway_Cam:
      - rtsp://drivewaycam.local.iot:8554/1080p?mp4
      - ffmpeg:Driveway_Cam#audio=aac
    Frontyard_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@frontyardcam.local.iot/stream1
      - ffmpeg:Frontyard_Cam#audio=aac
    Kitchen_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@kitchencam.local.iot/stream1
      - ffmpeg:Kitchen_Cam#audio=aac
    Garage_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@garagecam.local.iot/stream1
      - ffmpeg:Garage_Cam#audio=aac
    Backdoor_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@backdoorcam.local.iot/stream1
      - ffmpeg:Backdoor_Cam#audio=aac
    Backyard_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@backyardcam.local.iot/stream1
      - ffmpeg:Backyard_Cam#audio=aac
    Doorbell_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@doorbellcam.local.iot/stream1
      - ffmpeg:Doorbell_Cam#audio=aac
    Driveway_Cam_Sub:
      - rtsp://drivewaycam.local.iot:8554/360p?mp4
      - ffmpeg:Driveway_Cam_Sub#audio=aac
    Frontyard_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@frontyardcam.local.iot/stream2
      - ffmpeg:Frontyard_Cam_Sub#audio=aac
    Kitchen_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@kitchencam.local.iot/stream2
      - ffmpeg:Kitchen_Cam_Sub#audio=aac
    Garage_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@garagecam.local.iot/stream2
      - ffmpeg:Garage_Cam_Sub#audio=aac
    Backdoor_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@backdoorcam.local.iot/stream2
      - ffmpeg:Backdoor_Cam_Sub#audio=aac
    Backyard_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@backyardcam.local.iot/stream2
      - ffmpeg:Backyard_Cam_Sub#audio=aac
    Doorbell_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@doorbellcam.local.iot/stream2
      - ffmpeg:Doorbell_Cam_Sub#audio=aac
    Livingroom_Cam:
      - rtsp://rtsplocal:zoNpRtphiE@livingroomcam.local.iot/stream1
      - ffmpeg:Livingroom_Cam#audio=aac
    Livingroom_Cam_Sub:
      - rtsp://rtsplocal:zoNpRtphiE@livingroomcam.local.iot/stream2
      - ffmpeg:Livingroom_Cam_Sub#audio=aac

cameras:
  Frontyard_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Frontyard_Cam
          roles:
            - record
            - audio
            - detect
    zones:
      Road_Out_Front:
        coordinates: 
          0.071,0.116,0.225,0.093,0.371,0.08,0.519,0.086,0.622,0.093,0.78,0.125,0.9,0.166,1,0.213,0.998,0.003,0.001,0.002,0.002,0.147
        loitering_time: 0
        inertia: 3
      Front_Yard:
        coordinates: 
          1,0.208,0.734,0.114,0.603,0.09,0.457,0.078,0.301,0.083,0.149,0.101,0.067,0.114,0.001,0.147,0,1,1,1
        loitering_time: 0
        inertia: 3
        objects:
          - bear
          - bird
          - cat
          - dog
          - horse
          - mouse
          - package
          - person
    motion:
      threshold: 45
      contour_area: 20
      improve_contrast: true
    review:
      alerts:
        required_zones: Front_Yard
  Driveway_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Driveway_Cam
          roles:
            - record
            - audio
            - detect
    zones: {}
    motion:
      threshold: 50
      contour_area: 25
      improve_contrast: true
      lightning_threshold: 0.6
  Kitchen_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Kitchen_Cam
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
  Livingroom_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Livingroom_Cam
          roles:
            - record
            - detect
            - audio
    objects:
      track:
        - person
      filters:
        person:
          mask: 1,0.637,0.87,0.586,0.828,0.53,0.691,0.586,0.626,0.718,0.611,0.861,0.622,1,1,1
    motion:
      mask: 
        0.154,0,0.119,0.098,0.087,0.176,0.169,0.161,0.247,0.14,0.299,0.083,0.326,0,0.326,-0.005
      threshold: 35
      contour_area: 10
      improve_contrast: true
  Garage_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Garage_Cam
          roles:
            - record
            - audio
            - detect
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask:
            - 0.047,0.036,0.11,0.057,0.131,0.171,0.105,0.275,0.029,0.326,0.006,0.181
            - 0.916,0.513,0.837,0.611,0.797,0.803,0.837,0.933,0.913,0.922,1,0.793,1,0.793
  Backdoor_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Backdoor_Cam
          roles:
            - record
            - audio
            - detect
    motion: {}
  Backyard_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Backyard_Cam
          roles:
            - record
            - audio
            - detect
    objects:
      filters:
        person:
          mask:
            - 0.991,0.622,0.898,0.637,0.863,0.746,0.858,0.922,0.933,0.927,0.985,0.912
            - 0.07,0.388,0.154,0.341,0.236,0.416,0.295,0.447,0.274,0.613,0.193,0.671,0.129,0.625,0.096,0.611,0.06,0.57,0.048,0.465
        car:
          mask: 
            0.529,0.718,0.616,0.784,0.608,0.867,0.562,0.925,0.509,0.903,0.474,0.854,0.471,0.789
    motion:
      threshold: 25
      contour_area: 10
      improve_contrast: true
  Doorbell_Cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554:/Doorbell_Cam
          roles:
            - record
            - audio
            - detect
    motion:
      mask: 0.587,0.349,0.662,0.352,0.692,0.585,0.635,0.588,0.562,0.589
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - horse
        - face
        - amazon
        - package
        - mouse
        - bear
version: 0.15-1
camera_groups:
  Indoor:
    order: 1
    icon: LuHome
    cameras:
      - Kitchen_Cam
      - Garage_Cam
  Ourdoor:
    order: 2
    icon: LuTrees
    cameras:
      - Frontyard_Cam
      - Driveway_Cam
      - Backdoor_Cam
      - Doorbell_Cam
      - Backyard_Cam
semantic_search:
  enabled: true
  reindex: false
  model_size: small
notifications:
  enabled: 'true'
  email: <REDACTED>
```

### Any other relevant information

```yaml
Logbook Entry from Trace:

Frigate Notification DEBUG: Info: FPS: 5, Frigate Review id: 1739115436.244735-mz2o1g, Frigate Detections: ['1739115281.850476-kaqnx8'] Objects: Person, Sub Labels: Config: Camera(formatted): Livingroom_Cam(Livingroom Cam), Base URL: REDACTED, Critical: False, TTS: False TTS Helper: N/A, Alert Once: False, Final_Update (delay): False (5)s, Attachment: REDACTED/api/frigate/notifications/1739115281.850476-kaqnx8/thumbnail.jpg Video: , iOS URL: REDACTED/api/frigate/notifications/1739115281.850476-kaqnx8/thumbnail.jpg Target: Mobile Device, Cooldown: 0s, Initial Delay: 0s, Color: #03a9f4, Sound: default, Volume: 1.0 IOS Live entity: "" Android Auto: False, Tag: 1739115281.850476-kaqnx8, Group: Livingroom_Cam-frigate-notification, Channel: , Sticky: False, Title: , Message: A Person was detected on the Livingroom Cam camera., Subtitle: , Tap Action: REDACTED/api/frigate/notifications/1739115281.850476-kaqnx8/Livingroom_Cam/clip.mp4, Action Button 1 Text/URL/Icon: View Clip (REDACTED/api/frigate/notifications/1739115281.850476-kaqnx8/Livingroom_Cam/clip.mp4) , Action Button 2 Text/URL/Icon: View Snapshot (REDACTED/api/frigate/notifications/1739115281.850476-kaqnx8/snapshot.jpg) , Action Button 3 Text/URL/Icon: Silence New Notifications (silence- ) , Icon: mdi:homeassistant TV: False, Position: center, Size: large, Duration: 10, Transparency: 0%, TV Interrupt: False, Telegram: False, Telegram_chat_id: , Filters: Severity: Required Severity: ['alert', 'detection'], TEST: PASS - alert Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Entered Zones: [], TEST: PASS , Required objects: Input: , TEST: PASS - ['person'] presence entity (not home): Entity: [''] TEST: PASS, disabled times: [], State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: True triggered by automation
mqtt topic frigate/reviews
9:37:16 AM - 5 minutes ago
```
