### ISSUE TITLE
[Issue]: Silence Action Not Triggering Automation

### ISSUE THREAD

**Issue by saucedge** [SgtBatten/HA_blueprints#378]
### Description

A notification is generated as expected and sent to my Android phone.  When I click the Silence action, I see an event fired in Home Assistant as expected:

```
event_type: mobile_app_notification_action
data:
  action_2_title: View Snapshot
  subject: ""
  notification_icon: mdi:homeassistant
  car_ui: "false"
  action_3_title: Silence New Notifications
  sticky: "false"
  tag: 1739567697.111714-vvdtck
  color: "#03a9f4"
  group: doorbell-frigate-notification
  image: /api/frigate/notifications/1739567697.111714-vvdtck/thumbnail.jpg
  video: ""
  webhook_id: 9315bc036401edd2ca2d86174c20ded2e0a34fd973f1d8e200a0d0bad06049b7
  channel: ""
  clickAction: /api/frigate/notifications/1739567697.111714-vvdtck/doorbell/clip.mp4
  message: A Person was detected on the Doorbell camera.
  action_1_title: View Clip
  action_1_key: URI
  action_1_uri: /api/frigate/notifications/1739567697.111714-vvdtck/doorbell/clip.mp4
  action_2_key: URI
  action_2_uri: /api/frigate/notifications/1739567697.111714-vvdtck/snapshot.jpg
  action_3_key: silence-automation.frigate_doorbell_notifications
  action_3_uri: silence-automation.frigate_doorbell_notifications
  server_id: "1"
  action: silence-automation.frigate_doorbell_notifications
  device_id: 27325ab62930ad1e
origin: REMOTE
time_fired: "2025-02-14T21:17:02.064235+00:00"
context:
  id: 01JM354X7GPXK8QCWYQCJ9VVBG
  parent_id: null
  user_id: 69619b5c259745109b0a904889a29989
```
But, the automation is not turned off and there are no traces logged for the automation.  I've been ignoring this behavior for a while but I think it's been going on for multiple versions.  Let me know what additional info I can provide--thanks!

### Version

0.14.0.3e

### Automation Config

```yaml
alias: Frigate Doorbell Notifications
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.doorbell
    notify_device: 12b5dfa06357eae5e6e1aae820bf8580
    notify_group: parents
    review_severity:
      - alert
    custom_filter: >-
      {{ (states.binary_sensor.front_screen_door_contact_3.last_changed < (
      now() - timedelta(minutes=2))) and
      is_state("binary_sensor.front_screen_door_contact_3", "off") and
      is_state("input_boolean.disable_security_alerts", "off")}}
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
