### ISSUE TITLE
[Config Support]: Failed to load attachment Unrecognized attachment file type

### ISSUE THREAD

**Issue by mason-wheeler** [SgtBatten/HA_blueprints#379]
![Image](https://github.com/user-attachments/assets/e82618c3-d593-45d6-9e0a-7886e72da596)

### Describe the problem you are having or the outcome you are trying to achieve.

Hello! I am running into an issue where any attachment is showing up as an unrecognized file type (see screenshot). When I first installed and setup the notification it was working but now it isn't. Not sure if its a bug or if its a config issue. Any help would be much appreciated. I did enable debug and took the filepath of the attachment and put it in the browser URL and I am able to pull it up without issue, also able to make a simple automation that I can manually trigger to push the attachment in a notification and I am able to view again without issue. 

### Version

0.14.0.2w

### Automation config

```yaml
alias: "Object Dectected"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.back_door
      - camera.front_door
      - camera.back_yard
    notify_device: {device_id}
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg
    icon: mdi:cctv
    title: "{{ label }} Detected at {{camera_name}}"
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    cooldown: 120
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    final_update: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    silence_timer: 60
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    debug: true
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: {IP}
  user: {USER}
  password: {PW}

go2rtc:
  streams:
    back_yard: 
      rtsp://admin:{PW}@192.168.68.170:554/cam/realmonitor?channel=1&subtype=0
    back_yard_sub: 
      rtsp://admin:{PW}@192.168.68.170:554/cam/realmonitor?channel=1&subtype=1
    back_door: 
      rtsp://admin:{PW}@192.168.68.171:554/cam/realmonitor?channel=1&subtype=0
    back_door_sub: 
      rtsp://admin:{PW}@192.168.68.171:554/cam/realmonitor?channel=1&subtype=1
    front_door: 
      rtsp://admin:{PW}@192.168.68.172:554/cam/realmonitor?channel=1&subtype=0
    front_door_sub: 
      rtsp://admin:{PW}@192.168.68.172:554/cam/realmonitor?channel=1&subtype=1


cameras:
  back_yard:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_yard # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_yard_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask:
        - 0,0.162,0.093,0.071,0.195,0,0,0
        - 1,0.132,0.831,0,1,0
  back_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/back_door # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_door_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    motion:
      mask: 0.886,0.315,0.91,0,1,0,1,0.473
  front_door:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_door_sub # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - detect



logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  # logs:
  #   frigate.event: debug

database:
  path: /config/frigate.db

snapshots:
  enabled: true
  retain:
    default: 30
    
record:
  enabled: true
  retain:
    days: 5
    mode: all
  alerts:
    retain:
      days: 15
  detections:
    retain:
      days: 15
objects:
  track:
    - person
    - dog
    - cat
   # -  car

detectors:
  coral:
    type: edgetpu
    device: usb

ui:
  time_format: browser

version: 0.15-1
semantic_search:
  enabled: false
  reindex: false
  model_size: small
```

### Any other information that may be helpful

I scrubbed user/passwords from config's.
