### ISSUE TITLE
[Config Support]: Changing Notification Icon

### ISSUE THREAD

**Issue by UeT-Fire** [SgtBatten/HA_blueprints#380]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,

I would like to change the notification icon, as it is actually shown as an option in the blueprint. But no matter which mdi icon I select there, I only get the Home Assistant icon when I get a notification. I use the latest Home Assistant app on an iPhone. Does this option only work on Android or do I have to set something specific?

You can actually display the clip as a subsequent attachment. Since the last update, it has also been optimized as an m3u8 for iOS. Thank you very much at this point, previously the clips no longer worked for me when I opened the clip via Safari.

But this final attachment doesn't work for me. Is it still a known problem?

Thank you in advance.

### Version

Frigate Notifications (0.14.0.2w)

### Automation config

```yaml
alias: Frigate Benachrichtigung auf Louis iPhone
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.doorbell
    notify_device: 6d958025ddf2c8f99ed175863f49e8c1
    base_url: https://smarthome.myurl.de
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    final_update: true
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    video: ""
    final_delay: 2
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    labels: []
    review_severity:
      - alert
    sound: Kill-Bill-Whistle.wav
    title: Frigate
```

### Frigate Config

```yaml

```
