### ISSUE TITLE
snapshots in notifications on iphone

### ISSUE THREAD

**Issue by Doriginal** [SgtBatten/HA_blueprints#383]
### Description

Hello,
Since the last update, I no longer receive snapshots in notifications on iphone

![Image](https://github.com/user-attachments/assets/d60a8f87-6b01-468d-8efe-00a8060e8856)

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Frigate Notifications Avant (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.tapo_avant
    notify_device: daaed97d453cc6f357441f63f56d8f03
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/thumbnail.jpg"
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8

```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```

**Comment by SgtBatten** [comment]
Enable debug. 

Copy the URLs from the debug output and test them on your computer or phone. 

I suggest you need to test the thumbnail and the review preview URLs which you have set for attachment and attachment 2

**Comment by Doriginal** [comment]
i have enable debug:

Frigate Notification DEBUG: Info: FPS: 5, Frigate Review id: 1740311879.754659-lgdb20, Frigate Detections: ['1740311879.152616-wtpva0'] Objects: Person, Sub Labels: Config: Camera(formatted): Tapo_Inter(Tapo Inter), Base URL: REDACTED, Critical: False, TTS: False TTS Helper: N/A, Alert Once: False, Final_Update (delay): True (5)s, Attachment: REDACTED/api/frigate/notifications/1740311879.754659-lgdb20/review_preview.gif Video: REDACTED/api/frigate/notifications/1740311879.152616-wtpva0/Tapo_Inter/master.m3u8, iOS URL: REDACTED/api/frigate/notifications/1740311879.152616-wtpva0/Tapo_Inter/master.m3u8 Target: Mobile Device, Cooldown: 0s, Initial Delay: 0s, Color: #03a9f4, Sound: default, Volume: 1.0 IOS Live entity: "" Android Auto: False, Tag: 1740311879.152616-wtpva0, Group: Tapo_Inter-frigate-notification, Channel: , Sticky: False, Title: Frigate, Message: Person detected - Tapo Inter at 12:57, Subtitle: , Tap Action: REDACTED/api/frigate/notifications/1740311879.152616-wtpva0/Tapo_Inter/clip.mp4, Action Button 1 Text/URL/Icon: View Clip (REDACTED/api/frigate/notifications/1740311879.152616-wtpva0/Tapo_Inter/clip.mp4) , Action Button 2 Text/URL/Icon: View Snapshot (REDACTED/api/frigate/notifications/1740311879.152616-wtpva0/snapshot.jpg) , Action Button 3 Text/URL/Icon: Silence New Notifications (silence- ) , Icon: mdi:homeassistant TV: False, Position: center, Size: large, Duration: 10, Transparency: 0%, TV Interrupt: False, Telegram: False, Telegram_chat_id: , Filters: Severity: Required Severity: ['alert', 'detection'], TEST: PASS - alert Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Entered Zones: [], TEST: PASS , Required objects: Input: , TEST: PASS - ['person'] presence entity (not home): Entity: [''] TEST: PASS, disabled times: [], State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: True déclenché par l'automatisation mqtt topic frigate/reviews

if i test the url: https://*********.fr:59999/api/frigate/notifications/1740311879.754659-lgdb20/review_preview.gif
The gif displays fine but not in the notification

**Comment by TiddlyWiddly** [comment]
Same here. URL works fine.

**Comment by nwish** [comment]
Are you guys running the latest Frigate dev branch with face recognition enabled?  I was having the same issues and I think it has something to do with Frigate not generating a review item until face recognition has run.  Once I disabled it on the Frigate side, I no longer had issues with notifications.

**Comment by SgtBatten** [comment]
Interesting. Please let me know.

**Comment by nwish** [comment]
> Would final update and a delay resolve this? At least temporarily

Not sure to be honest.  I still can’t get snapshots to load either way.  Only thing that actually loads in iOS is the Review GIF and it’s finicky at best for me.  Snapshots are producing a 404 error with absolutely no errors in any of my logs (HA, Frigate, reverse proxy)

**Comment by SgtBatten** [comment]
When you are testing the url are you using the right ID. Review gif and snapshot won't be the same ID. 

The options in the blueprint use the right one but if you are manually changing between them it won't work without adjusting that. 

Also, are you definitely saving snapshots?

**Comment by Doriginal** [comment]
Hello,
Today I started from scratch, I reinstalled the Blueprint 0.14.0.2w and recreated my automations.
Notifications always arrive without the images whatever the option selected Thumbnail, Snapshot, Snapshot with bounding box, Review GIF...

### Automation Debug

```
Frigate Notification DEBUG (in loop): Send Notification: True Info: Sub Label: [], Image: "/api/frigate/notifications/1740384469.569966-vg6u7l/review_preview.gif" Title: Frigate Message: Person detected - Tapo Inter at 09:07 iOS sound: Silent, Android Sound: enabled, iOS url: "/api/frigate/notifications/1740384467.811468-rrds28/Tapo_Inter/master.m3u8", Video: "/api/frigate/notifications/1740384467.811468-rrds28/Tapo_Inter/master.m3u8", Critical: False, TTS: False Triggers: New Snapshot: False (not functional with reviews) Severity Changed: False, Presence Changed: False, Object changed: False, Zones Changed: False, Sublabel changed: False, Final Update: True Conditions: Filters: Severity: Required Severity: ['alert', 'detection'] TEST: PASS - alert, Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Last Zones: 0 - [], New Zones: 0 - [], TEST: PASS , Object Filter: Input: , TEST: PASS - ['person'], Presence entity (not home): Entity: [''], TEST: PASS, Time Filter: Disabled times: [], TEST: PASS State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: PASS, déclenché par l'automatisation
mqtt topic frigate/reviews

```
If I put the url “https://********.fr:59999/api/frigate/notifications/1740384469.569966-vg6u7l/review_preview.gif” in the browser on my laptop or on safari on my iphone, the image is displayed correctly.

I also tested in Home Assistant to create an action in the development tool and the notification correctly displays the snapshot.

![Image](https://github.com/user-attachments/assets/4a45a28b-e13a-4a22-946c-75c9ee277c90)

![Image](https://github.com/user-attachments/assets/7bddb988-39f9-4fd7-b7d8-fe1c4a87bf54)

**Comment by Doriginal** [comment]
To continue testing and solve my problem, I created two automations below:

### Automation Config


```yaml
alias: "!Security_Frigate_Notifications Intérieur"
description: ""
triggers:
  - topic: frigate/reviews
    payload: alert
    value_template: "{{ value_json['after']['severity'] }}"
    trigger: mqtt
actions:
  - data:
      message: >-
        A {{trigger.payload_json["after"]["data"]["objects"] | sort | join(", ")
        | title}} was detected 1.
      data:
        image: >-
          https://********.fr:59999/api/frigate/notifications/{{trigger.payload_json["after"]["data"]["detections"][0]}}/thumbnail.jpg
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        entity_id: >-
          camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
          lower}}
    action: notify.mobile_app_doriphone_12
mode: single

```

### Automation Config


```yaml
alias: "!Frigate: Person Alerts Intérieur"
description: ""
triggers:
  - topic: frigate/reviews
    payload: "on"
    value_template: |-
      {{'on' if (
          value_json.type in ['new'] and 
          'person' in value_json.after.data.objects and 
          value_json.after.camera not in ['trail']
        ) else 'off'}}
    trigger: mqtt
actions:
  - action: notify.mobile_app_doriphone_12
    data:
      message: "{{trigger.payload_json.after.camera}} detected a person 2"
      data:
        image: >-
          https://******.fr:59999/api/frigate/notifications/{{trigger.payload_json.after.id}}/review_preview.gif
mode: single


```

Les deux automations fonctionnes et envois bien le GIF et le Thumbnail.

![Image](https://github.com/user-attachments/assets/28ccd25f-85bb-4fc9-bdfe-6d4fb4382cc7)
