### ISSUE TITLE
[Config Support]: No Snapshot, Clip, etc in Notifications - Possible Base URL Issue

### ISSUE THREAD

**Issue by bradarussell** [SgtBatten/HA_blueprints#384]
### Describe the problem you are having or the outcome you are trying to achieve.

I'm not able to get any of the media (snapshots, thumbnails, clips, etc) working, but the notifications come through to my device (Android).  When I copy and paste the URL from the home assistant logs they won't work.  Sometimes the error is Invalid Response and sometimes it's a 404 error.  It doesn't work whether I'm on my LAN or away using the remote URL.  I've tried changing the URL with all the ways I could access HA and none of them provide access to the files.

I can view the media through the HA Media browser.  But there's an authSig= parameter in the URL when I view them there.  I do have 'Enable the unauthenticated notification event proxy' checked in my Frigate integration.  I've tried the Base URL with several options, but whether it's the Nabu Casa URL, my personal domain, or the IP address when testing from inside the LAN, it doesn't work.

My setup is more separated than typical:

Home Assistant, accessible via:
- local IP:8123
- https://ha.mydomain.com
- Nabu Casa URL

Frigate
- LXC in Proxmox
- accessible internally from frigatelocal.mydomain.com
- accessible remotely from frigate.mydomain.com (with authentication)

MQTT Broker
- LXC in Proxmox
- I don't think this is the issue since the notification is firing and being received

I wasn't clear if the Base URL was for HA or Frigate if Frigate runs separately, but I'm pretty sure it's the HA URL now.

### Version

0.14.0.3e

### Automation config

```yaml
alias: Frigate Notifications (0.14.0.3e)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.doorbell2
    notify_device: 7412dfdc43dc629c477902e7998ac48a
    mqtt_topic: frigate/reviews
    base_url: https://myhomeassistantcloudurl.ui.nabu.casa
    title: Test Frigate
    alert_once: false
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    final_update: true
    zone_filter: true
    labels: []
    redacted: false
    debug: true
    zones:
      - street
      - driveway
      - yard
      - frontdoor
      - street2
      - Street2
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?crop=1
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
```

### Frigate Config

```yaml
tls:
  enabled: false

logger:
  default: debug
  logs:
    frigate.doorbell: error

mqtt:
  enabled: true
  host: 192.168.1.2
  port: 1883
  topic_prefix: frigate
  user: mosquitto
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

environment_vars:
  LIBVA_DRIVER_NAME: nvidia

birdseye:
  enabled: true
  mode: objects

ffmpeg:
  hwaccel_args: preset-nvidia
  output_args:
    record: preset-record-generic-audio-aac

go2rtc:
  frigate:
    hwaccel_args: preset-nvidia
  log:
    exec: trace
  streams:
    doorbell2:
      - ffmpeg:http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus
      - rtsp://192.168.1.3/Preview_01_sub
    doorbell2_sub:
      - ffmpeg:http://192.168.1.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password

cameras:
  doorbell2:
    ffmpeg:
      hwaccel_args: preset-nvidia
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell2
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/doorbell2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    record:
      enabled: true
      retain:
        days: 3
        mode: all
      alerts:
        retain:
          days: 31
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 3
    snapshots:
      enabled: true
      crop: true
      quality: 90
      bounding_box: false
      required_zones:
        - Street2
        - frontdoor
      retain:
        default: 90
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bicycle
      filters:
        car:
          mask:
            - 0.611,0.536,0.328,0.508,0.333,0.316,0.585,0.304
            - 0.438,0.564,0.294,0.518,0.211,0.462,0.084,0.463,0.073,0.592,0.085,0.665,0.232,0.667,0.29,0.648
        person:
          mask: 0.521,0.534,0.52,0.567,0.505,0.567,0.507,0.534
    motion:
      mask:
        - 0.726,0,0.239,0,0.24,0.069,0.597,0.068,0.727,0.067
        - 0.051,0.605,0.092,0.864,0.139,0.848,0.193,0.73,0.286,0.656,0.305,0.618,0.268,0.561,0.229,0.504,0.184,0.518,0.118,0.505,0.05,0.483
        - 0.621,0.242,0.585,0.242,0.58,0.355,0.578,0.409,0.626,0.438
        - 0.095,0.084,0.129,0.112,0.122,0.27,0.056,0.248
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      frontdoor:
        coordinates: 
          0.172,1,0.123,0.876,0.192,0.748,0.274,0.675,0.295,0.629,0.305,0.542,0.458,0.565,0.626,0.585,0.59,1
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
          - bicycle
        inertia: 3
      Street2:
        coordinates: 
          0.617,0.579,0.486,0.562,0.443,0.555,0.316,0.538,0.32,0.511,0.469,0.527,0.507,0.518,0.624,0.526
        loitering_time: 0
        objects:
          - bicycle
          - car
          - cat
          - dog
          - person
        inertia: 3
    review:
      alerts:
        required_zones: frontdoor
      detections:
        required_zones:
          - Street2
          - frontdoor


version: 0.15-1
semantic_search:
  enabled: true
  reindex: false
  model_size: large

review:
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - bicycle
      - person
      - car
      - dog
      - cat
  detections:
    labels:
      - car
      - person
      - bicycle
      - dog
      - cat
```

### Any other information that may be helpful

I'm probably missing something simple in my config.  I've tried a lot of options but none of them have seemed to work.

Thank you very much for all your work on this project and all the support you provide people.  I've read through everything I could find to see it others have similar issues and came up empty.
