### ISSUE TITLE
[Config Support]: How do i send notifications to my TV?

### ISSUE THREAD

**Issue by Strux-DK** [SgtBatten/HA_blueprints#385]
### Describe the problem you are having or the outcome you are trying to achieve.

It seems there is some misunderstanding between my home assistant instances notify entities, this blueprint and (lack of) my wisdom. I hope you can help me with what i should do next.

I have tried several times to setup frigate notifications for my Philips Smart TV (58PUS9005). I am really not sure what to put into the "Notification Group or Android/Fire TV (Optional)" box in the blueprint. Is it a notify entity? Is it a media player entity? Where do i find the name of my TV?
To put things in perspective:
I have downloaded and configured the 'Notifications for Android TV' app on the TV and the corresponding integration in Home Assistant. I also have a 'Philips TV' integration (https://www.home-assistant.io/integrations/philips_js) and a 'Android TV Remote' integration (https://www.home-assistant.io/integrations/androidtv_remote), so that's 3 integrations connected to my TV. I don't have any sense of perspective of what is used for what, unfortunately. The former integration, 'Notifications for Android TV' has created no entities whatsoever:

![Image](https://github.com/user-attachments/assets/6ff15b9f-4a09-4b92-9e6b-faa1d8164f79)

The 'Philips TV' integrations has 1 device and 7 entities:

![Image](https://github.com/user-attachments/assets/082bdc82-06c5-49f5-af43-c9acf2946135)

![Image](https://github.com/user-attachments/assets/8c15fc99-42cd-4e35-be07-f4f3c3bcbe7f)

While the 'Android TV remote' integration provides me with 1 device and 2 entities:

![Image](https://github.com/user-attachments/assets/43ad5220-b5b9-4a7f-8869-40fbfb941270)

![Image](https://github.com/user-attachments/assets/a5d3fe8a-ee72-47ce-8c73-f50ac342bfea)

Which one should i use? To further complicate things, when i go to 'Developer Tools' > 'Actions' and start typing "notify tv", i get to entities that i see referenced nowhere else, not even the naming convention is used anywhere else. How do i figure out where (what integration) these entities are coming from?

![Image](https://github.com/user-attachments/assets/9e46591c-0b9b-431f-9812-2c12906b2a9a)

i tried sending a notify message to the philips_smart_tv notify entity and it works, but when i input 'philips_smart_tv' into the box in the blueprint and click 'Run actions' to test it, nothing happens. Since you also write about a notify group i thought that maybe you meant that i was supposed to create a notify group and add the TV into that and then reference the group. Tried it, didn't help. Couldn't even select the notify entities you see on the last screenshot!

Since you created this extremely versatile blueprint, i know you must be hella smart. I hope you can help my dumb ass with some overview and how to proceed from here.

### Version

0.14.0.2w

### Automation config

```yaml
alias: Frigate Notifications for Philips Smart TV
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    notify_group: Android TV notification group
    camera:
      - camera.entrance_2
    base_url: http://192.168.1.18:8123
    title: Knock Knock
    message: this is a test
    alert_once: false
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    final_update: true
    zone_filter: true
    zones:
      - front_door
    labels:
      - person
    cooldown: 300
    final_delay: 15
    tv: true
    tv_interrupt: true
    debug: true
    notify_device: c23d2bb8ad0875fd9298b9fd93e3e190
```

### Frigate Config

```yaml
N/A
```
