### ISSUE TITLE
[Issue]: Frigate Telegram Alert Image Not Sending

### ISSUE THREAD

**Issue by lion06** [SgtBatten/HA_blueprints#386]
### Description

Hello,

I have Frigate installed on a separate machine from Home Assistant. Notifications and automations are working, except when trying to send an alert image via Telegram.

I receive the following error:
`Registratore: homeassistant.components.telegram_bot
Fonte: components/telegram_bot/__init__.py:984
Integrazione: Telegram bot (documentazione, problemi)
Prima occorrenza: 09:17:27 (1 occorrenze)
Ultimo accesso: 09:17:27

Can't send file with kwargs: {'caption': 'A Person was detected on the Salone Sud camera.', 'url': 'http://192.168.15.50:8123/api/frigate/notifications/1740125838.540413-8ad0cd/thumbnail.jpg'}`

### Version

Frigate Notifications (0.14.0.2w)

### Automation Config

```yaml
alias: aaaa
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.salone_sud
    notify_device: d7895ce1b95077c10f8a4a972abz12e2
    notify_telegram_chat_id: "-xxxxx"
    base_url: http://192.168.15.50:8123
    debug: true
    review_severity:
      - alert
    zone_filter: false
    zone_multi: true
    zone_order_enforced: false
    zones: []
```

### Frigate Config

```yaml
# Impostazioni MQTT
mqtt:
  enabled: true
  host: 192.168.15.50
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxx
  password: hhhhhhhhhh

tls:
  enabled: false

# 
ffmpeg:
  hwaccel_args: preset-vaapi

# Lista di detector
detectors:
  coral:
    type: edgetpu
    device: pci

# Impostazioni comuni di registrazione
record:
  enabled: true
  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 2
      mode: motion
  detections:
    retain:
      days: 2
      mode: motion

# Impostazioni comuni di snapshot
snapshots:
  enabled: true
  retain:
    default: 2

cameras:
  Salone_Sud:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.15.204:554/Streaming/Channels/2
          roles:
            - detect
        - path: rtsp://xxx:xxx@192.168.15.204:554/Streaming/Channels/1
          roles: [record]
    detect:
      enabled: true
    zones:
      Gente_in_salone:
        coordinates: 0.19,1,0.905,0.966,0.937,0.102,0,0.088
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Gente_in_salone
      detections:
        required_zones: Gente_in_salone

version: 0.15-1
```

### Any other relevant information

```yaml

```
