### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by tunavis** [SgtBatten/HA_blueprints#39]
### Describe the problem you are having or the outcome you are trying to achieve.

My Frigate is working 100% but this blueprint for notifcations is giving me such headache. My Camera's are not displaying on the dropdown? Any advise gents?

### Version

Latest

### Automation config file

```yaml
Don't have any automation file yet as reason being my camera's are not displaying on dropdown
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.0.4
  user: admin
  password: 5480477Tuna


cameras:
  kitchen_camera:
    ffmpeg:
      inputs:
        - path: rtsp://tunavis:BeMyGuest@123@30.30.30.246:554/stream1
          roles:
            - rtmp
    detect:
      width: 1280
      height: 720

  
  Garage_Door_Camera:
    ffmpeg:
      inputs:
        - path: rtsp://admin:IGJYXQ@30.30.30.245:554/H.264
          roles:
            - rtmp
            - detect
    rtmp:
      enabled: False        
    detect:
      width: 1280
      height: 720
    motion:
      mask:
        - 428,118,435,101,411,95
```

### Any other information that may be helpful

![image](https://github.com/SgtBatten/HA_blueprints/assets/8057000/8ba4410d-0899-48f8-a432-3f91ba2313ad)

![image](https://github.com/SgtBatten/HA_blueprints/assets/8057000/c49590c7-80ac-4a89-976b-cdc8ea56e35f)
