### ISSUE TITLE
[Config Support]: Notification images, clips, etc no longer attached after updating

### ISSUE THREAD

**Issue by theoptimisticcynic** [SgtBatten/HA_blueprints#392]
### Describe the problem you are having or the outcome you are trying to achieve.

I updated to the latest Frigate and also the latest blueprint and HA integration.
I created a new automation based on the latest stable blueprint and I successfully receive notifications on Android however no images, snapshots, etc are attached.

Prior to this update I was using events mqtt topic and older version of blueprint but did have thumbnails successfully attached.

I'm relatively new to blueprints and kind of lost trying to trace what's going on so any help is appreciated in seeing where things are breaking. I can successfully click on the actions and it opens the clips and snapshots but there are no attachments. I don't see anything that looks like an error, but not sure where to look.

My goal is to have cropped snapshots of the object detected showing up in my notification, followed by an update with a gif.

### Version

0.14.0.2w

### Automation config

```yaml
alias: Updated Frigate Notifications
description: Started with fresh import (0.14.0.2w)
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_left
    notify_device: 5dcc94fd678de7220cbbeb82164b16d7
    base_url: http://REDACTED
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    update_sub_label: false
    alert_once: true
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?crop=1
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    final_update: true
    review_severity:
      - alert
    zone_filter: false
```

### Frigate Config

```yaml

```

### Any other information that may be helpful

The URLs are only available on my local network not external.
Running behind nginx proxy manager mapping the URL to the ip address port 5000
