### ISSUE TITLE
[Config Support]: notifications not sent immediately

### ISSUE THREAD

**Issue by ivanjx** [SgtBatten/HA_blueprints#398]
### Describe the problem you are having or the outcome you are trying to achieve.

whenever the automation is triggered, the actual notification is sent 1-2 minutes after the event. i tried changing many fields but it does not seem to help.

![Image](https://github.com/user-attachments/assets/7bbad3a9-1161-4ea5-af44-5af12a95934b)

### Version

0.14.0.3f

### Automation config

```yaml
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera:
      - camera.cam1
    notify_device: xxx
    notify_group: notify_all
    base_url: https://xxx
    title: Home Assistant
    group: frigate-notification
    alert_once: true
    review_severity:
      - alert
      - detection
    zone_multi: true
    zones:
      - gate
      - beforealert
      - alert
    zone_order_enforced: true
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    update_sub_label: false
    tap_action: /lovelace
    url_3: ""
    button_3: ""
    zone_filter: true
    labels: []
    presence_filter:
      - ""
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    final_update: false
    attachment_2: ""
    final_delay: 0
    interruption_level: time-sensitive
    silence_timer: 0
    initial_delay: 1
```

### Frigate Config

```yaml

```

### Any other information that may be helpful

Frigate is using latest master build from their github.
