### ISSUE TITLE
[Issue]: Text notification is not longer being sent (android)

### ISSUE THREAD

**Issue by jagauthier** [SgtBatten/HA_blueprints#399]
### Description

I've noticed that the text on my notifications is completely missing.  

![Image](https://github.com/user-attachments/assets/bb9036cc-d37b-4685-86b6-4001f3b7df6d)

### Version

0.12.0.4e

### Automation Config

```yaml
alias: Camera - Front Door - Jason Phone
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_device: 4326f853999c593ea3007cb6f0f6f227
    message: "{{camera_name}}: {{detail_message}}"
    presence_filter:
      - ""
    mqtt_topic: frigate/events
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
