### ISSUE TITLE
[Config Support]:

### ISSUE THREAD

**Issue by JohannCR** [SgtBatten/HA_blueprints#400]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi, awesome blueprint !
I cannot make the custom filter work though...
Anyone knows what I did wrong ?

### Version

0.12.0.4e

### Automation config

```yaml
`use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera: camera.frigate_entree
    notify_device: c8be3cb8688851f054027f0d4beb18a6
    title: Quelqu'un à la porte
    zone_filter: true
    zones:
      - entree_person_zone
    labels:
      - person
    update_thumbnail: true
    button_1: Voir video
    button_2: Voir capture
    button_3: Sourdine
    notify_group: all
    message: Quelqu'un à la porte
    alert_once: true
    state_entity: input_boolean.porte_ouverte_30sec
    state_filter_states:
      - "off"
    update_sub_label: false
    state_filter: false
    custom_filter: >-
      {{ states('input_boolean.porte_ouverte_30sec') == 'off' and
      states('input_boolean.no_spam_entree') == 'off' and
      states('input_boolean.no_spam') == 'off' }}
    ios_live_view: camera.frigate_entree
    attachment: snapshot.jpg`
```

### Frigate Config

```yaml

```
