### ISSUE TITLE
[Issue]: Automation Sending clip as .mp4 even though ios set for .m3u8

### ISSUE THREAD

**Issue by disclosurez** [SgtBatten/HA_blueprints#401]
### Description

Hi, i'm getting .mp4 clips instead of .m3u8 links when I have ios set?

### Version

latest just updated now

### Automation Config

```yaml
- id: '1741003859080'
  alias: New automation
  description: ''
  triggers:
  - type: temperature
    device_id: d0ed432aac19ae89d7c28448d05e6169
    entity_id: 8840df2830409264dafbeabedfc50b80
    domain: sensor
    trigger: device
    above: 21
  conditions:
  - condition: time
    before: '16:00:00'
    after: 08:00:00
  actions:
  - device_id: 7be25e606438d96b8f0e02d45b3158ee
    domain: climate
    entity_id: cbd6d853eddfcbbc25908631db8115bb
    type: set_hvac_mode
    hvac_mode: cool
  mode: single
- id: '1741097412420'
  alias: Frigate
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      presence_filter:
      - ''
      camera:
      - camera.back
      - camera.front
      - camera.front_door
      - camera.side
      notify_device: feb2947a11e664f1304a929ecef641f5
      critical: '{{''false'' if now().hour in [8,9,10,11,12,13,14,15,16,17,18] else
        ''true''}}'
      video: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8'
      base_url: https://home.redacted.net
```

### Frigate Config

```yaml
# Sample Config file for Frigate install

mqtt:
  host: 192.168.0.40
  port: 1883
  topic_prefix: frigate

objects:
  track:
    - person
    - cat
    - dog


snapshots:
  enabled: True
  retain:
    default: 30

go2rtc:
  streams:
    Front:
      - rtsp://192.168.0.41:554/stream1
      - ffmpeg:Front#audio=aac
    Front_Sub:
      - rtsp://192.168.0.41:554/stream0
    Front_Door:
      - rtsp://192.168.0.42:554/stream1
      - ffmpeg:Front_Door#audio=aac
    Front_Door_Sub:
      - rtsp://192.168.0.42:554/stream0
    Back:
      - rtsp://192.168.0.43:554/stream1
      - ffmpeg:Back#audio=aac
    Back_Sub:
      - rtsp://192.168.0.43:554/stream0
    Side:
      - rtsp://192.168.0.44:554/stream1
      - ffmpeg:Side#audio=aac
    Side_Sub:
      - rtsp://192.168.0.44:554/stream0

ffmpeg:
  hwaccel_args: preset-vaapi  # May not work for your hardware, especially with Annke cameras.
  output_args:
    record: preset-record-generic-audio-copy  # Enable audio copy

detectors:
  coral:
    type: edgetpu
    device: usb

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

cameras:
  Front:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      fps: 25
    zones:
      Drive:
        coordinates: 0.385,0.331,0.094,0.876,0,0.456,0,1,0.158,0.997,0.934,0.995,0.813,0.263
        loitering_time: 0
        inertia: 3
        objects: person
      Path:
        coordinates: 
          0.037,0.618,0.006,0.461,0,0.405,0.363,0.265,0.783,0.181,0.806,0.26,0.433,0.318,0.309,0.339,0.263,0.38
        loitering_time: 0
        objects: person
        inertia: 3
    review:
      alerts:
        required_zones:
          - Drive
          - Path
      detections:
        required_zones:
          - Path
          - Drive
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true

  Front_Door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Front_Door_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      fps: 25
    motion:
      threshold: 40
      contour_area: 20
      improve_contrast: true
    zones:
      Porch:
        coordinates: 
          1,0.435,0.982,0.415,0.97,0.402,0.72,0.184,0.673,0.002,0,0.002,0.013,0.991,0.777,1,1,0.515,1,0.495,0.994,0.426,0.998,0.465,0.998,0.483
        loitering_time: 0
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: Porch
      detections:
        required_zones: Porch

  Side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Side_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      fps: 25
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Sidepath:
        coordinates: 0.252,0.354,0.304,0.341,0.369,0.574,0.439,0.773,0.501,1,0.327,1
        inertia: 3
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Sidepath
      detections:
        required_zones: Sidepath
  Back:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Back
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Back_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 1280
      fps: 25
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      Garden:
        coordinates: 0.121,0.004,0.003,0.249,0.003,0.994,0.434,0.997,0.344,0.624,0.37,0.003
        loitering_time: 0
        inertia: 3
        objects: person
    review:
      alerts:
        required_zones: Garden
      detections:
        required_zones: Garden
version: 0.15-1

semantic_search:
  enabled: true
  reindex: true
  model_size: small

camera_groups:
  Home:
    order: 1
    icon: LuAirplay
    cameras:
      - Front
      - Front_Door
      - Side
      - Back
```

### Any other relevant information

```yaml

```
