### ISSUE TITLE
[Config Support]: All cameras are triggering notification, even though a single camera is defined

### ISSUE THREAD

**Issue by shim895** [SgtBatten/HA_blueprints#402]
### Describe the problem you are having or the outcome you are trying to achieve.

I am trying to create an automation per camera (I have 9 total). I create a single automation, singling out one camera, but it is getting triggered when ANY of my 9 cameras receive a review event. My question is, how do I limit an automation to a single camera's review event?

For reference, here is an example automation for one of my cameras (upstairs):
```
  - alias: Frigate Camera Notification (upstairs)
    condition:
      condition: state
      entity_id:
        - input_boolean.frigate_notifications_upstairs
      state: "on"
    use_blueprint:
      path: SgtBatten/Stable.yaml
      input:
        presence_filter:
          - ""
        camera:
          - camera.upstairs
        notify_device: XXXXXXXXXXXX
        base_url: https://XXX.XXXXXX.com
        title: >-
          Upstairs Camera Notification
        message: >-
          {{ label }}{{ ' was' if type == 'end' else '' }} detected on the upstairs camera
        alert_once: true
        final_update: true
        labels:
        - person
        - dog
        - cat
        attachment: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
        attachment_2: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
        tap_action: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
        url_1: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
        debug: true
        redacted: false
```

Here is the same camera's frigate configuration:
```
  upstairs:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.68.5:8554/upstairs
          roles:
            - detect
            - record
    motion:
      enabled: true
      mask: 0.362,0.007,0.364,0.053,0.704,0.093,0.704,0.002
    review:
      alerts:
        labels:
          - person
          - dog
          - cat
      detections:
        labels:
          - person
          - dog
          - cat
    ui:
      order: 9
      dashboard: true
```

I almost have to missing some simple config/filter parameter. I figured it was
```
        camera:
          - camera.upstairs
```
but that doesn't appear to be the case.

### Version

Frigate Notifications (0.14.0.2w)

### Automation config

```yaml
SEE ABOVE
```

### Frigate Config

```yaml
SEE ABOVE
```

**Comment by shim895** [comment]
> You would need to modify the mqtt trigger such that instead of only looking for the type of "new" it also looks for the camera name like the older versions of the blueprint did before it change to Multicam.
> 
> I've had an idea that maybe I could add a workable solution for single cam setups though.

Exactly what I was thinking as well. I just wanted to ensure I wasn't overlooking some config option. I'll go down that path.

Thank you!

**Comment by shim895** [comment]
Oddly enough, I moved the initial condition I had in the automation to a "master_condition" and all of my cameras are firing notifications correctly.

From:
```
  - alias: Frigate Camera Notification (upstairs)
    condition:
      condition: state
      entity_id:
        - input_boolean.frigate_notifications_upstairs
      state: "on"
    use_blueprint:
      path: SgtBatten/Stable.yaml
****
```

To:
```
****
        master_condition:
          - condition: state
            entity_id: input_boolean.frigate_notifications_upstairs
            state: "on"
```

**Comment by SgtBatten** [comment]
I guess I should have clarified that when you said all cameras were triggering it you meant that the last triggered time was updating right? You wouldn't have been getting notifications sent for all cams.

**Comment by shim895** [comment]
If I had this sort of automation running:
```
 - alias: Frigate Camera Notification (upstairs)
    condition:
      condition: state
      entity_id:
        - input_boolean.frigate_notifications_upstairs
      state: "on"
    use_blueprint:
      path: SgtBatten/Stable.yaml
      input:
        presence_filter:
          - ""
        camera:
          - camera.upstairs
        notify_device: XXXXXXXXXXXX
................
```
which specified a single camera (camera.upstairs), any of my 9 cameras would trigger it. I would have expected only the one camera (camera.upstairs) to trigger it.

Removing that initial condition, and adding a master_condition (as detailed above), took care of it somehow. Now I have 9 separate automations configured and each is working as it should.

**Comment by SgtBatten** [comment]
I was trying to confirm exactly hat you mean by trigger. 

did you get a notification on other cameras (not expected) or simply observe traces being generated (expected)

**Comment by shim895** [comment]
I actually received notifications on the other camera automations, i.e. a triggering event. Here's a couple of examples of events on the side-yard camera triggering the upstairs and downstairs specific automations.

![image](https://github.com/user-attachments/assets/2fc94c52-0fcd-4041-ae95-a7d16f9ae5b5)
![image](https://github.com/user-attachments/assets/3b61ab94-7c55-4f88-876e-d4188913f430)

**Comment by SgtBatten** [comment]
Oh interesting. there was an old version of the blueprint which this happened on but i'm fairly confident that's fixed.

**Comment by SgtBatten** [comment]
Both the master condition and camera name has to match. 

![Image](https://github.com/user-attachments/assets/a668f8a6-54fe-447e-9ca5-e9e413d1099b)

**Comment by shim895** [comment]
I'll try reverting back to the way I had things to see if I can replicate again.

**Comment by shim895** [comment]
OK, was easy enough to test :)

This format works:
```
  - alias: Frigate Camera Notification (upstairs)
    use_blueprint:
      path: SgtBatten/Stable.yaml
      input:
        presence_filter:
          - ""
        camera:
          - camera.upstairs
        notify_device: XXXXXXXXXXX
        base_url: https://hass.XXXXXX.com
        title: >-
          Upstairs Camera Notification
        message: >-
          {{ label }}{{ ' was' if type == 'end' else '' }} detected on the upstairs camera
        alert_once: true
        final_update: false
        labels:
        - person
        - dog
        - cat
        attachment: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
        attachment_2: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
        tap_action: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
        url_1: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
        master_condition:
          - condition: state
            entity_id: input_boolean.frigate_notifications_upstairs
            state: "on"
```

This format does not:
```
  - alias: ALT - Frigate Camera Notification (upstairs)
    condition:
      condition: state
      entity_id:
        - input_boolean.frigate_notifications_upstairs
      state: "on"
    use_blueprint:
      path: SgtBatten/Stable.yaml
      input:
        presence_filter:
          - ""
        camera:
          - camera.upstairs
        notify_device: XXXXXXXXXXXX
        base_url: https://hass.XXXXXXX.com
        title: >-
          Upstairs Camera Notification
        message: >-
          {{ label }}{{ ' was' if type == 'end' else '' }} detected on the upstairs camera
        alert_once: true
        final_update: false
        labels:
        - person
        - dog
        - cat
        attachment: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
        attachment_2: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
        tap_action: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
        url_1: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
```

The only difference is the automation condition vs. the master_condition. With the latter, I get random camera alerts on random automations.

HTH
