### ISSUE TITLE
[Config Support]: Visually Grouping on Android

### ISSUE THREAD

**Issue by MelchMwoan** [SgtBatten/HA_blueprints#406]
### Describe the problem you are having or the outcome you are trying to achieve.

Hey, I'm trying to group my notifications on android, but it doesn't appear to be working. It looks like it isn't assigning the group to the notification.

![Image](https://github.com/user-attachments/assets/4d3790b7-e987-4ddd-aee7-1648a6cea432)

I've set both the group and the channel in the config and I've tried both the stable and the beta blueprint.

### Version

0.14.0.2w & 0.14.0.3f

### Automation config

```yaml
alias: Frigate Notifications - Beta
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.deurbel
      - camera.reolink
    notify_device: 98b93fdb74b49746273779d2d032898d
    base_url: <removed>
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    update_sub_label: false
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    final_update: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif?format=ts
    icon: mdi:cctv
    sound: none
    channel: cams
    group: cams
    title: "{{label}} detected at {{camera_name}}"
    debug: false
```

### Frigate Config

```yaml

```
