### ISSUE TITLE
[Config Support]: No android notifications since haos 25.3

### ISSUE THREAD

**Issue by Davecl** [SgtBatten/HA_blueprints#407]
### Describe the problem you are having or the outcome you are trying to achieve.

Since I updated haos to 25.3 my android notifications have stopped coming.
Nothing else has changed.
Frigate is still working perfectly, i'm just not getting notifications on my phone

### Version

Frigate Notifications (0.12.0.4e)

### Automation config

```yaml
alias: Frigate Notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front
    notify_device: 58d543ceda6a06f463d15cb0ee9935a7
    title: Front Camera
    zone_filter: true
    zones:
      - front_garden
    labels:
      - person
```

### Frigate Config

```yaml
mqtt:
  host: core-mosquitto
  user: MQTTuser
  password: ******




detectors:
  coral:
    type: edgetpu
    device: usb




record:
  enabled: true
  sync_recordings: false

  alerts:
    retain:
      days: 2
  detections:
    retain:
      days: 2
objects:
  track:
    - person
  filters:
    person:
      threshold: 0.75
      min_area: 5000
      max_area: 100000
go2rtc:
  streams:
    front:
      - rtsp://dav*****@192.168.0.88/stream2
    back:
      - rtsp://dav*****@192.168.0.89/stream2
#live:
  #stream_name: front

cameras:
  front:
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2
      required_zones:
        - front_garden
      clean_copy: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://dav*****@192.168.0.88/stream1
          roles:
            - record

        - path: rtsp://dav*****@192.168.0.88/stream2
          roles:
            - detect
      hwaccel_args: preset-intel-qsv-h264


    live:
      stream_name: front
    motion:
      mask:
        - 0.329,0,0.329,0.04,0.003,0.049,0.005,0.002
        - 0.686,0.364,0.808,0.409,0.822,0.476,0.808,0.591,0.775,0.654,0.753,0.67,0.734,0.664,0.694,0.648,0.669,0.625,0.641,0.581,0.639,0.534,0.653,0.468
        - 0.181,0.047,0.365,0,0.386,0.23,0.376,0.285,0.35,0.419,0.262,0.484,0.209,0.469,0.232,0.32,0.171,0.229
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      front_garden:
        coordinates: 
          0.311,0.246,0.233,0.34,0.206,0.495,0.163,0.661,0.117,0.806,0.085,1,0.302,0.988,0.958,0.994,0.996,0.994,0.989,0.798,0.832,0.498,0.722,0.344,0.631,0.241
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: front_garden
      detections:
        required_zones: front_garden
  back:
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        default: 2
      required_zones:
        - back_garden
      clean_copy: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://dav*****@192.168.0.89/stream1
          roles:
            - record

        - path: rtsp://dav*****@192.168.0.89/stream2
          roles:
            - detect
      hwaccel_args: preset-intel-qsv-h264


    live:
      stream_name: back
    motion:
      mask:
        - 0.01,0.53,0.112,0.601,0.109,0.758,0.066,0.843,0.013,0.843,0,0.785
        - 0.337,0,0.344,0.06,0.021,0.056,0.012,0
        - 0.016,0.036,0.193,0.039,0.179,0.206,0.16,0.237,0.14,0.277,0.004,0.368,0.001,0.065
      threshold: 30
      contour_area: 10
      improve_contrast: true
    zones:
      back_garden:
        coordinates: 
          0.248,0.101,0.225,0.168,0,0.403,0,0.651,0,0.837,0,1,0.316,1,0.948,1,1,0.952,0.993,0.756,1,0.511,1,0.329,0.943,0.218,0.66,0.121,0.499,0.124,0.434,0.048,0.341,0.053
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: back_garden
      detections:
        required_zones: back_garden
    objects:
      filters:
        person: {}
      mask: 0.431,0.748,0.3,0.801,0.226,0.081,0.347,0.066

version: 0.15-1
```
