### ISSUE TITLE
[Config Support]: Notification fires "always"

### ISSUE THREAD

**Issue by fanno** [SgtBatten/HA_blueprints#408]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello

I have been struffeling with norifications, they keep fure no matter what i try.

tried: presence_filter and master_condition and one and the other.

### Version

0.1240.2w

### Automation config

```yaml
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - person.jenilyn
      - person.fanno
      - device_tracker.sm_s921b
      - device_tracker.sm_a415f
      - group.family
    camera:
      - camera.hallway_cam
      - camera.livingroom_cam
    notify_device: 40eb84bd03a9e9381fc4c78bec5928f9
    base_url: http://home.local
    debug: false
    master_condition:
      - condition: and
        conditions:
          - condition: or
            conditions:
              - type: is_occupied
                condition: device
                device_id: 222aef582cd44c1acfdd528bc2865283
                entity_id: 79b59b9d46617262140b118abc31bbce
                domain: binary_sensor
              - type: is_occupied
                condition: device
                device_id: c0c8a190a9419fb625a9a071a18698bd
                entity_id: 514212582df70aba2ebba080b97a71e8
                domain: binary_sensor
          - condition: device
            device_id: 7f555077e948126b309f1f54745261ee
            domain: device_tracker
            entity_id: 5d74433db24e5f0c2f45dde9ff4f6e60
            type: is_not_home
          - condition: device
            device_id: 40eb84bd03a9e9381fc4c78bec5928f9
            domain: device_tracker
            entity_id: f42c98e8d7ecbdea0b0ef99f90dcd412
            type: is_not_home
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    sticky: true
    tv: false
    custom_action_manual: []
    cooldown: 60
    notify_group: all_mobile_devices
    labels:
      - person
    state_filter: false
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: xxxxxxxxxxxxxxxx
  port: 1883
  user: xxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxx
  stats_interval: 60
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral:
    type: edgetpu
    device: pci

tls:
  enabled: false

go2rtc:
  streams:
    hallway_cam:
      - rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio.
    hallway_cam_sub:
      - rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio.
    livingroom_cam:
      - rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio.
    livingroom_cam_sub:
      - rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=1 # <- stream which supports video & aac audio.      
  webrtc:
    candidates:
      - xxxxxxxxxxxxxxxx:8555
      - stun:8555

record:
  enabled: true
  retain:
    days: 5
  events:
    retain:
      default: 30

snapshots:
  enabled: true
  retain:
    default: 30

cameras:
  hallway_cam: # <------ Name the camera
    record:
      enabled: true
      retain:
        mode: motion
        days: 5
      events:
        retain:
          default: 30
    snapshots:
      enabled: true
      retain:
        default: 30
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for recording
          roles:
            - record
        - path: rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704
      height: 576
      fps: 10
    objects:
      track:
        - person
    motion:
      mask: 
        0.241,0.082,0.426,0.143,0.476,0.279,0.715,0.13,0.718,0.085,0.761,0.073,0.835,0.069,0.966,0.104,0.925,0.799,0.839,1,1,1,1,0,0,0,0,1,0.124,1,0.236,1,0.091,0.412,0.069,0.257,0.052,0.1,0.19,0.017
      threshold: 30
      contour_area: 10
      improve_contrast: true
  livingroom_cam: # <------ Name the camera
    record:
      enabled: true
      retain:
        mode: motion
        days: 5
      events:
        retain:
          default: 30
    snapshots:
      enabled: true
      retain:
        default: 30
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for recording
          roles:
            - record
        - path: rtsp://xxxxxxxxxxxxxxxx/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704
      height: 576
      fps: 10
    objects:
      track:
        - person
    motion:
      mask:
        - 0.743,0.083,0.972,0.204,0.96,0.321,0.774,1,1,1,1,0,0,0,0,1,0.304,1,0.184,0.655,0.081,0.373,0.064,0.006,0.624,0.007,0.622,0.027
        - 0.65,0.05,0.847,0.169,0.816,0.385,0.639,0.237
      threshold: 30
      contour_area: 10
      improve_contrast: true
version: 0.14
```

**Comment by SgtBatten** [comment]
Can you enable debug and share the output from that part of the trace.

**Comment by fanno** [comment]
yes i will do so.

i will be able to reply that data late thursday / friday i am away from home working most of the week.

**Comment by fanno** [comment]
Wife happened to be walking around at home so i could get it.

![Image](https://github.com/user-attachments/assets/1e809c57-e68d-4366-b72e-3ff2f7ebb0fc)

![Image](https://github.com/user-attachments/assets/0b116d6e-c725-4a5a-907b-20c7c9c67c93)

number of entries on the app lotification do not match what is in the logbok
```
Frigate Notification DEBUG: Info: FPS: 5, Frigate Review id: 1741634835.607237-lmkn6t, Frigate Detections: ['1741634827.551442-0j2upw'] Objects: Person, Sub Labels: Config: Camera(formatted): livingroom_cam(Livingroom Cam), Base URL: REDACTED, Critical: False, TTS: False TTS Helper: N/A, Alert Once: False, Final_Update (delay): False (5)s, Attachment: REDACTED/api/frigate/notifications/1741634827.551442-0j2upw/thumbnail.jpg Video: REDACTED/api/frigate/notifications/1741634827.551442-0j2upw/livingroom_cam/clip.mp4, iOS URL: REDACTED/api/frigate/notifications/1741634827.551442-0j2upw/livingroom_cam/clip.mp4 Target: group (input/formatted): all_mobile_devices/all_mobile_devices, , Cooldown: 60s, Initial Delay: 0s, Color: #03a9f4, Sound: default, Volume: 1.0 IOS Live entity: "" Android Auto: False, Tag: 1741634827.551442-0j2upw, Group: livingroom_cam-frigate-notification, Channel: , Sticky: True, Title: , Message: A Person was detected on the Livingroom Cam camera., Subtitle: , Tap Action: REDACTED/api/frigate/notifications/1741634827.551442-0j2upw/livingroom_cam/clip.mp4, Action Button 1 Text/URL/Icon: View Clip (REDACTED/api/frigate/notifications/1741634827.551442-0j2upw/livingroom_cam/clip.mp4) , Action Button 2 Text/URL/Icon: View Snapshot (REDACTED/api/frigate/notifications/1741634827.551442-0j2upw/snapshot.jpg) , Action Button 3 Text/URL/Icon: Silence New Notifications (silence- ) , Icon: mdi:homeassistant TV: False, Position: center, Size: large, Duration: 10, Transparency: 0%, TV Interrupt: False, Telegram: False, Telegram_chat_id: , Filters: Severity: Required Severity: ['alert', 'detection'], TEST: PASS - alert Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Entered Zones: [], TEST: PASS , Required objects: Input: ['person'], TEST: PASS - ['person'] presence entity (not home): Entity: ['person.jenilyn', 'person.fanno', 'device_tracker.sm_s921b', 'device_tracker.sm_a415f', 'group.family'] TEST: PASS, disabled times: [], State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: True udløst af automatisering
mqtt topic frigate/reviews
19.27.15 - For 2 minutter siden
```


```
Frigate Notification DEBUG: Info: FPS: 5, Frigate Review id: 1741635101.046996-2nhsyw, Frigate Detections: ['1741635100.324524-jr3f4q'] Objects: Person, Sub Labels: Config: Camera(formatted): hallway_cam(Hallway Cam), Base URL: REDACTED, Critical: False, TTS: False TTS Helper: N/A, Alert Once: False, Final_Update (delay): False (5)s, Attachment: REDACTED/api/frigate/notifications/1741635100.324524-jr3f4q/thumbnail.jpg Video: REDACTED/api/frigate/notifications/1741635100.324524-jr3f4q/hallway_cam/clip.mp4, iOS URL: REDACTED/api/frigate/notifications/1741635100.324524-jr3f4q/hallway_cam/clip.mp4 Target: group (input/formatted): all_mobile_devices/all_mobile_devices, , Cooldown: 60s, Initial Delay: 0s, Color: #03a9f4, Sound: default, Volume: 1.0 IOS Live entity: "" Android Auto: False, Tag: 1741635100.324524-jr3f4q, Group: hallway_cam-frigate-notification, Channel: , Sticky: True, Title: , Message: A Person was detected on the Hallway Cam camera., Subtitle: , Tap Action: REDACTED/api/frigate/notifications/1741635100.324524-jr3f4q/hallway_cam/clip.mp4, Action Button 1 Text/URL/Icon: View Clip (REDACTED/api/frigate/notifications/1741635100.324524-jr3f4q/hallway_cam/clip.mp4) , Action Button 2 Text/URL/Icon: View Snapshot (REDACTED/api/frigate/notifications/1741635100.324524-jr3f4q/snapshot.jpg) , Action Button 3 Text/URL/Icon: Silence New Notifications (silence- ) , Icon: mdi:homeassistant TV: False, Position: center, Size: large, Duration: 10, Transparency: 0%, TV Interrupt: False, Telegram: False, Telegram_chat_id: , Filters: Severity: Required Severity: ['alert', 'detection'], TEST: PASS - alert Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Entered Zones: [], TEST: PASS , Required objects: Input: ['person'], TEST: PASS - ['person'] presence entity (not home): Entity: ['person.jenilyn', 'person.fanno', 'device_tracker.sm_s921b', 'device_tracker.sm_a415f', 'group.family'] TEST: PASS, disabled times: [], State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: True udløst af automatisering
mqtt topic frigate/reviews
19.31.41 - For 33 sekunder siden
```

**Comment by fanno** [comment]
```
Frigate Notification DEBUG (in loop): Send Notification: False Info: Sub Label: [], Image: "REDACTED/api/frigate/notifications/1741635037.057602-guk97w/thumbnail.jpg" Title: Message: A Person was detected on the Livingroom Cam camera. iOS sound: Silent, Android Sound: enabled, iOS url: "REDACTED/api/frigate/notifications/1741635037.057602-guk97w/livingroom_cam/clip.mp4", Video: "REDACTED/api/frigate/notifications/1741635037.057602-guk97w/livingroom_cam/clip.mp4", Critical: False, TTS: False Triggers: New Snapshot: False (not functional with reviews) Severity Changed: False, Presence Changed: False, Object changed: False, Zones Changed: False, Sublabel changed: False, Final Update: False Conditions: Filters: Severity: Required Severity: ['alert', 'detection'] TEST: PASS - alert, Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Last Zones: 0 - [], New Zones: 0 - [], TEST: PASS , Object Filter: Input: ['person'], TEST: PASS - ['person'], Presence entity (not home): Entity: ['person.jenilyn', 'person.fanno', 'device_tracker.sm_s921b', 'device_tracker.sm_a415f', 'group.family'], TEST: PASS, Time Filter: Disabled times: [], TEST: PASS State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: PASS, udløst af automatisering
mqtt topic frigate/reviews
19.32.07 - For 2 minutter siden
```

here is a few that showed up.

**Comment by SgtBatten** [comment]
If there are not traces to match the notifications are you sure you don't have a second automation setup accidentally?

When you get time is need you to pinpoint one event. 

Clear all notifications on the nhone. Walk around to trigger it. Screenshot the trace diagram and share the debug information, it's in two places in the trace and I'd like to see both. Plus the notification itself. 
#351 shows a guide.

Thanks

**Comment by fanno** [comment]
I have a clone but the slider is off, will it still trigger ?

**Comment by SgtBatten** [comment]
No, but if the automation you think  is triggering the extra notification is the culprit it should have relevant traces. 

Can you try to isolate a false notification and share all the details as described above

**Comment by fanno** [comment]
yes i will try when i get home still in sweeden working =)

**Comment by fanno** [comment]
i disabled the last automation, and now getting no notifications (tho i am home)

i then reenabled it and still getting none. s it posible that it only updates behavior only when its deactivated and then reactivated ??

i will have to go away from home and come back to recreate it. tomorrow cant today

**Comment by fanno** [comment]
I went away from house and came back and now i am only getting 1 event. when i come home as one would expect.

when changing it should i really have to disable the automation and then re enable it for it to take effect ?

or could something else be going on?

**Comment by fanno** [comment]
*sig* it did it again last night but i was not ready to monitor it.

i am wondering if it has anything to do with language ? my wife uses english and i am danish. sometimes the home assistant says home OR hjemme both means home. not sure how home assistant works behind the sceenes

**Comment by SgtBatten** [comment]
I've seen instaces of home assistant caching changes in the past but no it's not strictly necessary to disable it. 

If you are changing the blueprint itself then you would need to reload automations from the settings menu. But I don't believe you are doing this kind of change. 

I'm not familiar with how languages could cause a duplication sorry, that would be a new perspective on this one for sure.

**Comment by fanno** [comment]
I am only changing the settings via:
settings >automation & scenes > and then the frigate notification (0.14.0.2w)

What i was thinking with language is that say when i am not home (danish hjemme, the notifications dont seem to happen as much at least) if i am away and wife is home and she has status "Home"  the event triggers.

Tho all this don't seem "solid" and 100 % reproducable whitch is mainly what is causing my confusuon

For instance this one from yesterday:
```
Frigate Notification DEBUG: Info: FPS: 5, Frigate Review id: 1741980035.602524-4z67dk, Frigate Detections: ['1741980035.120865-i1jp12'] Objects: Person, Sub Labels: Config: Camera(formatted): livingroom_cam(Livingroom Cam), Base URL: REDACTED, Critical: False, TTS: False TTS Helper: N/A, Alert Once: False, Final_Update (delay): False (5)s, Attachment: REDACTED/api/frigate/notifications/1741980035.120865-i1jp12/thumbnail.jpg Video: REDACTED/api/frigate/notifications/1741980035.120865-i1jp12/livingroom_cam/clip.mp4, iOS URL: REDACTED/api/frigate/notifications/1741980035.120865-i1jp12/livingroom_cam/clip.mp4 Target: group (input/formatted): all_mobile_devices/all_mobile_devices, , Cooldown: 60s, Initial Delay: 0s, Color: #03a9f4, Sound: default, Volume: 1.0 IOS Live entity: "" Android Auto: False, Tag: 1741980035.120865-i1jp12, Group: livingroom_cam-frigate-notification, Channel: , Sticky: True, Title: , Message: A Person was detected on the Livingroom Cam camera., Subtitle: , Tap Action: REDACTED/api/frigate/notifications/1741980035.120865-i1jp12/livingroom_cam/clip.mp4, Action Button 1 Text/URL/Icon: View Clip (REDACTED/api/frigate/notifications/1741980035.120865-i1jp12/livingroom_cam/clip.mp4) , Action Button 2 Text/URL/Icon: View Snapshot (REDACTED/api/frigate/notifications/1741980035.120865-i1jp12/snapshot.jpg) , Action Button 3 Text/URL/Icon: Silence New Notifications (silence- ) , Icon: mdi:homeassistant TV: False, Position: center, Size: large, Duration: 10, Transparency: 0%, TV Interrupt: False, Telegram: False, Telegram_chat_id: , Filters: Severity: Required Severity: ['alert', 'detection'], TEST: PASS - alert Zones: Zone Filter toggle on: False, Multi-Zone toggle on: False, Required zones: [], Zone Order toggle on: False Entered Zones: [], TEST: PASS , Required objects: Input: ['person'], TEST: PASS - ['person'] presence entity (not home): Entity: ['person.jenilyn', 'person.fanno', 'device_tracker.sm_s921b', 'device_tracker.sm_a415f', 'group.family'] TEST: PASS, disabled times: [], State Filter: State Filter toggle on: False, State Filter Entity: , Required States: [], TEST: PASS, Custom Filter: True udløst af automatisering
mqtt topic frigate/reviews
```

Required objects: Input: ['person'], TEST: PASS
Suggest to me that PASS means it was a person

presence entity (not home): Entity: ['person.jenilyn', 'person.fanno', 'device_tracker.sm_s921b', 'device_tracker.sm_a415f', 'group.family'] TEST: PASS
suggests to me that ALL should have been not_home ? tho i know we were both home.

i also dont know if issues fould come from group.family or me adding the device_tracker.sm_s921b and sm_a415f i have just been trying verious stuff

```
family:
  name: "family"
  entities:
    - person.fanno
    - person.jenilyn
```

What happens if the state happen to be Unavailable/Unknown for some reason ?
