### ISSUE TITLE
[Bug]: State filter appears to be ignored

### ISSUE THREAD

**Issue by bean72** [SgtBatten/HA_blueprints#41]
### Description

I had my camera firing a notification based on the state of my alarm panel. Originally it was triggering when my alarm was both disarmed and armed. I recently changed it to only fire when armed, yet its still sending the notification while disarmed. All my other cameras are set up exactly the same and respect their state filter, seems that changes after creation do not apply?

### Version

0.12.0.1

### Automation Config

```yaml
alias: SECURITY - Front Door Alert
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.front_door
    tv_size: large
    tv_position: center
    color: grey
    cooldown: 300
    labels:
      - person
    notify_group: notify.personalerts
    state_filter: true
    state_entity: alarm_control_panel.home_alarm
    state_filter_states:
      - armed_stay
      - armed_away
      - triggered
      - pending
    debug: true
```

### Any other relevant information

```yaml
Frigate Notification DEBUG (in loop): Info: Last Zones: [], Current zones: [], sublabel: None, IOS sound: False, Android Sound: enabled, Triggers: New Snapshot: False, Presence Changed: False, stationary moved: False, entered zones changed: False, sublabel changed: False, Conditions: Loitering: 0 or Presence Entity not home: OFF - PASS, zone filter TEST: OFF - PASS, multi-zone filter: OFF - PASS, state filter TEST: ON - FAIL image: "/api/frigate/notifications/1685546679.713229-uzy6ji/thumbnail.jpg?format=android" triggered by automation SECURITY - Front Door Alert mqtt topic frigate/events
8:24:45 AM - 14 minutes ago


Frigate Notification DEBUG: Info: fps: 5, frigate event id: 1685546679.713229-uzy6ji, object (formatted): person (Person), Config: camera(formatted): front_door(Front Door), Base URL: , critical: False, alert once: False, Update Thumbnails: False, Target: group (input/formatted): notify.personalerts/personalerts, cooldown: 300s, loiter timer: 0s, color: grey, sound: default, Title: , Message: A Person was detected on the Front Door camera., tap_action: /api/frigate/notifications/1685546679.713229-uzy6ji/front_door/clip.mp4, button 1 Text/URL: View Clip (/api/frigate/notifications/1685546679.713229-uzy6ji/front_door/clip.mp4), button 2 Text/URL: View Snapshot (/api/frigate/notifications/1685546679.713229-uzy6ji/snapshot.jpg), button 3 Text/URL: Silence New Notifications (silence-front_door), icon: mdi:home-assistant tv: False, tv_position: center, tv_size: large, tv_duration: 10, tv_transparency: 0%, tv_interrupt: False, Filters: Zones: zone filter toggle on: False, Multi Zone toggle on: False, Required zones: [], Entered Zones: [], Zone Filter TEST: PASS, Required objects TEST: Input: ['person'], TEST: PASS presence entity (not home): Entity: TEST: PASS, disabled times: [], State Filter: state filter toggle on: True, state filter entity: alarm_control_panel.home_alarm, required states: ['armed_stay', 'armed_away', 'triggered', 'pending'], State Filter TEST: FAIL, triggered by automation SECURITY - Front Door Alert mqtt topic frigate/events
8:24:40 AM -
```
