### ISSUE TITLE
{"success":false,"message":"Event not found"}

### ISSUE THREAD

**Issue by stamandr** [SgtBatten/HA_blueprints#410]
### Description

Since upgrading to 2025.3.1, when the Frigate Blueprint runs I get double alerts on my phone. The first alert is correct. The second alert contains the following

{"success":false,"message":"Event not found"}

![Image](https://github.com/user-attachments/assets/b95b4c30-3a2a-4225-b999-ba40926c1469)

### Version

0.14.0.2w

### Automation Config

```yaml
alias: "(Frontdoor) - Frigate Notifications (0.14.0.2w)"
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera:
      - camera.frontdoor
    notify_device: 5ab4f196bb5cacaf1d03f64991ae80d4
    notify_group: Phones
    title: Frontdoor - Person
    critical: "true"
    color: "#f44336"
    zone_filter: true
    zones:
      - FrontDoor_Person_Zone
      - front_door
    labels:
      - person
    message: A Person was detected on the FrontDoor camera
    update_thumbnail: true
    presence_filter:
      - ""
    volume: 50
    update_sub_label: false
    final_update: true
    icon: mdi:doorbell-video
    android_auto: true
    cooldown: 10
    alert_once: false
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
