### ISSUE TITLE
[Config Support]: 2 cameras different angles and different zone

### ISSUE THREAD

**Issue by Frazou1** [SgtBatten/HA_blueprints#412]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi, i wondering if we can monitor 2 camera where they look at the same place but different angles and each camera have theire home zone and when they detect object they will fired and send snapshot and clip of the camera 1 ?

### Version

0.14.0.3f

### Automation config

```yaml
alias: Frigate Notifications (0.14.0.3f)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.camera_stationnement
      - camera.cam_avant
    notify_device: d0d9e52e51bf00ca693a6161e29b1b6a
    zone_filter: true
    zones:
      - cam_stationnement_park
      - cam_avant_park
    labels:
      - person
      - cat
      - dog
```

### Frigate Config

```yaml

```
