### ISSUE TITLE
[Config Support]: Unable to trigger automation

### ISSUE THREAD

**Issue by leedomike** [SgtBatten/HA_blueprints#413]
### Describe the problem you are having or the outcome you are trying to achieve.

I am not able to trigger the automation. MQTT appears to be working (i'm new to this, but I've tried the troubleshooting stuff to publish and listen to events and everything seems to work). I have created a basic automation that I will post that triggers just fine. 

My automations are very basic right now just so I can get everything up and running. But ideally I want to add a lot more functionality that I think this blueprint has.

### Version

0.14.0.2w

### Automation config

```yaml
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.boyziicam
    notify_device: 2e61dc0d89a1bae8edccb47599547eb1
    cooldown: 30
    mqtt_topic: frigate/events
    debug: true
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.[redacted]
  user: [redacted]
  password: [redacted]
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  boyziicam:
    ffmpeg:
      inputs:
        - path: rtsp://[redacted]:8554/boyz-ii-cam
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5 
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1  
    record:
      enabled: true
      retain:
        days: 7

motion:
  threshold: 50
  contour_area: 20
  improve_contrast: true

version: 0.15-1

semantic_search:
  enabled: false
  reindex: false
  model_size: small
```

### Any other information that may be helpful

Hand crafted automation:
```
alias: Frigate Snapshot Notifications
description: Send a notification with a snapshot for each detection.
triggers:
  - topic: frigate/events
    trigger: mqtt
conditions:
  - condition: template
    value_template: >
      {{ trigger.payload_json['after']['label'] in ['person', 'car', 'pet',
      'delivery', 'package'] }}
actions:
  - data:
      title: Frigate Alert
      message: "{{ trigger.payload_json['after']['label'] | capitalize }} detected!"
      data:
        image: >-
          http://192.168.[redacted]:8555/api/events/{{
          trigger.payload_json['after']['id'] }}/snapshot.jpg
        clickAction: /lovelace/frigate
    action: notify.mobile_app_batphone
mode: parallel
```

**Comment by SgtBatten** [comment]
If you want to use frigate/events you need to use an older version starting with 0.12. 0.14 uses reviews.

**Comment by leedomike** [comment]
Okay, I had to look into it and make some updates (with some chatgpt help). I was able to get reviews working with my Frigate, I can manually receive MQTT for frigate/reviews, and my hand made automation triggers. I still can't get your blueprint to trigger. 

Your blueprint yaml 
``` 
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.boyz_ii_cam
    notify_device: 2e61dc0d89a1bae8edccb47599547eb1
    cooldown: 30
    mqtt_topic: frigate/reviews
    debug: true
```
Handmade automation yaml 
``` 
alias: Frigate Snapshot Notifications
description: Send a notification with a snapshot for each detection.
triggers:
  - topic: frigate/reviews
    trigger: mqtt
conditions:
  - condition: template
    value_template: >
      {{ trigger.payload_json['after']['label'] in ['person', 'car', 'pet',
      'delivery', 'package'] }}
actions:
  - data:
      title: Frigate Alert
      message: "{{ trigger.payload_json['after']['label'] | capitalize }} detected!"
      data:
        image: >-
          http://192.168.[redacted]:8555/api/events/{{
          trigger.payload_json['after']['id'] }}/snapshot.jpg
        clickAction: /lovelace/frigate
    action: notify.mobile_app_batphone
mode: parallel
```
Frigate.yaml 
```
mqtt:
  enabled: true
  host: 192.168.[redacted]
  port: 1883  # Add this line
  user: [redacted]
  password: [redacted]
  topic_prefix: frigate
objects:
  track:
    - person
    - car
  filters:
    person:
      min_score: 0.5
      threshold: 0.7
detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  boyz_ii_cam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.[redacted]:8554/boyz-ii-cam
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 1
    record:
      enabled: true
      retain:
        days: 0.04
    review:      # <-- Add at this indentation level
      alerts:
        labels:
          - car
          - person
      detections:
        labels:
          - car
          - person
motion:
  enabled: true
  threshold: 50
  contour_area: 20
  improve_contrast: true

version: 0.15-1

semantic_search:
  enabled: true
  reindex: true
  model_size: small
```
