### ISSUE TITLE
[Config Support]: zone and detection

### ISSUE THREAD

**Issue by Frazou1** [SgtBatten/HA_blueprints#414]
### Describe the problem you are having or the outcome you are trying to achieve.

I find a problem and im not sure where they come from. I have the blueprint beta and i put a zone and ogject. In this exemple object was person. This afternoon i got a notification and when i look into the clip they was 7 minutes !!  I look the video and at the begining i saw a car coming but they are not on my zone identified. At the end like 30 sec before the clip finish i saw the person. So i dont understand how they recording during 7 min the clip ! Also in frigate i have a clip for the last 30 sec where we saw the person !

### Version

0.14.0.3f

### Automation config

```yaml
alias: Frigate Notifications (0.14.0.3f)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.camera_sonette
    notify_device: d0d9e52e51bf00ca693a6161e29b1b6a
    zone_filter: true
    zones:
      - cam_sonette_motion
    labels:
      - person
      - cat
      - dog
```

### Frigate Config

```yaml

```
