### ISSUE TITLE
[Config Support]: Message template not showing up

### ISSUE THREAD

**Issue by tbowmo** [SgtBatten/HA_blueprints#416]
### Describe the problem you are having or the outcome you are trying to achieve.

I'm using 0.14.02w, and I have the following message template set `{{ label }} {{ ' er' if type == 'end' else '' }} detekteret på {{ camera_name }} {% if enteredzones %} ved {{ enteredzones | join(', ') | replace('_',' ') }}{% endif %}`

However, it never shows anything like this on my phone (android), are there any hidden ninja tricks that I need to perform, in order to get the message formatted like this?

I do get notifications with video and snapshots, including the 3 buttons at the bottom of the notification. But the title / message is missing.

### Version

0.14.0.2w

### Automation config

```yaml
alias: Test Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.syd
      - camera.nord
    zones:
      - frontdoor
      - driveway
      - Porten
    notify_device: b29f11ba84d6aa265daf8bdb61cfd876
    review_severity:
      - alert
    cooldown: 0
    message: >-
      {{ label }} {{ ' er' if type == 'end' else '' }} detekteret på {{
      camera_name }} {% if enteredzones %} ved {{ enteredzones | join(', ') |
      replace('_',' ') }}{% endif %}
    update_sub_label: false
    final_update: true
    alert_once: true
    icon: mdi:cctv
```

### Frigate Config

```yaml
ui:
  time_format: 24hour

tls:
  enabled: false

mqtt:
  enabled: true
  host: 192.168.3.117
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'
detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: true
  mode: objects
  width: 1280
  height: 720
  restream: true
  layout:
    max_cameras: 4

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - cat
    - dog
  filters:
    motorcycle:
      min_score: 0.7
    bicycle:
      min_score: 0.7

go2rtc:
  streams:
    syd:
      - ffmpeg:http://192.168.3.121/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
    nord:
      - ffmpeg:http://192.168.3.122/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}#video=copy#audio=copy#audio=opus
    syd_sub:
      - ffmpeg:http://192.168.3.121/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}
    nord_sub:
      - ffmpeg:http://192.168.3.122/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=frigate&password={FRIGATE_RTSP_PASSWORD}
#    syd_laden:
#      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.3.111/11
#    nord_laden:
#      - rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@192.168.3.112/11
  webrtc:
    candidates:
      - 192.168.1.72:8555
      - stun:8555

detect:
  fps: 4

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: true
  retain:
    default: 30

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  syd:
    ui:
      order: 1
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/syd_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/syd
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask: 0,0,0.999,0,1,0.268,0.499,0.233,0,0.273
    birdseye:
      order: 1
    zones:
      frontdoor:
        coordinates: 1,0.512,1,0.284,0.88,0.266,0.872,0.491
        inertia: 3
        loitering_time: 1
        objects:
          - bicycle
          - cat
          - dog
          - motorcycle
          - person
      klinik:
        coordinates: 0.242,0.29,0.267,0.515,0.406,0.498,0.386,0.271
        loitering_time: 0
        objects:
          - person
          - dog
          - cat
      porten:
        coordinates: 0,0.804,0.2,0.729,0.193,0.391,0.003,0.422
        inertia: 3
        loitering_time: 0
      driveway:
        coordinates: 1,0.602,1,1,0.565,1,0.431,0.561
        loitering_time: 0
    objects:
      filters:
        car: {}
        person: {}
    review:
      alerts:
        required_zones:
          - frontdoor
          - porten
          - klinik
          - driveway
  nord:
    ui:
      order: 2
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nord_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/nord
          input_args: preset-rtsp-restream
          roles:
            - record
    motion:
      mask: 0,0,1,0,1,0.436,0.494,0.31,0.409,0.227,0.219,0.207,0,0.204
      threshold: 30
      contour_area: 10
      improve_contrast: true
    birdseye:
      order: 2
    zones:
      frontdoor:
        coordinates: 0.036,0.221,0.176,0.215,0.178,0.419,0.037,0.442
        inertia: 3
        loitering_time: 0
        objects:
          - bicycle
          - cat
          - dog
          - motorcycle
          - person
      driveway:
        coordinates: 0.392,0.232,0.306,0.66,1,0.664,0.994,0.288
        inertia: 3
        loitering_time: 0
      porten:
        coordinates: 0.733,0.622,0.707,1,1,1,1,0.592
        loitering_time: 0
    review:
      alerts:
        required_zones:
          - driveway
          - frontdoor
          - porten
    objects:
      filters:
        car: {}
  syd_laden:
    ui:
      order: 3
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/syd_laden
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      order: 3
    zones: {}
    objects:
      filters:
        car:
          mask: 0.787,0.148,0.995,0.175,0.988,0.464,0.769,0.406
        person:
          mask: 0.758,0.69,0.927,0.686,0.957,1,0.763,0.991
        motorcycle:
          min_score: 0.7
        bicycle:
          min_score: 0.7
    review:
      detections:
        labels:
          - person
          - cat
          - dog

    motion:
      mask:
        - 0.157,0,0.175,0.837,0.299,0.889,0.369,0.79,0.426,0.629,0.371,0.554,0.379,0,0.353,0,0.336,0.677,0.23,0.76,0.212,0
        - 0.737,0.001,0.764,0,0.749,0.256,0.807,0.211,0.84,0.261,0.705,0.426,0.649,0.36,0.674,0.105,0.689,0,0.716,0,0.708,0.247,0.721,0.291
        - 0.461,0.572,0.445,0.714,0.508,0.72,0.525,0.576
  nord_laden:
    ui:
      order: 4
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nord_laden
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      enabled: false
    zones:
      porten:
        coordinates: 0,0,0.459,0,0.473,0.564,0.282,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: porten
      detections:
        labels:
          - person
          - cat
          - dog
    objects:
      filters:
        car:
          mask: 0,0,1,0,1,1,0,1
        motorcycle:
          mask: 0,0,1,0,1,1,0,1
          min_score: 0.7
        bicycle:
          min_score: 0.7
    motion:
      mask: 
        0.273,0.008,0.305,0.005,0.331,0.692,0.406,0.564,0.412,0.624,0.194,1,0.179,1,0.096,0,0.14,0,0.203,0.919,0.304,0.738
version: 0.15-1
camera_groups:
  Birdseye:
    order: 1
    icon: LuAirplay
    cameras: birdseye
```
