### ISSUE TITLE
[Config Support]: automatisation via blueprint does not trigger

### ISSUE THREAD

**Issue by geertvindevogel** [SgtBatten/HA_blueprints#417]
### Describe the problem you are having or the outcome you are trying to achieve.

I downloaded the blueprint but ik looks like the automation doesn’t trigger. I can choose my camera and my phone in the automation config but Nothing happens after a detection or alert. I run frigate in a container on proxmox. In frigate I see the alerts or detections. In HA I added frigate via HACS and that seems to work. What have I forgotten or did wrong? 

### Version

0.14.0.2w

### Automation config

```yaml
alias: AutoDetectie via blueprint
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.garage
    notify_device: 9244f940d5fefcead18a1032227a0d11
    title: Detection
    message: A car was detected on the Garage camera.
    zone_filter: true
    zones:
      - ZNVooraan
    labels:
      - car
      - person
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    debug: true
```

### Frigate Config

```yaml

```
