### ISSUE TITLE
[Config Support]: Two notifications from the same camera

### ISSUE THREAD

**Issue by Doriginal** [SgtBatten/HA_blueprints#419]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,
How can I get two notifications from the same camera?

I would like to have this:

1. A first notification with a cropped snapshot
2.  A second notification with a GIF

While keeping both notifications

Currently I've created two automations, one with the cropped snapshot and the second with the GIF, but the second notification overwrites the first.
I'm on ios.

Thanks again for your help.

### Version

0.14.0.2w

### Automation config

```yaml
alias: Frigate Notifications Avant Snapshot (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.tapo_avant
    notify_device: daaed97d453cc6f357441f63f56d8f03
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    title: Frigate
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    final_update: true
    labels:
      - person
      - dog
      - cat
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    initial_delay: 0
    base_url: https://*********.fr:59999
    debug: true
    redacted: false
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8


alias: Frigate Notification Avant GIF (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.tapo_avant
    notify_device: daaed97d453cc6f357441f63f56d8f03
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    title: Frigate
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    final_update: true
    labels:
      - person
      - dog
      - cat
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    initial_delay: 10
    base_url: https://******.fr:59999
    debug: true
    redacted: false
    final_delay: 15
```

### Frigate Config

```yaml

```
