### ISSUE TITLE
[Issue]: After Frigate 0.15 update clip and snaphsot not loading anymore

### ISSUE THREAD

**Issue by davide-molino** [SgtBatten/HA_blueprints#421]
### Description

Hi, After the Frigate 0.15 update the notification loads an error message as thumbnail/snapshot. If I tap on the notification I get a crossed play icon  instead of the clip. Tried also with the beta version of the blueprint but the issue remains. Every mobile device i tested this on is iOS (latest version available).

### Version

0.14.0.2w - 0.14.0.3f

### Automation Config

```yaml
alias: Notifica Facciata
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.1_facciata
    notify_device: [REDACTED]
    base_url: https://[REDACTED]
    message: "{{ label }} detected - {{ camera_name }}"
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    final_update: true
    labels:
      - person
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml
This from the trace output is the block that fails


condition: or
conditions:
  - condition: trigger
    id: silence
  - condition: trigger
    id: custom
  - condition: and
    conditions:
      - condition: trigger
        id: frigate-event
      - alias: Camera Match
        condition: template
        value_template: '{{ input_camera_name|select(''equalto'', camera)|list|length>0 }}'
      - alias: Master Condition
        condition: []
      - alias: Cooldown
        condition: template
        value_template: >-
          {{ not this.attributes.last_triggered or (now() -
          this.attributes.last_triggered).seconds > cooldown }}
      - alias: Disable Times
        condition: template
        value_template: >-
          {{ not disable_times|length or not now().hour in
          disable_times|map('int')|list }}
```
