### ISSUE TITLE
[Issue]: Silence New Notifications not working if automation has a hyphen ( - ) in it

### ISSUE THREAD

**Issue by TES-Kyle** [SgtBatten/HA_blueprints#423]
### Description

I'm not sure if I may be doing something incorrectly but I was having issues with "Silence New Notifications" action button (placed in action button 3) on my android phone. When I clicked it, it would not silence new notification for that automation.

I listened to the event "mobile_app_notification_action" and noticed that the action URL and other info was referencing:
silence-automation.garage2_camera_phone

When the title of the automation was actually:
Garage2 Camera - Phone

This is the only name that automation had. I tried to recreate the automation to make sure this is indeed what was happening. Then after recreating it, I removed the hyphen between Camera and Phone and left a single space and the "Silence New Notifications" action functioned as expected.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Garage2 Camera - Phone
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.garage2
    notify_device: 1f41be33271e5e113389ba99945e1998
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    attachment_2: ""
    channel: CameraAlert
    review_severity:
      - alert
    tap_action: /ccab4aaf_frigate/dashboard
    custom_action_manual: []
    tv: true
    tv_position: bottom-right
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml
event_type: mobile_app_notification_action
data:
  tag: 1743279503.429333-3nn52t
  group: Garage2-frigate-notification
  color: "#03a9f4"
  subject: ""
  image: /api/frigate/notifications/1743279503.429333-3nn52t/snapshot.jpg?bbox=1
  video: ""
  clickAction: /ccab4aaf_frigate/dashboard
  ttl: "0"
  priority: high
  notification_icon: mdi:homeassistant
  sticky: "false"
  channel: CameraAlert
  car_ui: "false"
  subtitle: ""
  url: /ccab4aaf_frigate/dashboard
  attachment: >-
    {url=/api/frigate/notifications/1743279503.429333-3nn52t/snapshot.jpg?bbox=1,
    content-type=jpeg}
  push: "{sound={name=default, volume=1.0, critical=0}}"
  entity_id: ""
  action_1_key: URI
  action_1_title: View Clip
  action_1_uri: /api/frigate/notifications/1743279503.429333-3nn52t/Garage2/clip.mp4
  action_2_key: URI
  action_2_title: View Snapshot
  action_2_uri: /api/frigate/notifications/1743279503.429333-3nn52t/snapshot.jpg
  action_3_key: silence-automation.garage2_camera_phone
  action_3_title: Silence New Notifications
  action_3_uri: silence-automation.garage2_camera_phone
  message: A Person was detected on the Garage2 camera.
  webhook_id: 763e321a2d86ef5bcea0bc75fd83aa552f86c6262db315bbc5b8b47f415b0895
  server_id: "1"
  action: silence-automation.garage2_camera_phone
  device_id: 96ba3b4c04f282fb
origin: REMOTE
time_fired: "2025-03-29T20:48:52.121776+00:00"
context:
  id: 01JQHTM7WS34KVZTFSBQ6K60AN
  parent_id: null
  user_id: fe9a4934d2604e2f86d9cc8a94e483bd
```
