### ISSUE TITLE
[Config Support]:

### ISSUE THREAD

**Issue by switchyfoot** [SgtBatten/HA_blueprints#424]
### Describe the problem you are having or the outcome you are trying to achieve.

Trying to get directional alerts working. I have required zones for alerts set in Frigate, and the notifications work well. This is an example of my frigate configuration for a zone:
`    review:
      alerts:
        required_zones:
          - Side_Gate
          - Side_Border
        labels:
          - person
    
    zones:
      Side_Gate:
        coordinates: 0,0,0.256,0,0.445,0.286,0.85,0.679,0,0.787
        loitering_time: 0
        objects:
          - person
        inertia: 3
      Side_Border:
        coordinates: 
          0,0.817,0.924,0.695,0.481,0.284,0.286,0.001,0.258,0.002,0.45,0.288,0.852,0.68,0,0.788
        loitering_time: 0
        objects:
          - person`

If I set the blueprint filters for only Alerts, Zone Filter = On, Required Zones = Side_Gate, and Object Filter = person - then I will get a notifications properly. But, when I try to add the Side_Border zone and toggle multi-zone and zone order, I get no notifications for a person walking through in either direction.

I really want to set this up so if a person crosses the "Side_Border" zone first then enters the "Side_Gate", then I get a notification.

### Version

0.14.0.2w

### Automation config

```yaml
alias: Frigate Notifications - Side Entry Alert
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.side
    notify_device: 872f3eb93e672a29c73e53a081b60a07
    base_url: http://192.168.10.199:8123
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1&crop=1&format=android
    labels:
      - person
    update_sub_label: false
    attachment_2: ""
    title: "{{ label }} detected - {{  camera_name  }}"
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    icon: mdi:shield-account
    group: "{{camera}} Camera"
    channel: >-
      {{ 'DayChannel' if is_state('input_boolean.quiet_hours', 'off') else
      'NightChannel' }}
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    button_2: View Stream
    debug: false
    review_severity:
      - alert
    notify_group: both_mobiles
    zones:
      - Side_Border
      - Side_Gate
    zone_multi: true
    zone_filter: true
    zone_order_enforced: true
    alert_once: true
```

### Frigate Config

```yaml
Side: # <------ Name IP203 camera
    enabled: true
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.123.203:554/cam/realmonitor?channel=1&subtype=2 # <----- The stream used for detection
          roles:
            - detect
        - path: rtsp://user:pass@192.168.123.203:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream used for recording
          roles:
            - record
    detect:
      enabled: true
      width: 1080
      height: 1920
    objects:
      track:
        - person
        - dog
        - cat
        - raccoon
        - fox
        - rabbit
        - bird
        - squirrel
        - robot lawnmower
      filters:
        person:
          min_score: .65
          threshold: .85
        dog:
          min_score: .70
          threshold: .90
        cat:
          min_score: .65
          threshold: .80
        raccoon:
          min_score: .65
          threshold: .80
        fox:
          min_score: .65
          threshold: .80
        rabbit:
          min_score: .65
          threshold: .80
        bird:
          min_score: .65
          threshold: .80
        squirrel:
          min_score: .65
          threshold: .80
        robot lawnmower:
          min_score: .65
          threshold: .80
    review:
      alerts:
        required_zones:
          - Side_Gate
          - Side_Border
        labels:
          - person
    record:
      enabled: true
    snapshots:
      enabled: true
      timestamp: false
    motion:
      mask: 0.457,0.043,0.458,0.064,0.949,0.065,0.95,0.042

    zones:
      Side_Gate:
        coordinates: 0,0,0.256,0,0.445,0.286,0.85,0.679,0,0.787
        loitering_time: 0
        objects:
          - person
        inertia: 3
      Side_Border:
        coordinates: 
          0,0.817,0.924,0.695,0.481,0.284,0.286,0.001,0.258,0.002,0.45,0.288,0.852,0.68,0,0.788
        loitering_time: 0
        objects:
          - person
```
