### ISSUE TITLE
Reolink POE Duo video not playing

### ISSUE THREAD

**Issue by staceychambers** [SgtBatten/HA_blueprints#426]
### Describe the problem you are having or the outcome you are trying to achieve.

I have numerous cameras connected to Frigate and sending notifications via the Frigate Notifications Blueprint. However I have a dual lens Reolink camera that the video is failing to play in the notifications. I am using a duplicated blueprint from another camera that is working correctly. I have confirmed that this camera is saving recordings and clips with the other cameras in the Frigate folder. Has anyone else successfully received video notifications from dual lens 180 degree cameras?

### Version

Frigate Notifications (0.14.0.2w)

### Automation config

```yaml
alias: Frigate_Frontyard_Mailbox
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_yard
    notify_device: ad2d477152bcd5cfeec530a7e710febb
    labels: []
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1&crop=1
    title: Someone is at the Mailbox
    message: There is a car stopped at the mailbox
    zone_filter: true
    zones:
      - Mailbox
    loiter_timer: 0
    url_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    base_url: https://f6bl1mdmckymv4he6ysvzqqa31jdlpv0.ui.nabu.casa
    tv: false
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1&crop=1
```

### Frigate Config

```yaml

```

### Any other information that may be helpful

all other cameras including Reolink play the video. its just the POE Duo dual lens 180 degree camera
