### ISSUE TITLE
[Config Support]: Cooldown when multiple cameras are using a single SgtBatteb blueprint

### ISSUE THREAD

**Issue by narsaw** [SgtBatten/HA_blueprints#427]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello since this blueprint allows you to select more than one camera entity in the "**Frigate Cameras**" section I went ahead and did that. I have 7 cameras and I selected each one. 

In the Timers section, there is a "**Cooldown**" feature with a description that says "_Delay before sending another notification for this camera after the last event_"

What does happens to "this camera" when this blueprint has 7 camera entities? I am noticing that some alerts from Frigate is not trigger a HA notification. In the Trace for a failed notification I see:

`Cooldown]
Executed: April 7, 2025 at 11:22:38 PM
Result:
result: false
entities: []`

### Version

0.14.0.2w

### Automation config

```yaml
alias: Frigate multi-camera notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.backyard
      - camera.drivewayeast_2
      - camera.drivewaywest_2
      - camera.frontdoor
      - camera.rightgate
      - camera.sportcourt
      - camera.frontyard
    notify_device: 8f31755b849221844ab0e1d2609c29a4
    base_url: https://ha01.sawhsystems.com
    title: Motion detected
    message: >-
      A {{ label }} {{ ' was' if type == 'end' else '' }} detected on the {{
      camera_name }} camera.
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1
    attachment_2: ""
    final_update: false
    master_condition:
      - condition: state
        entity_id: input_boolean.disable_outside_motion_notification
        state: "off"
    zone_filter: true
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    zones:
      - frontdoor_area
      - entire_front
      - enter_driveway
      - zbackyard
      - zsportcourt
      - rightside
      - in_driveway
    labels:
      - person
      - dog
      - car
      - cat
    cooldown: 30
    silence_timer: 60
    icon_1: "sfsymbols:video\t"
    icon_2: sfsymbols:camera
    icon_3: sfsymbols:pause.rectangle
    url_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
```

### Frigate Config

```yaml

```
