### ISSUE TITLE
[Config Support]: Reolink Duo 3 notification video not playing

### ISSUE THREAD

**Issue by staceychambers** [SgtBatten/HA_blueprints#428]
### Describe the problem you are having or the outcome you are trying to achieve.

I have numerous cameras connected to Frigate and sending notifcation via the HA Frigate Notification blueprint with video. I have two Reolink cameras and one of them is sending video successfully(Trackmix) however the POE Duo 3 is sending notificaiton but the video has a broken link and will not play. i have duplicated known working blueprints from others notifications and changed the camera and zones but cannot get video to send. 

### Version

Frigate Notifications (0.14.0.2w)

### Automation config

```yaml
alias: Frigate_Frontyard_Mailbox
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_yard
    notify_device: ad2d477152bcd5cfeec530a7e710febb
    labels: []
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1&crop=1
    title: Someone is at the Mailbox
    message: There is a car stopped at the mailbox
    zone_filter: true
    zones:
      - Mailbox
    loiter_timer: 0
    url_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    base_url: https://f6bl1mdmckymv4he6ysvzqqa31jdlpv0.ui.nabu.casa
    tv: false
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?bbox=1&crop=1
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.6
  user: mqtt_user
  password: HA@409!Homeassistant

# api:
#   listen: 0.0.0.0:8971

record:
  enabled: true
  retain:
    days: 2
    mode: motion
  alerts:
    retain:
      days: 2
  detections:
    retain:
      days: 2

snapshots:
  enabled: true
  retain:
    default: 2

go2rtc:
  streams:
    driveway_sub: rtsp://login:pass@1$@192.168.1.190:554/h264Preview_01_sub
    Front_yard: rtsp://login:pass@1$@192.168.1.224:554/h264Preview_01_sub

cameras:
  Bourbon_room:
    ffmpeg:
      inputs:
        - path: rtsp://Eufy_Lumberton4:Lumberton_1@192.168.1.140/live0
          roles:
            - detect

    detect:
      width: 720  # Adjust as per your camera specs
      height: 480
      fps: 5

    motion:
      mask:
        - 0.989,0.075,0.512,0.082,0.52,0.006,0.994,0.006
        - 0.1,0.599,0.313,0.576,0.308,0.012,0.096,0.012,0.073,0.505
    zones:
      Bourbon_Zone:
        coordinates: 0.442,0.711,0.44,0.164,0.747,0.181,0.755,0.685
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Bourbon_Zone
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://Eufy_Lumberton4:Lumberton_1@192.168.1.160/live0
          roles:
            - detect

    detect:
      width: 720  # Adjust as per your camera specs
      height: 480
      fps: 5

    motion:
      mask: 0.002,0.106,0.998,0.094,0.996,0.003,0.003,0.009
    zones:
      Garage_Zone:
        coordinates: 0.154,0.99,0.182,0.365,0.615,0.29,0.927,0.336,0.908,0.993
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: Garage_Zone
      detections:
        required_zones: Garage_Zone
  Front_Yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_yard
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/Front_yard
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 1536  # Adjust as per your camera specs
      height: 432
      fps: 7
    objects:
      track:
        - person
        - car
        - bus
        - bicycle
    zones:
      Mailbox:
        coordinates: 0.277,0.12,0.3,0.305,0.632,0.313,0.624,0.114
        loitering_time: 0
        inertia: 3
      Sidewalk:
        coordinates: 0.937,0.418,0.838,1,0.814,1,0.513,0.446,0.49,0.341,0.634,0.319,0.766,0.19
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      threshold: 30
      contour_area: 16
      improve_contrast: true
      mask:
        - 0,0,0,0.523,0.213,0.204,0.278,0.095,0.63,0.091,0.634,0.003
        - 0.538,0.5,0.801,0.989,0.45,0.997,0.448,0.662
    review:
      alerts: {}
      detections: {}

  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/driveway_sub
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 896 # Adjust as per your camera specs
      height: 512
      fps: 6
    zones:
      Driveway_zone:
        coordinates: 0.11,0.564,0.487,0.451,0.978,0.597,0.881,0.985,0.125,0.991
        loitering_time: 0
    review:
      alerts:
        required_zones: Driveway_zone
      detections: {}

  Porch:
    ffmpeg:
      inputs:
        - path: rtsp://Eufy_Lumberton4:Lumberton_1@192.168.1.149/live0
          roles:
            - detect

    detect:
      width: 720  # Adjust as per your camera specs
      height: 480
      fps: 5

    objects:
      track:
        - person
        - dog

    zones:
      Porch_Zone:
        coordinates: 0.017,1,0.361,0.435,0.821,0.672,0.742,1
        loitering_time: 0
        inertia: 3
    motion: {}
    review:
      alerts:
        required_zones: Porch_Zone
      detections: {}
  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://Eufy_Lumberton4:Lumberton_1@192.168.1.169/live0
          roles:
            - detect

    detect:
      width: 720  # Adjust as per your camera specs
      height: 480
      fps: 5

    zones:
      Couch:
        coordinates: 0,0.229,0.101,0.709,0.794,0.931,0.8,0.267
        loitering_time: 0
        objects: person
        inertia: 3
    motion:
      mask: 
        0,0,0,0.154,0.317,0.135,0.381,0.161,0.447,0.237,0.703,0.246,0.842,0.116,0.992,0.107,0.994,0.007
      threshold: 36
      contour_area: 26
      improve_contrast: true
    review:
      alerts:
        required_zones: Couch
      detections:
        required_zones: Couch

    objects:
      filters:
        person:
          mask: 0.398,0.216,0.757,0.241,0.708,0.004,0.383,0.009
  Office:
    ffmpeg:
      inputs:
        - path: rtsp://Eufy_Lumberton4:Lumberton_1@192.168.1.171/live0
          roles:
            - detect
    objects:
      track:
        - person
        - dog

    detect:
      width: 720  # Adjust as per your camera specs
      height: 480
      fps: 5
    zones:
      Pets:
        coordinates: 0,0.415,0,0.991,0.261,1,0.178,0.416
        loitering_time: 0
        inertia: 3
      dogbed:
        coordinates: 0.512,1,0.528,0.37,0.992,0.289,0.999,0.722,0.993,0.99
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 38
      contour_area: 18
      improve_contrast: true
    review:
      alerts:
        required_zones: Pets
      detections:
        required_zones: Pets
version: 0.15-1
```

### Any other information that may be helpful

![Image](https://github.com/user-attachments/assets/b9a042fe-0ea5-4af9-a27a-d053889630d5)

The stream plays on my ios in HA just not in notifications

![Image](https://github.com/user-attachments/assets/5664258f-5439-44b1-8369-daef3f06940c)

![Image](https://github.com/user-attachments/assets/c2ec5900-f5de-4b45-8e98-39c0b3569dd1)
