### ISSUE TITLE
[Config Support]: iOS stream blank when using go2rtc stream

### ISSUE THREAD

**Issue by ideasman69** [SgtBatten/HA_blueprints#430]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi, I've been using this blueprint for the past few months and LOVE it. Recently I installed a POE doorbell which required me to use go2rtc for 2 way communication. Noticed that when using go2rtc, pressing and holding on the iOS notification no longer plays a live stream of the camera.

I've been able to reproduce using my two amcrest cameras.

When the cameras are configured in Frigate directly to the rtsp stream (**Driveway** in the attached Frigate config), i get the live preview in iOS like this:
![Image](https://github.com/user-attachments/assets/cbe1ad1c-1dd2-4b3c-977d-68d93fda57c1)

When the cameras are configured through go2rtc (**Front yard** in the attached Frigate config), i just get a black screen.

All cameras (both direct rtsp and go2rtc) stream fine in the HomeAssistant app and look noticeably better when configured to use go2rtc.

Any assistance would be greatly appreciated!

### Version

0.14.0.2w

### Automation config

```yaml
alias: CCTV - Driveway
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.driveway
    notify_device: 714fed9ef52eb54cbdc049ffd715ccc9
    base_url: https://urlredacted
    message: "{{ label }} detected - {{ camera_name }}"
    title: Driveway
    update_sub_label: false
    ios_live_view: camera.driveway
    tap_action: homeassistant://navigate/dashboard-home/security
```

### Frigate Config

```yaml
go2rtc:
  streams:
    front_yard:
      - rtsp://user:pass@camera1:554/cam/realmonitor?channel=1&subtype=0
    front_yard_sub:
      - rtsp://user:pass@camera1:554/cam/realmonitor?channel=1&subtype=1

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@camera2:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://user:pass@camera2:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_yard_sub
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/front_yard
          roles:
            - record
```
