### ISSUE TITLE
[Issue]: error when making new automation

### ISSUE THREAD

**Issue by olemal** [SgtBatten/HA_blueprints#431]
### Description

Fairly fresh install of HAOS, HACS, Blueprint latest. Tested both latest and latest beta frigate notifications. When I add a new automation I get an error and it wont send notifications. I did reinstall frigate integration (5.8.0) to verify if I checked "Enable the unauthenticated notification event proxy" but I did not see it. 

error:
Logger: homeassistant.helpers.template
Source: helpers/template.py:2917
First occurred: 5:28:38 PM (2 occurrences)
Last logged: 5:28:38 PM

Template variable warning: 'None' has no attribute 'entity_id' when rendering 'silence-{{ this.entity_id }}'
Template variable warning: 'None' has no attribute 'entity_id' when rendering 'custom-{{ this.entity_id}}'

### Version

Stable 0.14.0.2w, Beta 0.14.0.3h

### Automation Config

```yaml
alias: New automation
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.wificam
    notify_device: e89909aeaa84b866186a53ceb2d85b39
    base_url: http://10.0.1.99:8123
```

### Frigate Config

```yaml
mqtt:
  host: 10.0.1.98
  port: 1883
  user: usr
  password: pwd
  client_id: frigate
  topic_prefix: frigate/review
  stats_interval: 60

record:
  enabled: true
  retain:
    days: 2
    mode: all
  alerts:
    retain:
      days: 7
  detections:
    retain:
      days: 7

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

go2rtc:
  streams:
    wifiCam:
      - ffmpeg:rtsp://usr:pwd@10.0.1.220:554/h264Preview_01_main
      - ffmpeg:wifiCam#audio=opus

cameras:
  wifiCam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/wifiCam?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - record
    onvif:
      host: 10.0.1.220
      port: 8000
      user: usr
      password: pwd
    audio:
      enabled: true
      listen:
        - bark
        - fire_alarm
        - scream
        - speech
        - yell
    detect:
      width: 896
      height: 512
      fps: 10
    objects:
      track:
        - dog
        - person
    motion: {}
version: 0.15-1
```

### Any other relevant information

```yaml
Logger: homeassistant.helpers.template
Source: helpers/template.py:2917
First occurred: 5:28:38 PM (2 occurrences)
Last logged: 5:28:38 PM

Template variable warning: 'None' has no attribute 'entity_id' when rendering 'silence-{{ this.entity_id }}'
Template variable warning: 'None' has no attribute 'entity_id' when rendering 'custom-{{ this.entity_id}}'
```
