### ISSUE TITLE
[Issue]: Notification snapshot is not resized to fit phone screen (Pixel 6 Pro/ Android 15)

### ISSUE THREAD

**Issue by mojo17** [SgtBatten/HA_blueprints#432]
### Description

When I receive a notification and tap on the View Snapshot action button, the image that loads is very large, and only a small portion shows up on the screen. I have to pan around to see it all. Pinching to zoom out does not work either.

The expectation is that the image is resized to fit on the phone screen.

I'm encountering this issue on Pixel 6 Pro running Android 15.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_door
    notify_device: 4XXXXc2b96cdXXXXc0c4faca4f2XXXX
    title: Person Detected
    alert_once: true
    icon: mdi:cctv
    labels:
      - person
    button_1: Clip
    button_2: Snapshot
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
