### ISSUE TITLE
[Config Support]: Automation does not trigger

### ISSUE THREAD

**Issue by anatom74** [SgtBatten/HA_blueprints#433]
### Describe the problem you are having or the outcome you are trying to achieve.

I get frigate/reviews published (checked with MQTT Explorer) but no triggers in Automation

frigate/reviews event:

```
{"type": "new", "before": {"id": "1745222649.767392-k6afi2", "camera": "CAM-Frontyard", "start_time": 1745222649.767392, "end_time": null, "severity": "detection", "thumb_path": "/media/frigate/clips/review/thumb-CAM-Frontyard-1745222649.767392-k6afi2.webp", "data": {"detections": ["1745222340.297824-ci1n0k"], "objects": ["car"], "sub_labels": [], "zones": [], "audio": []}}, "after": {"id": "1745222649.767392-k6afi2", "camera": "CAM-Frontyard", "start_time": 1745222649.767392, "end_time": null, "severity": "detection", "thumb_path": "/media/frigate/clips/review/thumb-CAM-Frontyard-1745222649.767392-k6afi2.webp", "data": {"detections": ["1745222340.297824-ci1n0k"], "objects": ["car"], "sub_labels": [], "zones": [], "audio": []}}}
```
`

### Version

0.14.0.3h

### Automation config

```yaml
alias: Frigate Camera Notification
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.cam_entrance
      - camera.cam_north
      - camera.cam_frontyard
      - camera.cam_west
    notify_device: a9fcc6bbfef2ec5fd6828086e2a5a747
    silence_timer: 2
    debug: true
```

### Frigate Config

```yaml
auth:
  # Optional: Enable authentication
  enabled: false

mqtt:
  enabled: true
  host: 192.168.10.20
  user: mqtt-user
  password: ***
  stats_interval: 60
  port: 1883

database:
  path: /config/frigate.db

#model:
#  path: plus://e63b7345cc83a84ed79dedfc99c16616

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

detectors:
  coral:
    type: edgetpu
    device: usb

version: 0.15-1

### Camera Settings ###
### Front Camera - Facing SE  IPC-T5442TM-AS 2.8mm ###
cameras:
  CAM-Frontyard:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 0
    birdseye:
      order: 0
    ffmpeg:
      #hwaccel_args:
      #  - -c:v:1
      #  - h264_v4l2m2m
      inputs:
        - path: rtsp://admin:***@192.168.10.91:554/livecam/realmonitor?channel=1&subtype=0
          roles:
            #- rtmp
            - record
            #- detect

        - path: rtsp://admin:***@192.168.10.91:554/livecam/realmonitor?channel=1&subtype=2
          roles:
            - detect

    motion:
      threshold: 34
      contour_area: 15
      improve_contrast: true
      mask: 0.065,1,0.05,0.873,0.045,0.737,0.157,0.723,0.107,0.435,0,0.343,0,1,0.075,1

    detect:
      enabled: true
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true

    objects:
      filters:
        person:
          mask:
            - 0.365,0,0.364,0.063,0.381,0.065,0.379,0.002
            - 0.402,0.002,0.399,0.069,0.422,0.067,0.421,0.002
            - 0.435,0.008,0.442,0.067,0.456,0.065,0.456,0.006
            - 0.512,0.016,0.517,0.067,0.528,0.067,0.529,0.012
            - 0.478,0.002,0.481,0.061,0.492,0.061,0.495,0.008
            - 0.402,0.002,0.399,0.069,0.422,0.067,0.421,0.002
            - 0.435,0.008,0.442,0.067,0.456,0.065,0.456,0.006
            - 0.512,0.016,0.517,0.067,0.528,0.067,0.529,0.012
            - 0.542,0.012,0.545,0.067,0.558,0.067,0.556,0.018
      mask:
        - 0.402,0.002,0.399,0.069,0.422,0.067,0.421,0.002
        - 0.435,0.008,0.442,0.067,0.456,0.065,0.456,0.006
        - 0.512,0.016,0.517,0.067,0.528,0.067,0.529,0.012
    zones: {}
  CAM-Entrance:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 1
    birdseye:
      order: 1
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:***@192.168.10.15:554/livecam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            #- rtmp
            #- detect
            - record
        - path: 
            rtsp://admin:***@192.168.10.15:554/livecam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect

    motion:
      threshold: 30

      mask:
        - 0.165,0.927,0.282,0.925,0.286,0.976,0.164,0.983
        - 0.28,0.459,0.294,0.462,0.291,0.485,0.28,0.485
        - 0.008,0.54,0.021,0.546,0.022,0.574,0.008,0.579
        - 0.074,0.353,0.364,0.406,0.656,0.45,0.915,0.407,1,0.379,1,0.078,1,0,0,0,0,0.264,0,0.323,0.042,0.337,0.017,0.326,0.043,0.333
        - 0.062,0.53,0.059,0.587,0.119,0.591,0.115,0.531
      contour_area: 15
      improve_contrast: true
    #objects:
    #  filters:
    #    person:
    # Optional: minimum width*height of the bounding box for the detected object (default: 0)
    #  min_area: 5000
    # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
    #  max_area: 100000
    # Optional: minimum width/height of the bounding box for the detected object (default: 0)
    #  min_ratio: 0.5
    # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
    #  max_ratio: 2.0
    # Optional: minimum score for the object to initiate tracking (default: shown below)
    #  min_score: 0.5
    # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
    # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
    # Checks based on the bottom center of the bounding box of the object
    #  mask: 0.000,0.000,0.781,0.000,0.781,0.278,0.000,0.278

  CAM-West:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 4
    birdseye:
      order: 4
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:***@192.168.10.223:554/livecam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        #- rtmp
        #- record

        - path: 
            rtsp://admin:***@192.168.10.223:554/livecam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
        #- rtmp

    motion:
      threshold: 39
      contour_area: 14
      improve_contrast: true
      mask:
        - 0.142,1,0,1,0,0.5,0.079,0.812,0.137,0.906,0.15,1
        - 0.276,0.211,0.244,0.234,0.225,0.272,0.228,0.3,0.32,0.327,0.354,0.267,0.358,0.227,0.315,0.201
    objects:
      filters:
        person:
          mask:
            - 0.506,0.211,0.721,0.216,0.711,0.554,0.441,0.521
            - 0.028,0.657,0.107,0.67,0.119,0.782,0.058,0.785
        dog:
          mask: 0.469,0.375,0.441,0.519,0.708,0.56,0.718,0.222,0.503,0.213
  CAM-North:
    enabled: true
    audio:
      enabled: false
    ui:
      order: 5
    birdseye:
      order: 5
    detect:
      width: 704
      height: 576
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:***@192.168.10.150:554/livecam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
          roles:
            - detect
        #- rtmp
        #- record

        - path: 
            rtsp://admin:***@192.168.10.150:554/livecam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record

    motion:
      threshold: 31
      contour_area: 12
      improve_contrast: true

      mask: 0.878,0.133,0.85,0.151,0.829,0.187,0.872,0.208,0.919,0.191,0.921,0.131

record:
  enabled: true
  retain:
    days: 14
    mode: motion

  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    # Optional: Number of seconds before the detection to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the detection to include (default: shown below)
    post_capture: 5
    # Optional: Retention settings for recordings of detections
    retain:
      # Required: Retention days (default: shown below)
      days: 14

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 30
  timestamp: true

detect:
  stationary:
    interval: 50
    threshold: 30

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - bus
    - dog
    - cat
    - bicycle
    - motorcycle
    - bird

  # Optional: filters to reduce false positives for specific object types
  filters:
    cat:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      #min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      #max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.45
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.55
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0.000,0.000,0.781,0.000,0.781,0.278,0.000,0.278

# can be overridden at the camera level
review:
  alerts:
    labels:
      - cat
      #- car
      - person

#semantic_search:
  #enabled: true
  #reindex: false
  #model_size: small
```
