### ISSUE TITLE
[Issue]: When clicking on 'view clip' it redirects to my HA instance but the video doesn't play

### ISSUE THREAD

**Issue by aaronjrodrigues** [SgtBatten/HA_blueprints#434]
### Description

I noticed that lately when I try to view the clips from my notifications it shows a weird error. I've attached a video of what happens.

https://github.com/user-attachments/assets/7a86287f-b321-4746-82a7-2554cfc4331f

I thought this was some weird cloudflare issue because I had cloudflare proxying my homeassistant requests however even after changing it, the issue still persists. Could someone please guide me as to what could be done to troubleshoot? My base url is set to my home assistant instance, so it can't be a base url issue.

Any help would be appreciated.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.aaron_backdoor
      - camera.alberts_entrance
      - camera.alberts_first_floor
      - camera.clothing_line
      - camera.dish_side
      - camera.entryway
      - camera.garage
      - camera.garden
      - camera.imou_garden
      - camera.kitchen_garden
      - camera.kitchen_side
      - camera.open_area
      - camera.rudolf_backyard
    notify_device: dca55410330127c18d5a4d25ee9e1b93
    notify_group: cameras
    message: "{{ label }} detected - {{ camera_name }}"
    labels:
      - person
    base_url: https://home.aaronrodrigues.com
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.1.116
  port: 1883
  user: mqtt
  password: 

model:
  path: plus://

semantic_search:
  enabled: true

genai:
  enabled: True
  provider: gemini
  api_key: 
  model: gemini-1.5-flash

objects:
  track:
    - person
    - dog
    - cat
    - car
    - license_plate

snapshots:
  enabled: true

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    entryway:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/101
    clothing_line:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/701
    open_area:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/301
    garden:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/401
    roadside:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/501
    gate:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/601
    rudolf_backyard:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/201
    kitchen_garden:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/801
    garage:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/901
    kitchen_side:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/1301
    dish_side:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/1101
    aaron_backdoor:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/1201
    imou_garden:
      - rtsp://admin:@192.168.1.137:554/cam/realmonitor?channel=1&subtype=0&proto=Onvif
      - ffmpeg:imou_garden#audio=opus
    ann_room:
      - rtsp://admin:@192.168.1.142:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:ann_room#audio=opus
    living_room:
      - rtsp://admin:@192.168.1.144:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      - ffmpeg:living_room#audio=opus
    alberts_entrance:
      - rtsp://admin:@192.168.0.99:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:alberts_entrance#audio=opus
    alberts_first_floor:
      - rtsp://admin:@192.168.0.102:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:alberts_entrance#audio=opus
    alberts_indoor:
      - rtsp://admin:@192.168.0.28:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:alberts_indoor#audio=opus
    low_entryway:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/102
    low_clothing_line:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/702
    low_open_area:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/302
    low_garden:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/402
    low_roadside:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/502
    low_gate:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/602
    low_rudolf_backyard:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/202
    low_kitchen_garden:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/802
    low_garage:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/902
    low_kitchen_side:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/1302
    low_dish_side:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/1102
    low_aaron_backdoor:
      - rtsp://admin:@192.168.1.160:554/Streaming/Channels/1202
    low_imou_garden:
      - rtsp://admin:@192.168.1.137:554/cam/realmonitor?channel=1&subtype=1&proto=Onvif
    low_ann_room:
      - rtsp://admin:@192.168.1.142:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    low_living_room:
      - rtsp://admin:@192.168.1.144:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
    low_alberts_entrance:
      - rtsp://admin:@192.168.0.99:554/cam/realmonitor?channel=1&subtype=1
    low_alberts_first_floor:
      - rtsp://admin:@192.168.0.102:554/cam/realmonitor?channel=1&subtype=1
    low_alberts_indoor:
      - rtsp://admin:@192.168.0.28:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.1.115:8555
      - stun:8555
      - redacted:8555

cameras:
  entryway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_entryway
          roles:
            - detect
        - path: rtsp://localhost:8554/entryway
          roles:
            - record
    detect:
      enabled: true
  clothing_line:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_clothing_line
          roles:
            - detect
        - path: rtsp://localhost:8554/clothing_line
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask:
        - 0.331,0.302,0.345,0.32,0.422,0.283,0.488,0.318,0.921,0.313,0.999,0.328,1,0,0.003,0.001,0,0.294
        - 0.244,0.404,0.003,0.421,0,0.293,0.331,0.299,0.345,0.323
  open_area:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_open_area
          roles:
            - detect
        - path: rtsp://localhost:8554/open_area
          roles:
            - record
    detect:
      enabled: true
  garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_garden
          roles:
            - detect
        - path: rtsp://localhost:8554/garden
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 
        0.513,0,0.488,0.112,0.458,0.152,0.427,0.188,0.384,0.201,0.354,0.201,0.342,0.174,0.329,0.188,0.298,0.201,0.261,0.221,0.211,0.24,0.198,0.264,0.173,0.271,0.152,0.28,0.129,0.302,0.115,0.319,0.084,0.331,0.053,0.346,0.03,0.371,0.011,0.392,0.001,0.401,0.001,0
  roadside:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_roadside
          roles:
            - detect
        - path: rtsp://localhost:8554/roadside
          roles:
            - record
    detect:
      enabled: true
  gate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_gate
          roles:
            - detect
        - path: rtsp://localhost:8554/gate
          roles:
            - record
    detect:
      enabled: true
  rudolf_backyard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_rudolf_backyard
          roles:
            - detect
        - path: rtsp://localhost:8554/rudolf_backyard
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 
        0.285,0.001,0.783,0.482,0.816,0.51,0.843,0.52,0.857,0.523,0.839,0.5,0.925,0.272,0.998,0.001
  kitchen_garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_kitchen_garden
          roles:
            - detect
        - path: rtsp://localhost:8554/kitchen_garden
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask: 0.045,0.996,0.388,0.273,0.756,0,0.002,0.003,0.003,0.997
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_garage
          roles:
            - detect
        - path: rtsp://localhost:8554/garage
          roles:
            - record
    detect:
      enabled: true
    #objects:
    #  filters:
    #    person:
    #      min_score: .65
    #      threshold: .85
  kitchen_side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_kitchen_side
          roles:
            - detect
        - path: rtsp://localhost:8554/kitchen_side
          roles:
            - record
    detect:
      enabled: true
    objects:
      filters:
        person:
          min_score: .65
          threshold: .85
      mask: 
        0.264,0.758,0.36,0.671,0.421,0.736,0.46,0.708,0.653,0.909,0.694,0.96,0.726,0.987,0.758,0.934,0.772,0.859,0.788,0.832,0.808,0.824,0.838,0.824,0.831,0.75,0.829,0.685,0.857,0.629,0.898,0.602,0.947,0.563,0.996,0.453,0.999,0.999,0.004,0.996,0.002,0.326,0.084,0.482,0.127,0.525,0.175,0.596,0.22,0.647,0.295,0.732
    motion:
      mask: 
        0.002,0.324,0.051,0.414,0.134,0.539,0.268,0.708,0.319,0.763,0.358,0.685,0.387,0.717,0.415,0.745,0.425,0.732,0.438,0.732,0.458,0.712,0.528,0.785,0.638,0.891,0.687,0.948,0.724,0.986,0.758,0.932,0.77,0.862,0.789,0.832,0.835,0.819,0.829,0.69,0.854,0.628,0.949,0.557,0.997,0.445,1,1,0,1
  dish_side:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_dish_side
          roles:
            - detect
        - path: rtsp://localhost:8554/dish_side
          roles:
            - record
    detect:
      enabled: true
    motion:
      mask:
        - 0.089,0.474,0.543,0,0.002,0,0,0.374,0.072,0.41
        - 0.121,0.525,0.102,0.465,0.087,0.479,0.072,0.413,0.003,0.379,0.004,0.997,0.011,1
    objects:
      filters:
        person:
          min_score: .65
          threshold: .85
  aaron_backdoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_aaron_backdoor
          roles:
            - detect
        - path: rtsp://localhost:8554/aaron_backdoor
          roles:
            - record
    detect:
      enabled: true
  imou_garden:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_imou_garden
          roles:
            - detect
        - path: rtsp://localhost:8554/imou_garden
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac

    onvif:
      host: 192.168.1.137
      port: 80
      user: admin
      password: L2DBF682
    detect:
      enabled: true

    zones: {}
    objects:
      filters:
        person:
          min_score: .65
          threshold: .85
  ann_room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_ann_room
          roles:
            - detect
        - path: rtsp://localhost:8554/ann_room
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.1.142
      port: 80
      user: admin
      password: L24D1A5B
    detect:
      enabled: true
    objects:
      filters:
        person:
          min_score: .65
          threshold: .85
    record:
      enabled: false
    zones: {}
  living_room:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_living_room
          roles:
            - detect
        - path: rtsp://localhost:8554/living_room
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    objects:
      filters:
        person:
          min_score: .65
          threshold: .85
    record:
      enabled: false
  alberts_entrance:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_alberts_entrance
          roles:
            - detect
        - path: rtsp://localhost:8554/alberts_entrance
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.0.99
      port: 80
      user: admin
      password: L2728944
    detect:
      enabled: true
    objects:
      track:
        - person
      mask:
        - 0.667,0.203,0.865,0.332,1,0.466,1,1,0.915,1,0.777,0.656,0.759,0.628,0.638,0.381,0.646,0.24
        - 0.25,0.251,0.383,0.236,0.643,0.233,0.671,0.201,0.465,0.065,0.434,0.083,0.24,0.091
      filters:
        person:
          min_score: .65
          threshold: .85
    motion:
      mask:
        - 0.666,0.206,0.648,0.241,0.655,0.272,0.78,0.471,0.819,0.533,0.855,0.502,1,0.754,1,0.477,0.863,0.34,0.75,0.258
        - 0.25,0.251,0.38,0.236,0.643,0.232,0.657,0.255,0.687,0.21,0.464,0.069,0.434,0.081,0.241,0.09
        - 0.64,0.095,0.997,0.096,0.994,0.039,0.642,0.042
  alberts_first_floor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_alberts_first_floor
          roles:
            - detect
        - path: rtsp://localhost:8554/alberts_first_floor
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    onvif:
      host: 192.168.0.102
      port: 80
      user: admin
      password: L2242A1B
    detect:
      enabled: true
    objects:
      track:
        - person
      mask: 0.597,0.004,0.702,0.56,0.795,1,1,0.997,0.999,0.003
    motion:
      mask:
        - 0.798,1,0.597,0,0.726,0,0.942,0.263,1,0.359,0.999,0.997
        - 0.628,0.107,1,0.107,1,0.029,0.628,0.032
  alberts_indoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/low_alberts_indoor
          roles:
            - detect
        - path: rtsp://localhost:8554/alberts_indoor
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      enabled: true
    onvif:
      host: 192.168.0.28
      port: 80
      user: admin
      password: L2B75CB3
    motion:
      mask: 0.642,0.094,0.994,0.094,0.992,0.043,0.644,0.04
version: 0.15-1

camera_groups: {}
```

### Any other relevant information

```yaml

```
