### ISSUE TITLE
[Config Support]: Automation configuration fails to save

### ISSUE THREAD

**Issue by CyberRagz** [SgtBatten/HA_blueprints#436]
### Describe the problem you are having or the outcome you are trying to achieve.

After loading the blueprint (Frigate Notifications (0.14.0.2w)),  I have only selected one entity a camera and one device an iPhone. , rest of the settings are default, while saving the error message is "Your new automation has saved, but waiting for it to setup has timed out. This could be due to errors parsing your configuration.yaml, please check the configuration in developer tools. Your automation will not be visible until this is corrected, and automations are reloaded. Changes to area, category, or labels were not saved and must be reapplied." 
The .yaml configuration of blueprint has no issues and developer tools does not report any error. 
Any help will be appreciated. I have all latest HA versions and Frigate addon.

### Version

Frigate Notifications (0.14.0.2w

### Automation config

```yaml
alias: frigate
description: ""
use_blueprint:
  path: sgtbates/stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.parking
    notify_device: 007a35fd52c0c5989d3bc6aa64688578
    title: Frigate
```

### Frigate Config

```yaml

```
