### ISSUE TITLE
[Issue]: Notification to my iPhone works but the clips can't be played

### ISSUE THREAD

**Issue by rdperkins** [SgtBatten/HA_blueprints#440]
### Description

I get the notification but when I hit the HA notification I get a dark gray screen with a black band across the center and a light gray triangle with a line through it in the middle of the band.

### Version

(0.14.0.2w)

### Automation Config

```yaml
alias: Frigate Notifications Front Doorbell Cam Motiondescription: ""use_blueprint:  path: SgtBatten/Stable.yaml  input:    presence_filter:      - ""    camera:      - camera.front_doorbell    notify_device: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX   base_url: http://192.168.XX.XX:8123
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.XX.XX #Insert the IP address of your Home Assistant
  port: 1883 #Leave as default 1883 or change to match the port set in your MQTT Broker configuration
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user #Change to match the username set in your MQTT Broker
  password: XXXXXXXXXXXXXX #Change to match the password set in your MQTT Broker
  stats_interval: 60

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  retry_interval: 10

logger:
  default: error
  logs:
    frigate: error
    frigate.ffmpeg: error

record:
  enabled: true
  retain:
    days: 14
    mode: motion
  alerts:
    pre_capture: 5 # This is the default in seconds
    post_capture: 5 # This is the default in seconds
    retain:
      days: 14
      mode: motion
  detections:
    pre_capture: 5 # This is the default in seconds
    post_capture: 5 # This is the default in seconds
    retain:
      days: 14
      mode: motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 21

detectors: # Moved to top level
  coral: # Moved to top level
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

cameras:
  front_doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:XXXXXXXXXXXXXX@192.168.X.XXX:554/h265Preview_01_main
          roles:
            - record
        - path: rtsp://admin:XXXXXXXXXXXXXX@192.168.X.XXX:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - deer
        - box

      mask: 0.663,0.818,0.453,0.592,0.274,0.592,0.27,0.988,0.759,0.993
    motion:
      mask: 0.47,0.651,0.432,0.047,0.585,0.216,0.587,0.747
```

### Any other relevant information

```yaml

```
