### ISSUE TITLE
[Issue]: Tap Action  View Stream leads to 404 if camera entity ID has _

### ISSUE THREAD

**Issue by mad-tunes** [SgtBatten/HA_blueprints#443]
### Description

I've got Tap Action set to View Stream, and found that one of my esp32cams always gave a 404 error.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Camera notifications
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front
      - camera.garden
      - camera.spare
    notify_device: 92e7b5a8c6744b18ddb4e862d91cc9db
    update_sub_label: false
    critical: "false"
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    final_update: true
    icon: mdi:cctv
    android_auto: true
    tap_action: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    button_1: Clip
    button_2: Snapshot
    button_3: Silence
    alert_once: false
    sticky: true
    message: "{{now().strftime(\"%H:%M\")}} {{ label }} detected {{ camera_name }}"
    silence_timer: 10
    debug: true
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
```

### Frigate Config

```yaml
mqtt:
  enabled: true
  host: 192.168.5.11
  user: mqtt
  password: mqtt

detectors:
  cpu0:
    type: cpu
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu

go2rtc:
  streams:
    Garden: ffmpeg:http://192.168.5.57:8080#video=h264#hardware=preset-vaapi # <- use hardware acceleration to create an h264 stream usable for other components.
    Fish: ffmpeg:http://192.168.5.58:8080#video=h264#hardware=preset-vaapi   # <- use hardware acceleration to create an h264 stream usable for other components.
    Front: ffmpeg:http://192.168.5.59:8080#video=h264#hardware=preset-vaapi  # <- use hardware acceleration to create an h264 stream usable for other components.
    Spare:  ffmpeg:http://192.168.5.60:8080#video=h264#hardware=preset-vaapi # <- use hardware acceleration to create an h264 stream usable for other components.
    # Test:   "ffmpeg:http://192.168.5.60:8080#video=h264#hardware=preset-vaapi" # <- use hardware acceleration to create an h264 stream usable for other components.
    # Test: "ffmpeg:rtsp://192.168.5.204:554/mjpeg/1#video=h264#hardware=preset-vaapi" # <- use hardware acceleration to create an h264 stream usable for other components.

cameras:
  Fish:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Fish
          roles:
            - detect
            # - record
    detect:
      enabled: false
      # enabled: true
      width: 320
      height: 240
      fps: 5
    record:
      enabled: false
    motion:
      enabled: false
      threshold: 30
      contour_area: 10
      improve_contrast: false

  Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Front
          roles:
            - detect
            - record
    detect:
      enabled: false
      # enabled: true
      width: 320
      height: 240
      fps: 5
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - car
    motion:
      enabled: false
      threshold: 40
      contour_area: 10
      improve_contrast: false
      mask: 0,0,0,0.078,0.478,0.078,0.478,0
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: false
      crop: false
      retain:
        default: 14
        # mode: active_objects
        objects:
          person: 30
      quality: 100

  Garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garden
          roles:
            - detect
            - record
    detect:
      enabled: false
      # enabled: true
      width: 320
      height: 240
      fps: 5
    objects:
      track:
        - person
        - bird
        - cat
        # - dog
        # - car
    motion:
      enabled: false
      threshold: 30
      contour_area: 10
      improve_contrast: false
      mask: 0,0,0,0.078,0.478,0.078,0.478,0
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: false
      crop: false
      retain:
        default: 14
        # mode: active_objects
        objects:
          person: 30
      quality: 100

  Spare:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Spare
          roles:
            - detect
            - record
    detect:
      enabled: false
      # enabled: true
      width: 320
      height: 240
      fps: 5
    objects:
      track:
        - person
        - bird
        - cat
        - dog
        - car
    motion:
      enabled: false
      threshold: 40
      contour_area: 10
      improve_contrast: false
      mask: 0,0,0,0.078,0.478,0.078,0.478,0
    record:
      enabled: true
      retain:
        days: 7
        mode: active_objects
      alerts:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
      detections:
        retain:
          days: 14
          mode: active_objects
        pre_capture: 30
        post_capture: 30
    snapshots:
      enabled: true
      clean_copy: true
      timestamp: true
      bounding_box: false
      crop: false
      retain:
        default: 14
        # mode: active_objects
        objects:
          person: 30
      quality: 100

timestamp_style:
  position: tl
  format: '%d/%m/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow
version: 0.15-1

# auth:
#   reset_admin_password: true
```

### Any other relevant information

```yaml
When I changed the cameras entity ID from camera.garden_2 to camera.garden, the tap action view stream works a treat just like my others.
```
