### ISSUE TITLE
[Feature Request]: Have notifications fire more quickly with zone filtering enabled.

### ISSUE THREAD

**Issue by Milkysunshine** [SgtBatten/HA_blueprints#444]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to enable zone filtering, and receive faster notifications. Currently, with it enabled, I am only getting notifications upon the completion of the clip by frigate.

**Describe the solution you'd like**
As soon as frigate determines what an object is, and which zone it is in, the blueprint would notify as it does without zone filters enabled.

**Describe alternatives you've considered**
Currently my options are:

Disable zone filtering and get ~50x the amount of alerts due to cars and other things outside of the desired zones.

Or, keep zone filtering enabled and risk missing real time events due to the nature of the notifications.

**Additional context**
I'm using the latest stable.

Here is my automation in case I am missing something silly:

```
alias: Frigate Notification - My Phone
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.thingino_1
    notify_device: 7beb955066cddb888796e16c56a24b14
    base_url: https://homeassistant.myredactedurl.com
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    review_severity:
      - alert
    message: >-
      {{ label }}{{ ' was' if type == 'end' else '' }} detected on the {{
      camera_name }} camera{{' in the ' if after_zones|length}}{{ after_zones |
      join(', ') | replace('_', ' ' ) | title }}.
    alert_once: true
    final_update: true
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/event_preview.gif
    final_delay: 5
    channel: HA-Frigate
    title: Frigate
    zone_filter: true
    zones:
      - Front_Yard
      - Walkway
      - Driveway
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}

```

I'm not sure if this is because of the way Frigate fires the events, or if it is even possible. Thanks for the great blueprint either way!
