### ISSUE TITLE
[Issue]: iOS Thumbnails Fail to Load

### ISSUE THREAD

**Issue by southpaw5271** [SgtBatten/HA_blueprints#446]
### Description

I have the latest version of the blueprint installed and whenever I get a notification I do not see the thumbnail and instead I see "Failed to load attachment". I have attached some screenshots of the iOS notification center to demonstrate this. Both the latest stable version and the beta have this issue.

![Image](https://github.com/user-attachments/assets/4d9c10de-a2b7-42b0-8253-5a07281c0bf4)

![Image](https://github.com/user-attachments/assets/e599d478-9829-46aa-9dc7-5bd2c2d5bdb5)

![Image](https://github.com/user-attachments/assets/e8e7a0c6-0dbf-4063-9cea-772d880a66d7)

### Version

0.14.0.2w (also tried the beta 0.14.0.3h)

### Automation Config

```yaml
alias: Camera - Front Door
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera:
      - camera.front_door
    notify_device: <redacted>
    message: "{{ label }} detected - {{ camera_name }}"
    update_thumbnail: true
    ios_live_view: true
    zone_filter: true
    zones:
      - front_lawn
    labels:
      - person
      - package
    debug: true
    base_url: https://<redacted>
    cooldown: 120
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?crop=1
    presence_filter:
      - person.<redacted>
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    final_update: true
    attachment_2: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{review_id}}/review_preview.gif
    initial_delay: 5
```

### Frigate Config

```yaml
mqtt:
  host: <redacted>
  user: <redacted>
  password: <redacted>
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  # hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
go2rtc:
  streams:
    back_door: # <- for RTSP streams
      - rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:rtsp_cam#audio=opus   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    side_yard: # <- for RTSP streams
      - rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:rtsp_cam#audio=opus   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    garage: # <- for RTSP streams
      - rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:rtsp_cam#audio=opus   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    front_door: # <- for RTSP streams
      - rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0 # <- stream which supports video & aac audio
      - ffmpeg:rtsp_cam#audio=opus   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    back_yard: # <- for RTSP streams
      - rtsp://<redacted>:<redacted>@<redacted>/live # <- stream which supports video & aac audio
      - ffmpeg:rtsp_cam#audio=opus   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)
    front_doorbell: # <- for RTSP streams
      - rtsp://<redacted>:<redacted>@<redacted>:<redacted>/h264Preview_01_main # <- stream which supports video & aac audio
      - ffmpeg:rtsp_cam#audio=opus   # <- copy of the stream which transcodes audio to the missing codec (usually will be opus)


birdseye:
  enabled: false
  mode: motion
  width: 1280
  height: 720
  layout:
    max_cameras: 4


cameras:
  dining_room:
    ui:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>:<redacted>/stream2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://<redacted>:<redacted>@<redacted>:<redacted>/stream1 # <----- The stream you want to use for detection
          roles:
            - record

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5

    motion:
      mask:
        - 235,0,0,0,0,22,230,21

    record:
      enabled: true
      retain:
        days: 5

      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
  living_room:
    ui:
      order: 7
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>:<redacted>/stream2 # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://<redacted>:<redacted>@<redacted>:<redacted>/stream1 # <----- The stream you want to use for detection
          roles:
            - record

    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5

    motion:
      mask:
        - 235,0,0,0,0,22,230,21

    record:
      enabled: true
      retain:
        days: 5

  # Front Doorbell Camera
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
  front_doorbell:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>:<redacted>/h264Preview_01_sub # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://<redacted>:<redacted>@<redacted>:<redacted>/h264Preview_01_main # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 7
    record:
      enabled: true
      retain:
        days: 5
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 5
    snapshots:
      enabled: true
      required_zones:
        - front_porch
    motion:
      mask:
        - 640,0,640,141,379,87,334,0
    objects:
      track:
        - person
    zones:
      front_porch:
        coordinates: 640,480,640,308,528,287,133,289,0,315,0,480
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    # Back Door Camera
    review:
      alerts:
        required_zones:
          - front_porch
  back_door:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=1     # <----- The stream you want to use for detection
          roles:
            - detect
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0     # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots:
      enabled: true
    motion:
      mask:
        - 518,47,683,44,680,10,512,10
        - 0,98,0,0,155,0,154,51

  # Side Yard Camera
  side_yard:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=1     # <----- The stream you want to use for detection
          roles:
            - detect
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0     # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots:
      enabled: true
    motion:
      mask:
        - 704,250,704,0,325,0

  # Garage Camera
    objects:
      filters:
        person:
          mask: 0.462,0.001,0.998,0.002,0.997,0.513
  garage:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=1     # <----- The stream you want to use for detection
          roles:
            - detect
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0     # <----- The stream you want to use for detection
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots:
      enabled: true
    motion:
      mask:
        - 518,47,683,44,680,10,512,10
  # Front Door Camera
  front_door:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://<redacted>:<redacted>@<redacted>:<redacted>/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
    zones:
      front_lawn:
        coordinates: 
          515,480,369,480,170,480,0,480,0,423,35,358,88,291,148,222,231,172,310,133,420,120,470,114,523,83,622,166
        objects:
          - person
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7

    motion:
      mask:
        - 514,45,682,44,684,13,516,14
        - 213,117,386,98,513,54,518,0,0,0,0,238
    record:
      enabled: true
      retain:
        days: 5
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 5
    snapshots:
      enabled: true
      required_zones:
        - front_lawn

  # Back Yard Camera
    review:
      alerts:
        required_zones:
          - front_lawn
  back_yard:
    ui:
      order: 6
    ffmpeg:
      inputs:
        - path: rtsp://<redacted>:<redacted>@<redacted>/live # <----- The stream you want to use for detection
          roles:
            - detect
        - path: rtsp://<redacted>:<redacted>@<redacted>/live # <----- The stream you want to use for detection
          roles:
            - record
    motion:
      mask:
        - 0.972,0.932,0.974,0.981,0.721,0.979,0.721,0.929
        - 0.489,0,0.488,0.072,0.301,0.113,0.164,0.164,0,0.251,0,0
    zones:
      back_lawn:
        coordinates: 
          0.73,1,0.783,0.909,0.909,0.132,0.795,0.081,0.643,0.065,0.362,0.121,0,0.262,0,0.417,0.06,0.614,0.294,1
        inertia: 3
        loitering_time: 0
    objects:
      track:
        - person
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: true
      retain:
        days: 5
      alerts:
        retain:
          days: 7
      detections:
        retain:
          days: 7
    snapshots:
      enabled: true
      required_zones:
        - back_lawn
version: 0.15-1
notifications:
  enabled: 'false'
  email: <redacted>
```

### Any other relevant information

```yaml

```

**Comment by SgtBatten** [comment]
Something is wrong with the attachment or video generated urls. 

Grab the generated ones foemthe debug output and test them in a browser

**Comment by Bob2345de** [comment]
Am having the same issue. Looking at the debug log the " Video:" appended to the url seems strange, could that be causing the issue?

Frigate Notification DEBUG: Info: FPS: 5, Frigate Review id: 1749455331.554146-uioxgw, Frigate Detections: ['1749455330.954894-xg7ksa'] Objects: Person, Sub Labels: Config: Camera(formatted): Garage(Garage), Base URL: xxxxxx, Critical: False, TTS: False TTS Helper: N/A, Alert Once: False, Final_Update (delay): False (0)s, Attachment: https://xxxxxx/api/frigate/notifications/1749455330.954894-xg7ksa/thumbnail.jpg Video: , iOS URL: https://xxxxxx/api/frigate/notifications/1749455330.954894-xg7ksa/thumbnail.jpg Target.......

**Comment by SgtBatten** [comment]
That looks fine. You don't have video set which is normal and how I would recommend it.  Does the thumbnail url work when opened In a browser.

**Comment by Bob2345de** [comment]
yes, the thumbnail url works in ios browser. Long press on the notification results in HLS stream not available. Both action buttons work as expected (clip, snapshot). Have tried delayed message to ensure jpg is avaiable, same results. NB with my current settings I am not getting the error thumbnail (as per OP), just none at all.

**Comment by o2ik5** [comment]
Having the same issue as @southpaw5271 where links look like `https://[HA]/api/frigate/notifications/1749455330.954894-xg7ksa/thumbnail.jpg` but in the notification it give 401 error, trying the same link in a browser that have HA logged in give the same 401 error

`Enable the unauthenticated notification event proxy` set to True in the integration configuration

**Comment by southpaw5271** [comment]
Sorry for the late reply. I have confirmed that I am able to load the thumbnail image in a browser and I have confirmed that the "Enable the unauthenticated notification event proxy" is set to true in the integration configuration. The issue persists.

**Comment by rllynch** [comment]
I was struggling with this issue for a while (same symptoms as @southpaw5271) and finally figured out I had the "Video (Optional)" field set to "Clip m3u8 (IOS)" which I guess doesn't work as an attachment and was overwriting the "Initial Attachment" setting.  After setting "Video (Optional)" to None the thumbnail appears as expected.  I can then tap on it to get the video.

Not sure if video attachments are supposed to work, but that change at least got the thumbnail to show up for me.

**Comment by signorecello** [comment]
Can confirm this happened to me and setting Video (Optional) to None solved it

**Comment by totempole** [comment]
Same here.. Setting Video to None results in Thumbnails working. With video set to on (ios option), the thumbnails fail to load as well as the actual video url still ending in .mp4 whereas it should end with master.m3u8

Modifying the URL and replacing the clip.mp4 with master.m3u8 works just fine in the browser.

Blueprint version: 0.14.0.2w
Frigate 0.16 running on a separate machine reachable via public https url
Frigate Proxy Add-on in HA
HA: 2025.11.4

**Comment by nsmarcin** [comment]
For me it either not showing thumbnail or not playing clip.
Hi, My goal is to receive notification on iOS with snapshot visible and ability to see clip. For now I want it to use locally. I noticed that when I select:

-Initial attachment: Snapshot
-Video: None
-Action Button 1: View Clip (iOS)
-Action Button 2: View Snapshot
Then when notification arrives I can see the thumbnail and snapshot, but cannot see the clip (slashed play icon, m3u8, that is probably iOS restriction, the link works fine on desktop). But interesting thing is that when I select:

-Initial attachment: Snapshot
-Video: Clip (iOS)
-Action Button 1: View Clip (iOS)
-Action Button 2: View Snapshot
There is no thumbnail in notification (only error on white background) but when I click "View clip" it opens in Safari and play just fine.

I have no idea why it works that way because in both cases the endpoint is the same m3u8 file. 

Below is the first scenario:
```
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera:
      - camera.Backyard_1
    notify_device: 676ecc762d68937f3c32e017608b90213
    tv: true
    base_url: http://192.168.100.10:8123
    zone_filter: true
    zones:
      - lawn
      - garage
    title: Home Assistant
    labels:
      - person
      - car
    video: ""
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    attachment_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    final_update: true
    url_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    message: >-
      A {{ label }} {{ ' was' if type == 'end' else '' }} detected on the {{
      camera_name }} camera.
    alert_once: true
```
And the second one:
```
alias: Frigate Notifications (0.14.0.2w)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera:
      - camera.Backyard_1
    notify_device: 676ecc762d68937f3c32e017608b90213
    tv: true
    base_url: http://192.168.100.10:8123
    zone_filter: true
    zones:
      - lawn
      - garage
    title: Home Assistant
    labels:
      - person
      - car
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    tap_action: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    attachment_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    final_update: true
    url_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    message: >-
      A {{ label }} {{ ' was' if type == 'end' else '' }} detected on the {{
      camera_name }} camera.
    alert_once: true

```
