### ISSUE TITLE
[Issue]: Spook identified a problem with the Frigate Notification re logbook.log

### ISSUE THREAD

**Issue by rdperkins** [SgtBatten/HA_blueprints#449]
### Description

The following error was shown on the two of my cameras I setup to do notifications:

Spook has found a ghost in your automations 👻

While floating around, Spook crossed path with the following automation:

[Frigate Notifications Front Doorbell Cam Motion](http://192.168.2.18:8123/config/automation/edit/1747100726916) (automation.frigate_notifications_front_doorbell_cam_motion)

This automation references the following actions, which are unknown to Home Assistant:

logbook.log

### Version

Stable

### Automation Config

```yaml
alias: Frigate Notifications Front Doorbell Cam Motion
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front_doorbell
    notify_device: xxxxx
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.2.18 #Insert the IP address of your Home Assistant
  port: 1883 #Leave as default 1883 or change to match the port set in your MQTT Broker configuration
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user #Change to match the username set in your MQTT Broker
  password: ZZZZZZZZZZZZ #Change to match the password set in your MQTT Broker
  stats_interval: 60

ffmpeg:
  global_args: -hide_banner -loglevel warning -threads 2
  retry_interval: 10

logger:
  default: error
  logs:
    frigate: error
    frigate.ffmpeg: error

record:
  enabled: true
  retain:
    days: 14
    mode: motion
  alerts:
    pre_capture: 5 # This is the default in seconds
    post_capture: 5 # This is the default in seconds
    retain:
      days: 14
      mode: motion
  detections:
    pre_capture: 5 # This is the default in seconds
    post_capture: 5 # This is the default in seconds
    retain:
      days: 14
      mode: motion

snapshots:
  enabled: true
  clean_copy: true
  timestamp: false
  bounding_box: true
  crop: false
  retain:
    default: 21

detectors: # Moved to top level
  coral: # Moved to top level
    type: edgetpu
    device: usb

database:
  path: /config/frigate.db

cameras:
  front_doorbell:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://admin:ZZZZZZZZ@192.168.4.199:554/h265Preview_01_main
          roles:
            - record
        - path: rtsp://admin:ZZZZZZZZZ@192.168.4.199:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    objects:
      track:
        - person
        - box
      filters:
        person:
          mask: 0.238,0.576,0.604,0.589,0.974,0.229,0.908,0.972,0.227,0.987,0.137,0.587

version: 0.15.0
```

### Any other relevant information

```yaml
I'm also having problems viewing the clips on my iphone. I get the notifications but when I click the HA notification it brings up a black screen with a disabled play button (play button with a line through it).
```
