### ISSUE TITLE
[Issue]: URL from "View Clip (IOS)" doesn't load on iOS or desktop browser

### ISSUE THREAD

**Issue by tboyko** [SgtBatten/HA_blueprints#451]
### Description

This is an example case for illustrative purposes.

An alert appears in iOS. Safari goes to the following url when the notification is tapped. It shows a media interface but never loads a video.

`192.168.7.91:8123/api/frigate/notifications/1750186412.451253-lu1w6s/Entrance/master.m3u8`

Same behavior on a desktop browser, only the developer console reveals the following:

```
[Error] Failed to load resource: Plug-in handled load (master.m3u8, line 0) - http://192.168.7.91:8123/api/frigate/notifications/1750186412.451253-lu1w6s/Entrance/master.m3u8
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) - http://192.168.7.91:8123/api/frigate/notifications/1750186412.451253-lu1w6s/Entrance/init-v1.mp4
```

Digging into the frigate logs, interestingly enough, I see the following (abbreviated):

```
GET /vod/event/1750186412.451253-lu1w6s/master.m3u8 HTTP/1.1" 200 
```

And, if I go to the full URL in safari (that being the frigate proxy), it loads the clip:

`http://192.168.7.91:5000/vod/event/1750186412.451253-lu1w6s/master.m3u8`

I've run out of ideas on how to troubleshoot this and haven't found any existing tickets that seem to relate. I have another instance of frigate and home assistant running elsewhere that does _not_ exhibit this issue, despite seemingly similar software configurations.

Any help is appreciated.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Frigate Notification
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - person.me
    camera:
      - camera.accessstairs
      - camera.driveway
      - camera.gate
      - camera.house
      - camera.lower_entrance
      - camera.lower_yard
      - camera.road
      - camera.theatre_entrance
      - camera.gate_inside
    notify_device: 60acccbf42b58bb165f6666deafc2496
    base_url: http://192.168.7.91:8123
    attachment: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg?crop=1&format=android
    attachment_2: ""
    review_severity:
      - alert
    cooldown: 600
    tap_action: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    message: "{{ label }} detected - {{ camera_name }}"
    title: LF
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.7.91
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: ''
  password: ''

ffmpeg:
  input_args: -an -rtsp_transport tcp

record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle

cameras:
  House:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.11:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0.023,0.057,0.316,0.054,0.317,0.096,0.021,0.099
        - 0.751,0,1,0,1,1,0.73,1,0.753,0.8,0.72,0.774
      threshold: 55
      contour_area: 10
      improve_contrast: false
    zones: {}
    review: {}
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.12:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0,0,0.663,0,0.662,0.151,0.232,0.445,0.097,0.59,0,0.752
        - 0.723,0.719,0.841,0.716,0.841,0.762,0.724,0.763
    zones:
      Driveway_Inside:
        coordinates: 
          0.616,0.298,0.775,0.436,0.972,0.205,0.997,0.224,0.994,0.996,0.007,0.993,0.005,0.015,0.646,0
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Driveway_Inside
      detections:
        required_zones: Driveway_Inside
  Gate:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.58:554/Streaming/Channels/201
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    zones:
      DrivewayArea:
        coordinates: 0.004,0.443,0.135,0.411,1,1,0.009,0.996
        loitering_time: 0
    motion:
      mask:
        - 0.717,0.856,0.837,0.854,0.839,0.905,0.721,0.907
        - 0.012,0.061,0.012,0.123,0.336,0.111,0.335,0.059
    review:
      alerts:
        required_zones: DrivewayArea
      detections:
        required_zones: DrivewayArea
  AccessStairs:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.58:554/Streaming/Channels/701
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
    motion:
      mask:
        - 0.015,0.065,0.016,0.111,0.329,0.115,0.327,0.055
        - 0.716,0.862,0.716,0.911,0.836,0.905,0.835,0.854
      threshold: 50
      contour_area: 10
      improve_contrast: true
  LowerYard2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.58:554/Streaming/Channels/801
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0.015,0.057,0.015,0.105,0.332,0.101,0.332,0.055
        - 0.719,0.858,0.719,0.909,0.838,0.913,0.838,0.844
    objects:
      mask: 
        0.227,0.836,0.256,0.803,0.291,0.798,0.312,0.828,0.316,0.95,0.282,0.977,0.246,0.96
  LowerYard:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.58:554/Streaming/Channels/501
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0.093,0,0.015,0.061,0.016,0.111,0.064,0.113,0.072,0.147,0.623,0.071,0.613,0
        - 0.719,0.854,0.721,0.917,0.829,0.915,0.831,0.852
  TheatreEntrance:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.58:554/Streaming/Channels/1201
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0.015,0.057,0.019,0.113,0.332,0.107,0.335,0.055
        - 0.718,0.848,0.719,0.923,0.847,0.915,0.843,0.846
  SlidingGlassDoor:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.58:554/Streaming/Channels/1001
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0.016,0.057,0.016,0.117,0.335,0.103,0.337,0.045
        - 0.717,0.858,0.717,0.911,0.836,0.907,0.834,0.854
    zones:
      OutsideFromTheatre:
        coordinates: 
          0.004,0.014,0.106,0.016,0.161,0.929,0.661,0.836,0.624,0.024,0.991,0.016,0.989,0.99,0.007,0.988
        loitering_time: 0
    review:
      alerts:
        required_zones: OutsideFromTheatre
      detections:
        required_zones: OutsideFromTheatre
  Entrance:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.13:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0,0,0.266,0,0.292,0,0.365,0.039,0.412,0.252,0.356,0.38,0.359,0.515,0.399,0.621,0.36,0.645,0.38,0.676,0.38,0.746,0.412,0.814,0.41,1,0,1
        - 0.718,0.72,0.839,0.717,0.841,0.759,0.72,0.763
      threshold: 30
      contour_area: 10
      improve_contrast: false
    zones:
      Entrance_Inside:
        coordinates: 0.417,0.578,0.855,0.595,1,0.828,0.997,0.988,0.445,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Entrance_Inside
      detections:
        required_zones: Entrance_Inside
  Road:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://192.168.7.14:554/h264/ch1/main/av_stream
          roles:
            - record
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    motion:
      mask:
        - 0.023,0.054,0.314,0.051,0.316,0.096,0.023,0.099
        - 0.721,0.722,0.842,0.719,0.842,0.759,0.719,0.763
        - 0.072,0.506,0.116,0.996,0.205,0.996,0.207,0.492
      threshold: 60
      contour_area: 10
      improve_contrast: true
    zones:
      Road_Inside:
        coordinates: 0,0.568,0.203,0.519,0.466,1,0,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: Road_Inside
      detections:
        required_zones: Road_Inside
version: 0.15-1
notifications:
  enabled: 'true'
```

### Any other relevant information

```yaml

```
