### ISSUE TITLE
[Issue]: upstream returned a bad status 404 while sending to client

### ISSUE THREAD

**Issue by latel** [SgtBatten/HA_blueprints#453]
### Description

I'm setting automation using this awesome blueprint to send video clip ios to my iphone,

## however when the notification is sent to my device, the notification said:
![Image](https://github.com/user-attachments/assets/1ec366e8-43c3-4bd1-b390-237f719a6eee)
at the same the frigate log told: "Response status code was unacceptable"
```
2025-06-20 00:03:09.074267869  [2025-06-20 00:03:09] frigate.api.media              ERROR   : No recordings found for living_room during the requested time range
2025-06-20 00:03:09.075016568  2025/06/20 00:03:09 [error] 189#189: *9757 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 10.10.10.12, server: , request: "GET /vod/event/1750348987.599871-0my4y0/master.m3u8 HTTP/1.1", host: "10.10.10.11:5000"
2025-06-20 00:03:09.075051784  10.10.10.12 - - [20/Jun/2025:00:03:09 +0800] "GET /vod/event/1750348987.599871-0my4y0/master.m3u8 HTTP/1.1" 404 124 "-" "Home Assistant/2025.2 (io.robbie.HomeAssistant; build:2025.1178; iOS 18.5.0)" "10.10.10.1, 10.10.10.11"
```
```

## and after a not long period, it turns into: "Unrecognized attachment file type"
<img width="566" alt="Image" src="https://github.com/user-attachments/assets/50fbc60b-374a-4f81-88fb-c38b663b5b34" />
at the same time, the frigate logs told:
```
2025-06-20 00:04:04.634948783  10.10.10.12 - - [20/Jun/2025:00:04:04 +0800] "GET /vod/event/1750348987.599871-0my4y0/master.m3u8 HTTP/1.1" 200 214 "-" "Home Assistant/2025.2 (io.robbie.HomeAssistant; build:2025.1178; iOS 18.5.0)" "10.10.10.1, 10.10.10.11"
2025-06-20 00:04:07.270557303  127.0.0.1 - - [20/Jun/2025:00:04:07 +0800] "" 400 0 "-" "-" "-"
```

### Version

0.14.0.2w

### Automation Config

```yaml
alias: New automation
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.tapo_c120_29c9
      - camera.living_room
      - camera.hik_ids02ix_1694_entryway
    notify_device: ba7cc6ed9e6cd8b2bc27817ae2a10e8d
    base_url: https://xx.xxxx.xxxx:4443/
    tap_action: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']
      | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera,
      'access_token')}}
    url_1: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
    attachment_2: ""
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/thumbnail.jpg"
    title: A1
    final_update: true
    debug: true
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/master.m3u8
```

### Frigate Config

```yaml
version: 0.16-0

go2rtc:
  # log:
  #   level: trace
  streams:
    .....
    hided
    .....

ffmpeg:
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: auto
  # hwaccel_args: preset-vaapi
  # hwaccel_args: preset-intel-qsv-h264
  # hwaccel_args: preset-intel-qsv-h265
  # output_args:
    # record: preset-record-generic-audio-aac
    # record: preset-record-generic-audio-copy

face_recognition:
  enabled: true
  model_size: large

mqtt:
  enabled: true
  host: 10.10.10.12
  port: 1883
  user: xxx
  password: xxxxxxxx
  stats_interval: 15

objects:
  track:
    - person
    - cat
  filters:
    person:
      min_score: 0.2
      threshold: 0.1
    cat:
      min_score: 0.3
      threshold: 0.5

# detectors:
#   detector_name:
#     type: cpu

# detectors:
#   ov:
#     type: openvino
#     device: AUTO
# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   path: /openvino-model/ssdlite_mobilenet_v2.xml
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detectors:
  coral:
    type: edgetpu
    device: usb
    delay: 10

snapshots:
  enabled: true
  bounding_box: true
  timestamp: true
  crop: true
  retain:
    default: 10
    objects:
      person: 15
  quality: 100

record:
  enabled: true
  expire_interval: 60
  sync_recordings: false
  retain:
    days: 10
    mode: all
  export:
    timelapse_args: -vf setpts=0.04*PTS -r 30
  preview:
    quality: medium
  alerts:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5
  detections:
    retain:
      days: 30
    pre_capture: 5
    post_capture: 5

detect:
  enabled: true

semantic_search:
  enabled: false
  model_size: small

lpr:
  enabled: false

classification:
  bird:
    enabled: false


cameras:
  living_room:
    enabled: true
    ffmpeg:
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://xxx:xxx@10.10.10.00x:8554/ch1
          roles:
            - record
            - detect
    record:
      enabled: true
    detect:
      enabled: true
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    zones:
      workdesk:
        coordinates: 
          0.165,0.154,0.153,0.246,0.097,0.247,0.093,0.338,0.138,0.368,0.335,0.416,0.342,0.348,0.363,0.212
        loitering_time: 0
        objects: person
    objects:
      filters:
        person: {}
  aqara_g5_pro_df57_1520p:
    enabled: true
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-aac
      inputs:
        - input_args: preset-rtsp-restream
          # path: rtsp://127.0.0.1:8554/living_room
          path: rtsp://xxx:xxxx@10.10.10.00x:8554/ch1
          # path: rtsp://10.10.10.11:44425/9e5ccb0b76f30cc9
          # path: rtsp://10.10.10.11:9554/tapo_c120?audio&video
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 2
    detect:
      enabled: true
    objects:
      track:
        - person
        - cat
    mqtt:
      enabled: true
      # Optional: crop the snapshot (default: shown below)
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500

    zones:
      workdesk:
        coordinates: 
          0.293,0.387,0.23,0.381,0.175,0.38,0.173,0.492,0.201,0.507,0.205,0.556,0.38,0.551,0.376,0.501,0.379,0.396
        inertia: 3
        loitering_time: 0
        objects: person
      dining:
        coordinates: 
          0.615,0.732,0.747,0.809,0.815,0.792,0.842,0.593,0.771,0.558,0.74,0.567,0.721,0.568,0.668,0.558,0.635,0.556
        loitering_time: 0
        objects: person
  Garden:
    enabled: false
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-aac
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://127.0.0.1:8554/TL-IPC56CE-9846-Garden
          # path: rtsp://10.10.10.11:9554/tapo_c120?audio&video
          roles:
            - record
            - detect
    record:
      enabled: true
    detect:
      enabled: false
    mqtt:
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    # audio:
    #   enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
  TL-IPC14CH-6DF5-Cat-Toilet:
    enabled: false
    ffmpeg:
      # output_args:
      #   record: preset-record-generic-audio-aac
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://127.0.0.1:8554/TL-IPC14CH-6DF5-Cat-Toilet
          # path: rtsp://10.10.10.11:9554/tapo_c120?audio&video
          roles:
            - record
            - detect
    record:
      enabled: true
      retain:
        days: 2
    detect:
      enabled: true
    mqtt:
      # Optional: crop the snapshot (default: shown below)
      timestamp: false
      bounding_box: false
      crop: true
      quality: 100
      height: 500
    # audio:
    #   enabled: false
    motion:
      threshold: 30
      contour_area: 10
      improve_contrast: true
      mask:
        - 0,0,0.439,0.003,0.682,0,0.606,0,0.597,0.25,0.458,0.255,0.451,0.329,0.435,0.539,0.171,0.536,0.186,1,0,1
        - 0.799,0,1,0,1,1,0.783,1,0.787,0.647
    objects:
      filters:
        person:
          mask:
            - 0,0.408,0.137,0.433,0.264,0.708,0.368,0.785,0.61,1,0.201,1,0,1
            - 0.837,0.003,1,0,1,1,0.763,1,0.805,0.72,0.835,0.33
          min_area: 100000
        cat:
          mask:
            - 0.837,0.003,1,0,1,1,0.763,1,0.805,0.72,0.835,0.33
            - 0.839,0.533,0.811,0.64,0.896,1,1,1,1,0.844
            - 0.837,0.003,1,0,1,1,0.763,1,0.805,0.72,0.835,0.33
      mask: 0.837,0.003,1,0,1,1,0.763,1,0.805,0.72,0.835,0.33
  TAPO-C120-29C9:
    enabled: true
    ffmpeg:
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://10.10.10.11:42657/a9635be7f5add150 #high
          roles:
            - record
        - input_args: preset-rtsp-restream
          path: rtsp://localhost:42657/2c78731c73556c97 #low
          roles:
            - detect
    record:
      enabled: true
    detect:
      enabled: true
    # audio:
    #   enabled: false
    motion:
      mask:
        - 0.636,0.166,0.677,0.182,0.695,0.224,0.683,0.271,0.65,0.264,0.626,0.234
        - 0,0,0.13,0,0.224,0,0.224,0.044,0.133,0.051,0.136,0.331,0.12,0.867,0.176,1,0,1
        - 0.713,0,1,0.309,1,0
      # threshold: 35
      # contour_area: 10
      improve_contrast: true
    objects:
      mask:
        - 0.865,0.672,0.848,0.763,0.876,0.82,0.954,0.669,0.913,0.637
        - 0.869,0.272,0.851,0.342,0.898,0.403,0.926,0.325
      # Optional: filters to reduce false positives for specific object types
      # filters:
        # person:
        #   min_score: 0.8
        # cat:
        #   min_score: 0.8
      track:
        - person
        - cat
    zones:
      dining_room:
        coordinates: 
          0.704,0.326,0.712,0.38,0.776,0.486,0.84,0.529,0.889,0.447,0.845,0.369,0.827,0.422,0.802,0.382,0.786,0.376,0.788,0.314,0.763,0.256
        # loitering_time: 1
        # inertia: 1
        objects:
          - person
        # filters:
          # person:
          #   # min_area: 5000
          #   # max_area: 100000
          #   min_score: 0.01
          #   threshold: 0.01
      work_desk:
        coordinates: 0.22,0.175,0.427,0.216,0.464,0,0.206,0
        # loitering_time: 0
        # inertia: 8
        objects:
          - person
        # filters:
        #   person:
        #     min_score: 0.01
        #     threshold: 0.01
  HIK-IDS02IX-1694-Entryway:
    enabled: true
    # live:
    #   stream_name: hikvision_entryway_sub
    ffmpeg:
      # 覆盖全局，单独禁用硬解
      hwaccel_args:
        - -hwaccel
        - none
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://10.10.10.11:42451/0c0bf212302cf4ea #low
          roles:
            - detect
        - input_args: preset-rtsp-restream
          path: rtsp://10.10.10.11:42451/382df6ea3e004104 #high
          roles:
            # - audio
            - record
    detect:
      enabled: true #還沒配置好檢測模式和區域先不要開，會額外消耗主機效能
      # width: 1280 #攝影機的寬度，視畫面情況而定，解析度不是越高越好
      # height: 720 #攝影機的高度，視畫面情況而定，解析度不是越高越好
    # audio:
    #   enabled: true
    record:
      enabled: true
    motion:
      mask:
        - 0.046,0.013,0.052,0.101,0.433,0.099,0.437,0.205,0.539,0.211,0.539,0.118,0.821,0.105,0.824,0.011,0.426,0.014
        - 0.032,0.547,0.125,0.882,0.165,1,0,1,0,0.415
        - 0.976,0.155,0.997,0.163,1,0.615,1,0.887,0.798,0.791,0.896,0.518
        - 0.164,0.997,0.117,0.622,0.247,0.462,0.349,0.363,0.382,0.352,0.603,0.435,0.696,0.589,0.683,0.672,0.771,0.558,0.851,0.589,0.899,0.85,0.881,0.997
    review:
      alerts:
        required_zones: stepway
    mqtt:
      # Optional: crop the snapshot (default: shown below)
      timestamp: false
      bounding_box: true
      crop: false
      quality: 100
      height: 500
    objects:
      mask:
        - 0.673,0.773,0.728,0.733,0.717,1,0.531,1,0.55,0.872,0.599,0.761
        - 0.199,0.319,0.228,0.494,0.323,0.578,0.411,0.501,0.373,0.306,0.266,0.155
      track:
        - person
        - cat
      # Optional: filters to reduce false positives for specific object types
      filters:
        person:
          min_score: 0.8
    zones:
      stepway:
        coordinates: 0.787,0.011,0.7,0.526,0.927,0.683,0.994,0.361,1,0
        loitering_time: 0
        inertia: 3
        objects: person
```

### Any other relevant information

```yaml

```
