### ISSUE TITLE
[Config Support]: Clip Playback iOS (fails) vs Desktop Browser (works)

### ISSUE THREAD

**Issue by Austin1** [SgtBatten/HA_blueprints#455]
### Describe the problem you are having or the outcome you are trying to achieve.

I receive a thumbnail to iOS notifications, but if I select the notification, it loads a clip.mp4 but fails to play. It just shows a spinning black box such as

<img width="332" alt="Image" src="https://github.com/user-attachments/assets/5cd61f5e-fd0a-444e-aec2-c91f5aae43f8" />

If i load the same url on my desktop computer, it works and plays back. I thought it was cloudflare or something with certificates but I've cleaned all that up nicely and still have same issue.

Here is URL that is being sent from HA notification: https://removed.ui.nabu.casa/api/frigate/notifications/1750724087.717429-2a2pv0/Doorbell/clip.mp4

Works on desktop, not on mobile, no matter if I'm on the network or not.

I'm trying some stuff after posting this so will report back if I solve.

### Version

0.14.0.2w

### Automation config

```yaml
alias: "Frigate Notifications (0.14.0.2w) front door "
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.doorbell
    notify_device: 982225ee68893893ec4a8205b978ea2e
    base_url: https://{removed}.ui.nabu.casa
    ios_live_view: camera.doorbell
```

### Frigate Config
this config is embarrassingly old but works so I haven't messed with it in a very long time.
```yaml
mqtt:
  host: 192.168.1.4
  user: austin
  password: 
  client_id: frigate
  topic_prefix: frigate
  port: 1883

tls:
    enabled: false

birdseye:
  enabled: true
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  output_args:
    record: preset-record-generic-audio-copy
go2rtc:
  webrtc:
    candidates:
      - 192.168.1.2:8555
      - stun:8555
  streams:
    Backporch:
      - rtsp://admin:@192.168.13.10:554/cam/realmonitor?channel=1&subtype=0
    Frontyard:
      - rtsp://admin:@192.168.13.11:554/cam/realmonitor?channel=1&subtype=0
    Garage:
      - rtsp://admin:@192.168.13.12:554/cam/realmonitor?channel=1&subtype=0
    Doorbell:
      - ffmpeg:http://192.168.13.13/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=#video=copy#audio=copy#audio=opus
      - rtsp://192.168.13.13/Preview_01_sub
    Doorbell_sub:
      - ffmpeg:http://192.168.13.13/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=    Amcrest_PTZ:
      - rtsp://admin:@192.168.13.15:554/cam/realmonitor?channel=1&subtype=0
cameras:
  Backporch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Backporch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
  Frontyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Frontyard?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  Amcrest_PTZ:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Amcrest_PTZ?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    onvif:
      host: 192.168.13.15
      port: 80
      user: ptz
      password:
      ignore_time_mismatch: true
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: true
detect:
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  # Optional: Configuration for stationary object tracking

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: false
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    days: 12
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  alerts:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 20
  detections:
    retain:
      days: 14
    pre_capture: 5
    post_capture: 20
version: 0.15-1
camera_groups:
  Drive:
    order: 1
    icon: LuDroplets
    cameras:
      - Doorbell
      - Garage
      - Frontyard

```
