### ISSUE TITLE
[Issue]: Android 16 notification sound persists

### ISSUE THREAD

**Issue by mgsb** [SgtBatten/HA_blueprints#456]
### Description

Since I upgraded to Android 16 (Pixel 7), notifications from Frigate continuously play the notification sound until they are dismissed. This behavior did not happen with Android 15 and there have been no changes to Frigate or HA.

### Version

0.14.0.2w

### Automation Config

```yaml
alias: Frigate Notifications
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    presence_filter:
      - ""
    camera:
      - camera.front
      - camera.patio
      - camera.garage
      - camera.backyard
    notify_device: 034920465d7c46f4e52b0ddb15fdf545
    tv: false
    base_url: http://192.168.10.8:8123
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    critical: "true"
    notify_group: mark_and_julie
    attachment: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    attachment_2: "{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg"
    sticky: true
    android_auto: true
    cooldown: 60
```

### Frigate Config

```yaml

```

### Any other relevant information

```yaml

```
