### ISSUE TITLE
[Config Support]: Getting frigate BP automation notifications working.

### ISSUE THREAD

**Issue by theunclebobbyb** [SgtBatten/HA_blueprints#46]
### Describe the problem you are having or the outcome you are trying to achieve.

I need help getting my frigate notifications working. I'm using the latest stable blueprint (0.12.0.1). I'm running frigate 0.12.0-DA3E197. I feel like its an issue with the blueprint somehow. If I manually create an automation to trigger based on if a person is detected or not, then it pushes the notification just fine. Weird thing is that even if I manually run the frigate blueprint automation it does not send my phone a notification at all. My manual automation does if I run it manually. I'm not sure what my issue is here. My mqtt seems to be working right based on my logbook that is reporting everything in real time. I made sure to have "Enable the unauthenticated notification event proxy" enabled on my frigate integration. I could not however tick this option until after I added my frigate integration. The only reason I saying that is because all the posts say it must be ticked during setup but I don't see any options to during setup. I only see it after I have it installed and I click "Configure" on it. 

### Version

Frigate Notifications (0.12.0.1)

### Automation config file

```yaml
alias: Front Road - Car - Test - Stable 0.12
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.wahoo_house_front
    notify_device: 886222a9632958b08806011435321f26
    zones:
      - front_road
    labels:
      - car
    debug: true
```

### Frigate Config

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 10.10.88.10
  user: mqtt-user
  password: mqtt-password

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac
    
    
go2rtc:
  streams:
    Wahoo-House-Front:
      - rtsp://172.30.0.5:7447/6333ab58e4b042ee37865a9f_0
    Wahoo-House-Back:
      - rtsp://172.30.0.5:7447/6338897ee4b0e266ae3c47b7_0
    Weston-Shop-Back:
      - rtsp://172.30.0.5:7447/63388a22e4b0e266ae3c47cb_0
    Weston-Shop-Front:
      - rtsp://172.30.0.5:7447/63388a3ae4b0e266ae3c47e5_0

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

cameras:
  Wahoo-House-Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Wahoo-House-Front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      events:
        required_zones:
          - front_driveway
          - front_yard
          - front_road
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
    motion:
      mask:
       - 517,31,409,246,223,45
       - 0,0,331,0,332,87,0,87
       - 703,236,814,252,886,205,853,106,694,100,640,172
       - 0,111,27,116,91,152,126,224,123,321,0,376
       - 569,101,1195,121,1190,0,703,0
    objects:
      track:
        - person
        - dog
        - car
      filters:
        car:
          mask: 266,1080,1920,1080,1920,374,819,215,0,535
    zones:
      front_yard:
        coordinates: 797,238,563,199,490,199,427,195,379,189,304,181,187,219,113,253,0,370,0,505,140,537
        objects:
          - person
          - dog
          - car
      front_driveway:
        coordinates: 1920,416,1718,381,1300,320,898,222,849,233,397,330,37,557,24,663,238,1080,1920,1080
        objects:
          - person
          - dog
      front_road:
        coordinates: 1508,0,1036,0,908,0,875,0,770,0,625,33,539,64,479,82,0,223,0,267,326,172,949,240,1920,358,1920,0,1920,39
        objects:
          - car
          - person
  Wahoo-House-Back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Wahoo-House-Back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      events:
        required_zones:
          - backyard_pool
          - hackberry_parking_lot
          - hackberry_soccer_fields
          - backyard
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
        - 683,444,590,468,562,399,662,349
        - 0,0,331,0,328,84,0,78
        - 1873,414,1920,446,1920,515,1920,655,1840,685,1681,660,1604,603,1583,508,1617,464,1779,402
        - 1427,0,562,0,628,150,982,204,1196,183
        - 446,316,597,203,575,106,530,0,340,0,176,33,172,216,296,304
        - 1055,426,961,430,958,303,1034,294
        - 658,357,670,410,730,459,843,429,792,318,676,294
        - 0,583,278,496,437,460,612,449,547,357,437,372,103,423,0,492
    zones:
      backyard_pool:
        coordinates: 473,802,751,760,970,655,959,565,827,496,572,475,304,498,65,610,40,718,164,783
        objects:
          - dog
          - cat
          - person
      hackberry_parking_lot:
        coordinates: 853,159,1624,198,1342,259,542,193
        objects:
          - person
      hackberry_soccer_fields:
        coordinates: 541,346,0,421,0,213,377,184,562,177,647,186,910,222,1358,250,1028,283,856,231,748,208,728,244,607,276,623,337
        objects:
          - person
          - dog
          - cat
      backyard:
        coordinates: 680,364,676,429,676,463,947,499,1021,654,814,783,236,852,0,765,0,1059,1895,1080,1920,511,1920,402,1898,319,1853,289,1600,279,1490,253,1391,313,1238,316,1034,325,830,268,633,278,641,316
        objects:
          - person
          - dog
          - cat
  Weston-Shop-Back:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Weston-Shop-Back
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
    motion:
        mask:
            - 0,0,328,0,328,83,0,78
  Weston-Shop-Front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Weston-Shop-Front
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    record:
      enabled: True
      retain:
        days: 90
        mode: motion
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
    snapshots:
      enabled: True
    motion:
        mask:
            - 0,0,328,0,328,83,0,78
```
