### ISSUE TITLE
[Bug]: Stream option not working

### ISSUE THREAD

**Issue by Bug23451** [SgtBatten/HA_blueprints#47]
### Description

After recieving a notification on my phone the action button set as view stream doesn't work, it points me to a error 404 web page

Snaps and clips work.

### Version

0.12.0.1 and 0.12.0.1f

### Automation Config

```yaml
alias: "Office Cam Notification "
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.office_cam
    notify_device: 7815696ecbf1c96e6894b779456d330e
    base_url: https://place.onThe.net/
    mqtt_topic: frigate/events
    message: >-
      {{ label }} detected - {{ camera_name }} at
      {{event['after']['start_time']|timestamp_custom('%H:%M')}}
    critical: "true"
    attachment: snapshot
    update_thumbnail: true
    video: /api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    sticky: true
    presence_filter: person.bug23451
    tap_action: /lovelace
    url_3: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera']}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    button_3: Stream
    button_2: Snapshot
    button_1: Clip
```
