### ISSUE TITLE
[Config Support]: How to pass images (snapshot/thumbnail) to other notification types (namely SMTP)

### ISSUE THREAD

**Issue by jamesb2147** [SgtBatten/HA_blueprints#50]
### Describe the problem you are having or the outcome you are trying to achieve.

I am attempting to pass the image as an attachment to an already-configured SMTP integration setup as notify.email. It appears that all the Frigate integration seems to work fine, like the events trigger and we can see in the trace timeline that it's generating a link to an image. 

Overall for email, text seems to work fine, for what it's worth, as I can control both the Subject and Body. It's just that the image attachment part doesn't come through.

### Version

0.12.0.1

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.back_porch
    notify_group: notify.email
    title: Person sighted
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera{{ ' in the ' + entered_zones if entered_zones
      else '.'}}
    attachment: snapshot
    debug: true
```

### Any other information that may be helpful

Here's some trace info from a DEBUG level event where you can see some of the required info coming through:

Frigate Notification () DEBUG: Info: fps: 5, frigate event id: 1686784172.22988-elye99, object (formatted): person (Person), Config: camera(formatted): back_porch(Back Porch), Base URL: , critical: False, alert once: False, Update Thumbnails: False, Target: group (input/formatted): notify.email/email, cooldown: 30s, loiter timer: 0s, color: steelblue, sound: default, Title: Person sighted, Message: A Person was detected on the Back Porch camera., tap_action: /api/frigate/notifications/1686784172.22988-elye99/back_porch/clip.mp4, button 1 Text/URL: View Clip (/api/frigate/notifications/1686784172.22988-elye99/back_porch/clip.mp4), button 2 Text/URL: View Snapshot (/api/frigate/notifications/1686784172.22988-elye99/snapshot.jpg), button 3 Text/URL: Silence New Notifications (silence-back_porch), icon: mdi:home-assistant tv: False, tv_position: center, tv_size: large, tv_duration: 10, tv_transparency: 0%, tv_interrupt: False, Filters: Zones: zone filter toggle on: False, Multi Zone toggle on: False, Required zones: [], Entered Zones: [], Zone Filter TEST: PASS, Required objects TEST: Input: , TEST: PASS presence entity (not home): Entity: TEST: PASS, disabled times: [], State Filter: state filter toggle on: False, state filter entity: , required states: [], State Filter TEST: PASS,

**Comment by jamesb2147** [comment]
LMK if you need the full automation config or anything. Here's the SMTP config, in case it helps:

```
notify:
  - name: "email"
    platform: smtp
    server: "smtp.mailgun.org"
    port: 587
    timeout: 15
    sender: "postmaster@mg.foobar.com"
    encryption: starttls
    username: "postmaster@mg.foobar.com"
    password: "foo-bar"
    recipient:
      - "foo-bar@googlegroups.com"
    sender_name: "Home Assistant"
```
