### ISSUE TITLE
Notification to iOS 

### ISSUE THREAD

**Issue by HuggiesHA** [SgtBatten/HA_blueprints#51]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello
I am really struggling with iOS notifications. I will admit my coding isn’t the best so do apologies.

I am using Nuba casa, so does the url need to be added or should it work with my HA app that is on my iOS device.

I have also added network storage on the new HA release so my frigate media is routing to that, so does the config for the automation need to change as getting “event not found” error messages. I am also getting notifications every 5 secs even the thought it show event not found.

- why don’t I see action buttons on my notification, ideally open a live stream and silent the notification 
- Should I be using the Nuba casa url or not
- I sent the notification silence to 30 secs but getting

### Version

12.1

### Automation config file

```yaml
alias: LR Motion1
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.livingroom
    notify_device: a2cf113808a839811c9c7824bbc3ad69
    title: Living Room Motion
    message: A Person was detected on the Living Room camera.
    attachment: snapshot
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    tv_size: large
    tv_position: center
    color: grey
    url_1: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    url_3: silence-{{ camera }}
    ios_live_view: true
    update_thumbnail: true
    icon: mdi:cctv
    url_2: "{{base_url}}/lovelace"
    tv_interrupt: false
```

### Frigate Config

```yaml
mqtt:
    host: 192.168.20.93
    port: 1883
    user: mqttuser
    password: mqttuser


cameras:
  Garage:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:r0mf0rd@192.168.20.82:554/profile2
          roles:
            - detect
            - snapshots
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      retain:
       default: 1
    record:
      enabled: True
      retain:
        days: 0
    objects:
      track:
        - person
  Kitchen:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://admin:R0mf0rd@192.168.20.129/live
          roles:
            - detect
            - snapshots
            - record
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      retain:
       default: 1
    record:
      enabled: True
      retain:
        days: 0
    objects:
      track:
        - person
  LivingRoom:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://Administrator:Brun4397!"12@192.168.20.161/stream1
          roles:
            - detect
            - snapshots
            - record
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: True
      bounding_box: True
      retain:
       default: 1
    record:
      enabled: True
      retain:
        days: 0
    objects:
      track:
        - person
```
