### ISSUE TITLE
[Bug]: clip not available when clicking notification

### ISSUE THREAD

**Issue by vavallee** [SgtBatten/HA_blueprints#52]
### Description

When clicking on the thumbnail photo received from HA for movement, the page that opens responds "Clip Not Available"

### Version

0.12.0.1

### Automation Config

```yaml
alias: Frigate Notifications (0.12.0.1f)
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.doorbell
    notify_device: 879f68a656f3e2c63cc86c854a9d6ee4
    base_url: https://[URL TO MY HA, also works externally]
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.1.177
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password
  stats_interval: 60

detectors:
  # coral:
  #   type: edgetpu
  #   device: usb
  cpu1:
    type: cpu
  cpu2:
    type: cpu

ffmpeg:
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic

cameras:
  doorbell:
    enabled: true
    objects:
      track:
        - person
        - car
        - package
        - bus
        - motorcycle

    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
            - clips
    detect:
      enabled: true
      width: 2560
      height: 1920
      fps: 5
    motion:
      mask:    
        - 0,761,2560,780,2560,0,0,0,0,0
        - 303,1005,725,1033,758,704,402,729
        - 0,1180,328,1176,353,838,0,809
        - 2560,505,2560,1427,1739,1342,1686,501
    #coordinates to ignore
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 3
go2rtc:
  streams:
    doorbell:
      - rtsp://xxxxx:xxxxx@192.168.1.16:554/h264Preview_01_main
  webrtc:
    candidates:
      - FRIGATE_IP:8555
```
