### ISSUE TITLE
[Bug]: view clip/view snapshot button issues

### ISSUE THREAD

**Issue by BNWEIN** [SgtBatten/HA_blueprints#53]
### Description

When I get the notification (which works perfectly) doesn’t matter what I press it just opens up home assistant companion app at the last thing I was looking at in the app, or the dashboard if the app wasn’t open. 

For example, clicking on view snapshot doesn’t show me the snap shot. Clicking view clip doesn’t take me to a clip of the video, and clicking silent new notifications doesn’t take me…. Well I’m not sure where this should take me? 

I should mention I am using IOS. 

### Version

0.12.0.1

### Automation Config

```yaml
alias: Frigate Driveway Car
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.driveway_cam
    notify_device: cd2fd539c594c8cb9fec4a007f3cf9bb
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera.
    ios_live_view: true
    debug: false
    base_url: home.my domain.co.uk
    update_thumbnail: false
    zone_filter: true
    zones:
      - driveway_entrance
    state_filter: false
    zone_multi: false
    labels:
      - car
```

### Frigate Config

```yaml
Don’t think you’ll need this?
```
