### ISSUE TITLE
[Bug]: hyphen not replaced in View Stream

### ISSUE THREAD

**Issue by djfjeff** [SgtBatten/HA_blueprints#56]
### Description

My camera are named `doorbell-front` in Frigate. When I click the link for "View Stream", the camera in the link is named `camera.doorbell-front` instead of `camera.doorbell_front`.

I see that the link is generated using `{{trigger.payload_json['after']['camera'].lower()}}` at line https://github.com/SgtBatten/HA_blueprints/blob/17e4d520d256ae48c4ad394c3318174acbf9e2e3/Frigate%20Camera%20Notifications/Stable#L392C67-L392C118

However, you can see at line https://github.com/SgtBatten/HA_blueprints/blob/17e4d520d256ae48c4ad394c3318174acbf9e2e3/Frigate%20Camera%20Notifications/Stable#L556 that you replace the `-` by `_`. I think this should also be used to generate the "View Stream" link.

### Version

0.12.0.1

### Automation Config

```yaml
alias: frigate_front_porch_notification
description: Notification for front porch event from Doorbell Front - When not home
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.doorbell_front
    message: >-
      A {{ label }} {{ 'is loitering' if loitering else 'was detected' }} on the
      {{ camera_name }} camera{{ ' in the ' + entered_zones if entered_zones
      else '.'}}
    attachment: snapshot
    channel: camera
    zone_filter: true
    zones:
      - zone_front_porch
    button_1: View Stream
    url_1: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    notify_device: dc87cc80ffe34432c139133a8322cf53
```
