### ISSUE TITLE
[Config Support]: Frigate Notifications Blueprint - different mqtt topic - multiple frigate instances

### ISSUE THREAD

**Issue by andrewhack** [SgtBatten/HA_blueprints#57]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi,

Can't figure it out how to change mqtt topic - in multi frigate instance setup the client_id/topic_prefix should be unique.
The blueprint is using: frigate/events

Can you assist please - I didn't found a description of similar situation?
Do I need to update the blueprint or this could be done as configuration?

Thank you in advance

### Version

0.12

### Automation config file

```yaml
alias: Frigate Notifications - Maingate1
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.maingate1
    notify_group: ALL_DEVICES
    attachment: snapshot
    labels:
      - person
```
