### ISSUE TITLE
[Bug]: Multiple frigate servers and multiple notification - only one notification is triggered

### ISSUE THREAD

**Issue by andrewhack** [SgtBatten/HA_blueprints#59]
### Description

I am using 2 frigate servers which are integrated with HASS and working.
Also have 2 frigate notifications for 2 different cameres (every camera is on different frigate server)
Only the first frigate notification is working (Crosstreet), the second is not triggered at all (Mainstreet1).

![image](https://github.com/SgtBatten/HA_blueprints/assets/46722365/e8350a4c-5eb0-4894-844b-376c1b2940df)

My own Alexa notification is working fine for camera - Mainstreet1

Any suggestion?

### Version

0.12.0.1g

### Automation Config

```yaml
alias: Frigate Notification - Crosstreet
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.crosstreet
    notify_group: ALL_DEVICES
    mqtt_topic: frigatenvr1/events
    client_id: frigatenvr1
    critical: "false"
    alert_once: true
    attachment: snapshot
    update_thumbnail: true
    sticky: false
    labels:
      - person


alias: Frigate Notifications - Mainstreet1
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.maingate1
    notify_group: ALL_DEVICES
    mqtt_topic: frigatenvr3/events
    client_id: frigatenvr3
    alert_once: true
    attachment: snapshot
    labels:
      - person
      - car
    debug: true


alias: Frigate NVR3 Person Notifications - Alexa
description: ""
trigger:
  - platform: mqtt
    topic: frigatenvr3/events
    payload: new
    value_template: "{{ value_json.type }}"
condition:
  - "{{ trigger.payload_json['after']['label'] == 'person' }}"
action:
  - service: notify.alexa_media_andrei_s_3rd_echo_dot
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected from
        {{trigger.payload_json["after"]["camera"]}} camera.
      data:
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        entity_id: >-
          camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
          lower}}
  - service: notify.alexa_media_andrei_s_2nd_echo_dot
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected from
        {{trigger.payload_json["after"]["camera"]}} camera.
      data:
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        entity_id: >-
          camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
          lower}}
  - service: notify.alexa_media_andrei_s_echo_dot
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected from
        {{trigger.payload_json["after"]["camera"]}} camera.
      data:
        tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
        when: "{{trigger.payload_json[\"after\"][\"start_time\"]|int}}"
        entity_id: >-
          camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
          lower}}
mode: single
```
