### ISSUE TITLE
[Feature Request]: Android Auto Option.

### ISSUE THREAD

**Issue by penright** [SgtBatten/HA_blueprints#60]
**Describe what you are trying to accomplish and why in non technical terms**
When an alert message is sent to Andriod, have the option to show it on Andriod Auto.

**Describe the solution you'd like**
Add a "Show on Andriod Auto" option with true/false. That would set the value of "car_ui" in the data for the notify service

```
action:
  - service: notify.mobile_app_<your_device_id_here>
    data:
      message: Le garage est ouvert
      data:
        car_ui: true
        notification_icon: mdi:garage-open
        channel: garage opened
        importance: high
        actions:
          - action: null
            title: Ouvrir garage
```

**Describe alternatives you've considered**

**Additional context**
This link is the AA git repository, where someone was making the request to add it. 
 https://github.com/home-assistant/android/issues/3520#issuecomment-1639721883

With AA rules, the images may not show up.
Right now I am on "Stable", but if you want to test let me know. I will be happy to help.
