### ISSUE TITLE
[Bug]: Clip not showing/broken

### ISSUE THREAD

**Issue by Hamish1066** [SgtBatten/HA_blueprints#61]
### Description

When I click the iOS notification, the clip is takes me to is just a crossed out play button - no actual video plays. 

### Version

0.12.0.1

### Automation Config

```yaml
alias: Front Door - Front Door Camera - Notification (Blueprint)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.front_door
    notify_device: f35621be2644c6418833fca46ca6914c
    message: A {{label}} was detected on the {{ camera_name }}.
    ios_live_view: true
    base_url: https://[myurl].ui.nabu.casa
    tap_action: /frigate/notifications/{{id}}/camera.front_door_2/clip.mp4
```

### Any other relevant information

```yaml
For the tap action, I've tried just the regular "View Clip" drop down option, which yielded the same result except that it took me to the browser in my phone rather than the HA iOS app. I specified the name in the tap action as there is a related bug with this Blueprint - I already have a non-Frigate (Nest) camera called "Front Door", so when I gave the camera in Frigate the same name, Home Assistant assigned it the name "Front Door 2" within the HA Frigate integration. I had to manually update the camera name to match the name given in Frigate, as the drop down option didn't work.
```

**Comment by SgtBatten** [comment]
> ```yaml
> /frigate/notifications/{{id}}/camera.front_door_2/clip.mp4
> ```

This is invalid. 

the camera name needs to match frigate config. and not have 'camera.' at the front. 

so `camera.front_door_2` probably needs to be just front_door i assume, which it would have been by default.

**Comment by Hamish1066** [comment]
> > ```yaml
> > /frigate/notifications/{{id}}/camera.front_door_2/clip.mp4
> > ```
> 
> This is invalid.
> 
> the camera name needs to match frigate config. and not have 'camera.' at the front.
> 
> so `camera.front_door_2` probably needs to be just front_door i assume, which it would have been by default.

Thanks. I tried it with {{camera}} and front_door as you recommended, but it didn't work. They both show the image here: https://www.reddit.com/r/homeassistant/comments/155vtoh/frigate_blueprint_clip_broken/

I also tried changing the name to "front_yard" so there is no more conflict with the other camera entity, and tried using the blueprint with just the drop downs, but I still get the image above. I've confirmed that I can otherwise see the clips on my devices.

**Comment by SgtBatten** [comment]
Copy the url that it opens onto a device on your local network. Remove the nabu casa url and replace it with the Lan IP and port of home assistant. Any difference?

**Comment by Hamish1066** [comment]
It didn't work with the Lan IP, but it did work when I replaced the Nabu Casa URL with homeassistant.local:8123. However, it only works in Chrome, and only on my laptop, not on my iPhone. I also tried pasting the Nabu Casa URL into Chrome, and it won't load - it just gives me a black video box that says "0:00" for time and the play button doesn't do anything.

**Comment by SgtBatten** [comment]
Perhaps a codec issue. Are the cams outputting h.265?

**Comment by Hamish1066** [comment]
Yes, I think that’s why it’s not playing in certain browsers - it is h.265 - but that doesn’t explain why it won’t play in that companion app. The stream and recordings both play on the companion app, so I think clips should play as well?

Peter
________________________________

**Comment by SgtBatten** [comment]
You said it wouldn't work with your nabu casa url even in chrome so I assume the same reason is the issue for the app. Though on android it doesn't open in the app, it opens in a browser so I can't play h.265 clips. I run two recorders for the hm265 cam. One in h.264 for being able to view it everywhere. And one just recording in beat quality in case I need it. 

I suggest you try without the base url set and see what occurs.

**Comment by Hamish1066** [comment]
I tried without the base url in the automation and there was no difference. I guess I’ll see if I can get a h.264 stream on my Reolink cameras. Any other suggestions?

Peter
________________________________

**Comment by SgtBatten** [comment]
h.265 is not well supported still. I cannot play it on any of my devices, even my desktop computer due to older hardware. I also have reolink cams and there were heaps of resources on this topic I used when i set them up. Some cams can be tricked into h.264 with slight reductions in resolution, others only do h.265 on certain streams like my duo2. 

I agree it's weird you can view it in the app when browsing frigate normally but not via the api. How certain are you it's opening in the app?

**Comment by Hamish1066** [comment]
I’m 100% certain that it’s opening in the app.  I’ve tried opening it in the app and the browser, and both have the same result. I’ll try to get h.264 working. Do you set the h.264 stream for detect and recording?

As a side note, I was thinking of getting a duo2. Does it not do h.264 at all?

Peter
________________________________

**Comment by SgtBatten** [comment]
The duo2 is the only 265 cam I have but I read about many others over the time. 

If I recall correctly the main duo2 stream is only 265. The substream is only 264. So in frigate I have two cams setup for the one duo2. One which detects and records on the 264 substream. I use this for all my notifications. The other cam detects on 264 and records the main 265 stream so I have the highest resolution recorded if I need to pull tapes.

**Comment by Hamish1066** [comment]
Thank you. Any chance you could share your config for the Duo and your other Reolink camera? I’ve read a LOT online of peoples configs for these, but all seem to be a year or two old - I can’t get them working on mine and I’m wondering if something has changed on that time.

Peter
________________________________

**Comment by Hamish1066** [comment]
Further, I just tried setting this up on a h.264 camera, and I’m having the exact same issue. So I think I can rule the stream out – it seems to be something else. Any ideas? It would be great if you could share your config as requested above so I could debug this.

From: Peter Rowntree ***@***.***>
Date: Sunday, July 23, 2023 at 5:38 AM
To: SgtBatten/HA_blueprints ***@***.***>, SgtBatten/HA_blueprints ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [SgtBatten/HA_blueprints] [Bug]: Clip not showing/broken (Issue #61)
Thank you. Any chance you could share your config for the Duo and your other Reolink camera? I’ve read a LOT online of peoples configs for these, but all seem to be a year or two old - I can’t get them working on mine and I’m wondering if something has changed on that time.

Peter
________________________________

**Comment by Hamish1066** [comment]
Sorry - one other thought - are you able to share the yaml for how the automation opens the specific clip, and perhaps I could try it in another automation without the blueprint?

Peter
________________________________

**Comment by SgtBatten** [comment]
> are you able to share the yaml for how the automation opens the specific clip, and perhaps I could try it in another automation without the blueprint?

You've already done this. The automation just open the url. It has some behind the scenes bits to generate the I'd but if you've copied it, and pasted it somewhere else that's the whole process. 

Frigate generates the event I'd and we are simply using the frigate notification API from the integration. 

Can you please check what you have configured for the integration?

![Screenshot_20230724-071203](https://github.com/SgtBatten/HA_blueprints/assets/24822223/b988e04f-bda2-4bfd-922c-dd9df317ff13)


Frigate config I will share in a little bit.

**Comment by Hamish1066** [comment]
Thanks. My config for the integration is identical:

[Image.jpeg]

For the yaml for how to open the specific clip, I don’t understand how to pull the event ID outside of your blueprint?

I really appreciate your help so far! I’m very excited about Frigate and this is the last piece that I would like to get working in order to ditch my old canards setup completely.


Peter
________________________________

**Comment by SgtBatten** [comment]
Here is the reference to the api we are using. It hasn't changed in forever so we know it's good. https://docs.frigate.video/integrations/home-assistant/#notification-api

to get the id, one easy way is to go to frigate events, click and event, click snapshot instead of clip 
![image](https://github.com/SgtBatten/HA_blueprints/assets/24822223/113b0fef-9212-4787-a7ce-31b17b1ad9b6)

right click and pen the image in new window. the url contains the relevant ID near the end where it says `/api/events/3620134358.35426-gydf7o/snapshot.jpg`

**Comment by SgtBatten** [comment]
I've cut most of this out just to show the relevant bits. All the cams below are reolink but the duo2 is the only one with a 265 stream. My config was a lot of trial and error and is not perfect, just showing you what i have working currently. front and front4k are the two frigate cams i pull from the duo2.

```
go2rtc:
  streams:
    side: http://192.168.1.81/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}
    side_sub: http://192.168.1.81/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}
    front_sub: ffmpeg:http://192.168.1.82/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}
    doorbell: http://192.168.1.83/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}
    doorbell_sub: http://192.168.1.83/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password={FRIGATE_REOLINK_PASSWORD}

cameras:
side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/side?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/side_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect

  front:
    ffmpeg:
      inputs:        
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

  front_4K:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_REOLINK_PASSWORD}@192.168.1.82:554/h265Preview_01_main
          roles:
            - record
          hwaccel_args:
            -hwaccel vaapi
            -hwaccel_device /dev/dri/renderD128
            -hwaccel_output_format vaapi
          input_args: 
            -avoid_negative_ts make_zero
            -fflags genpts+discardcorrupt
            -strict experimental
            -analyzeduration 1000M
            -probesize 1000M
        
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - detect
```

**Comment by Hamish1066** [comment]
So I've found that if I hold the notification I can see a live view of the camera stream, and I have the options to view the clip or snapshot. If I click view the clip it gives me the same broken play button image, and if I try the snapshot it worked once but otherwise says not found. Is there a way to configure the stream that pulls up when I hold the notification to show me the clip instead of the live stream? I think that could fix this issue for me, since it seems to be able to play from there.

**Comment by SgtBatten** [comment]
> Thanks. Why is there a difference in the IP addresses for go2rtc vs the camera setups?

Gortc connects to the reolink cams and then restreams them.

For the camera section it's connecting to gortc, not the camera.
Exception is front 4k main stream. I can't remember exactly but direct connection worked better when I set it up.

**Comment by Hamish1066** [comment]
I think I may have found the source of the issue. In the HA media sources folder, there is a “My Media” folder and a “Frigate” folder. If I go into the Frigate folder, everything is recorded as I’ve set it up. However, in the path mymedia/frigate/clips, there is nothing. I suspect clips are being pulled from here which is why they aren’t showing up. Does that make sense?

**Comment by SgtBatten** [comment]
That is normal. The median is in the frigate folder as you said. There integration is what connects frigate media with the HA media folder

**Comment by Solarflor** [comment]
Hi all,
I'm having a similar issue.
I have installed HA_blueprints Frigate Notifications (0.12.0.1) with notification on my Iphone and it seems to work almost well.
Almost because I'm even able to receive snapshot on my Iwatch.
![image](https://github.com/SgtBatten/HA_blueprints/assets/100423265/ef2f682a-0606-49d6-91c8-5f59f3e5a4b3)

But not on my Iphone where I only can see:
![image](https://github.com/SgtBatten/HA_blueprints/assets/100423265/3696ff24-80a7-44d2-8484-f9037585ae66)

Below frigate config

`mqtt:
 host: core-mosquitto
 port: 1883
 user: solarflor
 password: floriano1628

# Optional: birdseye configuration
# NOTE: Can (enabled, mode) be overridden at the camera level
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 5
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects


ffmpeg:
  hwaccel_args: preset-rpi-64-h264
detect:
  enabled: True # <---- disable detection until you have a working camera feed
  width: 1920 # <---- update for your camera's resolution
  height: 1080 # <---- update for your camera's resolution
motion:
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 3
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 3
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 3
        car: 2
        truck: 2
        bicycle: 2
        motorcycle: 2
        dog: 2
        cat: 2


cameras:
  Piazzale_1: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-rpi-64-h264
      inputs:
        - path: rtsp://admin:Antonio1628@192.168.1.209:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - detect
#            - rtmp
    objects:
      track:
        - person
        - car
#        - truck
#        - bicycle
#        - motorcycle
#        - dog
#        - cat
    record: # <----- Enable recording
      enabled: True
    snapshots: # <----- Enable snapshots
      enabled: True

`
I have a Dahua Camera IPC-HFW3441T-ZS

Thanks for your support

**Comment by Solarflor** [comment]
Here it is
`alias: Frigate Notifications (0.12.0.1)
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.piazzale_1
    notify_device: b76118c030e61eef2c2eee37a5d0fc0e
    attachment: snapshot
    labels:
      - person
    presence_filter: person.floriano
`

**Comment by Solarflor** [comment]
sorry, not sure why the code is showed as above (no readable way). I used the <> comand

**Comment by Hamish1066** [comment]
I'm still working at this problem btw. Interesting to see someone else has it. I've tested the notification on my MacBook Pro as well. When I open the notification in Safari, I get the same broken play button icon and no video. In Firefox, I get a video player that just plays black for the amount of the clip. In Chrome, it works fine. I've tried opening it in Chrome on my iPhone as well, but I get the broken play button.

**Comment by Hamish1066** [comment]
Another update - this is definitely related to file format issues with iOS/MacOS/Safari. I downloaded VLC for iPhone and tried the clip there - it plays fine. 

Is there a way to update the HA app so it can play these videos, or alternatively open the clips in VLC from the notification? 

I'm still not sure why these videos won't play on iOS/MacOS/Safari, when in theory they are h.265 so therefore compatible. Maybe there is an issue with my Frigate config? Or possibly my HA config?

**Comment by SgtBatten** [comment]
H.265 is not supported as far as I know. Not on android either. 

But you said it also happened on h.264?

**Comment by SgtBatten** [comment]
> Here it is

Have you tried using a baseurl?

**Comment by Solarflor** [comment]
> Have you tried using a baseurl?

give me some more instruction please

**Comment by SgtBatten** [comment]
> give me some more instruction please

How do you access home assistant remotely? Do you have a url you setup?

E.g through nabu casa or you own private domain. 

Or maybe you only use it at home, still you would have the Lan IP address and port and could use that. 

Whatever it is, enter it in the bases url field in the automation.

**Comment by Solarflor** [comment]
> How do you access home assistant remotely?

I have a duckdns url.

> Whatever it is, enter it in the bases url field in the automation

do you mean someting like
`base_url: http://[myurl].duckdns.org`
ok I will try although it is not a protect url (https)

**Comment by Hamish1066** [comment]
> H.265 is not supported as far as I know. Not on android either.
> 
> But you said it also happened on h.264?

H.265 is supported on iPhone and MacOS, but I understand from some further reading that certain transcoders, including FFmpeg which is used by Frigate, aren’t compatible. 

And yes, I’ve had the same issue using my h.264 cameras.

**Comment by Hamish1066** [comment]
OK I FINALLY GO THIS WORKING WOOOOOOOO!

So, this issue is h.265. It turns out that, although both iOS and MacOS can play h.265 video, as I stated above, it cannot play video transcoded with FFmpeg. But there is a workaround (below). 

I had two issues here:

1. The FFmpeg transcoding not playing on Apple devices (I understand it works fine on Android); and
2. Trying to play the clip in the HA companion app vs the web.

On issue 2, I was trying to play the clips directly within the companion app using this instead of the "View Clip" drop down option: 

`/frigate/notifications/{{id}}/{{camera}}/clip.mp4`

That forced it to open the clip in the HA app rather than the browser, and caused the playback issued described above.

On issue 1, I found you can force compatibility by adding -tag:v hvc1 \ to your FFmpeg line in your Frigate config. This gives you an hvc1 output instead of hev1, which is incompatible with Apple. 

My complete FFmpeg config is as follows (though only the one line mentioned above is necessary to get this to work:

```
ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -tag:v hvc1 
  output_args:
    record: preset-record-generic-audio-aac

@SgtBatten Thanks for your patience on this. I really appreciate you supporting such an awesome project (or projects - both HA and Frigate), and really appreciate you taking the time to create this Blueprint and respond to me. I'll leave this open for a day so that @Solarflor can try it out to confirm it's working, then assuming this works for that person we can close this issue.
```
