### ISSUE TITLE
[Config Support]: Notification Group

### ISSUE THREAD

**Issue by halexh** [SgtBatten/HA_blueprints#62]
### Describe the problem you are having or the outcome you are trying to achieve.

I am having trouble setting up a notification group.

Specifically, in my `configurations.yaml` file where I have added

```
notify:
  - name: Notification_Group
    platform: group
    services:
      - service: 
      - service: 
```

I have no idea what to put for service, or where to look to get service. I have notifications setup already, pushing notifications to just my phone, and it works really well. But I want to create a notification group to push to both my phone and my wife's. The documentation at https://www.home-assistant.io/integrations/group/#notify-groups doesnt really help me, and I am still unsure what to put for each service entry.

### Version

0.12.0.1

### Automation config file

```yaml
- id: '1690399193051'
  alias: 'Notify: Front Cam - Person'
  description: Sends push notification on person detected at front camera
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.front
      notify_device: 63fa2296a6448fb4f88ed5959ec20954
      base_url: <redacted>
      message: Person detected - {{camera_name}}
      update_thumbnail: true
```
