### ISSUE TITLE
[Config Support]: Not getting any notifications

### ISSUE THREAD

**Issue by johntdyer** [SgtBatten/HA_blueprints#67]
### Describe the problem you are having or the outcome you are trying to achieve.

I have a camera in my driveway "camera.frigate_driveway" which I can see in frigate API is detecting movement and is publishing to the events mqtt topic.

<img width="630" alt="image" src="https://github.com/SgtBatten/HA_blueprints/assets/58234/185f22d6-88b1-460a-ad85-b671e6a21b18">

```{"before": {"id": "1691013794.090061-imniai", "camera": "driveway", "frame_time": 1691016572.314422, "snapshot_time": 1691013794.771288, "label": "car", "sub_label": null, "top_score": 0.8046875, "false_positive": false, "start_time": 1691013794.090061, "end_time": null, "score": 0.796875, "box": [438, 32, 701, 199], "area": 43921, "ratio": 1.5748502994011977, "region": [392, 0, 860, 468], "stationary": true, "motionless_count": 41629, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true}, "after": {"id": "1691013794.090061-imniai", "camera": "driveway", "frame_time": 1691016632.444831, "snapshot_time": 1691013794.771288, "label": "car", "sub_label": null, "top_score": 0.8046875, "false_positive": false, "start_time": 1691013794.090061, "end_time": null, "score": 0.796875, "box": [438, 32, 701, 199], "area": 43921, "ratio": 1.5748502994011977, "region": [392, 0, 860, 468], "stationary": true, "motionless_count": 42531, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": true, "has_snapshot": true}, "type": "update"}
```

### Version

0.12.0.1

### Automation config file

```yaml
alias: Person Driveway new
description: new automation w/ latest blueprint
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frigate_driveway
    notify_device: de18046673382edb91ca0c0341af7bf4
    base_url: https://ha.xxxxx.xxxxx
    alert_once: true
    update_thumbnail: true
    ios_live_view: true
    debug: true

````
```


### Frigate Config

```yaml
# yaml-language-server: $schema=http://192.168.121.128:5000/api/config/schema.json
database:
  # path: /config/db/frigate.db
  path: /db/frigate.db

logger:
  # Optional: default log level (default: shown below)
  default: info

  logs:
    frigate.app: info
    frigate.video: info
    frigate.record: info
    # frigate.mqtt: info
    # frigate.edgetpu: info
    # frigate.zeroconf: info
    # frigate.record: info
    # frigate.events: info
    # peewee: info

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: 192.168.120.254
  user: xxxxx
  password: xxxx
  stats_interval: 60
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  # height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)

  # required_zones:
  #   - entire_yard
  #   - front_yard_street

  retain:
    default: 5
    objects:
      person: 5

objects:
  track:
    - person

rtmp:
  enabled: False

go2rtc:
  stream:
    office_high:
      - rtspx://192.168.100.1:7441/zuqiocLfJeAXUCOP
    office_low:
      - rtspx://192.168.100.1:7441/OG10qvYd9TREkcFA

    pool_high:
      - rtspx://192.168.100.1:7441/ubxWpFU376QD1eOm
    pool_low:
      - rtspx://192.168.100.1:7441/fD6ouM72bWoFijxK

    backyard_high:
      - rtspx://192.168.100.1:7441/CwnySMZFN2rYoMvx
    backyard_low:
      - rtspx://192.168.100.1:7441/3Exd46wtOuVxMMk8

    sideyard_high:
      - rtspx://192.168.100.1:7441/1aUpwawO1EJUDUBT
    sideyard_low:
      - rtspx://192.168.100.1:7441/vL3uSs1fIHd8MQPJ

    backdeck_high:
      - rtspx://192.168.100.1:7441/JiCxVjTaor4ehjT1
    backdeck_low:
      - rtspx://192.168.100.1:7441/pDafClgV3eXexuM9

    living_room_high:
      - rtspx://192.168.100.1:7441/sIhqRkwMU9rrAS4w
    living_room_low:
      - rtspx://192.168.100.1:7441/tlNVjdkcR3ewlss3

    garage_high:
      - rtspx://192.168.100.1:7441/xO2din5BhB2N6HST
    garage_low:
      - rtspx://192.168.100.1:7441/gC3wfmI6ETE4pq7T

    driveway_high:
      - rtspx://192.168.100.1:7441/1KMFJohmtwFnFbiL
    driveway_low:
      - rtspx://192.168.100.1:7441/vg2bEQ1lGfMcsJrH

    server_room_high:
      - rtspx://192.168.100.1:7441/JGkidgpVPslCkgEQ
    server_room_low:
      - rtspx://192.168.100.1:7441/ZnTxwTIDWUOmrHIt

    basement_high:
      - rtspx://192.168.100.1:7441/n5tmrpmbDHJTALdz
    basement_low:
      - rtspx://192.168.100.1:7441/C9JgAAcM7030HL4P

    upstairs_high:
      - rtspx://192.168.100.1:7441/o8hn7teaizs3lW5y
    upstairs_low:
      - rtspx://192.168.100.1:7441/LzS1mD1lQoa8v0nY

    grand_room_high:
      - rtspx://192.168.100.1:7441/v0oq2YR9MYlZ8yZR
    grand_room_low:
      - rtspx://192.168.100.1:7441/yXCjrq2ywbx2yG4C

    basement_unfinished_high:
      - rtspx://192.168.100.1:7441/QEjQ1m3iQVkVQTeW
    basement_unfinished_low:
      - rtspx://192.168.100.1:7441/U9Hg1pTRlnnvB09z

    front_door_high:
      - rtspx://192.168.100.1:7441/K7yQEKu8n0RlBTWA
    front_door_low:
      - rtspx://192.168.100.1:7441/UoaMPaE8gILYfvcG

record:
  enabled: True
  retain:
    days: 30
  events:
    pre_capture: 5
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    required_zones: []
    retain:
      default: 5
      # Optional: Per object retention days
      objects:
        person: 5

detect:
  width: 1024
  height: 576
  fps: 15
  enabled: True
  max_disappeared: 25
ffmpeg:
  # hwaccel_args:
  #   - -hwaccel
  #   - vaapi
  #   - -hwaccel_device
  #   - /dev/dri/renderD128
  #   - -hwaccel_output_format
  #   - yuv420p
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  input_args: >-
    -c:v h264_cuvid -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
    tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -an
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac

cameras:

###################
#    office       #
###################
  office:
    objects:
      track:
        - person
        - dog
        - cat

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/zuqiocLfJeAXUCOP?enableSrtp
          # rtsp://127.0.0.1:8554/office_high
          # input_args: preset-rtsp-restream
          #
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/OG10qvYd9TREkcFA?enableSrtp
        #@- path: rtsp://127.0.0.1:8554/office_low
          #@input_args: preset-rtsp-restream
        #
          roles:
            - detect


    detect:
      width: 1024
      height: 576
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
      # required_zones:
      #   - Front_Patio
      #   - Front_Steps
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
        # required_zones:
        #   - Front_Patio
        #   - Front_Steps
    # mqtt:
    #   required_zones:
    #     - Front_Patio
    #     - Front_Steps
    # zones:
###################
#    pool         #
###################
  pool:
    objects:
      track:
        - person
        - dog
        - cat
    ffmpeg:
      inputs:
        # High Resolution Stream 1920*1080
        - path: rtsps://192.168.100.1:7441/ubxWpFU376QD1eOm?enableSrtp
        # - path: rtsp://127.0.0.1:8554/office_high

          input_args: preset-rtsp-restream
          roles:
            - record

        # Low Resolution Stream 1280 * 720
        - path: rtsps://192.168.100.1:7441/fD6ouM72bWoFijxK?enableSrtp
        # - path: rtsp://127.0.0.1:8554/pool_low
          input_args: preset-rtsp-restream
          roles:
            - detect


    detect:
      width: 1280
      height: 720
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
      # required_zones:
      #   - Front_Patio
      #   - Front_Steps
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
        # required_zones:
        #   - Front_Patio
        #   - Front_Steps
    # mqtt:
    #   required_zones:
    #     - Front_Patio
    #     - Front_Steps
    # zones:


###################
#    backyard     #
###################
  backyard:
    objects:
      track:
        - person
        - dog

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/CwnySMZFN2rYoMvx?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/3Exd46wtOuVxMMk8?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    Side Yard    #
###################
  sideyard:
    objects:
      track:
        - person
        - dog
    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/1aUpwawO1EJUDUBT?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/vL3uSs1fIHd8MQPJ?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    backdeck     #
###################
  backdeck:
    objects:
      track:
        - person
        - dog
    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/JiCxVjTaor4ehjT1?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/pDafClgV3eXexuM9?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 15
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

    motion:
      mask:
        - 382,128,375,175,142,195,142,134

###################
#    living_room  #
###################
  living_room:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/sIhqRkwMU9rrAS4w?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/tlNVjdkcR3ewlss3?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 15
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    garage       #
###################
  garage:
    objects:
      track:
        - person
        - bicycle

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/xO2din5BhB2N6HST?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/gC3wfmI6ETE4pq7T?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 15
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
###################
#    driveway     #
###################
  driveway:
    objects:
      track:
        - person
        - dog
        - car
        - bicycle
    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/1KMFJohmtwFnFbiL?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/vg2bEQ1lGfMcsJrH?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 15
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    server_room  #
###################
  server_room:
    objects:
      track:
        - person

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/JGkidgpVPslCkgEQ?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/ZnTxwTIDWUOmrHIt?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 15
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    basement     #
###################
  basement:
    objects:
      track:
        - person
        - dog
        - cat


    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/n5tmrpmbDHJTALdz?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/C9JgAAcM7030HL4P?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 20
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    upstairs     #
###################
  upstairs:
    objects:
      track:
        - person
        - dog
        - cat

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/o8hn7teaizs3lW5y?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/LzS1mD1lQoa8v0nY?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    grand_room   #
###################
  grand_room:
    objects:
      track:
        - person
        - dog
        - cat

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/v0oq2YR9MYlZ8yZR?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/yXCjrq2ywbx2yG4C?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

##############################
#    basement_unfinished     #
##############################
  basement_unfinished:
    objects:
      track:
        - person
        - dog
        - cat

    ffmpeg:
      inputs:
        # High Resolution Stream 1920 * 1080
        - path: rtsps://192.168.100.1:7441/QEjQ1m3iQVkVQTeW?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1024 x 576
        - path: rtsps://192.168.100.1:7441/U9Hg1pTRlnnvB09z?enableSrtp
          roles:
            - detect

    detect:
      width: 1024
      height: 576
      fps: 15
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10

###################
#    front_door   #
###################
  front_door:

    ffmpeg:
      inputs:
        # High Resolution Stream 3840 * 2160
        - path: rtsps://192.168.100.1:7441/K7yQEKu8n0RlBTWA?enableSrtp
          roles:
            - record
        # Low Resolution Stream 1280 x 720
        - path: rtsps://192.168.100.1:7441/UoaMPaE8gILYfvcG?enableSrtp
          roles:
            - detect

    detect:
      width: 1280
      height: 720
      fps: 30
      enabled: True
      max_disappeared: 25

    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10


    objects:
      track:
        - person
        - people
        - dog
        - car
        - bicycle
        - bus

    zones:
      front_yard_zone:
        coordinates: 907,576,797,102,685,144,561,183,486,201,433,229,253,297,47,436,41,413,0,576,572,576,659,576,804,576
        objects:
          - bicycle
          - people
          - person
      driveway_zone:
        coordinates: 806,25,841,70,861,67,266,289,206,291,349,228,600,122
        objects:
          - car
          - bicycle
          - bus
          - person
      street_zone:
        coordinates: 28,376,359,204,728,51,669,30,114,228,0,307
        objects:
          - car
          - bicycle
          - person
          - bus


```
```


### Any other information that may be helpful

I have tried debug mode but that didnt really help... only time the automation seems to trigger is when I manually trigger it from the automation panel .   Any help would be appreciated
