### ISSUE TITLE
[Feature Request]: Provide option to trigger additional actions

### ISSUE THREAD

**Issue by bmck0118** [SgtBatten/HA_blueprints#69]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to trigger additional actions on run so that I can send a message to google home or turn on a light based on occupacy for example

**Describe the solution you'd like**
Add an extra option to trigger a service / action or even a script in addition to sending a notification

**Describe alternatives you've considered**
Can't think of any while being able to utilise the benefits of this blueprint configuration.  Option used currently is to create a separate automation triggered by the camera occupancy status but that doesn't easily provide the same filtering and options unless they are fully specified manually.

**Additional context**

**Comment by SgtBatten** [comment]
There is a seperate branch called custom action. I built in months ago as many people requested this. But no-one is providing feedback on it. 

Please try it and let me know what can be improved for your use case

**Comment by bmck0118** [comment]
Perfect. I'll check it out and let you know. Thanks.

**Comment by reesion** [comment]
> There is a seperate branch called custom action. I built in months ago as many people requested this. But no-one is providing feedback on it.
> 
> Please try it and let me know what can be improved for your use case

Hi,

I am using the custom action branch but am unable to see the additional options. Am i missing anything?

**Comment by SgtBatten** [comment]
Please use the beta

**Comment by SgtBatten** [comment]
Any feeback @reesion

**Comment by reesion** [comment]
> Any feedback @reesion ?

Hi, unfortunately I am unable to get it to work. I  added a condition for after sunset and before sunrise to trigger a light switch but it doesn’t seem to work.

**Comment by SgtBatten** [comment]
> it doesn’t seem to work.

It had been a while since I created it so after reviewing the code, I have reworked it just now. You will see 3 custom action fields now with some guidance

**Comment by SgtBatten** [comment]
> Is this the correct url?

https://github.com/SgtBatten/HA_blueprints/blob/custom_action/Frigate%20Camera%20Notifications/Beta

**Comment by reesion** [comment]
> https://github.com/SgtBatten/HA_blueprints/blob/custom_action/Frigate%20Camera%20Notifications/Beta

this doesn’t seem to work. I am using the ‘Auto trigger’ and have removed the conditions to eliminate the issue and just put a service Switch: Toggle to turn on a switch but still not working.

**Comment by SgtBatten** [comment]
Okay I will try to test soon 

The manual trigger is working for me. Tested that yesterday to toggle a light

**Comment by reesion** [comment]
> The manual trigger is working for me. Tested that yesterday to toggle a light

I have tested the manual trigger and can confirm it worked as well. Just couldn't get the 'Auto trigger' working

**Comment by krystiancharubin** [comment]
I've also been trying to get auto actions working but they are not triggering. Commented out most of the conditions leaving jus the length condition and it seems to still evaluate to false

```
- alias: "Custom Action Auto"
  choose:
  - conditions:
      - "{{ custom_action_auto |length}}"
      # - "{{ not zone_only or (not zone_multi and zones|select('in', entered_zones)|list|length > 0) or (zone_multi and entered_zones|length > 0 and zones |reject('in', entered_zones) |list |length == 0) }}"
      # - "{{ not initial_home }}"
      # - "{{ not state_only or states(input_entity) in states_filter }}"
    sequence: !input "custom_action_auto"
```
