### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by memattyg** [SgtBatten/HA_blueprints#73]
### Describe the problem you are having or the outcome you are trying to achieve.

I know this is probably a basic question, I am new and stuck.  I am having issues getting the action buttons in the blueprint to appear and work on iOS and watchOS.

On iOS, the notification comes through, but instead of buttons for view clip, view snapshot and silence, the buttons say Open, Always Open and Cancel.  When opened, the video plays in safari not HA.

On watchOS, the buttons appear as view clip, view snapshot and silence, but pressing them does nothing but show an error that they are undefined.

I have not made changes in the config file for the automation, just edited the blueprint in UI to create the automation.

### Version

12.0.1

### Automation config file

```yaml
- id: '1691849008720'
  alias: Front Door Person Notification
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.frontdoor
      notify_device: 88ae86aba32940bc6406889b49****** 
      alert_once: true
      ios_live_view: true
      labels:
      - person
      cooldown: 45
      silence_timer: 30
      zones:
      - zone1
      update_thumbnail: true
```
