### ISSUE TITLE
[Bug]: Error in logs when using debug logging

### ISSUE THREAD

**Issue by johntdyer** [SgtBatten/HA_blueprints#74]
### Description

I am seeing this in my logs
```
2023-08-14 07:55:51.911 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'client_id' is undefined when rendering 'DEBUG (in loop):
  Info:
    Last Zones: {{last_zones}},
    Current zones: {{entered_zones}},
    sublabel: {{sub_label}},
    iOS sound: {{update if not critical else 'yes due critical notifications'}},
    Android Sound: {{'disabled by alert once' if alert_once else 'enabled'}},
  Triggers:
    New Snapshot: {{new_snapshot}},
    Presence Changed: {{presence_changed}},
    stationary moved: {{stationary_moved}},
    entered zones changed: {{entered_zones_changed}},
    sublabel changed: {{sub_label_changed}},
  Conditions:
    Loitering: {{loitering}}
      or
    Presence Entity not home: {{'ON' if presence_entity != '' else 'OFF'}} - {{'PASS' if not home else 'FAIL'}},
    zone filter TEST: {{'ON' if zone_only else 'OFF'}} - {{'PASS' if zone_filter else 'FAIL'}},
    multi-zone filter: {{'OFF' if not zone_only or not zone_multi else 'ON'}} - {{'PASS' if not zone_only or not zone_multi or ( entered_zones|length and zones and zones |reject('in', entered_zones) |list |length == 0 ) else 'FAIL'}},
    state filter TEST: {{'ON' if state_only else 'OFF'}} - {{'PASS' if state_true else 'FAIL'}}

    image: "/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}.jpg?format=android"'

```

### Version

0.12.0.1

### Automation Config

```yaml
alias: Person Driveway new
description: new automation w/ latest blueprint
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frigate_driveway
    notify_device: de18046673382edb91ca0c0341af7bf4
    base_url: https://ha.xxxx.xxxx
    alert_once: true
    update_thumbnail: true
    ios_live_view: true
    debug: true
    cooldown: 90
    silence_timer: 10
    loiter_timer: 14
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"

```
```


### Frigate Config

_No response_

### Any other relevant information

```yaml
Also I noticed the `?format=android"'` query string param... is this a problem if I am using an iPhone?
```
