### ISSUE TITLE
Frigate Proxy

### ISSUE THREAD

**Issue by tunavis** [SgtBatten/HA_blueprints#75]
### Describe the problem you are having or the outcome you are trying to achieve.

Hi, i migrated my frigate from within HA to my docker invironment. So only using proxy feature. Does the blueprint still work only for proxy edition. Haven't received any capturing notifications from the migration?

### Version

Latest Version

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: Outdoor snapshot notfification
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.garage_door_camera_2
    base_url: https://xxxxxxx
    title: Outdoor Detection
    attachment: snapshot
    ios_live_view: true
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    button_3: View Clip
    url_2: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    url_1: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    button_2: View Snaphot
    button_1: View Snaphot
    notify_group: alertapp
```

### Frigate Config

```yaml
server: 192.168.0.11:5000

Docker enviroment: Simple rstp camera setup, pointing to my MQTT broker on HA.
```
