### ISSUE TITLE
[Config Support]: Undefined variables when rendering notification title/message

### ISSUE THREAD

**Issue by cdavis289** [SgtBatten/HA_blueprints#76]
### Describe the problem you are having or the outcome you are trying to achieve.

Getting this error when the notification is triggered: 

Template variable warning: 'entered_zones' is undefined when rendering '{{ entered_zones | replace("_", " ") | capitalize}}'

I've also just tried using {{entered_zones}} and that also gives me an error.

### Version

0.12.0.1 downloaded 8/15

### Automation config file

```yaml
alias: 2 Notification - Frigate G4 Doorbell Pro New
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.g4_doorbell_pro
    notify_device: 903d52304f3246be78b7aa441f6f1670
    base_url: http://192.168.20.2:8123
    title: "{{label | capitalize | title}} Detected"
    message: "{{ entered_zones | replace(\"_\", \" \") | capitalize}}"
    alert_once: true
    update_thumbnail: true
    ios_live_view: true
    zone_filter: true
    zones:
      - entry_stairs
    labels:
      - person
    button_3: Open Gate
    url_3: open_gate
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    debug: true
```

### Any other information that may be helpful

Executed: August 15, 2023 at 9:40:59 AM
Result:
params:
  domain: logbook
  service: log
  service_data:
    name: Frigate Notification
    message: |-
      DEBUG: 
        Info:
          fps: 5, 
          frigate event id: 1692117658.712056-tzh9mo, 
          object (formatted): person (Person),
        Config: 
          camera(formatted): g4_doorbell_pro(G4 Doorbell Pro), 
          Base URL: http://192.168.20.2:8123, 
          critical: False, 
          alert once: True, 
          Update Thumbnails: True, 
          Target: Mobile Device
          cooldown: 30s, 
          loiter timer: 0s,
          color: steelblue, 
          sound: default,
          Title: Person Detected, 
          Message: ,
          tap_action: http://192.168.20.2:8123/api/frigate/notifications/1692117658.712056-tzh9mo/snapshot.jpg, 
          button 1 Text/URL: View Clip (http://192.168.20.2:8123/api/frigate/notifications/1692117658.712056-tzh9mo/g4_doorbell_pro/clip.mp4), 
          button 2 Text/URL: View Snapshot (http://192.168.20.2:8123/api/frigate/notifications/1692117658.712056-tzh9mo/snapshot.jpg), 
          button 3 Text/URL: Open Gate (open_gate), 
          icon: mdi:home-assistant
          tv: False, 
          tv_position: center, 
          tv_size: large, 
          tv_duration: 10, 
          tv_transparency: 0%, 
          tv_interrupt: False, 
        Filters: 
          Zones: 
            zone filter toggle on: True, 
            Multi Zone toggle on: False, 
            Required zones: ['entry_stairs'], 
            Entered Zones: ['entry_stairs'], 
            Zone Filter TEST: PASS, 
          Required objects TEST: 
            Input: ['person'], 
            TEST: PASS
          presence entity (not home):
            Entity: 
            TEST:  PASS, 
          disabled times: [], 
          State Filter: 
            state filter toggle on: False, 
            state filter entity: , 
            required states: [], 
            State Filter TEST: PASS,
  target: {}
running_script: false
