### ISSUE TITLE
[Config Support]: Telegram notifications does not work

### ISSUE THREAD

**Issue by honeyfairy** [SgtBatten/HA_blueprints#81]
### Describe the problem you are having or the outcome you are trying to achieve.

I've integrated a frigate addon with my Home Assistant setup. The Stable blueprint is functioning correctly, delivering notifications to the Home Assistant app on my mobile device. I've also verified the functionality of the Telegram service by sending a successful test message. Nonetheless, there appears to be an issue, as the Telegram notifications are not operational when using the Beta blueprint.

### Version

Home Assistant 2023.8.3

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1h)ha2
description: ""
use_blueprint:
  path: SgtBatten/Beta.yaml
  input:
    camera: camera.mycam1
    base_url: http://102.55.55.55:8123
    notify_telegram_chat_id: "1900000008"
    attachment: /api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg
    video: >-
      {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4
    debug: true
    notify_device: f8480a01ed1c29d2342342342ea53
```

### Frigate Config

```yaml
mqtt:
  host: 102.redacted.66
  user: redacted
  password: redacted
cameras:
 
  mycam1:
    ffmpeg:

      inputs:
        - path: rtsp://Admin:Admin@102.redacted:5541/1/1
          roles:
            - detect
            - rtmp
            - record
            - clips

    detect:
      width: 2560
      height: 1440
     
    record:
      enabled: true

    objects:
      track:
        - person
        - car



    
record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  enabled: False
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```
