### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by consolecwby** [SgtBatten/HA_blueprints#84]
### Describe the problem you are having or the outcome you are trying to achieve.

I am running everything in docker containers on Unraid Version 6.12.3 2023-07-14

Homeassistant container is linuxserver/homeassistant:2023.8.4 docker
Frigate as blakeblackshear/frigate:stable
mqtt broker on eclipse-mosquitto

Frigate version 0.12
Frigate Integration Version 4.0
Frigate Notificaitons (0.12.0.1)
iOS app Home assistant companion 2023.4(2023.460)
iOS version 16.6

Do i need to connect Homeassitant to the Mqtt broker a special way since i am not running as Homeassistant OS?
I added the mqtt integration but not sure if i need to set it up so that it subscribes to certain things. 

### Version

0.12.0.1

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: |
  8/24/2023 Setup
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frontdoorbell
    notify_device: 1d92119dae3755b5bd47a773c15dd04e
    critical: "true"
    attachment: snapshot
    ios_live_view: true
    message: "Default:   e.g A Person was detected on the Frontdoorbell camera."
    alert_once: true
```

### Frigate Config

```yaml
mqtt:
    host: 192.168.1.5
    port: 1883
    user: frigate
    password: era451

detectors:
  coral0:
    type: edgetpu
    device: pci:0
  coral1:
    type: edgetpu
    device: pci:1

  coral2:
    type: edgetpu
    device: pci:2

snapshots:
  enabled: True
  crop: True
  bounding_box: True
  
record:
  enabled: True
  retain:
    days: 7
    mode: motion


objects:
  track:
    - person
    - car
    - dog
    - cat
    - elephant
#  filters:
#    person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
#      min_score: 0.6
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
#      threshold: 0.8
   
cameras:
  playroom: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.28:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution


  frontdoorkiosk: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.239:8080/h264_pcm.sdp
          roles:
            - detect
            - rtmp
        - path: rtsp://192.168.1.239:8080/h264_pcm.sdp
          roles:
            - record
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1600 # <---- update for your camera's resolution
      height: 896 # <---- update for your camera's resolution  


  frontdoorbell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:xytveg-hywvyv-Rurbo2@192.168.5.6:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect
            
        - path: rtsp://admin:xytveg-hywvyv-Rurbo2@192.168.5.6:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
  frontdoor: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.23:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://frigate:era451era451@192.168.5.23:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  pool: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.29:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

        - path: rtsp://frigate:era451era451@192.168.5.29:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution

    motion:
      mask:
        - 124,518,377,467,272,0,164,0
        - 1863,0,1806,569,1607,541,1548,0
    zones:
      pool_gate:
        coordinates: 358,1080,1291,1080,1593,611,1472,553,1429,536,1379,522,1339,501,1302,503,1229,487,1156,484,275,665
      pool_water:
        coordinates: 493,668,933,571,1197,517,1486,606,1266,793,845,1037
 
  driveway: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.25:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

        - path: rtsp://frigate:era451era451@192.168.5.25:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
  
  backyard: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.27:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

        - path: rtsp://frigate:era451era451@192.168.5.27:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
      
  patio-north: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.24:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

        - path: rtsp://frigate:era451era451@192.168.5.24:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  patio-south: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:era451era451@192.168.5.26:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect

        - path: rtsp://frigate:era451era451@192.168.5.26:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution

  garage: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:wetVen-jocjah-zimka4@192.168.5.30:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
          roles:
            - detect

        - path: rtsp://admin:wetVen-jocjah-zimka4@192.168.5.30:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 704 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
```

### Any other information that may be helpful

Once i get this running ill help you test the new stuff you posted in the forum.
