### ISSUE TITLE
[Config Support]:  Error rendering variables: TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by medhathaddad** [SgtBatten/HA_blueprints#85]
### Describe the problem you are having or the outcome you are trying to achieve.

I keep getting this error every time I try running the automation. The integration seems to be set up fine as I am able to receive notifications via Telegram.

Logger: homeassistant.components.automation.frigate_notifications_0_12_0_1
Source: components/automation/init.py:269
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 7:08:22 PM (2 occurrences)
Last logged: 7:24:35 PM

Error rendering variables: TypeError: can only concatenate str (not "int") to str

### Version

(0.12.0.1)

### Automation config file

```yaml
alias: Frigate Notifications (0.12.0.1)
description: ytrfyt
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.3
    notify_device: 45620487f824f803fc48161653989ee7
    base_url: http://homeassistant.local:8123/
```

### Frigate Config

```yaml
mqtt:
  enabled: True
  host: core-mosquitto
  topic_prefix: frigate
  client_id: frigate
  port: 1883
  user: --------
  password: ---------

cameras:
  1:
    ffmpeg:
      inputs:
        - path: rtsp://-----:------@192.168.--.--:554/Streaming/Channels/101/
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 15
    record: # <----- Enable recording
      enabled: True
      events:
        retain:
          default: 10
    rtmp:
      enabled: false
    snapshots:
        enabled: true
        timestamp: true
        bounding_box: true
        crop: False
        retain:
            default: 10
            objects:
                person: 15
    objects:
        track:
            - person
            - cat
            - dog
            - car
```
