### ISSUE TITLE
[Bug]: Multiple issues with Clips/Playback

### ISSUE THREAD

**Issue by asteriqz** [SgtBatten/HA_blueprints#87]
### Description

Hello,

I am having a few issues with my setup. I am using an iPhone iOS version 16.

Streaming and Clips both open up within Safari, 
I'm able to get it to open in HA although unable to get playback, it gives me a "broken play" button when setting the action to:
_/frigate/notifications/{{id}}/{{camera}}/clip.mp4_ although it works with the default action in Safari with the help of "input_args: -tag:v hvc1" as referenced by #61 - previous to this I wasn't able to view clips in Safari.

Is there anything obvious in my config that might cause this as I'd ideally want to view my clips within HA (avoid opening a heap of tabs every time I click on a notification).

All recordings work fine when manually opening them in Frigate.

### Version

0.12.0.1

### Automation Config

```yaml
alias: Backyard Camera
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.backyard
    notify_device: b299ae93b6f6c1edfe8f26596d37adb9
    base_url: https://xxx.xxx.xxx
    tap_action: /frigate/notifications/{{id}}/backyard/clip.mp4
    ios_live_view: true
    url_1: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    button_2: View Snapshot
    button_1: View Stream

```

### Frigate Config

```yaml
mqtt:
  enabled: True
  host: a0d7b954-emqx
  user: frigate
  password: xxx

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: -tag:v hvc1

database:
  path: /config/frigate.db
  
go2rtc:
  streams:
    username: "admin"
    password: "xxx"
    driveway: 
      - rtsp://admin:xxx@192.168.0.211:554/h265Preview_01_main
      - "ffmpeg:driveway#video=h264#hardware"
    backyard:
      - rtsp://admin:xxx@192.168.0.210:554/h265Preview_01_main
      - "ffmpeg:backyard#video=h264#hardware"
    # sideyard:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.104:554/h265Preview_01_main
    #  - "ffmpeg:sideyard#video=h264#hardware"
    #doorbell:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.108:554/h264Preview_01_main
    #viewcam:
    #  - rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.201.105:554/h265Preview_01_main
    #  - "ffmpeg:viewcam#video=h264#hardware"

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
        - car
    motion:
      mask:
       - 0,359,60,365,350,307,618,304,802,298,1115,295,1857,304,2197,295,2520,304,2719,310,2899,262,2918,184,2924,87,3086,0,0,0
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
    motion:
       mask:
        - 2024,55,1884,245,1812,408,1578,526,1300,570,898,501,892,391,675,388,667,223,881,182

record:
 enabled: True
 retain:
  days: 7
  mode: motion
 events:
  retain:
   default: 14
   mode: active_objects
snapshots:
  enabled: True

rtmp:
  enabled: false

birdseye:
  enabled: True
  mode: continuous
  restream: False
  width: 1920
  height: 1080
  quality: 4
```

**Comment by SgtBatten** [comment]
I'm neither an expert with video encoding or iOS unfortunately. 

I noticed you are recording from 265 to 264 using gortc. Have you tried (even temporarily) just recording the sub view that is already 264 and seeing if it makes a difference?

**Comment by asteriqz** [comment]
Thank you for the prompt response.

Removed all of gortc and went the following config: 

```yaml
cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.0.211:554/h264Preview_01_sub
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
        - car
    motion:
      mask:
       - 0,359,60,365,350,307,618,304,802,298,1115,295,1857,304,2197,295,2520,304,2719,310,2899,262,2918,184,2924,87,3086,0,0,0
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxx@192.168.0.210:554/h264Preview_01_sub
          roles:
            - detect   
            - record
    detect:
      width: 4096
      height: 1536
      fps: 5
    objects:
      track:
        - person
    motion:
       mask:
        - 2024,55,1884,245,1812,408,1578,526,1300,570,898,501,892,391,675,388,667,223,881,182
```

Still sadly facing the same issue.
