### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by hatmeh80** [SgtBatten/HA_blueprints#88]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello, cant get notifications on my iphone.

Also, in file editor i cant find folder media/friagate for snapshots ?

![Screenshot 2023-09-04 at 1 51 11 PM](https://github.com/SgtBatten/HA_blueprints/assets/25508643/b69d5709-8a04-46f9-8e4c-191de9eed793)

### Version

Frigate Notifications (0.12.0.1)

### Automation config file

```yaml
- id: '1693253424868'
  alias: Uri ipad
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: c3ffe4a3547989fbc3e0617d41d17d74
    entity_id: e707845a260d2f24036eb1734376c9ac
    domain: switch
  condition: []
  action:
  - service: notify.mobile_app_hassan_atmehs_ipad
    data:
      message: Dhdhd
      title: ' Bxhx'
      data:
        actions:
        - action: URI
          title: ' open camera '
          uri: /dashboard-camera
  mode: single
- id: '1693257740328'
  alias: New Automation cam iphone
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: c3ffe4a3547989fbc3e0617d41d17d74
    entity_id: e707845a260d2f24036eb1734376c9ac
    domain: switch
  condition: []
  action:
  - service: notify.mobile_app_hassans_iphone
    data:
      message: Shshz
      title: Dhdhddh
      data:
        type: custom:webrtc-camera
        url: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=Rori1411!_channel=1_stream=0.sdp
  mode: single
- id: '1693814986701'
  alias: Frigate Notifications (0.12.0.1)
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.frontdoor_2
      notify_device: ca3bea13e2155430e485cecd783b1bf7
      base_url: https://********
      title: Motion Detected
- id: '1693824643973'
  alias: Frigate Notifications (0.12.0.1)
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.frontdoor_2
      notify_device: ca3bea13e2155430e485cecd783b1bf7
      base_url: https://*******
- id: '1693825115620'
  alias: Frigate Notifications
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      notify_device: ca3bea13e2155430e485cecd783b1bf7
      base_url: **********
      camera: camera.frontdoor_2
```

### Frigate Config

```yaml
mqtt:
  host: 192.168.100.237
  user: mqttbroker
  password: rori2010
cameras:
  frontdoor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - detect
    detect:
      width: 1280
      height: 720
go2rtc:
  streams:
    frontdoor: rtsp://admin:Rori1411!@192.168.100.49:554/user=admin_password=Rori1411!_channel=1_stream=0.sdp
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

motion:
  threshold: 20
```
