### ISSUE TITLE
[Config Support]: Multiple Persons for Presence Filter

### ISSUE THREAD

**Issue by Chmynard** [SgtBatten/HA_blueprints#91]
### Describe the problem you are having or the outcome you are trying to achieve.

I am trying to use two presence's to check for the Presence Filter. For example, I do not want to get security camera footage of my spouse if I am at work. Flipside, if she leaves and I am at work, I do want to be notified. 

### Version

0.12.0.1

### Automation config file

```yaml
alias: KitchenCam Frigate
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.kitchencam
    notify_device: 07a3f17d6239762cfcd5d6b9e8fd874d
    message: A {{label}} was detected on the Kitchen camera.
    title: Person Detected
    update_thumbnail: true
    ios_live_view: true
    presence_filter: person.charles
```
