### ISSUE TITLE
[Config Support]: TV stream not working

### ISSUE THREAD

**Issue by jdherdt** [SgtBatten/HA_blueprints#92]
### Describe the problem you are having or the outcome you are trying to achieve.

I am trying to get a livestream on my TV from frigate when an event is triggered. That event is when a person walks by.
I have it working for sending a notification to my phone and also I have created a custom event so that I get a noise on my speakers saying : someone is at the door. 
While this is very convenient  I have noticed a bug where it plays the "someone is at the door" multiple times. Now I was thinking of also adding a live stream to my nvidia shield. 

When I try to use the blueprint it asks me to name the TV (in my case SHIELD) but when i look in the config it says "notification group: SHIELD". 

When i run the event it also doesn't seem to work. On my SHIELD nothing happens.

Can someone take a look at my config file and see what I did wrong and/or if this is a bug/issue ? 

### Version

0.12.0.1

### Automation config file

```yaml
alias: Frigate_Shield
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.door
    attachment: snapshot
    tv: true
    tv_position: top-right
    tv_size: medium
    tv_transparency: 50%
    base_url: https://homeassistant.xyz.com (yes the link works in my config)
    alert_once: true
    notify_group: SHIELD (i also already used this instead: media_player.shield_2)
```
