### ISSUE TITLE
[Bug]: Notify Group

### ISSUE THREAD

**Issue by tunavis** [SgtBatten/HA_blueprints#98]
### Description

Hi,

After updating home assistant to latest version my notify:
  - name: alertapp
    platform: group

not working.

Full Error: The automation "Frigate Notification - Outdoor Dectection" (automation.frigate_notifications_0_12_0_1) has an action that calls an unknown service: notify.alertapp.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](https://homeassistant.gito.co.za/config/automation/edit/1690100829008) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

### Version

0.12.0.1

### Automation Config

```yaml
alias: Frigate Notification - Outdoor Dectection
description: Outdoor snapshot notfification
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.garage_door_camera
    base_url: https://********(sensitive data)
    title: Outdoor Detection
    attachment: snapshot
    ios_live_view: true
    tap_action: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    button_3: View Clip
    url_2: "{{base_url}}/api/frigate/notifications/{{id}}/{{camera}}/clip.mp4"
    url_1: "{{base_url}}/api/frigate/notifications/{{id}}/snapshot.jpg"
    button_2: View Snaphot
    button_1: View Snaphot
    notify_group: alertapp
```
